### ISSUE TITLE
Selection and currentline has the same hex but different images in readme

### ISSUE THREAD

**Issue by blacksails** [dracula/dracula-theme#182]
Selection and currentline has the same hex but different images in the readme, what is the issue?

**Comment by blacksails** [comment]
Found that background and selection seems to have the same images.

**Comment by nesl247** [comment]
Which editor/theme are you referring to here?

**Comment by blacksails** [comment]
I refer to the table in the general readme.

**Comment by nesl247** [comment]
Funny enough I just checked the history and it's been the same since the day @zenorocha added the table. @zenorocha, is it correct or is there an issue?

**Comment by blacksails** [comment]
There must be an issue because the color of the images should match the hex.

**Comment by nesl247** [comment]
The color boxes being different is definitely an issue if the hex is supposed to be the same, but I'm also questioning the hex being the same.

**Comment by zenorocha** [comment]
We definitely need different colors for selection and current line. Let's finish the migration and then we start tackling improvements like this ;)

**Comment by nesl247** [comment]
I just tested it using a color picker and both boxes are actually the same and correct color. I know to the eye it looks different for some reason, but when I look really close it looks the same. The color pickers probably don't lie though so I'm going to say it's correct.

**Comment by nesl247** [comment]
I'm going to close this since they appear to be the same unless you have another color picker stating the opposite. If so I'd be happy to reopen the issue as we definitely want to get this right.

I opened up another issue for the hexes being the same which they really shouldn't be (#191).
