### ISSUE TITLE
Create fish shell theme (color variables)

### ISSUE THREAD

**Issue by brandonpittman** [dracula/dracula-theme#196]
[Fish shell theme](https://github.com/brandonpittman/template)

![Fish shell theme](http://pixelsnatch.com/f/dracula.fish-Az1cHQFY8l.png)

**Comment by nesl247** [comment]
Hey @brandonpittman,

Thanks this, but the officially supported shell themes should be based on robbyrussell, which is a really simple shell theme. However, I can create a fish shell repo and link to your theme as a related one.

Please create your theme in a repo, such as I have for my theme [here](https://github.com/nesl247/fish-theme-dracula). I'll create a fish repo today so you can submit a PR with a related link for your theme.

Thanks!

**Comment by brandonpittman** [comment]
What I submitted isn't a prompt, but a file that merely sets standard fish color variables to Dracula colors. I'm not touching anyone's prompt, just color variables that fish_config would normally set. 

So, you can use whatever prompt you want.

**Comment by nesl247** [comment]
I'll have to investigate this a bit further. I've not actually seen this done before, not just in fish, but in any shell, as the prompts would override this usually.

**Comment by brandonpittman** [comment]
I believe the prompt should be structure and not the colors. This way, you include the standard fish color variables in prompt code, and then no one gets surprised when they try a prompt.

**Comment by nesl247** [comment]
@brandonpittman Sorry, haven't had too much time to review this at the moment as I've been preparing to move.
