### ISSUE TITLE
OmniFocus 2

### ISSUE THREAD

**Issue by hivearts** [dracula/dracula-theme#197]
Hello,

I really like your themes guys, and use it on all editors that i have. (:
It would be good if someone can create theme for OmniFocus, i really will appreciate it.

Cheers,

**Comment by zenorocha** [comment]
Hey @hivearts! That would be awesome.

Have you seen this? https://github.com/dracula/dracula-theme#are-you-going-to-support-editor-x

Basically, all themes are submitted by the community, so feel free to create a pull request ;)

**Comment by nesl247** [comment]
@zenorocha Going to open this back up with a new label so people who might be interested in creating these can see there is interest.

**Comment by zenorocha** [comment]
Ohh sorry about that ;)

**Comment by psthompson** [comment]
I actually createda theme for OmniFocus for myself but I wasn't a big enough fan of it to share it. It doesn't match the quality of the other available app themes because Omni Focus forces a black or white main UI depending on the other colors used.

**Comment by psthompson** [comment]
I actually createda theme for OmniFocus for myself but I wasn't a big enough fan of it to share it. It doesn't match the quality of the other available app themes because Omni Focus forces a black or white main UI depending on the other colors used.

**Comment by psthompson** [comment]
I actually created a theme for OmniFocus for myself but I wasn't a big enough fan of it to share it. It doesn't match the quality of the other available app themes because Omni Focus forces a black or white main UI depending on the other colors used.

![](http://i.imgur.com/eQhvnj6.png)

**Comment by psthompson** [comment]
I actually created a theme for OmniFocus for myself but I wasn't a big enough fan of it to share it. It doesn't match the quality of the other available app themes because Omni Focus forces a black or white main UI depending on the other colors used.

![](http://i.imgur.com/13GTisy.png)

**Comment by hivearts** [comment]
Yes, black color sucks, but it's still the best theme for omnifocus that i have seen on internet.

Can you please upload a style somewhere?

**Comment by stephengfriend** [comment]
@neurohacked Any chance of sharing that theme? I've recently switched over to Dracula for my universal theme and would love this.

**Comment by zenorocha** [comment]
I'm closing this issue for now due to its inactivity, but if @neurohacked is interested in sharing his theme we would love to highlight it for other people to use :)
