### ISSUE TITLE
Xresources / xterm color scheme

### ISSUE THREAD

**Issue by Aszarsha** [dracula/dracula-theme#198]
Hello :-)

I just implemented .Xresources version (for xterm, urxvt, and other X11 applications) of the three terminal versions of Dracula available here on GitHub. The repo is [Aszarsha/dracula-Xresources](https://github.com/Aszarsha/dracula-Xresources).

1) [dracula/mintty](https://github.com/dracula/mintty) (the most faithful to the original color scheme) over xterm:
![dracula-xresources mintty](https://cloud.githubusercontent.com/assets/632292/15819941/4b0d329e-2be6-11e6-98a1-581c4714495b.png)

2) [dracula/terminal.app](https://github.com/dracula/terminal.app) over xterm:
![dracula-xresources terminal app](https://cloud.githubusercontent.com/assets/632292/15819946/524bc020-2be6-11e6-82da-e490a8f58577.png)

3) [dracula/iterm](https://github.com/dracula/iterm) over xterm:
![dracula-xresources iterm2](https://cloud.githubusercontent.com/assets/632292/15819958/729ea04a-2be6-11e6-8417-59e5a93850d3.png)

Cheers! :)

**Comment by nesl247** [comment]
Hi @Aszarsha,

Thanks for the contribution! If you would like, we can create an official xresources repo where you could submit a PR for one of these, probably the mintty one as you said it's the most correct, and then become the maintainer for it.

If that sounds interesting to you, let me know and I'll set it all up.

Thanks again!

**Comment by Aszarsha** [comment]
Sounds good! :)
Just in case, let's close the issue only once everything is up?

**Comment by nesl247** [comment]
Yep, of course. Just didn't want to create it all if you didn't want to work on it. Will create it all for you now.

**Comment by nesl247** [comment]
Can you please create a PR against https://github.com/dracula/xresources? Please make sure to update the README to include only yourself in the maintainers list.

Thanks!

**Comment by Aszarsha** [comment]
Ok, I made the pull request. I also made a pull request to dracula.github.io to add a screenshot, but didn't create the web pages or anything, I'd rather leave that to you (although I could do it if necessary).

In the process, I also corrected minor things in the MinTTY repo (see pull request there).

Cheers! :)
