### ISSUE TITLE
Pythonista

### ISSUE THREAD

**Issue by hacknug** [dracula/dracula-theme#199]
Hey guys!

I just finished porting Dracula for Pythonista (an iOS app). Apparently the way to share themes for Pythonista is through a URL with all the info encoded. Here's said URL:

pythonista3://?action=add-theme&theme-data=eNqdVkuTojAQvvsrLPYqVYKKsDd1ytte9g9QIbSYJaStEGrHnZr_viGBkfiaYcjJ7v76_fBtMp16nGWSyHOqmFDe9OfU28f6hd6sZeZwIA1XqYLXW6Y6NlUmCONphjIHaQSCVRAFOytQNEqBTDNCy0JiI3IjEcbhZhFZiSesnMgyLeGcIZGGq2QDHeipzgMK5dfsH7ScYG5dJdk1JFhqV7cDyIFUjJ8N7xcIjv5vKBpOpBWp4UQkUShTzgTcaBCkssQXSahGWWqf2yfe1hRPULfkN_2zjRtprSQTxYWmqRQ52gTvg_0m3nmG8T6zGMpJXT-Q_xGRbJlkLkDHUDrybYH9HCjqGBkKg9TugjTRusYwBwd7ic4fmI3n7VvOvdnFJylA-pLkrDHeho5eXeu_aEt9L-z9OtlFricniX-AKgdhq6_O3JYjQ567oCNo-6Lwg3Ewk2I9Dg_dW-nPhTBFOKPPzHQSDuqAsiJKPW6ALrPx3MW1LvufmxyK3eC_l8nFyEwegZYZvrrhDYjtoN9F-DkKeAr76LVe8kaXIsWnjS_wuueF3nR2wd0pyPYlWeyTqyo2gvb67rWLXaNXntXlnQgvdU_MFw8m6p7z7fIoARvlau-kUI5o4L7A4bgC97E_npbVfL9Zb6_6r2Fcd_03Eldh3nAYAaBYVSDUA0QUrsPN8pLkL8zs-IWtd2jGkZZaMZFq3KR3R_krAU86lOmUtAYOJrmDY28-7-NIKqa6OB1OL94VrjtuAtLLYHjJRr_IvfyD_wWDY6m1gay1KUa4DTSkYRTG3uT9P3h2KkQ~

Let me know if there's anything else you need me to do.

**Comment by nesl247** [comment]
Thanks for the contribution @hacknug. It'll probably be this weekend, but I'll create a repository for this theme in which you will be the maintainer. Even though it's just a link, we can have the readme and screenshot and everything as needed.

Thanks! I'm gonna leave this issue open until I get the repo created for you.

**Comment by nesl247** [comment]
Ok, so I've created the repository for you and invited you to be a maintainer for that repository. Please see https://github.com/dracula/pythonista/issues/1.
