### ISSUE TITLE
problem ovveriding classes (html editor)

### ISSUE THREAD

**Issue by wanbinkimoon** [dracula/dracula-theme#200]
Hi, 
I love the color palette and the theme but  I want to add a cyan touch to the html editor which, in my opinion is a bit flat, so i wanted to ovveride those 2 classes `.punctuation.definition.tag.begin.html` and `.punctuation.definition.tag.begin.html` but the theme seems not work

**Comment by nesl247** [comment]
Hi @wanbinkimoon. Which theme are you referring to? This repository is more of a metadata repository now, rather than containing the actual themes. We moved to an organization, so everything is split up now into separate repositories.

**Comment by wanbinkimoon** [comment]
the atom theme

**Comment by nesl247** [comment]
Can you please open an issue (here)[https://github.com/dracula/atom/issues] instead then? Thanks!
