### ISSUE TITLE
New theme: XChat

### ISSUE THREAD

**Issue by beefsack** [dracula/dracula-theme#201]
I've created a new theme for XChat, you can see it at https://github.com/beefsack/dracula-xchat.

I'd happily put it up for consideration for moving under the Dracula organisation, but also happy to maintain it separately if it's not a good fit.

**Comment by nesl247** [comment]
Hey @beefsack,

Thanks for the contribution! We'd be happy to have this under the Dracula organization. If you'd like to do that, let me know and I'll go ahead and create the repository and such and add you to the organization.

Thanks!

**Comment by beefsack** [comment]
Hi @nesl247, sounds great, cheers!

**Comment by nesl247** [comment]
I've gone ahead and created the repo and invited you to be a member of the organization. You can find the repository here: https://github.com/dracula/xchat

**Comment by beefsack** [comment]
Cheers 😄 have pushed to the new repo just now.
