### ISSUE TITLE
Error in PHPStorm 9.0.2

### ISSUE THREAD

**Issue by WinstonN** [dracula/dracula-theme#203]
Getting this error on Ubuntu 14.04 PHPstorm 9.0.2

Cannot read scheme Dracula.icls  from '$ROOT_CONFIG$/colors': Argument for @NotNull parameter 'element' of com/intellij/openapi/editor/markup/TextAttributes.<init> must not be null

**Comment by zenorocha** [comment]
Could you please report this issue to the proper repo: https://github.com/dracula/jetbrains? Thanks!

**Comment by WinstonN** [comment]
@zenorocha sure!
