### ISSUE TITLE
Visual Studio Code jsx highlighting problem

### ISSUE THREAD

**Issue by ufukomer** [dracula/dracula-theme#204]
When I put create a new line (in a situation like below), it disturbs the JSX highlighting:

![](http://image.prntscr.com/image/b57121946b8d4aa59b94af496778b9e0.png)

But it's ok if I don't break a new line (green underline is not related with the issue, it's about tslint rule):

![](http://image.prntscr.com/image/9a297bd2e2224589bfb487457e20ec6c.png)

**Comment by nesl247** [comment]
@ufukomer Would you mind filing a bug at https://github.com/dracula/visual-studio-code instead?

Thanks!
