### ISSUE TITLE
dracula for xfce4-terminal

### ISSUE THREAD

**Issue by Adjective-Object** [dracula/dracula-theme#205]
## Repo
https://github.com/Adjective-Object/dracula-xfce4-terminal

## Screenshot
![Screenshot](http://i.imgur.com/yuDq9FY.png)

**Comment by Adjective-Object** [comment]
Any updates?

**Comment by nesl247** [comment]
Hey, sorry, things have been crazy over the last few months, and I haven't dedicated the time I should have. I will get this taken care of this weekend, if not later today.

Thanks again!

**Comment by nesl247** [comment]
Hi @Adjective-Object, I've gone ahead and created the repository for you at https://github.com/dracula/xfce4. If you could please submit a PR, it would be appreciated. Once it's been merged in, I'll add you as a member of the organization.

Thanks again for your contribution!

**Comment by carks32** [comment]
Sadly that @Adjective-Object didn't finish this :sob:

**Comment by Adjective-Object** [comment]
Whoops, looks like life got away from me too. I don't think I can make a pull against a repo unless it's registered as a fork of it, and I don't think I can fork an empty repo. 

@nesl247 mind throwing a README into the repo so I can rebase my branch onto it?
