### ISSUE TITLE
Dracula for Notepad++

### ISSUE THREAD

**Issue by ukarim** [dracula/dracula-theme#206]
Hello. I've created theme for Notepad++. You can see it at https://github.com/ukarim/dracula-notepad-plus-plus.
![screenshot](https://raw.githubusercontent.com/ukarim/dracula-notepad-plus-plus/master/screenshot.png)

**Comment by zenorocha** [comment]
Hey @ukarim,

Sorry for taking so long to reply. I'm very glad you took the time to create a Notepad++ theme!

I just sent you an invitation to join the Dracula organization. I also migrated your repository to this organization, keeping your commit history and everything else. See it here: https://github.com/dracula/notepad-plus-plus

You can now remove yours with you want.

Thanks again for contributing and supporting this theme!
