### ISSUE TITLE
Not dracula.vim url on Vim page

### ISSUE THREAD

**Issue by Narann** [dracula/dracula-theme#207]
Hi and thanks for Dracula theme. :)

https://draculatheme.com/vim/

I can't use vundle or pathogen. I must be totally silly but when I read this:

> If you aren't so clever just move the dracula.vim file into ~/.vim/colors and add...

It doesn't seems to be any `dracula.vim` file url anywhere on the page.

Am I missing something? Where can I find `dracula.vim`?

Thanks in advance and keep the good work!

**Comment by Narann** [comment]
I finally find it!

https://github.com/dracula/vim/tree/master/colors

Do you thing you can add a direct url to:

https://github.com/dracula/vim/blob/master/colors/dracula.vim

It's jsut that there is no direct access to this file on the page and you have to dig into github to find it.

Thanks in advance!

**Comment by zenorocha** [comment]
Hey guys, thanks for sharing! Would you mind sending a PR or move this discussion to https://github.com/dracula/vim? Thanks a lot for using Dracula and reporting these problems :)
