### ISSUE TITLE
Dracula Theme for Chrome

### ISSUE THREAD

**Issue by jamesbvaughan** [dracula/dracula-theme#208]
Is anyone aware of a Dracula theme for Chrome/Chromium? If there's not one out there already I might be down to try to make one.

**Comment by zenorocha** [comment]
Hey @jamesbvaughan,

Sorry for the delay on answering you. We do have a Chrome DevTools theme (https://github.com/dracula/chrome-devtools), but not for the Chrome browser itself. Let me know if you give it a try :)

**Comment by nickimola** [comment]
We actually do have one now:
https://github.com/dracula/google-chrome
