### ISSUE TITLE
installed but my iterm looks nothing like dracula theme

### ISSUE THREAD

**Issue by craigcosmo** [dracula/dracula-theme#210]
screenshot of my iterm

<img width="669" alt="screen shot 2016-12-04 at 1 13 24 pm" src="https://cloud.githubusercontent.com/assets/538657/20864435/7acde804-ba23-11e6-8024-4cfac553d538.png">

screenshot of dracula

<img width="720" alt="screen shot 2016-12-04 at 1 06 30 pm" src="https://cloud.githubusercontent.com/assets/538657/20864436/80b2610a-ba23-11e6-9e5d-d8c0c398ae67.png">

The differences:
1. font - do I have to manually change the font in iterm setting?
2. where is my git status and branch? I'm opening jsplay which is git repo of mine.
3. Why my iterm display a long path 'Craig's macbookpro...' but dracula doesn't, what step I have to do to hide the 'Craig's macbookpro'?

**Comment by pix2D** [comment]
This is just a theme. It only changes colors. For additional terminal features look here:
https://github.com/robbyrussell/oh-my-zsh

**Comment by Raghava2016** [comment]
Facing same issue.

**Comment by craigcosmo** [comment]
install https://github.com/robbyrussell/oh-my-zsh will help

**Comment by Raghava2016** [comment]
installed oh-my-zsh,restarted iTerm. same issue persist.

**Comment by thiagorossener** [comment]
@Raghava2016 run the command to change from bash to zsh:

`$ chsh -s /bin/zsh`

**Comment by ysihaoy** [comment]
Good question, what's the font family of this theme?? Thanks.

**Comment by shariquesha** [comment]
Look here https://draculatheme.com/zsh/

**Comment by dinhlongviolin1** [comment]
Thank alot, solved my propblems 👍

**Comment by theajr** [comment]
If it helps anyone, you need to install `font-hack-nerd-font` fonts.  See full steps [here.](https://medium.com/@omergoldberg/my-iterm2-setup-504b11ffb5be)
