### ISSUE TITLE
Midnight Commander's colors became purple

### ISSUE THREAD

**Issue by sergeyvdovareize** [dracula/dracula-theme#211]
Hi.
After applying the theme to the iterm2 terminal the colors in Midnight Commander had become too gentle. Is it ok?
![mc dracula colors](http://image.prntscr.com/image/29434712d42348f98e344c92c0319378.png)

Thanks

**Comment by zenorocha** [comment]
Hey @sergeyvdovareize, sorry about that. Is this issue still happening? Can you help us fix it? If yes, the best place to discuss this should be on https://github.com/dracula/iterm. Thanks a lot for reporting!

**Comment by kizivat** [comment]
Hi.
 The same happened to me in gnome-terminal (Ubuntu 18.04). Any solutions yet, please?
