### ISSUE TITLE
Maintainer for vscode doesn't seem to be active anymore

### ISSUE THREAD

**Issue by dsifford** [dracula/dracula-theme#213]
Issues for the vscode repo look pretty stale. I sent in a PR a few days ago and that hasn't been acknowledged.

Willing to help maintain if one is needed for now.

**Comment by zenorocha** [comment]
Sorry about that @dsifford, I'm very glad you're willing to help :D

I just sent an invitation and added you to the team: https://github.com/dracula/visual-studio-code/commit/0809aa55cf130d666ab6a43f7da4a9139ef7d7f7

Let me know if you need anything.

**Comment by dsifford** [comment]
Thanks @zenorocha 

I'm not super experienced with the vscode marketplace, but it looks like it [requires authentication](https://code.visualstudio.com/docs/tools/vscecli#_publishing-extensions) to be able to publish changes to the extension. How would I go about getting authenticated for the repo?

**Comment by dsifford** [comment]
@zenorocha Just confirmed. I can't publish to the vscode extension marketplace without being granted access to the theme on visualstudio.com or without being given the access token. 

PR merged in the repo. Just waiting to deploy. Thanks.

**Comment by dsifford** [comment]
@zenorocha FYI: I reached out to @Ulthes by email and haven't heard back.

I've opened an issue about this also here: https://github.com/Microsoft/vscode/issues/21015

**Comment by dsifford** [comment]
@zenorocha Disregard.. Finally got in touch. Good to go now.
