### ISSUE TITLE
discussion - move emacs near the top

### ISSUE THREAD

**Issue by darshanime** [dracula/dracula-theme#215]
I hate to nit-pick (and don't get me wrong, I love this project) but in the home page, the lovely graphic which shows compatible editors, Emacs is way way down the list. It comes after even Slack(and Slack is not an editor!)

To quote numbers, Emacs is at 13 (Vim is at 3)

I think it would be nice to move it near the top 5 maybe, because Emacs is the most important editor ever created. 

![image](https://cloud.githubusercontent.com/assets/6951919/23579273/021fee3c-0110-11e7-8d04-fbaaf1088a06.png)

**Comment by zenorocha** [comment]
Hello @darshanime, you're right. The way things are organized today is very bad. We need some sorting and filtering capabilities.

**Comment by zenorocha** [comment]
Closing since we recently changed the way items are sorted by number of visits.
