### ISSUE TITLE
New Google Chrome Theme based on Dracula Color palette

### ISSUE THREAD

**Issue by nickimola** [dracula/dracula-theme#216]
Hi,

I've created a new theme for google chrome, it can be found here:
https://github.com/nickimola/Dracula-Chrome-theme

or here
https://chrome.google.com/webstore/detail/dracula-chrome-theme/gfapcejdoghpoidkfodoiiffaaibpaem?hl=en-US&gl=GB

![screen1](https://cloud.githubusercontent.com/assets/9289704/23648130/2eeefd4c-0311-11e7-9ec5-058992e55e98.jpg)

**Comment by zenorocha** [comment]
That's awesome @nickimola! Are you interested in moving this repository to the Dracula organization and maintain it? If yes, I can send an invitation to join ;)

**Comment by nickimola** [comment]
Thank you @zenorocha that will be awesome ;)

**Comment by zenorocha** [comment]
Awesome! I sent you an invitation, let me know when you accept it.

**Comment by nickimola** [comment]
Just accepted. So whats next?

**Comment by zenorocha** [comment]
Awesome! The next step would be transferring this repository to the dracula org. I just changed your role so you should be able to do that. 

After you moved, make sure to follow the https://github.com/dracula/template. Once everything is in place, we can create a page on draculatheme.com for this.

**Comment by nickimola** [comment]
Hi,

I've just moved the repo to Dracula.

2017-03-09 5:49 GMT+00:00 Zeno Rocha <notifications@github.com>:

**Comment by jessemillar** [comment]
Why is this theme not mentioned on https://draculatheme.com/? I'm glad I dug into the repos and found it!

**Comment by nickimola** [comment]
Ideally, both https://github.com/dracula/google-chrome, https://github.com/matthew-groth/Dracula-New-Tab-Page and this https://github.com/dracula/chrome-devtools should and could be mentioned on the website, as the all work together for a full Dracula chrome experience

**Comment by jessemillar** [comment]
@nickimola The DevTools theme is already mentioned on the website but doesn't have an icon on the homepage (https://draculatheme.com/chrome/). It also mentions that it's "no longer supported officially". I agree with the potential "need" for a browsers section on the homepage.
