### ISSUE TITLE
Request New Theme: Konsole

### ISSUE THREAD

**Issue by joshbenham** [dracula/dracula-theme#217]
## New Theme?

I was wondering if we could get a Konsole theme working. I am currently using 

https://github.com/mbadolato/iTerm2-Color-Schemes/blob/master/konsole/Dracula.colorscheme

But it does not seem 100% correct and the "Intense Colours" have me confused.

![dracula - spectacle theme](https://cloud.githubusercontent.com/assets/401672/23692458/dd8ecbe0-0422-11e7-9af5-9ab90835983c.png)

**Comment by zenorocha** [comment]
Hello @joshbenham! I noticed that @rishabhsrao created a theme for Konsole (https://github.com/rishabhsrao/dracula-konsole), but I reached out to him and he hasn't replied yet (https://github.com/rishabhsrao/dracula-konsole/issues/1).

If you're interested, we can create a repository under the Dracula organization and have you maintain. What do you think?

**Comment by rishabhsrao** [comment]
Hi @zenorocha Sorry about the delayed reply; I missed the notification. Sure, I'll transfer the repo to the Dracula org.

**Comment by zenorocha** [comment]
Done! https://github.com/dracula/konsole ;)
