### ISSUE TITLE
New Theme: .dircolors

### ISSUE THREAD

**Issue by joshbenham** [dracula/dracula-theme#218]
## New Theme?

I am a bit new to editing .dircolors (colorized LS files) and have just always used a Solarized one for ages so I went and tried making my own to pretty much work with (https://github.com/dracula/dracula-theme/issues/217)

I tested this by using **Konsole** and I only used colors from 0-8 of the colors palette because I knew they were the correct colors.

![dracula color print](https://cloud.githubusercontent.com/assets/401672/23781055/d0c3e1ca-059e-11e7-925c-03a4535581d9.png)

Once I got these colours I started editing and this is what I came up with. (https://github.com/joshbenham/linux-dotfiles/blob/master/dircolors/Dracula.dircolors)

You can see it in action on this test folder here.

![dracule color dircolors](https://cloud.githubusercontent.com/assets/401672/23781187/97417ca4-059f-11e7-8cf0-6c52a53d2d73.png)

If anyone knows how to test dircolors or can give me some guidance I would love some feedback.

**Comment by kkdk5535** [comment]
Very Impressive work, looking forward for community to support this new thought

**Comment by lwm** [comment]
<3

**Comment by zenorocha** [comment]
This is live now, see #699
