### ISSUE TITLE
new theme: chrome new tab

### ISSUE THREAD

**Issue by mgroth0** [dracula/dracula-theme#219]
https://github.com/matthew-groth/Dracula-New-Tab-Page

goes well with the [Chrome theme](https://github.com/dracula/dracula-theme)

while that theme changes the default new tab color, it flashes white every time a new tab is opened. This fixes that.

**Comment by hacknug** [comment]
Hey @mgroth0 :wave: Do you think this should be a part of https://github.com/dracula/google-chrome instead of a different theme?

**Comment by ChildishGiant** [comment]
I imagine some people will want the theme without the new tab part so I think it's best to keep them separate.

**Comment by hacknug** [comment]
Agree but since they're only a couple links to different extensions, maybe they can be kept together in the same repo then?

**Comment by zenorocha** [comment]
Closing since I agree with @ChildishGiant
