### ISSUE TITLE
Ubuntu 16.04 terminal vim 

### ISSUE THREAD

**Issue by Barmus** [dracula/dracula-theme#220]
I got a problem when apply this theme to my default terminal-vim , the way it looks on my screen is much different from the standard picture! Are there any possibilities to fix this ? (By the way , this also happens to the terminal-Emacs) I love this theme quite much !  I'll be grateful if you can help me out !

**Comment by zenorocha** [comment]
Hello @Barmus, can you open an issue on those specific repositories?

https://github.com/dracula/vim
https://github.com/dracula/emacs

Thanks!
