### ISSUE TITLE
I created a monodevelop theme :)

### ISSUE THREAD

**Issue by GabLeRoux** [dracula/dracula-theme#221]
Hi there,  
I created [GabLeRoux/monodevelop](https://github.com/GabLeRoux/monodevelop) theme. I did not look at all the details on how the theme can be merged, but It works for me and looks great. I started from monokai for other default colors and json values. Maybe it can be improved, but it's more than enough for me :)

![image](https://cloud.githubusercontent.com/assets/1264761/24280654/95c9b13c-1028-11e7-8fcf-0b232a0ead76.png)

Let me know if I must update something.

**Comment by zenorocha** [comment]
Hey @GabLeRoux, that's awesome! 

What we usually do is transferring the repository to this organization and then adding a page on the site. You would still control and maintain the repository, nothing changes :)

Let me know if you like this idea so I can send you an invitation.

**Comment by zenorocha** [comment]
And sorry for taking so long to reply :/

**Comment by GabLeRoux** [comment]
Sure, go on! :D 
No problem for the delay, we all have many things to do, really glad this can become official! 👍

**Comment by zenorocha** [comment]
Great, let me know when you accept the invitation ;)

**Comment by GabLeRoux** [comment]
I did not find any invitation in my github notifications nor in project's settings, but I've added you as a contributor if it helps somehow, or do I have to transfer the repo?

![screenshot 2017-04-20 08 58 49](https://cloud.githubusercontent.com/assets/1264761/25231915/9e98ca34-25a7-11e7-8ecf-cd8325fd4fe2.png)

Let me know if I missed something here ;)

**Comment by zenorocha** [comment]
Take a look now, invitations are sent via email and can be accepted at https://github.com/dracula

**Comment by GabLeRoux** [comment]
Accepted invite 🎉  Thanks

**Comment by zenorocha** [comment]
Awesome! You can now standardize the README based on the https://github.com/dracula/template and send a pull request to https://github.com/dracula/dracula.github.io/ with the new theme ;)

**Comment by zenorocha** [comment]
All done!

https://draculatheme.com/monodevelop/
https://github.com/dracula/monodevelop/commit/fc55b762354c55155c94458b3844c63cada0c505

🎉
