### ISSUE TITLE
New Theme: CotEditor

### ISSUE THREAD

**Issue by ghost** [dracula/dracula-theme#224]
## New Theme

I made a new theme for [CotEditor](https://coteditor.com/)! My repo is [here](https://github.com/roonieone/dracula-coteditor).

**Comment by zenorocha** [comment]
That's great @roonieone!

**Comment by zenorocha** [comment]
What we usually do is transferring the repository to this organization and then adding a page on the site. You would still control and maintain the repository, nothing changes :)

Let me know if you like this idea so I can send you an invitation.

**Comment by roonieone** [comment]
Yeah, sounds good to me!

**Comment by zenorocha** [comment]
Great, let me know when you accept the invitation ;)

**Comment by zenorocha** [comment]
Friendly ping, did you get the invitation? I just resend it, you can accept it here: https://github.com/dracula

**Comment by roonieone** [comment]
Accepted!

**Comment by zenorocha** [comment]
Cool! Try transferring to the `dracula` org now.

**Comment by zenorocha** [comment]
After you do that, we'll need the instructions to install and enable it on the site.

**Comment by roonieone** [comment]
Not sure how to transfer it. When I try, it says `dracula already has a repository in the dracula/template network`...

**Comment by joaoevangelista** [comment]
Hmm is the remote set to the new repository at `dracula` org ?

**Comment by yougotwill** [comment]
Hi @zenorocha, not sure what happened to this previous user and if this is the right place to post this. If it's a problem I'm happy to be redirected to the correct place. 😄 

However given the lack of activity on this issue I've made the theme from scratch and made my own repo https://github.com/yougotwill/coteditor-dracula-theme . 

Hopefully this can also be helpful to other cot users out there 👍

**Comment by yougotwill** [comment]
@hacknug Looks like you are still active on this repo. Is there any chance we can integrate my repo?

**Comment by hacknug** [comment]
@yougotwill Hey there! 👋 

I've managed to talk to Zeno about helping out maintaining the organization and will be sending invitations to join the organization to everyone with a new theme as soon as I'm a co-owner.

Will get back to you asap!

**Comment by hacknug** [comment]
@yougotwill just sent you an invite to join the organization. Once you've joined we can move your repo to it. Let me know if there's anything else you need me to do 👍

**Comment by yougotwill** [comment]
Amazing! Thank you so much. 🙏

**Comment by yougotwill** [comment]
@hacknug I have joined the organisation. I haven"t transferred a repo before so just to confirm. 

1. I go to "transfer ownership" in the settings tab and click the transfer button.
2. Then enter the repo and the organisation name "dracula".
3. Update the remote as mentioned above?

Anything else I need to do. I just want to make sure this goes smoothly 😆

**Comment by hacknug** [comment]
@yougotwill I'd say yes but you're going to be the first one I do this with so… 🤷‍♂

One thing I'm not sure of is what can happen with the repo being a fork of `dracula/template`. I think @ghost ☝️ was having issues with that so maybe you'll have to do something so it's not a fork.

I guess we'll see. Let me know if you need any help!

**Comment by yougotwill** [comment]
Cool @hacknug Will sort it out this evening

**Comment by yougotwill** [comment]
@hacknug I managed to successfully transfer the repo. Though it looks like I don't have the correct permissions to edit things. For example I want to change `dracula-coteditor` to just `coteditor` for consistency. Could you help with that please?

Also the solution to @ghost 's problem is to create a new repo. You can't transfer a forked repo into the same network if another repo exists. You would have to contact Github support so it's easier just to create a new repo under the same name and change the name of the old one and archive it which I have done.

**Comment by hacknug** [comment]
@yougotwill can you try now?

**Comment by yougotwill** [comment]
@hacknug It works thanks! Will look into making a pr for the website when I have time.

**Comment by hacknug** [comment]
Sounds good. Thanks!
