### ISSUE TITLE
How to install on Jetbrain on Windows platform?

### ISSUE THREAD

**Issue by donnygunawan93** [dracula/dracula-theme#225]
How to install on Jetbrain on Windows platform?

**Comment by joaoevangelista** [comment]
Download and copy [Dracula.icls](https://github.com/dracula/jetbrains/blob/master/Dracula.icls) to your distribution folder under your home.

The path is usually:

`C:\Users\<username>\.IntelliJY.X\config\colors`

Where username is your account name and .IntelliJY.x is your IntelliJ or other Jetbrains IDE dot folder
