### ISSUE TITLE
Not much colors in the terminal theme

### ISSUE THREAD

**Issue by IvanYurchenko** [dracula/dracula-theme#226]
I installed the theme as mentioned on the [official site](https://draculatheme.com/terminal/). However, I don't see much colors in my terminal:
![screenshot](https://d1ro8r1rbfn3jf.cloudfront.net/ms_105836/v6xDCpHLjc8Vp31JYcixgpymJAY0uc/dracula-theme%2B%25E2%2580%2594%2B-bash%2B%25E2%2580%2594%2B80%25C3%259724%2B2017-04-25%2B13-14-37.png?Expires=1493201888&Signature=X2GwDK~kirMLeEqF7MQKf9sY~mgoHYoBFzjgLJgJOI5wjbc23N03jDFETbzOvHhF8vRIpSnEi5lrKJEmJzWrrk9axxjwQnUE8GltoilKG6FK3n8jQ08dsz0w7-FihrtFP4wSbO0Rhy4GwdQz47Aa0PRpBY5JRatMld-OUMuI8uijIlPtQW6kKJnYDX0sHG~x8TPt7cmWM2l9EOSZL1cpA6BuNPCJ81Jk5i4T5KTKPLfOQ7BwH2b66-I8upitOzT9aqQI6XuPp3C3KTNjovlwVeKlVPI8WnY3yJHFSbgkgTT1evfg26r1PQ0oalf76utBz2BLA5hNsTlFB1X3Anw~mQ__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA)

I also tried relaunching terminal and Finder with no effect.

Compare to the screenshot from the official site:
![screenshot from the site](https://d1ro8r1rbfn3jf.cloudfront.net/ms_105836/Ph7nep9wLGoIYheqAuY09EJHtceH6P/Dracula%2B%25E2%2580%2594%2BA%2Bdark%2Btheme%2Bfor%2BTerminal.app%2Band%2Bmore%2B2017-04-25%2B13-17-14.png?Expires=1493201906&Signature=DnZ4b3ZQm7XbfLd~2iSmcS~ltxBVOTLvTPKUB6o7e06uw28Sc2b0XtmDzQ9rZvKQUfm~SQ-e0gUGyyqeue~2jkYZXFbO~yyc74fbYFDAIpYTHRCrXE5vyG8kJgWLdqBiUbZ8hwr14RjpeA4D5Ko~sYWwzFpsxzfICLEwbDKUTwU7d8naJvF0ApUVx6cwfO7wQoOhmt4W4090cSiXxWpP64WwG7j0pG5LSLo3odCVxIPYdIXnRfEWmKY5VmF5oFGzPxzvfwl968LK5JxuSZ666Rm1AOIpaXqweSWViIqoaE6tkZho7T4dAQ7UvqKYAbvnfY7MyxDGo2MzDlLorSHP9A__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA)

Is it normal? If it's not, could you give an advice on how should I install it correctly?

**Comment by zenorocha** [comment]
As you can see from the window title, I use `zsh` instead of `bash`. If you want that exact view you'll need https://github.com/robbyrussell/oh-my-zsh and https://github.com/dracula/zsh.

**Comment by IvanYurchenko** [comment]
I see now, thank you!
