### ISSUE TITLE
The latest Visual Studio Code update (v 1.1.2) seems to have broken the colors :(

### ISSUE THREAD

**Issue by joshgarwood** [dracula/dracula-theme#227]
## New Theme?

We would love to support all code editors out there, but we need your help to accomplish that. Feel free to create a new theme based on our [color palette](https://github.com/dracula/dracula-theme#color-palette).

## Existing Theme?

Consider fixing the issue yourself. That's the best way to contribute ;)

If that doesn't work, take a screenshot that shows the actual bug and mention the [specific maintainer](https://github.com/dracula/dracula-theme#team) of your theme.

**Comment by zenorocha** [comment]
Hello @joshgarwood, please open an issue on https://github.com/dracula/visual-studio-code.

**Comment by dsifford** [comment]
Thanks! I'm aware and working on the fix. dracula/visual-studio-code#27
