### ISSUE TITLE
Using Dracula on my service

### ISSUE THREAD

**Issue by felixsanz** [dracula/dracula-theme#228]
Ey! I've added Dracula theme to my syntax highlighter as a service -> https://photon.sh

You can view it here directly -> https://photon.sh/demo?theme=dracula

Are you OK with that?

I'm maintaining it and I'll continue doing so if you let me use it there. Feel free to add it to the list of compatible software if you want!

Thanks in advance.

**Comment by felixsanz** [comment]
Btw it's just too beautiful :)

Some examples of "weird" languages:

https://photon.sh/demo?language=fortran-modern&theme=dracula
https://photon.sh/demo?language=erlang&theme=dracula
https://photon.sh/demo?language=arduino&theme=dracula
https://photon.sh/demo?language=r&theme=dracula
https://photon.sh/demo?language=vuejs&theme=dracula

**Comment by zenorocha** [comment]
That's amazing @felixsanz, I'm super impressed with the work you did there. Feel free to use Dracula over there.

You might want to take a look on https://github.com/zenorocha/clipboard.js too, just an idea for a plugin ;)

**Comment by zenorocha** [comment]
Also, any plans to support Google Closure Templates (Soy)?

**Comment by heinst** [comment]
All I have to say us: Google Closure is the devil reincarnated

**Comment by felixsanz** [comment]
@zenorocha In fact, Photon uses Clipboard.js in the settings page! So people can click on the icon and the API Key is copied into the clipboard. Take a look inside! :stuck_out_tongue_closed_eyes: 

The demo shows just a few languages because the list is really big. Actually there is support for 300+ languages. Said that, Google Clousure Templates **wasn't** on the list, **but now it is** :) I've added it taking your reply as a request! Check it out here -> https://photon.sh/demo?language=soy&theme=dracula

Soy + Dracula = Beautiful. Isn't it?

**Comment by felixsanz** [comment]
By the way the theme is open-sourced here: https://github.com/photonsh/themes/tree/master/dracula

In case you want to link it in the repo.

**Comment by zenorocha** [comment]
Niiiice! I may be able to use this on my projects. Thanks for sharing!
