### ISSUE TITLE
Setting t_Co

### ISSUE THREAD

**Issue by BourgeoisBear** [dracula/dracula-theme#229]
For most terminals I've tried this with under Linux (xfce4-terminal, urxvt), the dracula theme does not work.

To fix this, just add:

`set t_Co=256` before the `let g:colors_name = 'dracula'`  on line 21.

I figure it would be just as easy for you to add this directly than for me to issue a pull request.

Thx.

JS

**Comment by zenorocha** [comment]
This is an umbrella repository for all themes. I see you left a comment on https://github.com/dracula/vim/issues/29#issuecomment-300545098 so I'm going to close this for now.
