### ISSUE TITLE
No color difference

### ISSUE THREAD

**Issue by umanga907** [dracula/dracula-theme#233]
Hi,
I imported the theme, the only change i got on my terminal is the background and the text color.
Every text are in same color.
Am i missing something ? 
I am on mac os Sierra 10.12.5

**Comment by zenorocha** [comment]
Hello @umanga907, please open an issue on the appropriate repository.

https://github.com/dracula/terminal.app
https://github.com/dracula/iterm
https://draculatheme.com/hyper/
https://draculatheme.com/xresources/
https://draculatheme.com/zsh/
https://draculatheme.com/mintty/
