### ISSUE TITLE
Netbeans theme

### ISSUE THREAD

**Issue by pichardoJ** [dracula/dracula-theme#234]
Hi, I saw in https://github.com/dracula/dracula-theme/issues/19 that there was a Netbeans theme on the way, I was wondering if there is something to it? I mean I could possibly try to do something of it, but I wanted to know if someone is already working it?

**Comment by zenorocha** [comment]
Closing this one since we weren't able to create a Netbeans theme so far.

If you're reading this and interested in having a Netbeans theme, feel free to create one based on the [template we created](https://github.com/dracula/template) and send a comment over here.

**Comment by digz6666** [comment]
@jpitchardu I found similar one here: https://github.com/jasontdev/dracula-theme-for-netbeans
