### ISSUE TITLE
Photoshop Swatch

### ISSUE THREAD

**Issue by jef** [dracula/dracula-theme#235]
Here's a swatch, maybe this could go along with the README.md for people that want to do stuff in Photoshop?

![Image of Swatches](http://i.imgur.com/qmWoGcT.png)

[Link to download the .aco(]https://dbr.ee/PApN)

**Comment by zenorocha** [comment]
It took years but it's finally here:
- https://draculatheme.com/adobe
- https://github.com/dracula/adobe

I made it as a `.ase` instead of `.aco` for Adobe Illustrator compatibility.

Thanks for doing this @jef!

**Comment by jef** [comment]
Wow... forgot this even existed. That download site is even dead 🤣

Thanks for merging!
