### ISSUE TITLE
Browser notes

### ISSUE THREAD

**Issue by ButsAndCats** [dracula/dracula-theme#236]
It doesn't really need a repo but I use this to make notes quickly sometimes.

`data:text/html, <body contenteditable style="background-color: #282a36;font-size: 1rem/1.5; font-family: Menlo, monospace; font-weight: 500; color: #8be9fd;max-width:60rem;margin:0 auto;padding:4rem;">`

Just paste it into your address bar and bookmark it.

**Comment by nickimola** [comment]
Thanks! this is really cool 👍

**Comment by zenorocha** [comment]
I'm going to close this one since it's not an issue, but that's super awesome @ButsAndCats!
