### ISSUE TITLE
Dracula for DuckDuckGo

### ISSUE THREAD

**Issue by makitsune** [dracula/dracula-theme#237]
I made this and I've been using it for a while. I felt like I needed to post it here!
https://github.com/makixx/duckduckgo

![firefox-1](https://raw.githubusercontent.com/makixx/duckduckgo/master/firefox-1.png)
![firefox-2](https://raw.githubusercontent.com/makixx/duckduckgo/master/firefox-2.png)

**Comment by hacknug** [comment]
Hey @makitsune! 👋 Just sent you a new invitation to join the organization and the DuckDuckGo team. Should we get rid of your personal repo to prevent users from using an out of date version of the theme?

Closing the issue since the theme was already migrated. Let me know if you need anything else.
