### ISSUE TITLE
Default font messes up character display

### ISSUE THREAD

**Issue by apexJCL** [dracula/dracula-theme#239]
## Current configuration

Fresh WebStorm install with Dracula as theme

## Issue

Bad character encoding display, editor and terminal are affected

## Monokai theme activated
![image](https://user-images.githubusercontent.com/4037632/28973303-7bab6870-78f8-11e7-8277-c7d2963062bb.png)

![image](https://user-images.githubusercontent.com/4037632/28973342-98fde4ac-78f8-11e7-8cc5-2827f68dc16c.png)

## Dracula theme activated

![image](https://user-images.githubusercontent.com/4037632/28973440-cf07a132-78f8-11e7-8454-1f91cbddd926.png)

## What I've done

Issue seems to be related with the default font used (Source Code Pro), because when I change it to my usual default (Fira Code).

I don't know if my font is messed up or if it's a bug known to the font itself.

**Comment by zenorocha** [comment]
Hey @apexJCL, can you open this issue on the appropriate repository (https://github.com/dracula/jetbrains)? Thanks!

**Comment by joaoevangelista** [comment]
Just to be quick, if you have SCP installed might be the font issue with Webstorm, if you like Fira, there is no need to keep SCP as selected, you can change it to one of your like
