### ISSUE TITLE
Dracula for Vivaldi

### ISSUE THREAD

**Issue by screendriver** [dracula/dracula-theme#241]
I've made a "theme" for the awesome [Vivaldi Browser](https://vivaldi.com). You can find my repository [here](https://github.com/screendriver/dracula-vivaldi)

<img width="857" alt="screenshot" src="https://user-images.githubusercontent.com/149248/29284697-0bbe4a0a-812c-11e7-9834-5883fa9047e3.png">

**Comment by sleepiejohn** [comment]
Hello @screendriver I created the repository at https://github.com/dracula/vivaldi and pushed your commits there  😸 :

**Comment by zenorocha** [comment]
Hey guys, so cool to see a Dracula theme for Vivaldi!

I added @screendriver to the organization and moved screenshot/instructions to the site:

👉https://draculatheme.com/vivaldi

https://github.com/dracula/vivaldi/commit/ffc352cc17f6a881412b4fc089317cb146266054
https://github.com/dracula/dracula.github.io/commit/7e65f8ea54cca3aa66f9e721ecd7c7783211bc48

**Comment by screendriver** [comment]
Cool! 🆒 
Thank you very much 👍 💃

**Comment by screendriver** [comment]
> Hello @screendriver I created the repository at https://github.com/dracula/vivaldi and pushed your commits there 

Now I could delete [my repository](https://github.com/screendriver/dracula-vivaldi), right? @sleepiejohn @zenorocha

**Comment by zenorocha** [comment]
Yes ;)

**Comment by rojagit** [comment]
I added the Vivaldi theme from the link mentioned. How is it different from the dark theme already provided by Vivaldi...also this too works only for browser areas, not for web pages. Anything that will darken web pages also ?

**Comment by screendriver** [comment]
@rojagit please open a new issue for that. But to answer your questions:

- it's different in terms that it uses different colours than the dark theme
- UI theming in Vivaldi has nothing to do with theming web pages. You can't theme web pages with Vivaldi natively

**Comment by rojagit** [comment]
Thanks! An yes I will remember to log a new issue next time.

**Comment by screendriver** [comment]
No problem. You're welcome ☺️
