### ISSUE TITLE
Dracula for st

### ISSUE THREAD

**Issue by jelohe** [dracula/dracula-theme#242]
## New Theme

I've ported the dracula theme to the awesome terminal emulator [st](http://st.suckless.org/)

![screenshot from 2017-08-25 11-57-28](https://user-images.githubusercontent.com/18138817/29710884-9c96801a-8992-11e7-9389-e725fc9465b4.png)

[Here is my repository](https://github.com/jelohe/dracula-for-st)

**Comment by zenorocha** [comment]
Hey @jelohe, would you be interested in moving this theme to the official organization? You would still be the owner and maintainer, but the repo would live under https://github.com/dracula.

Let me know and I'll send further instructions.

**Comment by andys8** [comment]
Looks like the content of the repo and the suckless patch are identical. https://st.suckless.org/patches/dracula/

Would it make sense to link to the patch from the draculatheme website?
