### ISSUE TITLE
Dracula for Vim Airline

### ISSUE THREAD

**Issue by JaredSartin** [dracula/dracula-theme#243]
Would love to have Vim Airline support. I am new to theming and would love some help on refining it. Still trying to look up the color palettes in something like `colortest.sh` to allow comparison and porting.

**Comment by JaredSartin** [comment]
Found #140 does this, with no install info?

**Comment by JaredSartin** [comment]
And final update/close.
`let g:airline_theme='dracula'` is all you need in .vimrc!

**Comment by mrchoc** [comment]
How do I install this for neovim? I tried adding that line but airplane theme isn't changing
