### ISSUE TITLE
Dracula Theme Sublime Text 3

### ISSUE THREAD

**Issue by Jadex1** [dracula/dracula-theme#244]
It seems the syntax highlighting in sublime text 3 is not working. https://forum.sublimetext.com/t/dracula-syntax-highlighting/31637/2 I just started using sublime text and I really enjoy this theme. It seems they updated the api for syntax highlighting which might be causing some issues.

**Comment by kenstuddy** [comment]
Can you please give more details about this issue and possibly include some screenshots? It appears to be working for me, at least for JavaScript, on Sublime 3 build 3143 on Ubuntu 16.04 with Xfce 4.12 as my DE.

Here is a screenshot of what it looks like for me:
!()[https://i.imgur.com/ht59XTT.png]
Here is the official screenshot:
!()[https://i.imgur.com/AWmb6kB.png]

**Comment by zenorocha** [comment]
Closing since this has been fixed on https://github.com/dracula/sublime.
