### ISSUE TITLE
Compatibility High Sierra

### ISSUE THREAD

**Issue by thibaut129** [dracula/dracula-theme#245]
Hi,

With the last version of OsX I don't have any color. 
Is there any fix for that ?

Thanks

**Comment by tiaguinho** [comment]
I'm using the theme on my terminal, vs code and PHP Storm without any problem.

Where do you try to use?

**Comment by FrankelJb** [comment]
I can confirm that this is an issue with the Alfred version of Dracula Theme. See the Alfred forum here: https://www.alfredforum.com/topic/10832-high-sierra-lag/?tab=comments#comment-55659

**Comment by zenorocha** [comment]
In that case, this issue should be moved to https://github.com/dracula/alfred.
