### ISSUE TITLE
Gtk?

### ISSUE THREAD

**Issue by a-schaefers** [dracula/dracula-theme#246]
Before I reinvent the wheel, somebody already made a gtk theme, right? It would seem natural to me that it has been done by now, but I cannot seem to find one. Just checking before I get to work, thanks. I have also just completed an openbox port, if you would like me to make a PR.

**Comment by pichardoJ** [comment]
I've been looking for one for a while now, I've not found anything related.

**Comment by Trollwut** [comment]
[This GTK theme](https://www.opendesktop.org/p/1099856/) works with the newest GNOME stuff and also has a Dracula flair. I love it! :)

**Comment by DOMApe** [comment]
I use Ant-Dracula

**Comment by SebDanielsson** [comment]
Is there a reason why EliverLara/Ant-Dracula isn't linked to on the website? What work would be required to add the theme to the website?

**Comment by scottzach1** [comment]
> Is there a reason why EliverLara/Ant-Dracula isn't linked to on the website? What work would be required to add the theme to the website?

https://github.com/EliverLara/Ant-Dracula/issues/40

**Comment by SebDanielsson** [comment]
> > Is there a reason why EliverLara/Ant-Dracula isn't linked to on the website? What work would be required to add the theme to the website?
> 
> https://github.com/EliverLara/Ant-Dracula/issues/40

Wow, what a coincidence. This is really good news.

**Comment by zenorocha** [comment]
Yeah, it would be great if we can have @EliverLara's theme as our official one.

**Comment by GrbavaCigla** [comment]
https://github.com/EliverLara/Ant-Dracula/issues/40#issuecomment-626375071

**Comment by zenorocha** [comment]
We officially have a GTK theme now. Thanks @EliverLara for doing such a great job on this!

https://draculatheme.com/gtk
