### ISSUE TITLE
Dracula Tilix

### ISSUE THREAD

**Issue by krzysztofzuraw** [dracula/dracula-theme#247]
Theme for [tilix](https://gnunn1.github.io/tilix-web/)
Repo: https://github.com/krzysztofzuraw/dracula-tilix
Screenshot:
![screenshot](https://user-images.githubusercontent.com/9116238/60766132-4b9ae080-a0a5-11e9-8a5f-ea1c6dd4678c.png)

**Comment by pichardoJ** [comment]
I checked this, and it looks good, however, there are some colors that are not on the palette. May I suggest the use of the following palette:

```
"palette": [
        "#000000",
        "#FF5454",
        "#50FA7B",
        "#F1FA8C",
        "#BD93F9",
        "#FF79C6",
        "#8BE8FD",
        "#BFBFBF",
        "#4D4D4D",
        "#FF6E67",
        "#5AF78D",
        "#F4F99D",
        "#CAA8FA",
        "#FF92D0",
        "#9AEDFE",
        "#E6E6E6"
    ],
```

**Comment by krzysztofzuraw** [comment]
@pichardoJ sure, changed in: https://github.com/krzysztofzuraw/dracula-tilix/commit/79597ecb93d2237a142ac36c4c4eb8614200d6e8

**Comment by pichardoJ** [comment]
@zenorocha Should this theme be added to the main repository?

**Comment by kendocode** [comment]
What needs to be done to get this into the main repo so it's easier to find? Could @krzysztofzuraw just submit a PR or is there another procedure?

Thanks for making this!

**Comment by hacknug** [comment]
Someone mentioned in #318 that comments were hard to read when highlighted. Guess this would be the right place to discuss that?

**Comment by pichardoJ** [comment]
@hacknug Isn't that issue related to Vim rather than the emulator?

**Comment by hacknug** [comment]
Wow. Don't even know how this comment ended up here. it was supposed to go to #232 lol

Since we're here already, @krzysztofzuraw could you please update the repo's screenshot to reflect the changes made to the palette? Once that's done, I think we can move the repo to the organization 👍

**Comment by krzysztofzuraw** [comment]
Updated - both repo and this issue screenshot

**Comment by krzysztofzuraw** [comment]
@hacknug should I open PR with theme or you first need to create a new repo in org (via README)?

**Comment by hacknug** [comment]
@krzysztofzuraw you need to trasfer it to the organization. Once it's been transfer I'll set the permissions so your team (aka @dracula/tilix) can push changes to the repo. Let me know once you've done it so I can do my part 👍

**Comment by krzysztofzuraw** [comment]
@hacknug repo transfered https://github.com/dracula/dracula-tilix

**Comment by hacknug** [comment]
Just renamed the repo and set the right permissions so your team can push directly. Thank you so much for your contribution! :tada:
