### ISSUE TITLE
MacDown Theme

### ISSUE THREAD

**Issue by arandilopez** [dracula/dracula-theme#248]
## New Theme

Hello, I want to contribute with a theme for MacDown.

Repo: https://github.com/arandilopez/dracula-macdown

<img width="1392" alt="screenshot" src="https://user-images.githubusercontent.com/2985233/32155706-04742a6e-bd07-11e7-95b4-58cf1f2a4eac.png">

**Comment by zenorocha** [comment]
Hey @arandilopez!

First of all, sorry for taking so long to reply. 

Now about your theme... I'm glad to see a theme for MacDown!

I just cloned your repo and pushed all the commits to a [new one over here](https://github.com/dracula/macdown). I also sent you an invite to join the Dracula org. You'll continue maintaining this project, the only difference is that we can make it more visible and include it on the [site](https://draculatheme.com).

We have the screenshot and instructions already, that's great! I will go ahead and create a new page on the site if that's ok for you.

Great job!

**Comment by arandilopez** [comment]
Thanks @zenorocha, I'm happy to work with all of you!

**Comment by zenorocha** [comment]
Awesome! I'm happy to work with you too ;D

* Added a page on the site: https://github.com/dracula/dracula.github.io/commit/59dfc5761a86ed0606ec6b747950c148082e5d90
* Made some changes on the theme repo: https://github.com/dracula/macdown/commit/57771c57afdc4cdc953a5872d2c078e3e3e5e479
* Added as a submodule on the main repo: https://github.com/dracula/dracula-theme/commit/ef4d70150fbdf2c36db7be148217ae51c0af142d

I think we can close this now. Feel free to share it online @arandilopez ;)

👉 https://draculatheme.com/macdown/
