### ISSUE TITLE
New theme: termite

### ISSUE THREAD

**Issue by gabrielsimoes** [dracula/dracula-theme#249]
**[Termite](https://github.com/thestinger/termite)**
**Screenshot:**

![Screenshot](https://raw.githubusercontent.com/gabrielsimoes/dracula-termite/master/screenshot.png)

**[Repository](https://github.com/gabrielsimoes/dracula-termite)**

**Comment by AurelienLourot** [comment]
@gabrielsimoes I have now cloned your repo to https://github.com/dracula/termite and made you admin :)

@zenorocha we need to serve now the installation instructions at draculatheme.com/termite. Can I help you with this?

**Comment by zenorocha** [comment]
Here's a PR that includes termite: https://github.com/dracula/dracula.github.io/pull/67

I can merge it as soon as I have the instructions to activate the theme.
