### ISSUE TITLE
New theme: Quiver

### ISSUE THREAD

**Issue by benknoble** [dracula/dracula-theme#250]
## New Theme?

✅ We would love to support all code editors out there, but we need your help to accomplish that. Feel free to create a new theme based on our [color palette](https://github.com/dracula/dracula-theme#color-palette).

I've done my best to use the theme palette for Quiver, but it's not precise.

Here's a screenshot.

Installation is simply an import of the .json into Quiver.
![quiver_dracula](https://user-images.githubusercontent.com/22802209/32532258-1e5ed246-c417-11e7-8c3b-6677dc229c83.jpg)

Repo: [benknoble/quiver-dracula](https://github.com/benknoble/quiver-dracula)

**Comment by benknoble** [comment]
@zenorocha Thanks for the invite; I'm glad you like the theme !

For the team section, who specifically do I include ?

**Comment by zenorocha** [comment]
Awesome! About your questions I...

* Added a page on the site: https://github.com/dracula/dracula.github.io/commit/d61e85fc8b091324a20d93d55abb7eac936bad57
* Made some changes on the theme repo: https://github.com/dracula/quiver/commit/93a98adb43dff2303c9e0b14958bb44c41be114b https://github.com/dracula/quiver/commit/9fc947e7a98274f6c58f33fd3c11c49eb3078920 https://github.com/dracula/quiver/commit/d506ee3fbad39e42e83b78fcf4b318a6f06e44db
* Added as a submodule on the main repo: https://github.com/dracula/dracula-theme/commit/0e92547dcf274302bcf3411334989289385e97d3

I think we can close this now. Feel free to share it online @benknoble ;)

👉 https://draculatheme.com/quiver/

**Comment by benknoble** [comment]
Epic ! Thanks for your work maintaining this amazing theme 😱

**Comment by zenorocha** [comment]
You got it ;D Thank you for your contribution 👻
