### ISSUE TITLE
Dracula for Steam

### ISSUE THREAD

**Issue by Trollwut** [dracula/dracula-theme#251]
Hi guys! Recently I switched to Dracula everywhere, because this color scheme just rocks! Unfortunately there hasn't been a Steam skin, but well, I did it!

You can find information about that [in my repository](https://github.com/Trollwut/Dracula-by-Trollwut) and if you like, you can use or edit it as you wish. Also there are instructions on how to install it and a screenie.

See the [TODO section](https://github.com/Trollwut/Dracula-by-Trollwut#todo), as there are two little things I'd like to have changed.

Also I'll mail the Steam Customizer guys (the tool I used to create this) if it's ok to publish it.

Have fun with it!

**Comment by zenorocha** [comment]
Hey @Trollwut, that's great!

I just cloned your repo and pushed all the commits to a [new one over here](https://github.com/dracula/steam). I also sent you an invite to join the Dracula org. You'll continue maintaining this project, the only difference is that we can make it more visible and include it on the [site](https://draculatheme.com).

We have the screenshot and instructions already, that's great! The next steps would be normalizing the README so it looks like the [template we did](https://github.com/dracula/template).

What do you think?

**Comment by duttaditya18** [comment]
@Trollwut Colors are a little bit all over the place. Some work needs to be done.

**Comment by Trollwut** [comment]
@zenorocha Hey, that sounds great! Would like to do it that way. I joined the org, just tell me how to go on. I'll do changes to fit the template in time! :)

@duttaditya18 Yes, as being said in the README.md. Unfortunately I'm not that skilled in theming Steam and just got a quick version up for now. I'll look over it when I have some time or maybe someone else knows it already. :)

**Comment by Trollwut** [comment]
@zenorocha Hey mate! Despite I'm being late for just a couple of minutes, I finally changed it to the Dracula's readme template.

I already pushed it to your linked repo. Please tell me what you think!

**Comment by PopeRigby** [comment]
How is this coming along?

**Comment by Trollwut** [comment]
May you clarify your question?

The wished changes have been made in this repo, if this is what you asked for: https://github.com/dracula/steam :)

**Comment by PopeRigby** [comment]
I thought it was going to be put on the website.

**Comment by Trollwut** [comment]
@zenorocha may know more :)

**Comment by hacknug** [comment]
Feel free to open a PR in [the site's repo](https://github.com/dracula/dracula.github.io/) and I'll merge it in asap.

Closing this as the theme has been moved to the repo 👍
