### ISSUE TITLE
Dracula for Rider

### ISSUE THREAD

**Issue by noshitsherlock** [dracula/dracula-theme#252]
## Rider

Using the theme everywhere, just switched to Rider and would love support for a theme there.

**Comment by zenorocha** [comment]
Hey @noshitsherlock, have you checked https://github.com/dracula/jetbrains?

**Comment by noshitsherlock** [comment]
[**@zenorocha**](https://github.com/zenorocha) commented on [Dec 5, 2017, 5:35 PM GMT+1](https://github.com/dracula/dracula-theme/issues/252#issuecomment-349361045 "2017-12-05T16:35:03Z - Replied by Github Reply Comments"):
> Hey [@noshitsherlock](https://github.com/noshitsherlock), have you checked [https://github.com/dracula/jetbrains](https://github.com/dracula/jetbrains)?

hmms.. did not think that would work, but it did 😆 Just had to change the style font to consolas and increase the font size 👍

**Comment by zenorocha** [comment]
Awesome!
