### ISSUE TITLE
Dracula for Mattermost

### ISSUE THREAD

**Issue by milouse** [dracula/dracula-theme#253]
Hi there!

I've just published a new theme for [mattermost](https://about.mattermost.com/) based on your color palette.

Repo: https://github.com/milouse/mattermost
Screenshot: ![Screenshot of dracula theme for mattermost](https://github.com/milouse/mattermost/raw/master/mattermost.png)

**Comment by zenorocha** [comment]
That's awesome @milouse! What do you think of transferring it to the dracula org? You'll still be the maintainer and responsible one to make decisions about the theme, it's just to help people to find it easier.

**Comment by milouse** [comment]
Thanks for your quick reply @zenorocha. I'm totally willing to transfer it to dracula org :) It's a pleasure to contribute as I can to such a great theme !

**Comment by zenorocha** [comment]
Awesome, you should receive an invitation to join the organization. After that you can move the repository.

**Comment by milouse** [comment]
[Migration done](https://github.com/dracula/mattermost) :) Thanks for your trust!

**Comment by zenorocha** [comment]
Awesome :D

I'll add it to the website now!
