### ISSUE TITLE
Visual Studio for Mac (community) ?

### ISSUE THREAD

**Issue by docoder** [dracula/dracula-theme#255]
I use Visual Studio for Mac (community) now. Anyone will consider creating a new theme to support that ?

**Comment by zenorocha** [comment]
Have you tried this https://draculatheme.com/visual-studio?

**Comment by docoder** [comment]
Sure.
It can not seem to apply to Visual Studio for Mac

**Comment by docoder** [comment]
My fault 😅.
[https://draculatheme.com/visual-studio](https://draculatheme.com/visual-studio) is usable。
Preferences -> Text Editor -> Color Theme -> Add.

**Comment by zenorocha** [comment]
Nice!
