### ISSUE TITLE
Dracula for jGrasp

### ISSUE THREAD

**Issue by peter-er** [dracula/dracula-theme#258]
Hey, I made Dracula for jGrasp. I'm new to GitHub so sorry if I did a few things wrong (like I don't think I was supposed to fork the template).

[Dracula for jGrasp](https://github.com/peter-er/jGrasp-dracula)

![jgraspdracula](https://user-images.githubusercontent.com/3751731/34923451-d9bd4f68-f950-11e7-8294-b46d5ecca429.png)

**Comment by zenorocha** [comment]
Hey @peter-er!

First of all, sorry for taking so long to reply. 

Now about your theme... I'm glad to see a theme for jGrasp! You did a great job for a new GitHub user ;)

I just cloned your repo and pushed all the commits to a [new one over here](https://github.com/dracula/jgrasp). I also sent you an invite to join the Dracula org. You'll continue maintaining this project, the only difference is that we can make it more visible and include it on the [site](https://draculatheme.com).

We have the screenshot already, that's great! The next steps would be adding instructions on how to install it. You can leave them here and I can put them on the site.

You can also update some of the information on the README like the [team section](https://github.com/dracula/jgrasp#team).

Anyways, thanks for the contribution!

**Comment by zenorocha** [comment]
Hey @peter-er, any news about this? I'm afraid we'll have to archive the repository in case we don't hear from you since there are no instructions for people to use the theme.

**Comment by peter-er** [comment]
Hi @zenorocha, so sorry. I updated it awhile ago but I only did my personal repository and not the actual one. I think it should be good now.

**Comment by hacknug** [comment]
Hey @peter-er 👋 Would you mind pushing the changes to the org repo?

**Comment by peter-er** [comment]
@hacknug Does it look OK now?

**Comment by hacknug** [comment]
Thank you so much! I also wanted to ask you if there's any reason to keep both repos active? Won't this make it harder for you to maintain?

(Closing the issue since the org repo is now 👌)
