### ISSUE TITLE
Dracula Wordpress dashbord

### ISSUE THREAD

**Issue by oguhpereira** [dracula/dracula-theme#259]
It's the new theme for wordpress admin dashbord.
I add rename on folder for instalation.

panel{
#44475a BackgroundHover
}

Subpainel{
Cyan selectForeground;
green hoverForeground
}

https://github.com/oguhpereira/dracula-theme/tree/master/wordpress
![screenshot from 2018-01-23 00-54-13](https://user-images.githubusercontent.com/24482087/35255825-22bd7d9a-ffd8-11e7-8298-f871b8c7380a.png)

**Comment by sleepiejohn** [comment]
Hi @oguhpereira could you please create a repository on your account with a README following our [template](https://github.com/dracula/template) ? This will ensure consistency and inclusion on the website. Thanks 😸

**Comment by oguhpereira** [comment]
Thank you for your feedback.
I created the respository [Dracula theme for WordPress](https://github.com/oguhpereira/Dracula-WordPress)
:smile:
