### ISSUE TITLE
Keyboard theme

### ISSUE THREAD

**Issue by karlbateman** [dracula/dracula-theme#261]
Hey all,
I created a configuration for the online [Keyboard Layout Editor](http://www.keyboard-layout-editor.com/) which you can load to create Dracula themed keycaps.

![draculatheme_coloured_num_theme](https://user-images.githubusercontent.com/33239151/35779989-83eb8f7c-09cd-11e8-810d-d17aecc90a65.png)

The configuration to load is available [here](https://gist.github.com/karlbateman/c094b116584b53db0a75d7365b5b3d70)

I'm not sure where else to mention this, so hope it's alright creating an issue here. I hope you approve :smile:

**Comment by omgitsjoao** [comment]
I think I will replicate the layout on my Chroma, see what it looks like 😸

**Comment by zenorocha** [comment]
Hey @karlbateman, that's great!

I'll go ahead and great a repository to host that configuration file. I'll also invite you to participate on the Dracula organization, so you can make any changes you want to that theme.

What do you think?

**Comment by karlbateman** [comment]
@zenorocha That's great, thank you.

**Comment by zenorocha** [comment]
Hey @karlbateman, I still didn't have a chance to create the repository. Would you mind create one based on the [template we created](https://github.com/dracula/template)? I can move to the organization right after.

**Comment by zenorocha** [comment]
Awesome ;D
