### ISSUE TITLE
New BBEdit theme

### ISSUE THREAD

**Issue by pudge** [dracula/dracula-theme#262]
Here's my repo: https://github.com/pudge/bbedit-dracula

<img width="752" alt="bbedit" src="https://user-images.githubusercontent.com/15170/35995593-b682ffe4-0cc8-11e8-889b-5610fb4f23e2.png">

**Comment by duttaditya18** [comment]
Looks cool.

**Comment by zenorocha** [comment]
Hey @pudge, that's awesome man!

I just cloned your repo and pushed all the commits to a [new one over here](https://github.com/dracula/bbedit). I also sent you an invite to join the Dracula org. You'll continue maintaining this project, the only difference is that we can make it more visible and include it on the [site](https://draculatheme.com).

We have the screenshot already, that's great! The next steps would be adding instructions on how to install it. You can leave them here and I can put them on the site.

What do you think?

**Comment by pudge** [comment]
Sounds great. I’ll get that soon. Thanks!

**Comment by pudge** [comment]
Here's the instructions, @zenorocha.  Let me know what else you need.

[instructions.md.txt](https://github.com/dracula/dracula-theme/files/1728491/instructions.md.txt)

**Comment by zenorocha** [comment]
Awesome!

* Added a page on the site: https://github.com/dracula/dracula.github.io/commit/cd852744e5d1e9c082026c59aba35de65c87c6fc
* Made some changes on the theme repo: https://github.com/dracula/bbedit/commit/e4bda3b9257e64a6a096b587081bb445cd701f0e https://github.com/dracula/bbedit/commit/286ca3206e02a05ddcd825ee5a716eeb5da45499
* Added as a submodule on the main repo: https://github.com/dracula/dracula-theme/commit/3ac84c2e25a370e79216790307bddbfc9127f93d

I think we can close this now. Feel free to share it online @pudge ;)

👉 https://draculatheme.com/bbedit/
