### ISSUE TITLE
@ Emacs : M-x package-install <RET> dracula-theme  command is not working.  Error: Package not found.

### ISSUE THREAD

**Issue by Devaashish-23** [dracula/dracula-theme#263]
## New Theme?

We would love to support all code editors out there, but we need your help to accomplish that. Feel free to create a new theme based on our [color palette](https://github.com/dracula/dracula-theme#color-palette).

## Existing Theme?

Consider fixing the issue yourself. That's the best way to contribute ;)

If that doesn't work, take a screenshot that shows the actual bug and mention the [specific maintainer](https://github.com/dracula/dracula-theme#team) of your theme.

**Comment by zenorocha** [comment]
Hey @Devaashish-23, if you're having problem with Emacs, please open an issue on: https://github.com/dracula/emacs

**Comment by Devaashish-23** [comment]
I already tried that but the problem is not with the website.
It's the package.
On executing **M-x package-install <RET> dracula-theme**
Error: **Package not found**
