### ISSUE TITLE
Dracula for gitk

### ISSUE THREAD

**Issue by AurelienLourot** [dracula/dracula-theme#265]
Hey :) I've made a [Dracula theme for `gitk`](https://github.com/AurelienLourot/gitk).

![Screenshot](https://raw.githubusercontent.com/AurelienLourot/gitk/master/screenshot.png)

**Comment by sleepiejohn** [comment]
Hello @AurelienLourot  I created the repository at https://github.com/dracula/gitk and pushed your commits there

**Comment by zenorocha** [comment]
Hey @AurelienLourot, I added you to the GitHub organization ;)

**Comment by zenorocha** [comment]
And it's live! https://draculatheme.com/gitk/

https://github.com/dracula/gitk/commit/cd85c8a6671602a934f14388ae3b27f9166fe3cf
https://github.com/dracula/dracula.github.io/commit/1471dd7c16d8458cbd227f485aff3cfa0dfd6f8e
