### ISSUE TITLE
New Dracula theme for MindNode.app

### ISSUE THREAD

**Issue by eivindml** [dracula/dracula-theme#266]
Hi,

I'm a new Dracula fan 🧛🏻‍♂️ and a user of the mind mapping app MinNode for macOS, so I decided to create a theme file for it. 

Take a look:

<img width="1012" alt="screenshot" src="https://user-images.githubusercontent.com/202450/37768215-154d74d0-2dcd-11e8-9675-19bd03aa4bc2.png">

I've also created a repo and updated README etc. Take a look here, and let me know if there is anything else needed to approve this theme. https://github.com/eivindml/dracula-mindnode

**Comment by zenorocha** [comment]
That's sooo cool! I love Mindnode and use it all the time, it's great to see a Mindnode theme for it ;)

**Comment by zenorocha** [comment]
It's live! https://draculatheme.com/mindnode/

https://github.com/dracula/mindnode/commit/474a812396e9531984425596aadcb2056f3f33ee
https://github.com/dracula/dracula.github.io/commit/78f93c21b9277bb7bf229c4c44d7e352ebcf17a0
