### ISSUE TITLE
Alacritty theme

### ISSUE THREAD

**Issue by clarfon** [dracula/dracula-theme#267]
I put together a color scheme that works in [alacritty](/jwilm/alacritty):

```
custom_cursor_colors: true
colors:
  primary:
    background: '0x282a36'
    foreground: '0xf8f8f2'
  cursor:
    text: '0x44475a'
    cursor: '0xf8f8f2'
  normal:
    black:   '0x282a36'
    red:     '0xff5555'
    green:   '0x50fa7b'
    yellow:  '0xf1fa8c'
    blue:    '0x6272a4'
    magenta: '0xff79c6'
    cyan:    '0x8be9fd'
    white:   '0xf8f8f2'
  bright:
    black:   '0x44475a'
    red:     '0xff8888'
    green:   '0x82fba0'
    yellow:  '0xf7fcbd'
    blue:    '0x828fb7'
    magenta: '0xffacdc'
    cyan:    '0xbdf3fe'
    white:   '0xffffff'
  dim:
    black:   '0x14151b'
    red:     '0xff2222'
    green:   '0x1ef956'
    yellow:  '0xebf85b'
    blue:    '0x4d5b86'
    magenta: '0xff46b0'
    cyan:    '0x59dffc'
    white:   '0xe6e6d1'
```

You just have to replace the `colors` section in `~/.config/alacritty/alacritty.yml` with this.

**Comment by sleepiejohn** [comment]
Hi @clarcharr could you please create a repository on your account with a README following our [template](https://github.com/dracula/template) ? This will ensure consistency and inclusion on the website. Thanks 😸

**Comment by leandropincini** [comment]
Hello @sleepiejohn 
I didn't realize this issue is already open before crate my repo as requested. But can I?

Repo:
https://github.com/leandropincini/alacritty

Screen:

https://github.com/leandropincini/alacritty/raw/master/dracula-alacritty.png

TIA
Best Regards!

**Comment by timorunge** [comment]
I think adding a screenshot which is showing Alacritty completely would help; as well an "how to apply the colors for alacritty" as already done by @clarfon in his description. :)

**Comment by clarfon** [comment]
My profile explicitly says I use they/them/their pronouns; please do not use "his" for me.

I appreciate you making a template repo; I currently don't have the time for this but I'm glad someone else does. :)

**Comment by leandropincini** [comment]
Hello you :)

@timorunge Any special command that you want into the screenshot?

@clarfon Tks, by the way, I wish to add you into the credits (after @timorunge response) if there are no problems, of course.

**Comment by timorunge** [comment]
I'm sorry, @clarfon. I was not reading your profile. 

@leandropincini I'd follow the schema which is used in:

- https://draculatheme.com/iterm/
- https://draculatheme.com/terminal/

**Comment by leandropincini** [comment]
@timorunge done

**Comment by sleepiejohn** [comment]
thanks guys!
@zenorocha could you please put https://github.com/leandropincini/alacritty under the organization? thanks!

**Comment by leandropincini** [comment]
@zenorocha @sleepiejohn can I change the repository's name? TIA

**Comment by leandropincini** [comment]
@zenorocha @sleepiejohn @timorunge  news?

**Comment by hacknug** [comment]
Hey @leandropincini! 👋 I've just invited you to the organization. Feel free to transfer the repo whenever you have a moment.

**Comment by leandropincini** [comment]
@hacknug  Hi! 
https://github.com/dracula/alacritty

Done.

**Comment by hacknug** [comment]
@leandropincini thank you!
