### ISSUE TITLE
New theme: Mutt

### ISSUE THREAD

**Issue by paultownsend** [dracula/dracula-theme#268]
I have created a theme for the Mutt email client:

![Screenshot](https://i.imgur.com/XZbANR1.png)

Repository: https://github.com/paultownsend/dracula-mutt

**Comment by zenorocha** [comment]
It's live! https://draculatheme.com/mutt

https://github.com/dracula/dracula.github.io/commit/34b9cda1b0591654a9a7cb26c0f8451acc62d9f6
https://github.com/dracula/mutt/commit/6a521416618ffb677157f56e61a7bc3d7cef4d03
