### ISSUE TITLE
GitHub Pages Dracula

### ISSUE THREAD

**Issue by backlands** [dracula/dracula-theme#270]
I have created a GitHub Pages theme using Dracula that I am planning on maintaining moving forward. I was wondering if it could get added to the organization and the repository? Let me know your thoughts, you can find it over at [backlands/dracula](https://github.com/backlands/dracula). A screenshot is below and you can view a page at the [github.io page](https://backlands.github.io/dracula/).

![Image of GitHub Pages Dracula](https://raw.githubusercontent.com/backlands/dracula/master/thumbnail.png)

**Comment by sleepiejohn** [comment]
Hello @backlands I created the repository at https://github.com/dracula/jekyll and pushed your commits there

**Comment by zenorocha** [comment]
Hey guys!

A Dracula theme for GitHub Pages, that's exciting!

I just added you @backlands to the organization, you should be able to edit now.

Before I include it on the site, would you mind applying the template we created for the README and LICENSE? https://github.com/dracula/template

Thanks!

**Comment by zenorocha** [comment]
Another question, which name do you think it's more appropriate `dracula-jekyll` or `dracula-ghpages`?

**Comment by backlands** [comment]
Great, thanks a bunch @zenorocha!

I have edited the README and adjusted the LICENSE slightly to match the template linked. I will make further changes to the README once we nail down the permanent repository name.

On that note, I think that dracula/ghpages would be more fitting, because while the theme would most likely _work fine_ with any jekyll site, it would require quite a few changes by the user to remove and add elements they need. I also do not plan to provide support for full jekyll use, only GitHub Pages.

### GitHub Pages Preview & Travis CI

On another note, I tried to enable the repos GitHub Pages preview, however since the org is remapped to draculatheme.com we will need to setup this one a little special.

As you said the theme info will be at draculatheme.com/ghpages, so I think it would be appropriate to have the preview at draculatheme.com/ghpages/preview.

Travis CI will also need to be enabled and I plan to do that once the repository is at it's new name.

**Comment by zenorocha** [comment]
It's live! https://draculatheme.com/gh-pages/

https://github.com/dracula/gh-pages/commit/e3560267ad69dfc70254446442ee9894fa0543ab
https://github.com/dracula/dracula.github.io/commit/1eca9a43fadd5ed19e87a8dfae7247aa5353d4c0
