### ISSUE TITLE
Include new maintainers for their repositories

### ISSUE THREAD

**Issue by sleepiejohn** [dracula/dracula-theme#271]
This is mostly directed to @zenorocha since he has the proper rights on the organization.

We need to include the maintainers of the themes that are in the [issues tagged promote](https://github.com/dracula/dracula-theme/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Apromote). Also include them as modules for this repository.

I went ahead and created the repositories for them, there is a comment on each issue pointing to them.

PS for maintainers of new repositories: I could not include you into the organization, wait for @zenorocha to include so you can start manage the repositories under the org.

**Comment by zenorocha** [comment]
Just added them all ;)

Thank you so much @sleepiejohn for taking the initiative to create those repos!

**Comment by sleepiejohn** [comment]
Also a shoutout to @AurelienLourot who pinged me about it!
