### ISSUE TITLE
I created a Dracula theme for Prism.js which isn't listed in this repository

### ISSUE THREAD

**Issue by gusbemacbe** [dracula/dracula-theme#272]
Hello,

I didn't fix two bugs for 3 years because of my college, but today I saw somebody interested in my theme and wanting to use it, I have solved today and just finished fixing the bugs. I have updated the version of Prism.

[Prism](https://github.com/PrismJS/prism) is a syntax highlighting developed by @LeaVerou, like Highlight.js. It is popular. 

You can check my repository: 

https://github.com/gusbemacbe/dracula-prism

There is a demo in my repository.

Pick only `dracula-prism.css` and `prism.js`.

Do not forget of adding the font PT Mono for CSS. 

Gustavo Costa

**Comment by AurelienLourot** [comment]
Thanks a lot @gusbemacbe ! In order to accept your theme we need to bring your `README.md` closer to [this template](https://github.com/dracula/template). Is it OK for you? You can still keep your additional doc/sentences in a separate file, e.g. in your `index.html`.

**Comment by gusbemacbe** [comment]
Yes, I do. But I do not understand.

Do you suggest I copy the Dracula for X to my readme and all my instructions to my index? I'm a bit confused. 

Please, can you explain me the steps?

**Comment by AurelienLourot** [comment]
yes exactly, your README has to look like "Dracula for X" where you replace X (and other things of course, like put your own name/avatar as a contributor, fix the links). That means you'll have to delete many of your text. Moving your text somewhere else instead of deleting it was just a suggestion.

**Comment by gusbemacbe** [comment]
Ready, I copied README template to mine. I moved the instructions to my index.html.

You are free to modify my index.html if you want to improve.

**Comment by gusbemacbe** [comment]
Ready and merged.

**Comment by AurelienLourot** [comment]
@gusbemacbe I have cloned your repo to https://github.com/dracula/prism and made you admin :) @zenorocha I believe this is enough? If yes, the issue can be closed.

@gusbemacbe note that your readme is still pointing to https://gusbemacbe.github.io/dracula-prism/ and when you'll delete your old repo, this website will be down. Probably you'll want to serve your website based on our new repository, and it will have a different URL.

**Comment by gusbemacbe** [comment]
I suggest I transfer my repository to you, @AurelienLourot. 

If you think it is not bad idea, please, show me the steps.

**Comment by gusbemacbe** [comment]
I thought I understood.

1. I will remove my old repository.
2. Modify the settings of new repository to enable Github Pages.
3. Change the links.

Right?

**Comment by AurelienLourot** [comment]
:+1: exactly, thanks :)

**Comment by gusbemacbe** [comment]
Ready. 

If you suggest I change the geek vampire geek icon for another, do not hesitate. And if you suggest I improve something, ask me somehting.

**Comment by gusbemacbe** [comment]
Another suggestion - add Prism.js to your website because Prism.js is one of most popular syntax highlighting libraries or plugins. Besides, Lea Verou, Prism.js's author, is very known for the programming conferences.

**Comment by gusbemacbe** [comment]
@zenorocha and @AurelienLourot,

Should my `index.html` look like https://draculatheme.com/highlightjs/ to improve it? I read Dracula Themes site (dracula.github.io) is under MIT.

**Comment by gusbemacbe** [comment]
I found a Haloween icon to Prismjs icon to replace the geek vampire. It is a crystall ball, used by witches. Does it make sense?

**Comment by AurelienLourot** [comment]
Looks like I'm totally wrong: I see that your `index.html` is being served at https://draculatheme.com/prism. Not sure what is happening.

**Comment by gusbemacbe** [comment]
Great, @AurelienLourot. I hope Zeno considerate it.
