### ISSUE TITLE
messed up for groovy scripts

### ISSUE THREAD

**Issue by rojagit** [dracula/dracula-theme#276]
## Existing Theme?

Groovy scripts - I had installed the groovy user-defined lang, and after I installed this theme the colors got inversed and look like this
![image](https://user-images.githubusercontent.com/4193031/39451364-6cc6f45a-4c9c-11e8-801c-3d126280758a.png)

**Comment by zenorocha** [comment]
What software is this? Please open an issue on the right repository: https://github.com/dracula

**Comment by rojagit** [comment]
I posted here coz I downloaded and used the theme from https://github.com/dracula; after which the groovy script shows like this; maybe it is an issue of the groovy user-lang-def which I down loaded from https://gist.github.com/Thermionix/9ff4a362f2bdc026c0ec - So maybe I will post it there

**Comment by zenorocha** [comment]
My question was what theme for what software? From your snippet I noticed it was Notepad++, so the appropriate repository would be https://github.com/dracula/notepad-plus-plus.

**Comment by rojagit** [comment]
Had no clue Dracula was for different software...thanks for the info !

**Comment by sleepiejohn** [comment]
Yes, we have different implementations for each editor, so you can find more help in the theme repository for your editor ☺️
