### ISSUE TITLE
SublimeText Instructions: No package found

### ISSUE THREAD

**Issue by aklap** [dracula/dracula-theme#279]
> If you are using Package Control, you can easily install Dracula Theme via the Package Control: Install Package menu item. The Dracula Theme package is listed as Dracula Color Scheme in the packages list.

Searching in packages doesn't find any package with the name Dracula or Dracula Color Scheme.

**Comment by zenorocha** [comment]
Hey @aklap, thanks for reporting. I checked the package control and it seems like everything is correct. Can you try this one? https://packagecontrol.io/packages/Dracula%20Color%20Scheme
