### ISSUE TITLE
Dracula for Typora

### ISSUE THREAD

**Issue by oguhpereira** [dracula/dracula-theme#280]
I created dracula theme to [Typora](https://typora.io/).
my repository is https://github.com/oguhpereira/Dracula-Typora
![image](https://user-images.githubusercontent.com/24482087/41059279-6ce57c9a-69a2-11e8-860f-80738dbd9185.png)

**Comment by hacknug** [comment]
Hey @oguhpereira 👋 Would you like to move the theme to the organization?

**Comment by oguhpereira** [comment]
Yes @hacknug  :smile:

**Comment by hacknug** [comment]
Just invited you. Let me know once you've moved the repo and I'll set the repo's permissions.

**Comment by oguhpereira** [comment]
created https://github.com/dracula/dracula-typora

**Comment by hacknug** [comment]
All set. Thank you! :tada:
