### ISSUE TITLE
Firefox Color Theme

### ISSUE THREAD

**Issue by eduardomoroni** [dracula/dracula-theme#281]
Firefox just launched [Firefox Color](https://color.firefox.com/) a new theme system for Firefox.
I've tried to create support for this new awesome theme system, but I failed.

Could anyone with more expertise create and share with us?
https://github.com/dracula/dracula-theme#color-palette

Thanks

**Comment by hacknug** [comment]
Like this? https://color.firefox.com/?theme=XQAAAALrAAAAAAAAAABBqYhm849SCiazH1KEGccwS-xNVAVU52hsH-vWaG_44BqU3aonaJe5I4Ohp5xTZgxNtKhNXqWhWjJPgwg1qKVhJcS2YIc92lM34bCs2ived0PtTJd62px8cBPBzotac9o2JRtKIh4-9mnar7Goflxrvy7X2t78g10W7CH4gjVFzCEHhpncSSmuJECJCbs20r5OS81K_WbZCWHsemq5Ngm11KJbfhM2__QLLQA

**Comment by eduardomoroni** [comment]
Awesome, looks gorgeous!
Thanks @hacknug.

**Comment by hacknug** [comment]
@zenorocha should we add this to the site and maybe create a new repo for it?

**Comment by JulioVMelo** [comment]
i`m created one theme in the new version on firefox 
[Dracula dark theme](https://addons.mozilla.org/pt-BR/firefox/addon/draculadarktheme/)

**Comment by JulioVMelo** [comment]
@zenorocha

**Comment by zenorocha** [comment]
Closing since we already have this theme live:
* https://draculatheme.com/firefox
* https://github.com/dracula/firefox
* https://addons.mozilla.org/en-US/firefox/addon/dracula-dark-colorscheme/
