### ISSUE TITLE
Block representation/hint for Notepad++

### ISSUE THREAD

**Issue by sumanbk92** [dracula/dracula-theme#282]
Hi,

Recently i installed the **dracula** theme for **notepad++**.
But i wonder why there is no hint of the **current block**.
Many in-built theme styles have got block hints.  

I mean at least an underline for the brackets - { and }, would be helpful.
Please add a way to represent the same.

Image :
![issue](https://user-images.githubusercontent.com/8256637/42234989-e7ff9d76-7f13-11e8-915e-51ca5d607311.png)

Tested on:

- Notepad++ Version 7.5.6
- Placed Dracula.xml in %AppData%\Notepad++\themes

**Comment by zenorocha** [comment]
Issue moved to [dracula/notepad-plus-plus #8](https://github.com/dracula/notepad-plus-plus/issues/8) via [**ZenHub**](https://www.zenhub.com/)
