### ISSUE TITLE
Anyone have their own mobile Telegram theme?

### ISSUE THREAD

**Issue by itsmoirob** [dracula/dracula-theme#283]
I know theres a desktop telegram, but anyone have a mobile telegram theme? Wanted to ask first before I start manually creating one

**Comment by hacknug** [comment]
Hey @huezo :wave: Would you like to transfer your repo to the organization and become a maintainer?

**Comment by huezo** [comment]
Yes, I think it is very good to move the repository to the organization and be a maintainer.

**Comment by huezo** [comment]
> Hey @huezo wave Would you like to transfer your repo to the organization and become a maintainer?

Yes, I think it is very good to move the repository to the organization and be a maintainer.
I would like to participate in the organization, and upload the topic I agree to participate.

**Comment by hacknug** [comment]
@huezo I've just invited you to join the org. Once you accept, transfer the repo to the org and let me know over here. I'll set the right permissions and rename. Let me know if you have any questions 👍

**Comment by huezo** [comment]
> @huezo I've just invited you to join the org. Once you accept, transfer the repo to the org and let me know over here. I'll set the right permissions and rename. Let me know if you have any questions


I already made the repository:
[https://github.com/dracula/telegram-android](https://github.com/dracula/telegram-android)

**Comment by hacknug** [comment]
Sweet! Just noticed the README.md doesn't use the org's template. Could you please change it so it does? https://github.com/dracula/template

**Comment by huezo** [comment]
> Sweet! Just noticed the README.md doesn't use the org's template. Could you please change it so it does? https://github.com/dracula/template

**Hello, I already modified the README.md, could you tell me if everything is ok like that?**
[telegram-android](https://github.com/dracula/telegram-android)

**Comment by hacknug** [comment]
Perfect! Thank you so much :tada:
