### ISSUE TITLE
Dracula theme doesn't show git branch name

### ISSUE THREAD

**Issue by sim4life** [dracula/dracula-theme#284]
My dracula theme is working fine on my macOS High Sierra Terminal except that it doesn't show any git branch name and I've to type `git branch` every time.
Any suggestions?

<img width="1068" alt="platform_ _-bash_ _151x46_and_app_store" src="https://user-images.githubusercontent.com/302743/42447344-730c02c2-8371-11e8-9396-37586d6d77db.png">

**Comment by zenorocha** [comment]
This is done by https://github.com/dracula/zsh
