### ISSUE TITLE
New theme for i3

### ISSUE THREAD

**Issue by gkroon** [dracula/dracula-theme#285]
I've created a new theme for [i3](https://i3wm.org/) @ https://github.com/gkroon/dracula-i3.

![Screenshot](https://github.com/gkroon/dracula-i3/raw/master/dracula-i3.png)

**Comment by hacknug** [comment]
Hey @gkroon :wave: Just sent you an invitation to join the org. After accepting it, you can transfer the theme to the organization and I'll set the right permissions so you can push changes directly to it. Let me know if you have any questions about the process 👍

**Comment by gkroon** [comment]
@hacknug Thanks! I accepted your invitation, added a new [repo](https://github.com/dracula/i3) and copied all my work to this new repo. I also deleted my own repo so everything is in your organisation now.

**Comment by hacknug** [comment]
Thank you so much! You actually didn’t need to create a new one, only move it. That way GitHub would have created redirections for users looking for your repo haha. No problem though 👍
