### ISSUE TITLE
Install Question/Issue 

### ISSUE THREAD

**Issue by dlionz** [dracula/dracula-theme#288]
Hello, Im pretty new to Vim and I was hoping to install the dracula theme however my colors are looking a bit funky. 

@nesl247

here is my vimrc file 
```
34 " Vim Plug
 33 call plug#begin('~/.vim/plugged')
 32 "My Plugins
 31 Plug 'valloric/youcompleteme', {'do': './install.py --js-completer'}
 30 Plug 'marijnh/tern_for_vim'
 29 Plug 'scrooloose/nerdtree'
 28 Plug 'pangloss/vim-javascript'
 27 Plug 'othree/html5.vim'
 26 Plug 'mxw/vim-jsx'
 25 Plug 'elzr/vim-json'
 24 Plug 'jelera/vim-javascript-syntax'
 23 Plug 'hail2u/vim-css3-syntax'
 22 Plug 'cakebaker/scss-syntax.vim'
 21 Plug 'myusuf3/numbers.vim'
 20 Plug 'othree/javascript-libraries-syntax.vim'
 19 Plug '1995eaton/vim-better-javascript-completion'
 18 " Airline
 17 Plug 'vim-airline/vim-airline'
 16 Plug 'vim-airline/vim-airline-themes'
 15 " CtrlP
 14 Plug 'ctrlpvim/ctrlp.vim', { 'on': 'CtrlP' }
 13 " Color Schemes
 12 Plug 'dracula/vim',{'as':'dracula'}
 11 " NERD Commenter
 10 Plug 'scrooloose/nerdcommenter'
  9 " vim-ripgrep
  8 Plug 'jremmen/vim-ripgrep'
  7 " Surround
  6 Plug 'tpope/vim-surround'
  5 " Syntastic
  4 Plug 'vim-syntastic/syntastic'
  3 call plug#end()
  2 " Initialize plugin system
  1 call plug#end()
43  "set termguicolors
  1 "colorscheme material-monokai
```

and here is a screen shot of what its looking like currently 
<img width="780" alt="screen shot 2018-08-23 at 9 26 42 pm" src="https://user-images.githubusercontent.com/14165549/44561750-d12ad180-a71b-11e8-9a2f-b2b555dca99b.png">
 
Im not super sure whom I should be tagging either so apologies for that as well. Please let me know if I can provide more info.

thanks!

**Comment by zenorocha** [comment]
Issue moved to [dracula/vim #105](https://github.com/dracula/vim/issues/105) via [**ZenHub**](https://www.zenhub.com/)

**Comment by zenorocha** [comment]
Issue moved to [dracula/vim #106](https://github.com/dracula/vim/issues/106) via [**ZenHub**](https://www.zenhub.com/)
