### ISSUE TITLE
Eclipse

### ISSUE THREAD

**Issue by msmosso** [dracula/dracula-theme#29]
Wouldn't it be nice to create a theme for Eclipse? Check it out http://eclipsecolorthemes.org/?view=firsttheme :)

**Comment by ryanolsonx** [comment]
I know this is an old issue, but I'd love to have a color theme for eclipse. I see that there are some dracula themes on [Eclipse Color Themes](http://www.eclipsecolorthemes.org/?view=theme&id=31377). Can we make an official one? What would we name it?

**Comment by hacknug** [comment]
Reopening this because it's been requested once again and maybe someone would like to help putting an official version together 🙏

**Comment by zenorocha** [comment]
Seems like Eclipse Color Theme is down: https://www.reddit.com/r/eclipse/comments/f8rv55/eclipse_color_theme_is_down_and_there_is_no

So I'm not sure if we can proceed with that. If you're looking at this message in the future and you'd like to see a Dracula theme for Eclipse, please create a theme and submit. You can find more info about how to contribute here: https://draculatheme.com/contribute

**Comment by scottzach1** [comment]
Hi guys, 

Ihave been playing around a bit with what can be done regarding Eclipse.
Not the most knowledgeable with the software (assignments are marked in them).

Anyways, I found that the closest you can get to a full IDE theme is using the [Darkest Dark](https://marketplace.eclipse.org/content/darkest-dark-theme-devstyle) from the Eclipse Marketplace.

This is what I was able to produce: https://github.com/scottzach1/dracula-theme-eclipse

Although still not perfect, let me know what you guys think :).

Cheers Zac.

**Comment by zenorocha** [comment]
It looks great @scottzach1! I'd love to have this as an official theme. 

Can you make some adjustments for the site?

1. Add a INSTALL.md with instructions
2. Use the same README.md pattern
3. Rename screenshot to `screenshot.png`

**Comment by scottzach1** [comment]
Hi @zenorocha, made those changes and [repo](https://github.com/scottzach1/dracula-theme-eclipse) now follows the official template. I wasn't super sure what to do regarding the [draculatheme.com](http://draculatheme.com/) hyperlinks. But I guessed what they might likely become.

Happy for it to be put up on the official repo. Let me know if there is anything else that needs to be done / changed :).

Cheers Zac.

**Comment by zenorocha** [comment]
That's awesome @scottzach1! Great work 🎉 

I just sent you an invitation to join the Dracula org, once you accept you can transfer the repository, and I'll handle the site part.

**Comment by scottzach1** [comment]
Lovely! The repo has now been transfered to [dracula/eclipse](https://github.com/dracula/eclipse) :)

**Comment by zenorocha** [comment]
It's live! https://draculatheme.com/eclipse 🎉 🎉 🎉 

Thanks @scottzach1, I can't believe we're going to close an issue from Nov 18, 2013 lol
