### ISSUE TITLE
Request: Theme for protonmail

### ISSUE THREAD

**Issue by Link512** [dracula/dracula-theme#290]
It'd be awesome if we can have a dracula theme for [proton mail](https://protonmail.com/)

**Comment by zenorocha** [comment]
Hello @Link512, feel free to create one and send it over https://github.com/dracula/dracula-theme#are-you-going-to-support-editor-x. Thanks for using Dracula!

**Comment by mamyn0va** [comment]
It's there: https://github.com/csalmeida/protonmail-themes/blob/master/themes/dracula/dracula.css
