### ISSUE TITLE
Highlight colour is too dim (in SublimeText)

### ISSUE THREAD

**Issue by CottonEaster** [dracula/dracula-theme#291]
## Existing Theme?

Yes. 
> Consider fixing the issue yourself. That's the best way to contribute ;)
I do not really have the knowledge to do that, I am afraid.

If that doesn't work, take a screenshot that shows the actual bug and mention the [specific maintainer](https://github.com/dracula/dracula-theme#team) of your theme.

Screenshot (with the first of the two `readonly` lines selected/highlighted, believe it or not):

![image](https://user-images.githubusercontent.com/9998846/46382795-c2cdbf00-c6a4-11e8-86bf-a531ad564448.png)

That is using, within Sublime, the `Agila Dracula` 'theme' and the `Dracula Markdown` 'colour scheme'. There's an 'Agila Dracula' colour scheme available too, but it doesn't change the highlighting from what I have pictured here.

Specific maintainer: none given on `https://github.com/dracula/dracula-theme#team`.

It seems to be (compare #156) that the selection colour needs to stand out a bit more.

**Comment by zenorocha** [comment]
Issue moved to [dracula/sublime #16](https://github.com/dracula/sublime/issues/16) via [**ZenHub**](https://www.zenhub.com/)
