### ISSUE TITLE
New theme for Windows 10 Console (cmd.exe and powershell)

### ISSUE THREAD

**Issue by waf** [dracula/dracula-theme#292]
> EDIT: This is now complete. See [dracula/powershell](https://github.com/dracula/powershell) for the theme. Supports both the normal terminal and the new Windows 10 Terminal.

Hi, I've created a new theme for the default terminal in Windows 10 (both cmd.exe and powershell). Even though a lot of developers are probably using conemu or cmder, it's good to have the basic terminal look nice too.

I have a [dracula-cmd](https://github.com/waf/dracula-cmd/) repo based on the template repo. Here's a screenshot:

![dracula](https://raw.githubusercontent.com/waf/dracula-cmd/master/images/screenshot.png)

For reference, the default terminal, with no theming applied, looks like this: ![default](https://www.howtogeek.com/wp-content/uploads/2017/02/Windows_106-650x300.jpg)

For now, I've added the installation instructions in the readme. I can replace it with a link to the website if this new theme is approved. Thanks!

**Comment by tplk** [comment]
Isn't it basically [iTerm](https://github.com/dracula/iterm) theme?

**Comment by waf** [comment]
It's close to the iterm theme (based off the itermcolors) but has a modification to support the different way that iterm and Windows handle background colors. Windows supports a colortable with 16 colors, iterm supports more, so it's not a 1-to-1 mapping.

In addition, it provides a custom prompt for both cmd and powershell, along with fixes when used with posh-git and psreadline. PSReadLine is bundled with Windows and posh-git is a very popular library for developers on Windows.

**Comment by tplk** [comment]
I actually think that Windows 10 terminal supports 256 colors. At least, work for me in WSL.
![image](https://user-images.githubusercontent.com/20531968/46578530-68699100-ca0b-11e8-85b7-b80d7347f5a5.png)

**Comment by waf** [comment]
You're right about the color display capabilities, but when we're talking specifically about the colortable it only supports 16 (but each color in the table supports full rgb). See https://github.com/Microsoft/console/issues/23#issuecomment-365079360 for details. That entire issue has good context.

**Comment by zenorocha** [comment]
That's great @waf! I love seeing better support for Windows tools.

Do you want to join the [dracula organization](https://github.com/dracula)? That way we can go ahead and feature your theme on the website. No worries you'll still be the main maintainer of the repository and have control over the future of the theme. 

If you're ok with that, I sent you an invitation, after you accept it you should be able to transfer the repository. Thanks and good job!

**Comment by waf** [comment]
Thanks @zenorocha, I've joined the organization and transferred the repository.

Just a heads up, I renamed the repository to `powershell`, as that more accurately reflects how the repository has evolved; it used to be cmd.exe only. Please let me know if you have concerns about this name.

I'd like to spend a bit of time tweaking the README to reflect this change, and after that should I open a PR against the dracula.github.io repository? Thanks!

**Comment by zenorocha** [comment]
https://draculatheme.com/powershell ;)

**Comment by gregnau** [comment]
In case anyone else feels like doesn't want to go through the install procedure, here is a simple reg file colorscheme for Windows Prompt:

`
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Console]
"ColorTable00"=dword:00362A28
"ColorTable01"=dword:00F993BD
"ColorTable02"=dword:007BFA50
"ColorTable03"=dword:00FDE98B
"ColorTable04"=dword:005555FF
"ColorTable05"=dword:00C679FF
"ColorTable06"=dword:008CFAF1
"ColorTable07"=dword:00F2F8F8
"ColorTable08"=dword:00A47262
"ColorTable09"=dword:00FFACD6
"ColorTable10"=dword:0094FF69
"ColorTable11"=dword:00FFFFA4
"ColorTable12"=dword:006E6EFF
"ColorTable13"=dword:00DF92FF
"ColorTable14"=dword:00A5FFFF
"ColorTable15"=dword:00F2F8F8
`

[dracula_scheme_windowsprompt.zip](https://github.com/dracula/dracula-theme/files/5917790/dracula_scheme_windowsprompt.zip)

**Comment by pankace** [comment]
nice, thanks
