### ISSUE TITLE
 New theme for Couscous 

### ISSUE THREAD

**Issue by BilelJegham** [dracula/dracula-theme#295]
I make a template for Couscous which generates a GitHub pages website from your markdown documentation (http://couscous.io/).

![screenshot](https://user-images.githubusercontent.com/20130405/46895035-2fe01200-ce66-11e8-9fbb-d642b740c5f9.png)
The repo : https://github.com/BilelJegham/DraculaThemeCousous

Never forget Couscous is good  :smiley:

**Comment by hacknug** [comment]
Hey @BilelJegham 👋 Would you like to move the theme to the organization?

**Comment by BilelJegham** [comment]
Great idea @hacknug ! 🤩

**Comment by hacknug** [comment]
Just sent you the invite! let me know once you've moved the repo and I'll change the permissions 😃

**Comment by BilelJegham** [comment]
Done !

**Comment by hacknug** [comment]
Thanks @BilelJegham! Permissions set and repo renamed 🎉
