### ISSUE TITLE
Dracula theme for kitty

### ISSUE THREAD

**Issue by keegancsmith** [dracula/dracula-theme#296]
A dark theme for [kitty](https://sw.kovidgoyal.net/kitty/).

https://github.com/keegancsmith/kitty-dracula

![Screenshot](https://user-images.githubusercontent.com/187831/46914836-1abccd80-cfa3-11e8-9d59-c0be8736175d.png)

**Comment by keegancsmith** [comment]
Ping

**Comment by mienaikage** [comment]
I should have probably checked the issues before creating my own :see_no_evil:

https://github.com/mienaikage/kitty-theme-dracula

![screenshot from 2019-01-05 00-07-42](https://user-images.githubusercontent.com/966706/50717894-bc275d00-1082-11e9-8d59-50d5ba6cf252.png)

**Comment by hacknug** [comment]
Hey @keegancsmith 👋 Would you like to move the theme to the organization?

@mienaikage yours was updated more recently. Any changes that should be backported to the other repo?

**Comment by keegancsmith** [comment]
@hacknug yup, happy to do that and take in changes from @mienaikage.

**Comment by hacknug** [comment]
Just invited you to the org. Feel free to migrate the repo whenever and I'll set the permissions so you can push changes directly.

**Comment by keegancsmith** [comment]
Looks like it migrated properly :) https://github.com/dracula/kitty-dracula

**Comment by hacknug** [comment]
@keegancsmith permissions set and repo renamed to `kitty`. Thank you!
