### ISSUE TITLE
VSCode Javascript File lost Certain Color Highlight

### ISSUE THREAD

**Issue by weitieda** [dracula/dracula-theme#299]
Hi,

In VSCode, I have a styles.js file, but for the const declared at top, when I use them below, it's not highlighted with color. 

Is it normal?

Thanks

![image](https://user-images.githubusercontent.com/35972055/49167752-0ee35b80-f304-11e8-95bb-5217acfaeb85.png

**Comment by dsifford** [comment]
The javascript syntax changed recently and removed the support for highlighting assignments in all caps as constants.

So to answer your question: Yes, this is the new normal.

**Comment by weitieda** [comment]
> The javascript syntax changed recently and removed the support for highlighting assignments in all caps as constants.
> 
> So to answer your question: Yes, this is the new normal.

Alright, thanks for your reply.
