### ISSUE TITLE
Fish syntax theme

### ISSUE THREAD

**Issue by mienaikage** [dracula/dracula-theme#303]
I've noticed there are a few previously closed issues regarding fish themes, but those appear to be relating to the prompt. I have a colorscheme which is purely for fish's syntax highlighting, set via the color variables specified in the [fish documentation](https://fishshell.com/docs/current/index.html#variables-color). This has no effect on the prompt selected by the user.

![screenshot from 2019-01-05 22-49-18](https://user-images.githubusercontent.com/966706/50730099-1f75c580-113d-11e9-971e-002ba6be9868.png)

I'm happy to create a repo of there is interest in the syntax coloring.

EDIT: I merged in a color swap mentioned in a following comment.

**Comment by mienaikage** [comment]
I created a branch and shuffled around a few colors.

![screenshot from 2019-01-06 11-24-22](https://user-images.githubusercontent.com/966706/50735407-824f7700-11a6-11e9-83be-3d2fbc9b66f8.png)

**Comment by timorunge** [comment]
Added some colors for "fish_pager_color_XXX".

**Comment by hacknug** [comment]
Hey @mienaikage 👋 Would you like to move the theme to the organization? You'd need to add the installation instructions and a screenshot to the readme first.

**Comment by mienaikage** [comment]
@hacknug Installation instructions and screenshot have been added.

**Comment by hacknug** [comment]
Perfect! I just invited you to the organization so you can transfer the repo. Let me know once you've done it and I'll set the right permissions so you cna push changes directly.

**Comment by mienaikage** [comment]
Ownership transferred, name is still currently `fish-theme-dracula`.

**Comment by hacknug** [comment]
Thank you so much for your contribution! Just set the right permissions so you can take care of it from now on. Let me know if you ever need my help with anything 👍
