### ISSUE TITLE
Dracula for MobaXterm

### ISSUE THREAD

**Issue by Phuurl** [dracula/dracula-theme#308]
😱 Dracula theme for [MobaXterm](https://mobaxterm.mobatek.net)

[https://github.com/Phuurl/dracula-mobaxterm](https://github.com/Phuurl/dracula-mobaxterm)

![Screenshot](https://raw.githubusercontent.com/Phuurl/dracula-mobaxterm/master/dracula-mobaxterm.png)

**Comment by Phuurl** [comment]
Pinging @zenorocha if you get chance to add this

**Comment by hacknug** [comment]
@Phuurl just sent you an invite to join the organization. Once you've joined we can move your repo to it. Let me know if there's anything else you need me to do 👍

**Comment by Phuurl** [comment]
@hacknug Cool, I've moved it over - could you give me write/admin permissions to that repo? Need to drop the 'dracula-' from the name.
https://github.com/dracula/dracula-mobaxterm

**Comment by hacknug** [comment]
@Phuurl just did! I've replicated the settings on other repos so I think this should be enough.

**Comment by Phuurl** [comment]
👍 renamed it - was going to add it to the site as well, but it sounds like you might be rewriting it soon - would it be better for me to wait until that's done before adding it?

**Comment by hacknug** [comment]
I'll be using the content of the repo for the new version so feel free to add it whenever you can. Only issue is I can't publish new versions of the current site due to the contributors section on every page being broken 😢
