### ISSUE TITLE
Dracula for all websites

### ISSUE THREAD

**Issue by pavel-agarkov** [dracula/dracula-theme#309]
## New Theme: [Dracula - Midnight Lizard color scheme](https://midnight-lizard.org/schemes/index/full/ad0ef141-360c-4cf7-906e-110f4bf3b276)
I've implemented Dracula color theme in Midnight Lizard web-extension ([Chrome](https://chrome.google.com/webstore/detail/midnight-lizard/pbnndmlekkboofhnbonilimejonapojg), [Firefox](https://addons.mozilla.org/en-US/firefox/addon/midnight-lizard-quantum)).
With this extension installed Dracula color theme can be used on all websites.
Please check it out and let me know if something should be fixed.
## Screenshots
![DuckDuckGo](https://res.cloudinary.com/midnight-lizard/cs/ad0ef141-360c-4cf7-906e-110f4bf3b276/duckduckgo/800x500.jpg)

![Wikipedia](https://res.cloudinary.com/midnight-lizard/cs/ad0ef141-360c-4cf7-906e-110f4bf3b276/wikipedia/800x500.jpg)

![Medium](https://res.cloudinary.com/midnight-lizard/cs/ad0ef141-360c-4cf7-906e-110f4bf3b276/medium/800x500.jpg)

Technically Midnight Lizard color scheme is represented by the following zipped json file: [dracula.zip](https://github.com/dracula/dracula-theme/files/2800059/dracula.zip)

**Comment by guerremdq** [comment]
Looks like that Json is not compatible with the newer version of the plugin.  Attached the converted to the new format
[dracula.json.zip](https://github.com/dracula/dracula-theme/files/3081889/dracula.json.zip)

**Comment by pavel-agarkov** [comment]
@guerremdq - both formats are correct and actual.
mine is for publishing color schemes
yours is for installation

But users don't need any json files - color scheme can be installed in one click from [midnight-lizard.org](https://midnight-lizard.org/schemes/index/full/ad0ef141-360c-4cf7-906e-110f4bf3b276)

**Comment by hacknug** [comment]
Hey @pavel-agarkov @guerremdq :wave: Would you like to create a repo with screenshots, installation instructions and annything needed to maintain this theme? That way we could have it in the organization and people could report any issues they encounter with the theme.

[My Pythonista theme](https://draculatheme.com/pythonista/) is also one of this weird edge cases and I'll probably be doing this after I've gone through all of the issues on the repo and rebuilt the site 😇

**Comment by NicTanghe** [comment]
It works verry wel this should be added to the main repo.
Dit you make a fork and give it a propper discription ?

If yiu do those things and try and get a hold of the peeps they should give you push acces.

**Comment by pavel-agarkov** [comment]
@hacknug do I need to create a repo under my organization and then transfer it to dracula?

**Comment by hacknug** [comment]
Yeah, you should clone [the template repo](https://github.com/dracula/template), make any changes you need to showcase your theme and explain how everything works (take a look at any of the other repos in the org if you need an example), and then you can transfer your repo to the @dracula org.

Not sure if @zenorocha needs anything else for the new site, haven't been able to help out much lately (good thing he's back haha).

**Comment by pavel-agarkov** [comment]
@hacknug I've created the repo: https://github.com/pavel-agarkov/midnight-lizard
But I cannot transfer it to dracula org: You don’t have the permission to create public repositories on dracula

**Comment by hacknug** [comment]
@pavel-agarkov I think you'll first need to "fix" the fact your repo shows as a fork of the template. I don't think we can transfer this until it is its own repo. Everything else looks correct :+1:

**Comment by Dhyfer1** [comment]
Interesting, but I don't want to see all the pages with the Dracula theme, just the search results from Google and Bing. I think I'll take a look at "Dracula for all websites" ;)
