### ISSUE TITLE
Dracula for Arduino IDE

### ISSUE THREAD

**Issue by STiXzoOR** [dracula/dracula-theme#310]
😱 Dracula for [Arduino IDE](https://www.arduino.cc/en/main/software)

I created a dracula theme for Arduino IDE. I know it's not perfect but there is plenty of room for improvements. You can check it out [here](https://github.com/STiXzoOR/Dracula-for-Arduino).

![Screenshot](https://raw.githubusercontent.com/STiXzoOR/Dracula-for-Arduino/master/img/screenshot.png)

**Comment by hacknug** [comment]
Hey @STiXzoOR 👋 Would you like to move the theme to the organization?

**Comment by STiXzoOR** [comment]
Hello, yeah sure 👍

**Comment by hacknug** [comment]
Just sent you the invite to join the team. Let me know once you've transferred the repo and I'll set the right permissions!

**Comment by STiXzoOR** [comment]
Ok, i think i have transferred the repo to the organisation

**Comment by hacknug** [comment]
All set. Thank you so much for your contribution!
