### ISSUE TITLE
Dracula for Wing Python IDE

### ISSUE THREAD

**Issue by sdeibel** [dracula/dracula-theme#311]
https://github.com/sdeibel/dracula-wing -- already contains the screenshot

Thanks!

**Comment by hacknug** [comment]
Hey @sdeibel  👋 Would you like to move the theme to the organization?

**Comment by sdeibel** [comment]
Not sure what you mean but Dracula is already shipped with Wing.

**Comment by hacknug** [comment]
Just saw your comment about _Wing 7 beta2+_. Do you think it’s still worth keeping around for earlier versions of the software?

**Comment by sdeibel** [comment]
If https://draculatheme.com/ only contains entries for software that doesn't come with the theme, then I suppose no real need for adding Wing Python IDE there, although Wing 6 users do need to manually install the theme and there are still many of those.

**Comment by hacknug** [comment]
Then maybe it would be a good idea to move it to the org and leave the instructions the way you have them now. This way users of the old version that look for the theme will find it, and also see a note telling them about the new features of version 7. What do you think?

**Comment by sdeibel** [comment]
Sounds fine, thanks.  I've removed the reference to beta2+, so it just says Wing 7+ since at this point nobody is using beta1 and earlier.

**Comment by hacknug** [comment]
Perfect! just sent you the invitation to join the org. Let me know once the repo’s been transferred, and I’ll set the right permission so you can push directly to it 👍

**Comment by sdeibel** [comment]
Nestor Vera wrote:
>
> Perfect! just sent you the invitation to join the org. Let me know 
> once the repo’s been transferred, and I’ll set the right permission so 
> you can push directly to it 👍
>

I've initiated the transfer and was asked which teams to allow access 
and selected Wing so maybe the permissions part is already all set.

Thanks,

- Stephan

**Comment by hacknug** [comment]
@sdeibel sorry for the late reply. All good. Please let me know if you need help with anything else. Thank you for your contribution! 🎉
