### ISSUE TITLE
Why does the ZSH theme look nothing like dracula?

### ISSUE THREAD

**Issue by marbuser** [dracula/dracula-theme#312]
So I'm just curious as to why the ZSH dracula theme looks nothing like the others themes.

I've become accustom to a look like below;
![image](https://user-images.githubusercontent.com/34422459/52160701-2fa9a200-26f5-11e9-8869-093ed45e6783.png)

But instead, the ZSH theme looks like this (which is really ugly if I'm honest...)
![image](https://user-images.githubusercontent.com/34422459/52160702-3cc69100-26f5-11e9-8103-3d55da82ed31.png)

Is there any particular reason for this? Are we supposed to do something extra or what?

**Comment by tryton-vanmeer** [comment]
You would need to set the theme of your terminal to Dracula to get the right colours. 

I assume that's the default Terminal in MacOS? If so, this is what you want https://draculatheme.com/terminal/

**Comment by marbuser** [comment]
> You would need to set the theme of your terminal to Dracula to get the right colours.
> 
> I assume that's the default Terminal in MacOS? If so, this is what you want https://draculatheme.com/terminal/

Thanks but I've already done that. I'm using iTerm2.
If I open iTerm it's black like the image shown in OP, but if I open a new tab or a new window, it shows the Dracula colours. Any idea how to fix this? 🤔

**Comment by tryton-vanmeer** [comment]
Hmm, that's an odd issue. I'm not familiar with iTerm, so not sure  of any fixes. Only thing I can think of is an option for setting the default profile.

**Comment by marbuser** [comment]
Very odd. Managed to fix this by just resetting my iTerm completely. Seems to be working now. Must have been some sort of error/corruption in my profile.

Thanks for the help. :)
