### ISSUE TITLE
Dracula for LimeChat

### ISSUE THREAD

**Issue by shmink** [dracula/dracula-theme#313]
<img width="917" alt="screenshot 2019-02-04 at 12 12 29" src="https://user-images.githubusercontent.com/4008082/52209016-7248b700-287a-11e9-9818-dd1021158a0e.png">

[Repo](https://github.com/shmink/dracula-limechat)

I suppose still a work in progress but updating as I go along.

**Comment by shmink** [comment]
Anything new with this? Feedback or anything?

**Comment by hacknug** [comment]
I tried to get in touch with @zenorocha on Slack to see how I could help him maintain the organization. Hopefully he'll see this and maybe reach out soon.

**Comment by shmink** [comment]
@zenorocha let me know what you're thinking about this issue. At the least, some feedback would be nice so I could improve.

**Comment by hacknug** [comment]
Hey @shmink 👋 Would you like to move the theme to the organization?

**Comment by shmink** [comment]
Yes that sounds great. The only issue is I no longer have a mac to test and update the theme for limechat and future updates. With that in mind however the code should all be fine and with your approval, I'll go ahead and do what you suggest,

**Comment by hacknug** [comment]
Just sent you the invite! Let me know once you've move the repo and I'll change the permissions.

I wouldn't worry too much about that for now. If there's anything that needs to be updated people will probably open a issue to complain about it. I'll add myself as a member of the team to make sure I'm also notified 👍

**Comment by shmink** [comment]
Apologies for the tardy responses. I haven't received any invitation I'm afraid. With that, I'll be able to move the repo to the organisation?

**Comment by shmink** [comment]
Update: There was definitely no notification that I received but I just used [the following](https://stackoverflow.com/a/44028010) answer to accept. I then went into the settings of my limechat repo and transferred the ownership to `dracula`. Hopefully, that's worked out.

**Comment by hacknug** [comment]
Just changed the repo name and set the right permissions. Let me know if you need my help with anything else. Thank you for your contribution!
