### ISSUE TITLE
ZSH theme needs a new maintainer.

### ISSUE THREAD

**Issue by AGitBoy** [dracula/dracula-theme#314]
The zsh theme needs a new maintainer. The [issue](https://github.com/dracula/zsh/issues/1) was opened two years ago on the zsh repository, and has not been touched since. I have been the only person to volunteer as a maintainer, and it has been left ignored for two days, and from the looks of it, there hasn't been any activity since over a year ago.

So, it is my hope that by bringing it to the main repo's issue tracker, this issue will be given more attention.

**Comment by hacknug** [comment]
Hey @AGitBoy :wave: Thanks for bringing this up! I've just sent you an invitation to join the org and become a part of @dracula/zsh so you can help taking care of it from now on.
