### ISSUE TITLE
Dracula for ulauncher

### ISSUE THREAD

**Issue by cweagans** [dracula/dracula-theme#315]
## New theme: [Dracula for ulauncher](https://github.com/cweagans/dracula-ulauncher)

I've released a theme for [ulauncher](https://ulauncher.io). I'd be glad to transfer it to the dracula org if there's some interest.

**Comment by hacknug** [comment]
Hey @cweagans 👋 Would you like to move the theme to the organization?

**Comment by cweagans** [comment]
Sure!

**Comment by hacknug** [comment]
Just sent you the invite! let me know once you've move the repo and I'll set the right permissions so you can make changes.

**Comment by cweagans** [comment]
I have moved the repo. Sorry for the long delay.

I no longer use Linux, so I'm not sure how helpful I'll be in maintaining this long term. Feel free to do with it what you'd like though!

**Comment by zenorocha** [comment]
Thanks @cweagans!

Here's the Ulauncher theme on the site: https://draculatheme.com/ulauncher ;)
