### ISSUE TITLE
Create Dracula for Editplus

### ISSUE THREAD

**Issue by JRevirthuum** [dracula/dracula-theme#316]
Hi guys.

I created the Editplus theme.
I hope Editplus users like it.

thank you.

[Dracula for Editplus](https://github.com/JRevirthuum/dracula-theme-editplus)

**Comment by hacknug** [comment]
Hey @JRevirthuum 👋 Would you like to move the theme to the organization?

**Comment by JRevirthuum** [comment]
> Hey @JRevirthuum 👋 Would you like to move the theme to the organization?

I hope you do. 🙆🏼‍♂️

**Comment by hacknug** [comment]
Just sent you the invite to join the team. Let me know once you've moved the repo and I'll change the permissions so you can push changes directly. Thanks!
