### ISSUE TITLE
Dracula for Termite

### ISSUE THREAD

**Issue by 1337M0nst3r** [dracula/dracula-theme#319]
I made the Dracula color scheme for the Termite terminal emulator.

Here's the link to the repo: https://github.com/1337M0nst3r/dracula-termite

And here's the screenshot:
![screenshot](https://user-images.githubusercontent.com/34712352/54825071-59268900-4cb5-11e9-8cc8-495245b21a58.png)

**Comment by hacknug** [comment]
Hey @1337M0nst3r 👋 We already have https://github.com/dracula/termite, have you seen that?

**Comment by 1337M0nst3r** [comment]
@hacknug First, sorry for the late reply. I double checked before making this repository but I only looked at https://github.com/dracula/dracula-theme since I thought these were all the themes. Going to delete this repo once you see the reply.

**Comment by hacknug** [comment]
No need to apologize, we all have other things to take care of besides open-source 😉

Did you take a look at that repo? Anything that should be updated/fixed? // cc @dracula/termite

**Comment by 1337M0nst3r** [comment]
The highlight property is not set, it should be #44475a as in you color palette also the site at https://draculatheme.com/termite is not found. Hope it helps.

**Comment by hacknug** [comment]
@1337M0nst3r thanks for looking into this. Would you like to become a maintainer of the theme and make the changes yourself? Seems like the current maintainers are busy and I think it'd be cool to have an active user of the theme around in case someone has an issue or something.
