### ISSUE TITLE
Dracula for GameMaker Studio 2

### ISSUE THREAD

**Issue by tonystr** [dracula/dracula-theme#320]
# New theme for [GameMaker Stuido 2](https://www.yoyogames.com/gamemaker)

![Screenshot](https://user-images.githubusercontent.com/30723101/55037507-4e098b00-501e-11e9-9437-952f729ec06e.png)

Here's a link to the repository: [https://github.com/tonystr/Dracula](https://github.com/tonystr/Dracula)

**Comment by hacknug** [comment]
Hey @tonystr 👋 Would you like to move the theme to the organization?

**Comment by tonystr** [comment]
I sure would! Anything specific I should change first?

**Comment by hacknug** [comment]
Rename the repo to something like `gamemaker-studio` and it should be ready to move. just sent you the invite to the team!

**Comment by tonystr** [comment]
Already moved it! Lost permission to rename it though, could you handle that?

**Comment by hacknug** [comment]
Permissions set and repo renamed. Thank you for your contribution!
