### ISSUE TITLE
Geany theme

### ISSUE THREAD

**Issue by sergey27564** [dracula/dracula-theme#322]
![image](https://user-images.githubusercontent.com/16984827/56219115-de138100-606e-11e9-9582-4dc19ff62179.png)

https://github.com/sergey27564/geany-Dracula-Theme

**Comment by hacknug** [comment]
Hey @sergey27564 👋 Would you like to move the theme to the organization?

**Comment by sergey27564** [comment]
Yes :)
чт, 6 июн. 2019 г., 12:40 Nestor Vera <notifications@github.com>:

**Comment by hacknug** [comment]
Just sent you the invite. Let me know once you've joined the org and transfered the repo, and I'll set everything up.

**Comment by sergey27564** [comment]
joined, but i'll transfer repo later

чт, 6 июн. 2019 г., 12:55 Nestor Vera <notifications@github.com>:

**Comment by hacknug** [comment]
@sergey27564 just migrated the repo and set the permissions so you can push directly to it from now on. Thanks for your contribution!
