### ISSUE TITLE
Windows Terminal Theme

### ISSUE THREAD

**Issue by thismat** [dracula/dracula-theme#324]
I ported Dracula to the new Windows Terminal (Preview) app that was released because I use Dracula everywhere.

Figured I would contribute the theme here.

https://github.com/thismat/windows-terminal-dracula-theme

![Screenshot](https://raw.githubusercontent.com/thismat/windows-terminal-dracula-theme/master/screenshot.png)

**Comment by hacknug** [comment]
Hey @thismat :wave: Just sent you an invite to join the org so you can transfer the repo. Let me know once you've done that and I'll set the right permission so you can push changes directly.

Thanks for the contribution! 🎉

**Comment by thismat** [comment]
Hey @hacknug, great news! 

I have accepted the invite. And because I don't want to make a mistake in the transfer, you want it going to the `dracula` organization right? 👍 Thanks again!

**Comment by hacknug** [comment]
Yes!

**Comment by thismat** [comment]
Done!

**Comment by hacknug** [comment]
@thismat all set! Thank you so much for your contribution. Let me know if you need my help with anything else 🎉
