### ISSUE TITLE
Dracula theme for Oracle SQL Developer

### ISSUE THREAD

**Issue by apercova** [dracula/dracula-theme#326]
## New Theme

I've developed a theme based on the [color palette](https://github.com/dracula/dracula-theme#color-palette) for [Oracle SQL Developer](https://www.oracle.com/database/technologies/appdev/sql-developer.html) hosted at: [https://github.com/apercova/dracula-sqldeveloper](https://github.com/apercova/dracula-sqldeveloper).

![screenshot](https://raw.githubusercontent.com/apercova/dracula-sqldeveloper/master/images/dracula_syntax.png)

I've used the README's template, but by now the installation instructions point to [INSTALL.md](https://github.com/apercova/dracula-sqldeveloper/blob/master/INSTALL.md) file.

**Comment by apercova** [comment]
Hi @hacknug is there any advance on this.
Regards.

**Comment by hacknug** [comment]
@apercova I've just invited you to join the org. Once you accept, transfer the repo to the org and let me know over here. I'll set the right permissions and rename. Let me know if you have any questions 👍

**Comment by apercova** [comment]
Hi @hacknug 
I've created [sql-developer](https://github.com/dracula/sql-developer) repo at dracula org.
Install instructions are pointing to [INSTALL.md](https://github.com/dracula/sql-developer/blob/master/INSTALL.md). 
How can I get this instructions on web page at (https://draculatheme.com)[https://draculatheme.com]?

Regards

**Comment by hacknug** [comment]
Thanks! :tada:

Right now the build process for the website is broken bbut we're working on it. Don't worry, we'll take care of it soon™
