### ISSUE TITLE
Dracula for Eclipse

### ISSUE THREAD

**Issue by namitoyokota** [dracula/dracula-theme#327]
## New Theme?

We would love to support all code editors out there, but we need your help to accomplish that. Feel free to create a new theme based on our [color palette](https://github.com/dracula/dracula-theme#color-palette).

## Existing Theme?

Consider fixing the issue yourself. That's the best way to contribute ;)

If that doesn't work, take a screenshot that shows the actual bug and mention the [specific maintainer](https://github.com/dracula/dracula-theme#team) of your theme.

**Comment by hacknug** [comment]
Duplicate of #29
