### ISSUE TITLE
Dracula Theme for Windows Terminal

### ISSUE THREAD

**Issue by SebastianOner** [dracula/dracula-theme#328]
## New Theme
Recently Microsoft released the new Windows Terminal, I added the Color scheme to the configuration json and think other people could benefit from that as well
![image](https://user-images.githubusercontent.com/42720856/60430916-c1fb9680-9bfe-11e9-8b99-cf57a73a4f29.png)
[My Repo](https://github.com/SebastianOner/Dracula-Windows-Terminal)
I hope everything is according to code so far

**Comment by hacknug** [comment]
Hey @SebastianOner :wave: We already have a theme for the new [Windows Terminal](https://github.com/dracula/windows-terminal). If there's anything that could be improved/fixed, please open an issue on that repo to let the @dracula/windows-terminal know 😄
