### ISSUE TITLE
Dracula theme for Standard Notes

### ISSUE THREAD

**Issue by cameronldn** [dracula/dracula-theme#330]
## New Theme

I've created a new theme for [Standard Notes](https://standardnotes.org).
Hosted at: https://github.com/cameronldn/sn-theme-dracula

![Preview](https://raw.githubusercontent.com/cameronldn/sn-theme-dracula/master/preview.png)

**Comment by hacknug** [comment]
Hey @cameronldn! :wave: Would you like to move the theme to the organization?

**Comment by NetOperatorWibby** [comment]
OMG thanks for creating this. I thought I'd have to create the theme myself, SN is looking much better now.

**Comment by bigpick** [comment]
There is now a Dracula themed Standard Notes repository as part of the official org [here](https://github.com/dracula/standard-notes). @cameronldn , this could probably be closed now, right?
