### ISSUE TITLE
Konsole theme colors in incorrect order

### ISSUE THREAD

**Issue by ekaitz-zarraga** [dracula/dracula-theme#333]
Konsole theme has colors in incorrect order and that leads to a failed rendering as different issues of the project show:
https://github.com/dracula/konsole/issues/3
https://github.com/dracula/konsole/issues/2

The issues are supposed to be corrected by this pull request:
https://github.com/dracula/konsole/pull/4

But no response from the maintainer ( @rishabhsrao ) received.

Is there any way to get the changes merged or at least reviewed?

PS: I don't mind to be the new maintainer of the project if needed.

**Comment by rishabhsrao** [comment]
Hi! Sorry, I couldn't get back to you sooner. I've merged your pull request. I'll close this issue for now. Please feel free to reopen if you'd like to discuss something else. Thanks!
