### ISSUE TITLE
not able to download it in vscode 2019 pro version

### ISSUE THREAD

**Issue by rahul6612** [dracula/dracula-theme#334]
after searching in vs code extension search bar this theme does not appear why?
i am using vscode professional 2019

**Comment by hacknug** [comment]
Just checked and it's still available: https://marketplace.visualstudio.com/items?itemName=dracula-theme.theme-dracula

Maybe you're refering to @dracula/visual-studio?

**Comment by rahul6612** [comment]
i was trying to install it in visual studio professional 2019 unfortunately this extension is not available for visual studio professional but it is available for visual studio code.

**Comment by hacknug** [comment]
Yeah, it looks like there's a couple issues on the repo where people mention this. Maybe you could ask there so the maintainers and users can help you out? https://github.com/dracula/visual-studio
