### ISSUE TITLE
[Theme Request] tig(1)

### ISSUE THREAD

**Issue by silvioprog** [dracula/dracula-theme#335]
## New UI Theme for tig(1)

Could you please create a UI theme for [tig(1)](https://github.com/jonas/tig) following topic **UI colors** at https://jonas.github.io/tig/doc/tigrc.5.html?

Thank you!

**Comment by aftaylor2** [comment]
I'm using a Dracula terminal theme. Then I applied these changes to the tig config to help resolve contrast issues. By glancing at the docs it looks like the primary colors are limited. So a fully compliant Dracula theme may not be possible. You could try applying a theme on the terminal and then using this config:
```
# color default         white   black
color   cursor          black   green
color   search-result   black   yellow
# color author          green   black
# color status          green   black
color   line-number     red     black
color   title-focus     black   yellow
color   title-blur      black   magenta
# Diff colors
color diff-header       yellow  default
color diff-index        blue    default
color diff-chunk        magenta default
color "Reported-by:"    green   default
# View-specific color
color tree.date         black   cyan    bold
```

**Comment by zenorocha** [comment]
@aftaylor2 do you want to create a tig repository that includes installation instructions based on this suggestion you made?

https://github.com/dracula/template

**Comment by aftaylor2** [comment]
@zenorocha Yes, I will create a repo. I’m a bit busy at the moment, so please give me a few days.

**Comment by zenorocha** [comment]
@aftaylor2 friendly ping ;)

**Comment by aftaylor2** [comment]
Thanks for the reminder. Will get it to you later today.

**Comment by aftaylor2** [comment]
@zenorocha I created the repo. It currently is located at https://github.com/aftaylor2/dracula-tig . What are the next steps ?

**Comment by zenorocha** [comment]
We're live now!

https://draculatheme.com/tig 🎉 
https://github.com/dracula/tig 🎉 

Thanks @aftaylor2, feel free to delete that existing repository now.
