### ISSUE TITLE
[Theme Request] gdb(1) v8.3

### ISSUE THREAD

**Issue by silvioprog** [dracula/dracula-theme#337]
## New UI Theme for gdb(1) v8.3

Could you please create a UI theme for [gdb(1) v8.3](https://www.gnu.org/software/gdb) following the new command `set style` featured at https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;a=blob;f=gdb/NEWS?

Thank you!

**Comment by luxonauta** [comment]
I will close this Issue for organizational purposes, as it is an old request without community proposals. 😅
