### ISSUE TITLE
[New Theme] Insomnia

### ISSUE THREAD

**Issue by MatheusKProt** [dracula/dracula-theme#338]
## New Theme

I created a new theme for [Insomnia](http://insomnia.rest).
Hosted at: https://github.com/MatheusKProt/insomnia

![insomnia](https://user-images.githubusercontent.com/13322757/65794239-15b64700-e13e-11e9-8934-e7dfb873ad8e.png)

**Comment by MatheusKProt** [comment]
Readme created.

**Comment by hacknug** [comment]
@MatheusKProt I've just invited you to join the org. Once you're in, you'll be able to transfer the repo (make sure you actually transfer it so GitHub takes care of redirecting users to the new URL). Let me know once its done and I'll rename and set the right permissions 👍

**Comment by MatheusKProt** [comment]
@hacknug the transfer was made!

**Comment by hacknug** [comment]
All set. Thank you so much for your contribution! 🙌
