### ISSUE TITLE
New Dracula JetBrains UI plugin

### ISSUE THREAD

**Issue by WhiteVermouth** [dracula/dracula-theme#340]
#  Existing Theme

I've transferred the ownership of my personal JetBrains UI Plugin repository.
Location: https://github.com/dracula/jetbrains-dracula
This new theme may not coexist with the [old JetBrains Dracula theme](https://github.com/dracula/jetbrains).
Could you remove or mark deprecated the old repository.
PS: the author of the old JetBrains theme is no longer maintaining the theme. https://github.com/dracula/jetbrains/issues/33

**Comment by hacknug** [comment]
What do you think would be the best way to handle this update? (bunch of questions below, sorry)
- Is the old one still useful? If not, maybe we could tag the current version or move it to a different branch?
- What do you think would be the best to name the old repo? Would something like `legacy` work?

**Comment by WhiteVermouth** [comment]
- The old one is useful for users who use old version JetBrains IDEs ( version before 2019.1 ). This new UI plugin is only compatible with JetBrains IDEs 2019.1 or later.
- Rename the old one to "legacy-jetbrains" is a good choice, and thus this new one can be renamed to "jetbrains".

**Comment by hacknug** [comment]
All set. Thank you! 🙌
