### ISSUE TITLE
statusbar color 

### ISSUE THREAD

**Issue by betancour** [dracula/dracula-theme#346]
In the actual theme on vscode the status bar has an horrible color that don't allow to read the remote connection, I use this on my config to make it better

    "statusBarItem.remoteBackground": "#430f4d"

![image](https://user-images.githubusercontent.com/283403/67626445-f2a4b300-f821-11e9-829f-8da45604bf0a.png)

Please put in the next update to make it better for all.... 

regards Yitz

## New Theme?

We would love to support all code editors out there, but we need your help to accomplish that. Feel free to create a new theme based on our [color palette](https://github.com/dracula/dracula-theme#color-palette).

## Existing Theme?

Consider fixing the issue yourself. That's the best way to contribute ;)

If that doesn't work, take a screenshot that shows the actual bug and mention the [specific maintainer](https://github.com/dracula/dracula-theme#team) of your theme.

**Comment by JimmyMultani** [comment]
Hey @dsifford, could you take a look at this please?

**Comment by dsifford** [comment]
Feel free to open a PR @betancour. The background color that you select should be within spec though. The purple color you chose isn't part of the dracula pallette and would look off compared to everything else.

Original PR for that: dracula/visual-studio-code#105 (ping:  @misolori)

**Comment by betancour** [comment]
> Feel free to open a PR @betancour. The background color that you select should be within spec though. The purple color you chose isn't part of the dracula pallette and would look off compared to everything else.
> 
> Original PR for that: [dracula/visual-studio-code#105](https://github.com/dracula/visual-studio-code/pull/105) (ping: @misolori)

I know but that ugly pink makes bad constrast and you can read well, put another color or let it black who makes better constrast with white color....  😑😑😑😑😑

**Comment by dsifford** [comment]
Or use the background color as the font color.

I think I recall that there was a need to go with the vibrant color so that the user could be clearly aware they were working against a remote machine. I think we should try to follow that guidance with any changes we make.

At any rate: PRs accepted. Feel free to take a stab at it and we can talk more about it there.

**Comment by misolori** [comment]
You can always override this theme colors by adding this to your user settings (json):

```jsonc
"workbench.colorCustomizations": {
        "[Dracula]": {
            "statusBarItem.remoteBackground": "#0000"
        }
    }
```

And you can replace that hex with whatever color you want.

**Comment by betancour** [comment]
> You can always override these theme colors by adding this to your user settings (json):
> 
> ```js
> "workbench.colorCustomizations": {
>         "[Dracula]": {
>             "statusBarItem.remoteBackground": "#0000"
>         }
>     }
> ```
> 
> And you can replace that hex with whatever color you want
.
I've already did that, if you see my first post, but the question is make it possible to anyone who likes this fabulous theme....
