### ISSUE TITLE
Dracula for Vimium-FF (Firefox addon)

### ISSUE THREAD

**Issue by Trollwut** [dracula/dracula-theme#347]
I made a custom CSS for the Firefox addon [Vimium-FF](https://addons.mozilla.org/en-US/firefox/addon/vimium-ff/). 

If you want, it could be added to the collection of Dracula themes.

My repo is accessible here: https://github.com/Trollwut/vimium-dracula

**Comment by hacknug** [comment]
Hey @Trollwut 👋 `README.md` should look like [the template](https://github.com/dracula/template). If you could make a change and let me know once it's been updated, I'll invite you to the org so you can transfer the repo and maintain it there 👍

**Comment by Trollwut** [comment]
hey @hacknug !

Thanks for that! I've rewritten the README.md to fit to the template. Only the link to the contributers is not set yet, as I don't know how the repo's full name will be in the Dracula repo. :)

May you please have a look at it?

**Comment by hacknug** [comment]
Link will be `dracula/vimium` if it's also compatible with the linked Chrome version. Please confirm it will be.

Just sent you the invite to join the org. Once you join, you'll be able to transfer your repo to it (make sure you do this so GitHub takes care of redirecting users visiting your current URL). let me know once it's done and I'll set the right permission for you to take care of it 😉

**Comment by Trollwut** [comment]
yeah bby, tested it myself!

Working on Chromium 78 with the latest Vimium 1.64.6. Will tell you, when I tranfered the repo!

**Comment by Trollwut** [comment]
Aaaand it's transfered!

I selected *only* the Vimium group to have access to it. Please adjust if this wasn't sufficient.

Also please check if I did that right, as this was my first transfer of a repo :)

**Comment by hacknug** [comment]
@Trollwut everything looking good. Thank you so much for your contribution! 🎉
