### ISSUE TITLE
[New Theme] Termux

### ISSUE THREAD

**Issue by benjifs** [dracula/dracula-theme#350]
I created a new theme for Termux for Android.

You can find the repo with installation instruction here: https://github.com/benjifs/dracula-termux

![screenshot](https://user-images.githubusercontent.com/4167938/68988414-96b7c380-07fc-11ea-927b-e70ee1eb7ba5.jpg)

**Comment by hacknug** [comment]
Hey @benjifs 👋 I've just invited you to join the organization. Once you accept, you can transfer the repo to it and I'll set the right permissions so you can take care of it here 👍

**Comment by benjifs** [comment]
Thank you. I've transfered the repo but I think it needs to be renamed to match the current format. Once renamed, should I also add it to the `.gitmodules` file?

**Comment by hacknug** [comment]
@benjifs thank you! I just renamed the repo and set everything so you can take care of it from now on. Feel free to open a PR adding it to `.gitmodules`, yeah. just keep in mind they're ordered alphabetically :+1:
