### ISSUE TITLE
Dracula Dark Theme for Firefox

### ISSUE THREAD

**Issue by RaphGL** [dracula/dracula-theme#354]
[dracula-firefox repository](https://github.com/RaphK20/dracula-firefox)  
A dracula dark theme for firefox  
![screenshot](https://user-images.githubusercontent.com/28673457/69828700-657fc000-120c-11ea-8a8e-cb86bb936013.png)

**Comment by hacknug** [comment]
Do you happen to know the differences between yours and [this other theme](https://addons.mozilla.org/en-US/firefox/addon/draculadarktheme/)? Guessing these themes will also be slightly better than [whatever we can accomplish with Firefox Color](https://github.com/dracula/dracula-theme/issues/281#issuecomment-400628362), right?

**Comment by RaphK20** [comment]
> Do you happen to know the differences between yours and [this other theme](https://addons.mozilla.org/en-US/firefox/addon/draculadarktheme/)? Guessing these themes will also be slightly better than [whatever we can accomplish with Firefox Color](https://github.com/dracula/dracula-theme/issues/281#issuecomment-400628362), right?

I've looked it up and the theme you mentioned seem to have been made using Firefox Color, so the theme is not applied to the the home page, the popups and buttons properly and the color scheme used there is different as well, whereas mine is fully themed and written using JSON and the Manifest.json documentation.

The theme you mentioned:
![image](https://user-images.githubusercontent.com/28673457/70235620-d1a17d00-1752-11ea-96e5-09c5a1b46e88.png)

Mine:
![image](https://user-images.githubusercontent.com/28673457/70235690-f1d13c00-1752-11ea-8c5d-29c00d2e68d0.png)

**Comment by JimmyMultani** [comment]
Hey @RaphGL, we'd love to have this taken into the organization! Would you mind updating your repo to follow the template [here](https://github.com/dracula/template)? Thanks!

**Comment by RaphGL** [comment]
@JimmyMultani I've changed my repo to adhere to the template. Take a look and let me know if there's anything that needs some tweaking!

**Comment by JimmyMultani** [comment]
Hey @RaphGL, could you just update your avatar to match the template please? Link should be https://avatars2.githubusercontent.com/u/28673457?s=70.

Thank you!

**Comment by RaphGL** [comment]
@JimmyMultani Done.

**Comment by zenorocha** [comment]
That's awesome! I just invited you to the org, so know all you have to do is:

* Accept GitHub invitation
* Transfer the repository

Let me know if you have any questions.

**Comment by zenorocha** [comment]
It's live! Thanks @RaphGL 🎉 

https://draculatheme.com/firefox
