### ISSUE TITLE
Outdated instructions on draculatheme.com/jetbrains

### ISSUE THREAD

**Issue by rogerdahl** [dracula/dracula-theme#355]
The install instructions on draculatheme.com/jetbrains are outdated, referencing a non-existing `Dracula.icls` file. However, the README.md file in the `jetbrains-master` download describes an installation using a new plugin that works nicely.

Have you considered automatically generating the instructions on draculatheme.com based on the README.md file (or another file) that is part of this repository? That would help keep instructions in sync and allow instructions on draculatheme.com to be updated via `dracula-theme` PRs.

It's possible to create a fully automated process for rebuilding documentation, as is done on readthedocs.org, by configuring GitHub to send a signal to the doc site on commits.

**Comment by hacknug** [comment]
> Have you considered automatically generating the instructions on draculatheme.com based on the README.md file (or another file) that is part of this repository?
Yes. I talked to @zenorocha about this and we're planning on a website redesign that would introduce this change. Should happen at some point.

**Comment by zenorocha** [comment]
I'm happy to announce that this has been completed. Our site is now automatically generated based on a INSTALL.md file that is located on each individual theme.

THanks!
