### ISSUE TITLE
Broken link for jetbrains

### ISSUE THREAD

**Issue by rogerdahl** [dracula/dracula-theme#356]
The link for the `jetbrains` submodule at https://github.com/dracula/dracula-theme is broken.

You're not doing anything like `git push --force`, I hope...

**Comment by hacknug** [comment]
This is probably because we renamed [the old repo](https://github.com/dracula/jetbrains-legacy) to `jetbrains-legacy` and added [a new one for the recent versions](https://github.com/dracula/jetbrains). Would welcome a PR fixing this and adding the legacy one 👍

**Comment by zenorocha** [comment]
Just fixed that, thanks for reporting @rogerdahl!
