### ISSUE TITLE
[Theme request] Windows Subsystem for Linux

### ISSUE THREAD

**Issue by julianeden** [dracula/dracula-theme#360]
I have ubuntu running on Windows 10 through WSL and would love to get this theme in the shell it uses. Does anyone know if that's possible with any of these existing files, or does a new one need to be created?

**Comment by hacknug** [comment]
What's the terminal you're using on Ubuntu? Pretty sure there's something for it on the org's repos.

**Comment by julianeden** [comment]
Well, I'm not sure. It just says "Ubuntu" at the top. I'm not sure how to gain additional information about it. It's what runs by default when you install ubuntu with WSL.

**Comment by betancour** [comment]
Use the zsh on WSL and that fix what you need... there's plenty of manuals to do that.

**Comment by benknoble** [comment]
As @hacknug says, to customize a terminal's color palette, you need to know what the terminal is. Check the icon on the bottom bar (if Windows still does that) and see if you can find out which program is running.

**Comment by julianeden** [comment]
It seems to be Windows terminal. I'm currently trying to find out how to alter its theme.

**Comment by julianeden** [comment]
And yes I'll try to switch to zsh and see if that works. Still not sure where the dracula theme file would go for zsh on wsl though.

**Comment by betancour** [comment]
> And yes I'll try to switch to zsh and see if that works. Still not sure where the dracula theme file would go for zsh on wsl though.

https://draculatheme.com/zsh/

**Comment by betancour** [comment]
> I have ubuntu running on Windows 10 through WSL and would love to get this theme in the shell it uses. Does anyone know if that's possible with any of these existing files, or does a new one need to be created?

Julie also use the theme for CMD and Powershell this gonna display the colors on actual WSL terminal.
