### ISSUE TITLE
Dracula Theme For Centos 7

### ISSUE THREAD

**Issue by AmericanY** [dracula/dracula-theme#361]
I would like to have `Dracula` theme on my `Centos 7` server. I've checked the website and I'm unable to find it for `Centos` !

I'm connecting to my server via SSH on windows. and i know that i can color  the CMD or PowerShell but am looking for bash.

**Comment by zenorocha** [comment]
Hey @AmericanY, can you try using https://github.com/allamiro/dracula-bash or https://draculatheme.com/gnome-terminal.

Thanks!
