### ISSUE TITLE
Add google chrome theme to the Dracula official website

### ISSUE THREAD

**Issue by nickimola** [dracula/dracula-theme#364]
Hi

I have a theme for google chrome migrated to the organization almost 3years ago, but this was never featured nor mentioned on the official website.
Will you be able to add it please?
https://github.com/dracula/google-chrome

Thanks

**Comment by zenorocha** [comment]
Hey @nickimola, for sure! Thanks for your patience.

**Comment by zenorocha** [comment]
It's live! https://draculatheme.com/chrome
