### ISSUE TITLE
peacock vs code extension

### ISSUE THREAD

**Issue by shmink** [dracula/dracula-theme#365]
## New Theme

Peacock extension on vs code you can choose _favourite _colours__ so of course it had to be the dracula colour palette.

https://gist.github.com/shmink/01e977af077dd3070842b2ae9de64cf1

I can add as a repo if it's liked.

**Comment by shmink** [comment]
Update: I created a repo for it.

https://github.com/shmink/dracula-peacock-extension

**Comment by luxonauta** [comment]
Hey, very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/shmink/dracula-peacock-extension)
- [New repository.](https://github.com/dracula/peacock-extension)

Thanks for building this! 🎉
