### ISSUE TITLE
dracula-theme on emacs

### ISSUE THREAD

**Issue by avatar-lavventura** [dracula/dracula-theme#369]
The way I run `emacs`:

`TERM=xterm-256color emacs -nw <my_file>`

---

I am trying to have background on `dracula-theme` (https://github.com/dracula/dracula-theme). 

[![enter image description here][1]][1]

---

I have added following line into `.emacs`:

`(add-to-list 'default-frame-alist '(background-color . "#282a36"))`

Expected color:

[![enter image description here][2]][2]

but some blue color show up instead:

[![enter image description here][3]][3]

  [1]: https://i.stack.imgur.com/gB3KV.png
  [2]: https://i.stack.imgur.com/uTkZO.png
  [3]: https://i.stack.imgur.com/y3IGH.png

**Comment by benknoble** [comment]
Have you tried https://github.com/dracula/emacs/tree/master?

**Comment by avatar-lavventura** [comment]
Yes I have also followed (https://draculatheme.com/emacs/) guide, and back ground was black possible bug (https://github.com/dracula/emacs/issues/32).

**Comment by avatar-lavventura** [comment]
Please follow here (https://github.com/dracula/emacs/issues/32) for further updates
