### ISSUE TITLE
Dracula in Azure Data Studio

### ISSUE THREAD

**Issue by julienrbrt** [dracula/dracula-theme#370]
[Azure Data Studio](https://github.com/microsoft/azuredatastudio) seems to be based on Visual Studio Code.

Simply copying the Dracula extension installed from VScode into Azure Data Studio, leads to a satisfactory result:

![image](https://user-images.githubusercontent.com/29894366/74030323-0f1ec280-49af-11ea-916f-66e0811cf58b.png)

Would be however easier if the extension could be published in the Azure Data Studio extension store.

**Comment by chris-larsen** [comment]
Any update on this?

**Comment by Desmo46** [comment]
I would like to request this too please

**Comment by frank-yifei-wang** [comment]
I had success in manually downloading the **theme extension (.vsix file)** for VS Code and installing in Azure Data Studio. However I'd love to see Azure Data Studio being able to natively install those theme extensions.

For those who want to try my manual hack:
1. Go to VS Code Marketplace, **"Download Extension"** and save the .vsix file
2. Go to Azure Data Studio, Ctrl+Shift+P to open the command palette, **"Extensions: Install from VSIX..."**

**Comment by luxonauta** [comment]
That's cool; maybe @dsifford can help us make this a reality, as he's the theme maintainer for VSCode.

I also found a [how-to guide](https://learn.microsoft.com/en-us/sql/azure-data-studio/extensions/extension-authoring?view=sql-server-ver16).
