### ISSUE TITLE
Dracula for Kakoune

### ISSUE THREAD

**Issue by alexherbo2** [dracula/dracula-theme#373]
## [Dracula for Kakoune]

> A dark theme for [Kakoune].

![Screenshot](https://github.com/alexherbo2/kakoune-dracula-theme/raw/master/resources/screenshot.webp)

[Dracula for Kakoune]: https://github.com/alexherbo2/kakoune-dracula-theme
[Kakoune]: https://kakoune.org

**Comment by zenorocha** [comment]
Sorry for the delay @alexherbo2. I just sent you an invite to join the Dracula team. Once you accept it, you can transfer the repository to this organization, and I'll create the official website page :)

**Comment by zenorocha** [comment]
It's live! https://draculatheme.com/kakoune
