### ISSUE TITLE
Theme for wofi launcher

### ISSUE THREAD

**Issue by nathanblair** [dracula/dracula-theme#375]
## New Theme?

We would love to support all code editors out there, but we need your help to accomplish that. Feel free to create a new theme based on our [color palette](https://github.com/dracula/dracula-theme#color-palette).

^^ Not a code editor, but a wayland launcher application

[Documentation for wofi config](https://cloudninja.pw/docs/wofi.html)

![screenshot](https://user-images.githubusercontent.com/16280023/75612761-9d8cec80-5af4-11ea-972c-32007bbe78e4.png)

**Comment by zenorocha** [comment]
Hello @nathanblair! I saw your PR: https://github.com/dracula/dracula-theme/pull/374 and I love the fact that you're creating a theme for wofi.

In terms of how to distribute it, the best way would be to fork this template, add your files and instructions on how to install it: https://github.com/dracula/template

After you're done with that, we can transfer to the Dracula organization and create a dedicated page on the site.

**Comment by elumbella** [comment]
I created a fork and threw together a quick stylesheet. It is very simple atm, but I like it. However, I'm open to ideas!

Check it out here: https://github.com/elumbella/template

**Comment by zenorocha** [comment]
Hey @elumbella, that was great! I just cloned the repository and moved to the Dracula org: https://github.com/dracula/wofi

I had to make some small changes there, let me know if that's correct or not: https://github.com/dracula/wofi/commit/e13c362bf84446b0b573d02ecea2bc82d9e4983b

You should have received an invitation to join the org now.

Here's the page on the site now: https://draculatheme.com/wofi 🎉 🎉 🎉 

cc @nathanblair

**Comment by elumbella** [comment]
Thanks @zenorocha for the quick integration and invitation to the team. I have happily accepted!

I have since edited the INSTALL.md to match the actual installation process. Thanks for pointing that out :)
