### ISSUE TITLE
Please give me back write-right to my repositories

### ISSUE THREAD

**Issue by milouse** [dracula/dracula-theme#379]
Hi @zenorocha and anyone involved,

Some time ago, someone took the decision to limit the right of the dracula organization members and creates « team » to manage repositories, which is a very nice thing.

But since then I lose the access on the two repository I maintain:

- [Mattermost](https://github.com/dracula/mattermost): I'm in the [related team](https://github.com/orgs/dracula/teams/mattermost)… but the repository is not attached to the team…
- [Emacs](https://github.com/dracula/emacs): the repository is well attached to [its related team](https://github.com/orgs/dracula/teams/emacs), but I sent an invitation to join the team some weeks ago and never got a reply :/

This is very frustrating because without basic rights, it's hard to manage pull request or other basic workflow tasks.

Can an admin fix my situation? Thank you very much in advance!

**Comment by zenorocha** [comment]
I'm really sorry about that @milouse. This should be fixed now.

**Comment by milouse** [comment]
Yes it works, thank you very much @zenorocha!
