### ISSUE TITLE
Dracula for bspwm

### ISSUE THREAD

**Issue by DustVoice** [dracula/dracula-theme#380]
# Dracula for [bspwm](https://github.com/baskerville/bspwm)

> A dark theme for [bspwm](https://github.com/baskerville/bspwm).

**Pink accent color:**

![Screenshot](https://raw.githubusercontent.com/DustVoice/template/master/screenshot.png "Monitor focused - Pink focus") | ![Screenshot unfocused monitor](https://raw.githubusercontent.com/DustVoice/template/master/screenshot_unfocused_monitor.png "Monitor unfocused - Pink focus")
--- | ---
Monitor focused (_focused node = top-left; preselection = bottom-right_) | Monitor unfocused (_focused node = top-left; preselection = bottom-right_)

**Cyan accent color:**

![Screenshot cyan](https://raw.githubusercontent.com/DustVoice/template/master/screenshot_cyan.png "Monitor focused - Cyan focus") | ![Screenshot cyan unfocused monitor](https://raw.githubusercontent.com/DustVoice/template/master/screenshot_cyan_unfocused_monitor.png "Monitor unfocused - Cyan focus")
--- | ---
Monitor focused (_focused node = top-left; preselection = bottom-right_) | Monitor unfocused (_focused node = top-left; preselection = bottom-right_)

**Comment by DustVoice** [comment]
Link to the repository, as requested: https://github.com/DustVoice/template

**Comment by DustVoice** [comment]
Thanks for inviting me into the team and creating the repository. I just wanted to mention that the webpage will still have to be created. And big props to the creators and maintainers of this awesome color scheme, I'm using everywhere I can

**Comment by zenorocha** [comment]
Hey @DustVoice, as you noticed, the repository has been transferred (https://github.com/dracula/bspwm) and you can now delete the previous one (https://github.com/DustVoice/template).

The page for bspwm is also live: http://draculatheme.com/bspwm 🎉 🎉 🎉

Please take a look there, and if you want to change something, go ahead and update the `screenshot.png` or `INSTALL.md` files.

**Comment by zenorocha** [comment]
Thank **you** for creating this theme and I really appreciate all the effort.
