### ISSUE TITLE
PS1 setup for a Dracula theme basic and simple Bash prompt

### ISSUE THREAD

**Issue by hisnawi** [dracula/dracula-theme#383]
I love the Dracula theme but I am looking for very basic and simple PS1 setup that has same colors. I tried looking in other theme files in the repo trying to extract the correct formula I need but I failed.
Basically I am looking for a prompt to like like the following but with Dracula theme colors:

`export PS1="\[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h:\[\033[33;1m\]\w\[\033[m\]\$ "`

**Comment by benknoble** [comment]
You'll want to set up your terminal first; e.g., if you use Apple's Terminal.app: https://github.com/dracula/terminal-app

Then you can do what you're doing—your current `PS1` uses the terminals colors, so you need to set up its colors first.

**Comment by hisnawi** [comment]
Got it, I am not too familiar with the PS1 formula and how it picks up the colors.
Is there a way to customize there colors directly in the PS1 assignment without relying on the terminal colors?
Reason I am asking because I use Tmux to access remote systems that I can't control or can change their settings (including the terminal theme). But I can control the shell sessions I open with Tmux. That is why I want to use the export method to achieve that.

**Comment by benknoble** [comment]
You can't customize the colors directly in PS1 (other than picking attributes like bold, reverse, blink, etc., and picking which of the 8–16 colors are used).

To be clear, you're customizing your terminal emulator's colors. When you use `ssh` (not `tmux`—`tmux` is a terminal multiplexer it doesn't connect you remotely at all) to access a remote system, the system sends back the text for your terminal emulator to draw. If that includes ANSI color codes, the terminal emulator will process them and use its colors.

> how it picks up the colors

I suggest you read [1](https://en.wikipedia.org/wiki/ANSI_escape_code), [2](http://www.lihaoyi.com/post/BuildyourownCommandLinewithANSIescapecodes.html), [3](https://misc.flogisoft.com/bash/tip_colors_and_formatting), etc.

Note that these things are technically non-portable, as they depend on the terminal recognizing ANSI/xterm color sequences. In practice, most common `TERM`s do, but there are some issues.

**Comment by hisnawi** [comment]
Thanks for the detailed explanation.
