### ISSUE TITLE
Theme for Roam Research

### ISSUE THREAD

**Issue by zenorocha** [dracula/dracula-theme#384]
Inspiration
 * https://github.com/theianjones/roam-research-themes
* https://github.com/roam-unofficial/roam-toolkit

**Comment by nsgrantham** [comment]
Hi Zeno, I've made [Dracula for Roam Research](https://github.com/nsgrantham/roam-research-dracula-theme) and adapted it to meet the new theme requirements for Dracula. Let me know what you think.

**Comment by zenorocha** [comment]
That's amazing @nsgrantham! I just sent you an invitation to join the Dracula org. Once you accept, you can transfer the repo ;)

Thanks for doing that!

**Comment by nsgrantham** [comment]
Thanks Zeno! Transferred. https://github.com/dracula/roam-research

**Comment by zenorocha** [comment]
We're live! https://draculatheme.com/roam-research

Thanks @nsgrantham :D
