### ISSUE TITLE
Dracula for Spacemacs

### ISSUE THREAD

**Issue by GuilhermeCaruso** [dracula/dracula-theme#385]
## Repository
- Solution made to use dracula with spacemacs. Below is the repository
[Dracula for Spacemacs](https://github.com/GuilhermeCaruso/dracula-spacemacs)

**Comment by zenorocha** [comment]
Hey @GuilhermeCaruso, that's awesome, thanks for doing this!

I just sent you an invite to join the Dracula organization. Once you accept, just transfer the repository and I'll make the proper adjustments for the website page ;)

**Comment by GuilhermeCaruso** [comment]
Invite accepted and transfer made! Thanks!

**Comment by zenorocha** [comment]
Hey @milouse, can you review this before I publish it on the site? I'm not very familiar with Emacs, so I don't know the difference between Emacs and Spacemacs.

@GuilhermeCaruso can you describe the difference between your theme and https://github.com/dracula/emacs?

**Comment by GuilhermeCaruso** [comment]
@zenorocha Spacemacs is a development kit for emacs, it runs alongside emacs, however its visual configurations / styles are defined in an exclusive layer, for this reason the need to create a unique style for it.

**Comment by milouse** [comment]
Yeah, Spacemacs packages its own themes and modules, thus I'm not surprised it exists another way to make a dracula theme on it. I cannot say much as I never used it :/

**Comment by GuilhermeCaruso** [comment]
@zenorocha  Do you need any more information?

**Comment by zenorocha** [comment]
Sorry for the delay @GuilhermeCaruso. You can transfer the repo now.

**Comment by GuilhermeCaruso** [comment]
@zenorocha  The repository is already owned by @dracula/spacemacs

**Comment by zenorocha** [comment]
Hey @GuilhermeCaruso, the theme is finally live!

https://draculatheme.com/spacemacs

I had to make some small adjustments in order to follow the same pattern as the other repositories, but other than that it looks amazing.

https://github.com/dracula/spacemacs/commit/ee1052bff2b954bedd5e9ee1ddb694d3cf75fa66
