### ISSUE TITLE
Dracula for Godot

### ISSUE THREAD

**Issue by damiiani** [dracula/dracula-theme#388]
## Dracula for Godot

I created Dracula theme for the Godot Engine, below is the repository:
[Dracula for Godot](https://github.com/damiiani/dracula-godot)

And the current look:
![Godot](https://github.com/damiiani/dracula-godot/raw/master/screenshot.png)

Any tips are welcome...

**Comment by zenorocha** [comment]
This looks beautiful @damiiani! Congrats 🎉 🎉 🎉 

Would you be willing to transfer the repository to the Dracula organization? You would still be the maintainer and everything.

If you're okay with that, I just sent you an invite to join the Dracula team. Once you accept it, you can transfer the repository to this organization, and I'll create the official website page :)

**Comment by damiiani** [comment]
Already transfer it @zenorocha :)

**Comment by zenorocha** [comment]
https://draculatheme.com/godot 🎉 🎉 🎉

**Comment by zenorocha** [comment]
Thanks Gustavo! 🇧🇷
