### ISSUE TITLE
Dracula for rofi

### ISSUE THREAD

**Issue by RaphGL** [dracula/dracula-theme#389]
A dark theme for the rofi launcher. 
[Dracula for rofi](https://github.com/RaphGL/rofi)
![screenshot](https://user-images.githubusercontent.com/28673457/79795560-46103d80-833b-11ea-9c9c-c56228e9fbf2.jpg)

**Comment by zenorocha** [comment]
Hey @RaphGL, that's great! Congrats on the new theme 🎉 

Before we move to the Dracula org, can you make some adjustments for the site?
1. Add a INSTALL.md with instructions
2. Use the same README.md pattern
3. Convert the screenshot from JPG to PNG

You can see the https://github.com/dracula/template for reference.

**Comment by RaphGL** [comment]
I have adhered to the template on: RaphGL/rofi@ba82d15c0486469642a4c71dd222b7a67539670c
Could you check to see if everything is in order?

**Comment by zenorocha** [comment]
Looks perfect now :D Can you transfer the repo?

**Comment by RaphGL** [comment]
Done!

**Comment by zenorocha** [comment]
Aaaaand we're live: https://draculatheme.com/rofi

Thanks again @RaphGL, keep rocking  🎉
