### ISSUE TITLE
Dracula for Codelobster ?

### ISSUE THREAD

**Issue by pipiscrew** [dracula/dracula-theme#390]
hi all, 

Very nice work!

http://codelobster.com/ 

is a PHP / HTML / CSS / JavaScript **cross platform** editor used by many people. 

Website, alexa rank is **388k**.. Please consider to create a theme...

**Comment by zenorocha** [comment]
Hey @pipiscrew, that's a great suggestion. Have you thought about creating the theme yourself?

Here are the instructions on how to do it: https://draculatheme.com/contribute

**Comment by pipiscrew** [comment]
Sorry, Im not an artist, I will try with the then given colors when free.
