### ISSUE TITLE
Dracula theme for Github website

### ISSUE THREAD

**Issue by ysm0622** [dracula/dracula-theme#392]
Thank you so much for creating a nice theme. Is there a theme for the Github website? 
I am using the Dracula theme in vscode, but I'm wondering why there is no Dracula theme in the Github website where we see the code the most.

**Comment by benknoble** [comment]
Afaik there is no cross-browser way to theme GitHub. Some browsers have plugins that allow theming sites, though.

**Comment by ysm0622** [comment]
Thank you for the quick reply. I found a lot of Github Dark theme browser extension, but I couldn't find Dracula theme for Github.
If you know, then can you give me the link?

**Comment by benknoble** [comment]
I don't know of any off the top of my head, though if they use something Pygments-ish you could try the following CSS: https://github.com/dracula/pygments

**Comment by scottzach1** [comment]
For what it is worth. I have been using this for a little while now and have been really happy with how it performs. 

https://github.com/dracula/dracula-theme/issues/309

Looks pretty great on GitHub. For what it is worth, I would personally prefer having 1 extension manage all of the colors than having to install extensions for all the popular websites.

If someone wants to implement, perhaps it could be approached similar to how the [Dracula/messenger](https://github.com/Dracula/messenger) has been implemented?

**Comment by gabrielzschmitz** [comment]
> Thank you so much for creating a nice theme. Is there a theme for the Github website?
> I am using the Dracula theme in vscode, but I'm wondering why there is no Dracula theme in the Github website where we see the code the most.

https://github.com/poychang/github-dark-theme

**Comment by zenorocha** [comment]
https://draculatheme.com/github 💥
