### ISSUE TITLE
Dracula theme for Oh-my-posh(Powershell)

### ISSUE THREAD

**Issue by thanhvule0310** [dracula/dracula-theme#393]
## New Theme

I've created a new theme for [Oh-my-posh](https://github.com/JanDeDobbeleer/oh-my-posh)

Repository: https://github.com/thanhvule0310/dracula-ohmyposh

**Comment by Gary-H9** [comment]
If anyone comes across this, the repository is here, not sure what happened with this one: https://github.com/dracula/oh-my-posh 🧛‍♂️🦇
