### ISSUE TITLE
Dracula for Openbox 

### ISSUE THREAD

**Issue by the-zero885** [dracula/dracula-theme#394]
Hi Dracula Team! I made a Dracula theme for the Window Manager Openbox (used in Linux distros with LXDE, LXQt and some environments).

**Repository:** https://github.com/the-zero885/dracula-Openbox

**Screenshots:**
It has two versions, one with a border and one without.

![Theme with border](https://raw.githubusercontent.com/the-zero885/dracula-Openbox/master/dracula_withoutborder.png)
![Borderless theme](https://raw.githubusercontent.com/the-zero885/dracula-Openbox/master/dracula_withborder.png)
**Menu theme**
![Menu](https://raw.githubusercontent.com/the-zero885/dracula-Openbox/master/context-menu.png)

**Comment by zenorocha** [comment]
@the-zero885 sorry for taking forever to reply.

I'd love to get this repository merged into the official organization. 

I just sent you an invite to join the org.

Once you accept it, you'll be able to transfer the repo and I'll take care of adding it to the site.

Thanks for building this! 🎉

**Comment by the-zero885** [comment]
I have already accepted the invitation, thank you very much!

As soon as I can I will transfer the repo to the organization.

**Comment by zenorocha** [comment]
@luxonauta can you add the repo to `dracula-theme` and to the website?

**Comment by luxonauta** [comment]
Sure, Zeno! 🚀

**Comment by zenorocha** [comment]
It's live now!

https://draculatheme.com/openbox

Thank you all for your patience on this.
