### ISSUE TITLE
Aseprite dracula color theme :)

### ISSUE THREAD

**Issue by Abbabon** [dracula/dracula-theme#396]
Hi there! I've just finished creating a Dracula theme. Here is the repo: 

https://github.com/Abbabon/aseprite-dracula-theme

I've tried to fill your template to the best of my knowledge, but some editing will be required for the Readme.

I think the theme looks cool :) Still haven't worked with it a lot, but with several years of Dracula on both all my terminals, IDEs and even Chrome, I feel right at home :)

**Comment by zenorocha** [comment]
Hey @Abbabon, it looks great!

I just sent you an invite to join the [Dracula organization](https://github.com/dracula). Can you transfer the repository? Once you do that, I'll be able to add the theme to the [official site](https://draculatheme.com) :)

What do you think?

**Comment by Abbabon** [comment]
Hi Zeno! I've moved the repository :)

Anything else required at my end?
