### ISSUE TITLE
Dracula theme for Total Commander

### ISSUE THREAD

**Issue by PsyPeke** [dracula/dracula-theme#397]
## Dracula for Total Commander
I've created this first version of [Dracula Theme for Total Commander](https://github.com/PsyPeke/dracula-totalcommander). Maybe it's not perfect, but I hope it's a starting point.

**Comment by zenorocha** [comment]
It looks great @PsyPeke! I sent you an invite to join the Dracula organization. Can you transfer the repository? Once you do that, I'll be able to add the theme to the official site :)

**Comment by zenorocha** [comment]
Hey @PsyPeke, I was able to move the Total Commander repository to the Dracula organization:
* https://github.com/dracula/total-commander

You can go ahead and delete this repo now:
* https://github.com/PsyPeke/total-commander

You see the live page here:
* https://draculatheme.com/total-commander

Thanks @PsyPeke!! Good job on this :)
