### ISSUE TITLE
New Dracula Community

### ISSUE THREAD

**Issue by zenorocha** [dracula/dracula-theme#398]
> **TLDR: We're launching the Dracula Community ([community.draculatheme.com](https://community.draculatheme.com)) and would like to invite all maintainers to join before the public announcement.**

## Why?

Hello @dracula/maintainers!

For a long time, I missed having a place where we can openly discuss about Dracula.

GitHub is great, but I feel like Wiki and Issues are not the appropriate places to share our ideas. In the spirit of finding a place where we could all hang out, I started looking at several different options:

1. [Slack](http://slack.draculatheme.com/) / [Discord](https://discord.com/): I love the idea of having a chat room, but I don't like the fact that the content there is isolated and not indexed by Google. Answering a question there only helps one person, where it could help many.
2. [GitHub Discussions](https://github.com/zeit/next.js/discussions): When I first saw this I was very excited, but I've been waiting for months and they still didn't launch for everybody. Besides that, it looks like you don't have too much control to customize the tool.
3. [Spectrum](https://spectrum.chat/): Even though I love Spectrum, after they got acquired by GitHub, I feel like their future is still unclear.

In the end, the best solution I found is [Discourse](https://www.discourse.org/).

It gives us the flexibility and control we need, while keeping the information free for search engines to index. It's also trusted by other huge communities such as [Docker](https://forums.docker.com/), [Netlify](https://community.netlify.com/), and [Twitter](https://twittercommunity.com/).

## Join Now

The goal is to launch this community to all Dracula users next week. But before we do that, I'd like to invite all maintainers to join and give their feedback first.

**Go to [community.draculatheme.com](https://community.draculatheme.com) and create an account.**

## Thanks

Thanks @dsifford @benknoble @hacknug for brainstorming these ideas with me. Also, @jordanvidrine for creating the initial [Dracula theme for Discourse](https://github.com/dracula/discourse).

**Comment by dsifford** [comment]
Chiming in late here to mention that the new [GitHub Discussions Beta](https://github.blog/2020-05-06-new-from-satellite-2020-github-codespaces-github-discussions-securing-code-in-private-repositories-and-more/#discussions) might be the perfect thing for this (and avoid the $$ associated with hosting a discourse).

**Comment by nesl247** [comment]
I would definitely prefer to wait for GitHub discussions. I'd much rather not have another site to have to browse.

**Comment by milouse** [comment]
I'm not really found to have another new site too… However maybe a good way to ease the adoption curve would be to activate github-related plugins?

- https://meta.discourse.org/t/discourse-github/99895 to have some integration
- https://meta.discourse.org/t/openid-connect-authentication-plugin/103632 to allow us to connect/create account through our github credentials?

**Comment by oswaldoacauan** [comment]
I would also suggest to wait for GitHub discussions. Having scattered communities for the same project just discourage new people to join imo.

**Comment by zenorocha** [comment]
Thanks for providing this feedback, you guys are awesome!

Let me share some opinions about GitHub Discussions:

1. First of all, it looks amazing. It's a shiny new thing, and whenever there's a new thing, there's always excitement and hope. Unfortunately, we don't know if that feature is really going to be adopted, remember [Team Discussions](https://help.github.com/en/github/building-a-strong-community/about-team-discussions)?
1. Even after [GitHub Satellite's announcement yesterday](https://github.blog/2020-05-06-new-from-satellite-2020-github-codespaces-github-discussions-securing-code-in-private-repositories-and-more/), there's still no clear timeline of when this is going to be available.
1. The [Answered](https://github.com/githubevents/satellite2020/discussions/4) functionality is at the core of the entire experience, which shows their intention to be more like a StackOverflow than a forum tool. One of my ideas is to foster the culture of [sharing your setup](https://community.draculatheme.com/t/my-sublime-text-setup/18), like the [unixporn](https://www.reddit.com/r/unixporn/) and [vimporn](https://www.reddit.com/r/vimporn) communities on Reddit. In those cases, there's no right or wrong answer, just people sharing content.
1. Only last year, the draculatheme.com site had more than 1 million page views. This means that the domain has a strong authority and it's easy to be found by search engines. Having a tool running under that domain will not only help SEO, but also with discoverability. When people search for something, it will be easier for them to find it.
1. One interesting aspect that we didn't leverage yet is Private Discussions. If there's a delicate topic that we need to discuss, private topics can help with that.
1. One of the things I like about Discourse is the gamification aspect. Since it was built by the creator of StackOverflow, they do a really good job encouraging positive community behaviors with [badges and trust system](https://www.discourse.org/features).
1. Dracula is a theme and being able to customize any interface with that theme is really nice, it creates a unique identity. Discourse allows us to apply any CSS we want, while GitHub Discussion will not provide the ability to customize their interface.

With all that being said, there's still a lot of advantages of using GitHub Discussions. It doesn't require you to create another account in another place. It's free and it's one less software to maintain.

I guess we can wait a couple of weeks to see how this all plays out.

Any other opinions you want to share?

**Comment by BlakeWilliams** [comment]
Hey, I'm actually on the discussions team at GitHub. If discussions is something you're still considering feel free to reach out and we can chat about it. :)

**Comment by nesl247** [comment]
How perfect.

1) I'm 99% sure it will be adopted. People already use Issues for discussion. Team Discussions isn't used because it's generally just a bad idea. Why use that instead of Slack?

2) Seems like we have an in for early access

3) Just because it has an Answered button doesn't mean it has to be used like SO.

4) I feel searching for discussions on GH will be a lot easier than having to know Dracula has a third party forum tool. Keeping everything in one place (issues, PRs, discussions of other sorts, etc.) means that you don't have to browse to another tool to discuss a different topic. And you can open an issue from a discussion I believe, which is pretty powerful.

5) Not sure if the feature will have that, but it makes sense. However, I think private topics can easily be handled in Slack, as it isn't something the public community would need access to anyways. Other avenues would be twitter group DMs, etc. if GitHub isn't adding private discussions (which it should).

6) I rarely browse SO, but I will tell you, I've never once paid any attention to their badges. I browse it via Google, get my answer, and get out. SO is a pain to use personally, so following them as an example is not necessarily a great idea.

7) Being able to theme it would certainly be nice. Though I think this is the least important aspect here.

**Comment by zenorocha** [comment]
Wow, that's amazing news, thanks @BlakeWilliams. Let's make it happen!

**Comment by oswaldoacauan** [comment]
>>> I feel searching for discussions on GH will be a lot easier than having to know Dracula has a third party forum tool. Keeping everything in one place (issues, PRs, discussions of other sorts, etc.) means that you don't have to browse to another tool to discuss a different topic. And you can open an issue from a discussion I believe, which is pretty powerful.

This is the main point imo.

**Comment by AGitBoy** [comment]
I feel that having a community forum would be a good thing overall, but it depends on the time frame for the GitHub discussion system to be launched, if its a couple months we should probably wait it out, but if its more than 4 months we should probably consider the forum. If we do go ahead with it there are a couple things that I have questions/suggestions on.

1. When GitHub discussions goes up will we transition to using that if we have a forum set up? If so, what could we do to smooth over the transition between them.
2. Will issues still be used on GitHub, or will this be a hybrid forum/bug tracker sort of deal?
3. To smooth the transition, we should try and figure out a way for users to login to the forum with their existing GitHub accounts.

Other than that, I am heavily in favour of developing a community forum for the theme, as it would allow direct interaction with the user base to be much more streamlined than it currently is with the issue system.

**Comment by zenorocha** [comment]
Okay, everyone, we are live! 🎉🎉🎉

[GitHub Discussions](https://github.com/dracula/dracula-theme/discussions) have been enabled and we'll now start shutting down [community.draculatheme.com](https://community.draculatheme.com).

I'd like to kick things off with two posts:

* [Welcome to the Dracula Community](https://github.com/dracula/dracula-theme/discussions/400)
* [Share your Sublime Text setup](https://github.com/dracula/dracula-theme/discussions/401)

Thank you @BlakeWilliams and @becca for allowing us to join the beta.
