### ISSUE TITLE
php closing tag '?>'

### ISSUE THREAD

**Issue by crThiago** [dracula/dracula-theme#404]
I don't know if it is a bug, but when commenting the php closing tag '?>', It appears that way
![image](https://user-images.githubusercontent.com/33141686/82107958-d440cf00-9701-11ea-8f55-d34788ef22ac.png)

**Comment by benknoble** [comment]
@crThiago Since you marked this closed, did you find a solution? Note that in general you’ll get better replies if you post issues on the specific repository of the program you’re using (eg, if it’s a vim issue, post it on dracula/vim).

**Comment by crThiago** [comment]
yes, sorry i posted an issue in the vscode repository
