### ISSUE TITLE
Dracula for GitLab

### ISSUE THREAD

**Issue by makitsune** [dracula/dracula-theme#405]
I added a new theme for GitLab syntax highlighting and diffs! 

It's currently available here: https://github.com/makitsune/dracula-gitlab

The `INSTALL.md` will explain how to compile the CSS files and there's a guide for installing it with a browser extension. It's possible to also install this on a self-hosted GitLab instance but that's much more complicated.

All the links are already pointing to `github.com/dracula/gitlab` and `draculatheme.com/gitlab` so expect 404s.

Here's a working link to the `dracula.user.css` file hosted on my repo:
https://github.com/makitsune/dracula-gitlab/raw/master/dracula.user.css

I'm currently using this in production with my company's GitLab instance and I will fix any bugs as soon as we encounter them.

Hopefully one day, this theme can be extended to be site-wide. However, GitLab doesn't have any official dark themes yet. It would be a lot of hard work.

**Comment by zenorocha** [comment]
Hey @makitsune, do you know if this theme is still working?

I'd love to FINALLY get it added to the Dracula organization :)

**Comment by wasi-master** [comment]
@zenorocha I tested this and it works for code only, (The UI colors are from GitLab dark mode)
![image](https://user-images.githubusercontent.com/63045920/150293869-34ae5363-52a9-467c-af49-caf2029b5285.png)

**Comment by zenorocha** [comment]
thanks for testing @wasi-master! do you want to create a [template repo](https://github.com/dracula/template) for this?

**Comment by wasi-master** [comment]
@zenorocha So something like https://github.com/makitsune/dracula-gitlab? I guess you can clone that repo and give me access or something like that? Or can I do that now since I am part of the dracula organization?

**Comment by makitsune** [comment]
Hello! I'm sorry I've been inactive here. I recently had surgery and I've been recovering. I could give you access to the repo if you'd like.

**Comment by zenorocha** [comment]
Oops, sorry about that. I totally missed the repository @wasi-master.

@makitsune sorry to hear about the surgery. Please don't feel pressured to do anything ;)

We already cloned your repo, moved it to the Dracula org, and invited you as Admin to maintain it.
https://github.com/dracula/gitlab

Feel free to delete or archive your existing repo.
https://github.com/makitsune/dracula-gitlab

**Comment by wasi-master** [comment]
@zenorocha no worries

**Comment by zenorocha** [comment]
And we're live! https://draculatheme.com/gitlab 🎉
