### ISSUE TITLE
Dracula for Lightline

### ISSUE THREAD

**Issue by Natur3-Boy** [dracula/dracula-theme#406]
# Dracula for [Lightline](https://github.com/Natur3-Boy/dracula-for-lightline)

I've really enjoyed having this, so I thought I would share.

I know Lightline has darcula, but it's not the same. 

Cheers.

**Comment by benknoble** [comment]
We have (some) support for lightline in dracula/vim; would you consider opening a PR there?

**Comment by Natur3-Boy** [comment]
Oh! Please forgive my incompetence. I hadn't even thought of looking
there and just assumed Lightline would be supported under a separate
program. You're code is much better than mine; although, I had to do
some digging to find it.

Sorry for the inconvenience,
Dan

**Comment by benknoble** [comment]
No inconvenience; I'll close this. But honestly, if there's something you want to see changed, let us know via an issue or PR and we'll consider it!
