### ISSUE TITLE
colorls theme/config file

### ISSUE THREAD

**Issue by bigpick** [dracula/dracula-theme#411]
## New Theme
New theme for [colorls](https://github.com/athityakumar/colorls) 

### Dracula directory created from template available [here](https://github.com/bigpick/colorls).

Not sure where to put the installation instructions in the meantime

**Comment by bigpick** [comment]
@benknoble what’s the difference between a new theme request and a new theme submission? Looking through the existing Issues it seems that a request is for asking?

**Comment by benknoble** [comment]
@bigpick Hm unclear. I _thought_ it was for saying “hey I built a Dracula X lets get it transferred to the dracula org and on the website to make it official.” Best wait for @zenorocha regardless.

**Comment by bigpick** [comment]
FYI - [most recent colorls release](https://github.com/athityakumar/colorls/releases/tag/v1.4.2) now includes the required hex support is now in the latest gem for colorls 🎉 

> Implemented enhancements: 🚀. 
> Support hexstring colors in YAML file #365 (bigpick)

@zenorocha I've updated https://github.com/bigpick/colorls/blob/master/INSTALL.md accordingly; do you have any thoughts on the colorscheme/values?

**Comment by bigpick** [comment]
bump?

**Comment by zenorocha** [comment]
Hey @bigpick, I just sent you an invite to join the org. Once you accept, you can transfer the repo ;)

**Comment by bigpick** [comment]
Hiya @zenorocha , awesome! I've done so accordingly: https://github.com/dracula/colorls. (also updated per comments in #425)

**Comment by bigpick** [comment]
Live at https://draculatheme.com/colorls 🎉  

One question I do have: what is the process (if any) for getting a specific theme's submodule version bumped on [dracula-theme](https://github.com/dracula/dracula-theme) / [draculatheme.com](https://draculatheme.com/)? For example, since it's been added, I realized the main screenshot.png needed updated to the finalized color scheme, which I've since completed and pushed to master (and is reflected on the site's README), but now am curious how that get's updated to be reflected on https://draculatheme.com/colorls since it's tied to the older commit? 

By the way, thanks! Looking forward to hopefully being able to contribute some more elsewhere

**Comment by zenorocha** [comment]
Unfortunately, today is a very manual process :/

I have to go the draculatheme.com repo and run the deploy command. Ideally, we should automate this process, so that whenever there's a commit on any Dracula repo, we can deploy the site right away.

**Comment by zenorocha** [comment]
FYI, I just redeployed the site and it now has the new screenshot: https://draculatheme.com/colorls

**Comment by bigpick** [comment]
Awesome -- thanks a lot @zenorocha  looks great!

**Comment by bigpick** [comment]
Closing, as repo is live at:
* https://github.com/dracula/colorls

and site is live at:
* https://draculatheme.com/colorls

🎉
