### ISSUE TITLE
Dracula for mousepad

### ISSUE THREAD

**Issue by spazmantiz** [dracula/dracula-theme#413]
Hey, i made this little tutorial for installing dracula theme for mousepad text editor.
currently is in my github repo https://github.com/spazmantiz/dracula-mousepad

**Comment by zenorocha** [comment]
Hey @spazmantiz! 

I'm glad to see that you created a theme for Mousepad!

Are you interested in transferring your repository to the official organization (https://github.com/dracula)? You'll continue maintaining this project, the only difference is that we can make it more visible and include it on the site (https://draculatheme.com).

I just sent you an invite to join the organization. If you accept, you'll be able to transfer the repo and we can continue with adding to the site.

Thanks for building it!

**Comment by spazmantiz** [comment]
thanks @zenorocha for the invitation, i'll try to maintain the repo

**Comment by spazmantiz** [comment]
hey @zenorocha, i'm new to all of this can you give me detail how to transfer the repo? and i don't receive invitation that you mention.

**Comment by zenorocha** [comment]
Hey @spazmantiz, sorry about that, I just sent the invitation. You can now go to Settings > Options > Transfer.

![image](https://user-images.githubusercontent.com/398893/97127038-be462a00-16f5-11eb-8ca5-c61598a12dc9.png)

**Comment by zenorocha** [comment]
It's live! https://draculatheme.com/mousepad

Thanks @spazmantiz ;)
