### ISSUE TITLE
dracula-theme for Thunderbird

### ISSUE THREAD

**Issue by avatar-lavventura** [dracula/dracula-theme#416]
## New Theme?

Is is possible to apply dracula-theme into `[Thunderbird](https://www.thunderbird.net/en-US/)`?

**Comment by pragomer** [comment]
I would also very much like a dracula theme for thunderbird. (and, if some makes so.. not only color but perhaps it would be possible to do a little wider line spacing :-))

**Comment by maxfrei750** [comment]
@avatar-lavventura @pragomer @zenorocha Did you already see my Thunderbird theme?

See #473.

**Comment by zenorocha** [comment]
That's awesome @maxfrei750, closing this issue in favor of #473 :)

**Comment by avatar-lavventura** [comment]
Seems like it does not work for Thunderbird newest version; `Works with Thunderbird 60.0 - *`

**Comment by Valkryst** [comment]
@avatar-lavventura 
I'm currently running Thunderbird version 78.6.0 (32-bit) on Windows 10 and the theme is working
