### ISSUE TITLE
Adminer-Dracula-Theme

### ISSUE THREAD

**Issue by douglasdamasio** [dracula/dracula-theme#417]
New Theme?

Oh yes!
First, Good morning / Good afternoon / Good night ;)
I am proposing to submit a new topic to the **Adminer**,
[Adminer](https://www.adminer.org/) is a Database management in a single PHP file, a great alternative to phpMyAdmin.
Lately I've been using it through a docker container and their default theme is eye-popping! LOL!

Look:
![img](https://www.adminer.org/static/screenshots/create.png)

So I customized it using the dracula color palette, see how it turned out.

![img2](https://raw.githubusercontent.com/douglasdamasio/adminer-dracula-theme/master/screenshot.png)

Hope you like it!

Link to: [adminer-dracula-theme](https://github.com/douglasdamasio/adminer-dracula-theme)

Dracula is Awsome!

Bye =D

**Comment by zenorocha** [comment]
Hey @douglasdamasio! 

I'm glad to see that you created a theme for Adminer! I used this app a while ago and it looks much better now with Dracula colors ;)

Are you interested in transferring your repository to the official organization (https://github.com/dracula)? You'll continue maintaining this project, the only difference is that we can make it more visible and include it on the site (https://draculatheme.com).

I just sent you an invite to join the organization. If you accept, you'll be able to transfer the repo and we can continue with adding to the site.

Thanks for building it!

**Comment by douglasdamasio** [comment]
Wow it's amazing **@Zeno** !!
I am very happy with this news and also happy to be able to be part of this project that I admire a lot.
I'll transfer the project!

Congrats for us!

**Comment by douglasdamasio** [comment]
@zenorocha https://github.com/dracula/adminer-dracula-theme

**Comment by zenorocha** [comment]
It's live! https://draculatheme.com/adminer 🎉 🎉 🎉
