### ISSUE TITLE
New theme: Dracula for Mathematica/Wolfram Notebooks

### ISSUE THREAD

**Issue by jldohmann** [dracula/dracula-theme#419]
Hi, team! I implemented the Dracula theme for Wolfram Notebooks 😄 you can find it here: ![Dracula for Wolfram Notebooks](https://github.com/jldohmann/wolfram-notebooks)

Here's a preview for how it works:

![image](https://user-images.githubusercontent.com/14860856/85428551-fc162480-b542-11ea-93d4-2813f29500b7.png)

If you have a Wolfram desktop application, you can try it out interactively; it's [example.nb](https://github.com/jldohmann/wolfram-notebooks/blob/master/example.nb) in the repo.

Additionally, I created an automated installation method for Wolfram Language users by using the stylesheet as a [ResourceFunction](https://resources.wolframcloud.com/FunctionRepository/resources/DraculaTheme).

-----

Ever since I made this, I made it my default environment for when I'm working with Wolfram Language code, so I use it everyday! Hope y'all like it.

**Comment by zenorocha** [comment]
Hey @jldohmann! 

I'm glad to see that you created a theme for Wolfram Notebooks!

Are you interested in transferring your repository to the official organization (https://github.com/dracula)? You'll continue maintaining this project, the only difference is that we can make it more visible and include it on the site (https://draculatheme.com).

I just sent you an invite to join the organization. If you accept, you'll be able to transfer the repo and we can continue with adding to the site.

Thanks for building it!

**Comment by jldohmann** [comment]
Thanks @zenorocha ! I just transferred it over! [https://github.com/dracula/wolfram-notebooks](https://github.com/dracula/wolfram-notebooks)

**Comment by zenorocha** [comment]
https://draculatheme.com/wolfram-notebooks 🎉 🎉 🎉
