### ISSUE TITLE
New theme: Tower 5

### ISSUE THREAD

**Issue by amine2233** [dracula/dracula-theme#421]
## New Theme

The new version of Tower 5 integer a new text editor with the possibility to customise the theme, it will be nice if you can add the new theme for this nice Git Client

**Comment by zenorocha** [comment]
Ohh, that's interesting. I like Tower :)

**Comment by davrosull** [comment]
I've created a Dracula theme for Tower 5 here: https://github.com/davrosull/tower

 ![Screenshot](https://raw.githubusercontent.com/davrosull/tower/master/screenshot.png)

**Comment by zenorocha** [comment]
Hey @davrosull,

Good job on this!

Would you be interested in transferring this repository to the official organization (https://github.com/dracula)? You'll continue maintaining this project, the only difference is that we can make it more visible and include it on the site (https://draculatheme.com).

If you're ok with it, I sent you an invitation to join the org so you can transfer the repo :)

**Comment by davrosull** [comment]
Thanks @zenorocha - more than happy to transfer it.

**Comment by zenorocha** [comment]
We're live! Thanks @davrosull for building this theme :D

https://draculatheme.com/tower
