### ISSUE TITLE
what font is used in the screenshot in the README

### ISSUE THREAD

**Issue by gh0stkey** [dracula/dracula-theme#422]
what font is used in the screenshot in the README

**Comment by benknoble** [comment]
Er, for which theme? The main repo doesn’t have a screenshot, as far as I can see?

**Comment by gh0stkey** [comment]
> 嗯，哪个主题？据我所知，主仓库没有屏幕截图？

https://github.com/dracula/iterm/tree/3844329c0a2a058dbca956ba44e98c20bec7a17e

**Comment by benknoble** [comment]
@nesl247 @zenorocha can we transfer this to the iterm repo? Or is there a better place for it?

**Comment by benknoble** [comment]
Actually, seems like a dupe of https://github.com/dracula/iterm/issues/12

**Comment by zenorocha** [comment]
That's Monaco
