### ISSUE TITLE
New theme: Textadept

### ISSUE THREAD

**Issue by sodomon2** [dracula/dracula-theme#423]
so I have seen dracula theme is for many editors like sublime text,vscode,etc but it is not for the textadept editor and it would be great if it was so I make this issue 

it would be very good if they implemented it in textadept :b

**Comment by rgieseke** [comment]
It's in the latest update of base16-textadept - you would have to update Textadept to the latest nightly release though.

https://github.com/rgieseke/base16-textadept/blob/master/themes/base16-dracula.lua

**Comment by zenorocha** [comment]
Does that solve your problem @sodomon2? Thanks for sharing @rgieseke!

**Comment by sodomon2** [comment]
> It's in the latest update of base16-textadept - you would have to update Textadept to the latest nightly release though.
> 
> https://github.com/rgieseke/base16-textadept/blob/master/themes/base16-dracula.lua

why is textadept version 10.3 not supported??

**Comment by rgieseke** [comment]
> why is textadept version 10.3 not supported??

I use TA11 only and the updates with the new theme were pulled from the base16 repo after i did the update.

You could paste the color values from https://github.com/rgieseke/base16-textadept/blob/master/themes/base16-dracula.lua#L10 into an older theme file and it should work.

**Comment by sodomon2** [comment]
oh thank you for working
