### ISSUE TITLE
New Theme: Obsidian.md

### ISSUE THREAD

**Issue by andybyers21** [dracula/dracula-theme#424]
Hi All, I made a new theme for the markdown note taking app, Obsidian.md

### GitHub Repo Here:
https://github.com/andybyers21/Obsidian.md

![screenshot](https://raw.githubusercontent.com/andybyers21/Obsidian.md/master/screenshot.png)

**Comment by Abbabon** [comment]
Been using it for a while now :O
Great contribution!

**Comment by andybyers21** [comment]
> Been using it for a while now :O
> Great contribution!

Thanks, it's a fantastic app

**Comment by n0f3** [comment]
hi @andybyers21 how does it compare to: https://github.com/jarodise/Dracula-for-Obsidian.md?

**Comment by andybyers21** [comment]
> hi @andybyers21 how does it compare to: https://github.com/jarodise/Dracula-for-Obsidian.md?

Hi @n0f3, it's similar but closer to the official Dracula spec. Headings are all one colour rather than multi coloured. HTML, strong's and em's are also correctly coloured according to the spec. I've used a subtler font and colour scheme for the icons and interface and it also includes Andy Matuschak style note scrolling.

**Comment by n0f3** [comment]
Thank you for the reply andy! I didn't like the multiple colors in the other theme implementation, so I'll give yours a go instead!

**Comment by andybyers21** [comment]
Thanks. Let me know if you have any suggestions for improvement.

**Comment by zenorocha** [comment]
Hey @andybyers21! Good job on this theme. Obsidian looks great and I'm excited to try it out using this theme :)

I just sent you an invite to join the Dracula organization. Now you can transfer the repository.

By the way, @jarodise would you like to join efforts on this theme?

Thanks for your patience @andybyers21!

**Comment by andybyers21** [comment]
Thanks @zenorocha, I have initiated the transfer to the Dracula organisation.

Also, more than happy to have @jarodise along for the ride.

**Comment by zenorocha** [comment]
https://draculatheme.com/obsidian 🎉 🎉 🎉  Thanks @andybyers21!
