### ISSUE TITLE
New Theme: Colorls

### ISSUE THREAD

**Issue by bkclerke** [dracula/dracula-theme#425]
## New Theme Idea

I'm using Dracula with iTerm2 and I have Powerlevel10k and Colorls installed. I was trying to make the [colorls](https://github.com/athityakumar/colorls) match the Dracula theme. This is what I got so far:
<img width="762" alt="Screen Shot 2020-07-15 at 8 04 54 AM" src="https://user-images.githubusercontent.com/4968254/87561750-f4452e00-c671-11ea-8154-eae7201f8227.png">

#### ColorLS: dark-colors.yaml

```
# Main Colors
unrecognized_file: "#bd93f9" # purple
recognized_file:   "#ff79c6" # pink
dir:               "#8be9fd" # cyan

# Link
dead_link: "#ff5555" # red
link:      "#8be9fd" # cyan

# special files
socket:    "#50fa7b" # green
blockdev:  "#50fa7b" # green
chardev:   "#50fa7b" # green

# Access Modes
write:     "#6272a4" # comment
read:      "#ff79c6" # pink
exec:      "#ffb86c" # orange
no_access: "#ff5555" # red

# Age
day_old:     "#50fa7b" # green
hour_old:    "#ff79c6" # pink
no_modifier: "#8be9fd" # cyan

# File Size
file_large:  "#ffb86c" # orange
file_medium: "#50fa7b" # green
file_small:  "#8be9fd" # cyan

# Random
report: white
user:   "#6272a4" # comment
tree:   "#bd93f9" # purple
empty:  "#f1fa8c" # yellow
error:  "#ff5555" # red
normal: "#6272a4" # comment

# Git
addition:     "#ff79c6" # pink
modification: "#6272a4" # comment
deletion:     "#ff5555" # red
untracked:    "#f1fa8c" # yellow
unchanged:    "#50fa7b" # green
```

**Comment by bigpick** [comment]
Heya! You should check this out too: https://github.com/dracula/dracula-theme/issues/411 (I had added this support into colorls, and then opened that PR here once the colorls work was in)

**Comment by zenorocha** [comment]
I'll be closing this issue in favor of #411, but great job @bkclerke!

@bigpick what do you think of using @bkclerke's screenshot on https://github.com/bigpick/colorls? It looks phenomenal! ;)

**Comment by bigpick** [comment]
I agree -- they do look much nicer :)

TiL - On mac, press space after pressing the CMD+Shift+4 to get a screen shot to get a full window capture (with fancy drop shadow and all).

 I've updated https://github.com/bigpick/colorls with some new samples accordingly, what do you think? (I don't usually user powerlevel, so I just configured it for the screenshot purposes)

**Comment by zenorocha** [comment]
https://draculatheme.com/colorls :DDD

**Comment by betancour** [comment]
@bkclerke Blake, can you share the powelevel10k color configurations too?
