### ISSUE TITLE
Youtube theme

### ISSUE THREAD

**Issue by jesperkallunki** [dracula/dracula-theme#427]
https://github.com/Jepulisk/youtube

Youtube theme using https://github.com/RaitaroH/YouTube-DeepDark as base and dracula as color scheme.

Didn't find anything else except https://old.reddit.com/r/unixporn/comments/8cbhoq/kde_vivaldiyoutube_dracula_colors/ and the repo in comments doesn't exist anymore.

**Comment by Kritiqual** [comment]
Hi, I found his gist! https://gist.github.com/Dazage/bc4dfdd908e24f5591b1f5d26392a0fb

**Comment by luxonauta** [comment]
That's cool ✨; thank you very much for your interest in contributing; however, we already have a theme for [Youtube](https://draculatheme.com/youtube), so I will be closing this Issue!

**Comment by mtrong100** [comment]
dracula theme for youtube not working anymore
