### ISSUE TITLE
Dracula palette for TiddlyWiki

### ISSUE THREAD

**Issue by SlyBouhafs** [dracula/dracula-theme#428]
Hey! I just ported the Dracula theme to TiddlyWiki, here's the repo : https://github.com/SlyBouhafs/TiddlyWikiDracula

![screenshot](https://user-images.githubusercontent.com/1410462/87834259-e1a14380-c881-11ea-9a2f-4f6fb8a4f147.png)

What do you think ?

**Comment by zenorocha** [comment]
Hey @SlyBouhafs! 

I'm glad to see that you created a theme for TiddlyWiki! Are you interested in transferring your repository to the official organization (https://github.com/dracula)? You'll continue maintaining this project, the only difference is that we can make it more visible and include it on the site (https://draculatheme.com).

I just sent you an invite to join the organization. If you accept, you'll be able to transfer the repo and we can continue with adding to the site.

Thanks for your patience!

**Comment by zenorocha** [comment]
https://draculatheme.com/tiddlywiki/

Thanks @SlyBouhafs 🎉 🎉 🎉
