### ISSUE TITLE
Dracula themed Aurora theme 

### ISSUE THREAD

**Issue by NicTanghe** [dracula/dracula-theme#429]
## New Theme?
Ok i made a colortheme. For keyboards using aurora.
Its scewed because keyboard LEDs don't emit the same colours as a a pcscreen.

## Existing Theme?

They dont exist yet

Theme at https://github.com/NicTanghe/Aurora-Dracula/blob/master/README.md

**Comment by luxonauta** [comment]
This is awesome 🤯, I didn't know about this tool!

**Comment by luxonauta** [comment]
I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/NicTanghe/Aurora-Dracula)
- [New repository.](https://github.com/dracula/aurora)

Thanks for building this! 🎉

**Comment by NicTanghe** [comment]
hello,
No idea how to c the invite or join the org.

**Comment by luxonauta** [comment]
Hi 👋🏻, are you still interested in the project? 🫡
