### ISSUE TITLE
New Theme: Pywal

### ISSUE THREAD

**Issue by timescam** [dracula/dracula-theme#430]
Dracula for Pywal
![screenshot](https://user-images.githubusercontent.com/45168541/90750147-ffd9e380-e306-11ea-956b-4d6d44ed38a9.png)

~Currently Pywal only has the base16 version as base16-dracula, this is based on the [.xrecourse ](https://github.com/dracula/xresources) instead~
Repo: https://github.com/timescam/pywal

**Comment by timescam** [comment]
Updated the colors to the ANSI Color Palette under Dracula Specification.

**Comment by zenorocha** [comment]
Hey @timescam, you can transfer the repository now.

Thanks for your patience!

**Comment by timescam** [comment]
transferred

**Comment by zenorocha** [comment]
And we're live! https://draculatheme.com/pywal 🎉 🎉 🎉
