### ISSUE TITLE
Dracula Wallpaper

### ISSUE THREAD

**Issue by prathampowar2001** [dracula/dracula-theme#431]
## Wallpaper to go with the theme

Many people ricing their desktop would like to have a matching wallpaper.After some research I came across a wallpaper just perfect for me except the manjaro logo which I don't mind.If you agree this could be a cool wallpaper to go along with colorschemes.
The link 
https://preview.redd.it/skkl2ln1sk551.png?width=8001&format=png&auto=webp&s=94a185f32f1e9d69e044962a2b08e9e2ea975347

**Comment by zenorocha** [comment]
Hey @prathampowar2001, thanks a lot for the suggestion.

We do have all these wallpapers available now:
* https://github.com/dracula/wallpaper
* https://draculatheme.com/wallpaper
