### ISSUE TITLE
I created an ableton live10 Skin with the dracula theme

### ISSUE THREAD

**Issue by NicTanghe** [dracula/dracula-theme#432]
## New Theme?

Not sure if I named correctly [color palette](https://github.com/dracula/dracula-theme#color-palette).

This time I did use the propper Github Template.
Repo can be found at.
https://github.com/NicTanghe/Dracula-AbletonTheme

Its stil somewhat of a wip.

**Comment by zenorocha** [comment]
Hey @NicTanghe, we already have an Ableton Live 10 theme.

Site: https://draculatheme.com/ableton-live
Source Code: https://github.com/dracula/ableton-live 

It would be great if you could contribute to that one instead.

Thanks for using Dracula and creating new themes!

**Comment by NicTanghe** [comment]
Ooh i dident c it when i made this.
