### ISSUE TITLE
New theme: Zathura

### ISSUE THREAD

**Issue by ethancedwards8** [dracula/dracula-theme#433]
Thanks for creating this awesome theme, I contribute to the tmux theme regularly and I thought I would make my own. [Dracula-zathura theme!](https://github.com/ethancedwards8/dracula-zathura).

The user can hit C-i to switch between a dark background and a light background. The reasoning for this is sometimes it can be hard to read text if the background is dark.

**Comment by zenorocha** [comment]
Hey @ethancedwards8! 

I'm glad to see that you created a theme for Zathura! Are you interested in transferring your repository to the official organization (https://github.com/dracula)? You'll continue maintaining this project, the only difference is that we can make it more visible and include it on the site (https://draculatheme.com).

I just sent you an invite to join the organization. If you accept, you'll be able to transfer the repo and we can continue with adding to the site.

Thanks for building it!

**Comment by ethancedwards8** [comment]
Sure thing! I can attempt the transfer now or I can wait?

**Comment by ethancedwards8** [comment]
Thanks for adding this, I guess we should close this issue?

**Comment by zenorocha** [comment]
We're live! Thanks @ethancedwards8 :D

https://draculatheme.com/zathura/
