### ISSUE TITLE
dracula for thonny ide

### ISSUE THREAD

**Issue by danspinola** [dracula/dracula-theme#434]
Hi there! I ported Dracula for a thonny, which is a Python IDE for beginners. 😋

https://github.com/danspinola/thonny

**Comment by zenorocha** [comment]
Hey @danspinola! Thanks for your patience.

I just sent you an invitation to join the Dracula org. Once you accept the invite, you can transfer the repository.

Let me know if you have any other questions.

**Comment by danspinola** [comment]
Feito!

Ei, gostei muito do seu livro, 14 hábitos. Achei muito importante, principalmente pra mim que estou começando agora. 😄❤

**Comment by zenorocha** [comment]
Switching to English in order for this content to be accessible by others on GitHub...

Thank you so much man, I'm glad to hear that you enjoyed the book.

P.S.: I like that you created a sample.py too, just added to the template: https://github.com/dracula/template/blob/master/sample/sample.py

**Comment by zenorocha** [comment]
@danspinola I really like the fact that you translated that sample code to Python.

Can you leave a comment on this thread with your code snippet?

https://github.com/dracula/dracula-theme/discussions/444

Thanks!

**Comment by zenorocha** [comment]
It's live! https://draculatheme.com/thonny :D

Feel free to share with the Thonny community!
