### ISSUE TITLE
A Dracula Theme for MusicBee (https://github.com/mly32/Dracula-MusicBee)

### ISSUE THREAD

**Issue by mly32** [dracula/dracula-theme#435]
## New Theme

This is a theme (using the Dracula color palette) for [MusicBee](https://www.getmusicbee.com/), the popular music manager and player.

## Repo link

https://github.com/mly32/Dracula-MusicBee

**Comment by zenorocha** [comment]
Hey @mly32! Thanks for your patience.

I just sent you an invitation to join the Dracula org. Once you accept the invite, you can transfer the repository.

Let me know if you have any other questions.

**Comment by zenorocha** [comment]
It's live @mly32! https://draculatheme.com/musicbee :D

Feel free to share with the MusicBee community!
