### ISSUE TITLE
Theme for B4X

### ISSUE THREAD

**Issue by siqueirabt** [dracula/dracula-theme#436]
New Theme
I've created a new theme for B4X

Repository: https://github.com/siqueirabt/b4x-theme-dracula

**Comment by zenorocha** [comment]
Hey @siqueirabt! Thanks for your patience.

I just sent you an invitation to join the Dracula org. Once you accept the invite, you can transfer the repository.

Let me know if you have any other questions.

**Comment by zenorocha** [comment]
It's live @siqueirabt! https://draculatheme.com/b4x :D

Feel free to share with the B4X community!
