### ISSUE TITLE
Enable Dracula Theme for DOOM Emacs

### ISSUE THREAD

**Issue by helderburato** [dracula/dracula-theme#437]
## New Theme

This is a theme (using Dracula color palette) for [DOOM Emacs](https://github.com/hlissner/doom-emacs), a popular framework for Emacs.

## Repository

Added to [helderburato/doom-emacs](https://github.com/helderburato/doom-emacs).

**Comment by zenorocha** [comment]
Hey @helderburato! Thanks for your patience man.

I just sent you an invitation to join the Dracula org. Once you accept the invite, you can transfer the repository.

Let me know if you have any other question.

**Comment by helderburato** [comment]
Hey @zenorocha! No problem. 😄

All right, I accepted and I'll transfer the repository to Dracula.

**Comment by zenorocha** [comment]
Aaaaand it's live! https://draculatheme.com/doom-emacs :D

Feel free to share with the DOOM Emacs community!

**Comment by helderburato** [comment]
Amazing! ✨
Thanks @zenorocha!
