### ISSUE TITLE
🎉 New Theme: BetterDiscord

### ISSUE THREAD

**Issue by KabirKwatra** [dracula/dracula-theme#438]
## [New Theme: BetterDiscord](https://github.com/KabirKwatra/BetterDiscord)
> I setup the repo to be easily migrated so some of the links might be broken; it's based on the template

### Dracula for [BetterDiscord](https://betterdiscord.net)

> A dark theme for [BetterDiscord](https://betterdiscord.net).

![Screenshot](https://github.com/KabirKwatra/BetterDiscord/raw/master/screenshot.png)

### Install

All instructions can be found at [draculatheme.com/betterdiscord](https://draculatheme.com/betterdiscord).

### Team

This theme is maintained by the following person(s) and a bunch of [awesome contributors](https://github.com/dracula/betterdiscord/graphs/contributors).

[![Kabir Kwatra](https://avatars0.githubusercontent.com/u/30360059?v=3&s=70)](https://github.com/KabirKwatra) | [![Zeno Rocha](https://avatars2.githubusercontent.com/u/398893?v=3&s=70)](https://github.com/zenorocha)
--- | ---
[Kabir Kwatra](https://github.com/KabirKwatra) | [Zeno Rocha](https://github.com/zenorocha)

### License

[MIT License](./LICENSE)

**Comment by bigpick** [comment]
When I try to load this via the `themes` route, nothing seems to get applied (after updating it to load from your repo's raw URL in the meantime).

If I straight copy/paste the `base.css` into the custom CSS, some things change, but looks like _only_ the background colors change; none of the sidebar titles colors/etc change?

**Comment by KabirKwatra** [comment]
Should be fixed with kabirkwatra/BetterDiscord@a430ab9

**Comment by bigpick** [comment]
Cool - thanks! That got the theme file application working now.

Am curious though -- how'd you get the title of the role sections to be colored? I know you can get a individual role a color, but could not figure out how to get the role title itself colored as well

**Comment by KabirKwatra** [comment]
I seemed to have this plugin enabled when taking that screenshot: [BetterRoleColors](https://github.com/rauenzi/BetterDiscordAddons/tree/master/Plugins/BetterRoleColors)

**Comment by bigpick** [comment]
One thing that'd be nice is to also update the mention highlight background/lefthand sidebar so that it's not that default off-yellow... I thought I've seen ways to do so, but has been a while since I've looked at BD things (also not sure what Dracula/Zeno's take on that type of stuff, since technically is against ToS)

**Comment by KabirKwatra** [comment]
I would still love for this to be merged

**Comment by zenorocha** [comment]
Hey @KabirKwatra! I just sent you an invite to join the Dracula organization 🎉 

You can proceed with the transfer now.

Thanks for your patience :)

**Comment by zenorocha** [comment]
Thanks @KabirKwatra!  🎮 🎮 🎮  

https://draculatheme.com/betterdiscord
