### ISSUE TITLE
New Theme: Hex Installer OneUI/OneUI 2.0 Theme

### ISSUE THREAD

**Issue by aravindps** [dracula/dracula-theme#439]
## New Hex Installer OneUI/OneUI 2.0

I have add a Dracula based One UI theme for samsung One UI. 

https://github.com/aravindps/dracula-one-ui-hex

**Comment by luxonauta** [comment]
Hey, very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/aravindps/dracula-one-ui-hex)
- [New repository.](https://github.com/dracula/hex-installer)

Thanks for building this! 🎉

**Comment by aravindps** [comment]
Done!
