### ISSUE TITLE
Dracula for Marp

### ISSUE THREAD

**Issue by dgisolfi** [dracula/dracula-theme#440]
## New Theme: Marp

Repo: https://github.com/dgisolfi/marp

**Comment by zenorocha** [comment]
Hey @dgisolfi!

I just sent you an invitation to join the Dracula org. Once you accept the invite, you can transfer the repository.

Let me know if you have any other questions.

**Comment by zenorocha** [comment]
It's live @dgisolfi! https://draculatheme.com/marp :D

Feel free to share with the Marp community!
