### ISSUE TITLE
Dracula for Plank

### ISSUE THREAD

**Issue by weltonfelix** [dracula/dracula-theme#441]
Hi! I have created [Dracula theme for Plank dock](https://github.com/weltonfelix/plank).

**Comment by zenorocha** [comment]
Hey @weltonfelix! 

I'm glad to see that you created a theme for Plank! Are you interested in transferring your repository to the official organization (https://github.com/dracula)? You'll continue maintaining this project, the only difference is that we can make it more visible and include it on the site (https://draculatheme.com).

I just sent you an invite to join the organization. If you accept, you'll be able to transfer the repo and we can continue with adding to the site.

Thanks for building it!

**Comment by weltonfelix** [comment]
That sounds great! I just transferred it.

**Comment by zenorocha** [comment]
https://draculatheme.com/plank

Thanks @weltonfelix!
