### ISSUE TITLE
Dracual Theme for DWM-Dynamic Window Manager

### ISSUE THREAD

**Issue by pspiagicw** [dracula/dracula-theme#446]
## New Theme

Recently after discovering your website draculatheme.com . I riced my linux install with Dracula theme.Only problem my window manager was not according to the theme.I configured my dwm to go with the dracula theme.So I then contributed my colors.

[The Link](https://github.com/prathampowar2001/dracula-dwm)

**Comment by luxonauta** [comment]
Hey, very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/pspiagicw/dracula-dwm)
- [New repository.](https://github.com/dracula/dwm)

Thanks for building this! 🎉
