### ISSUE TITLE
New theme: IDLE

### ISSUE THREAD

**Issue by timescam** [dracula/dracula-theme#447]
Dracula for [IDLE](https://docs.python.org/3/library/idle.html) 
![screenshot](https://user-images.githubusercontent.com/45168541/90749502-16cc0600-e306-11ea-8b23-595ffcf00cc0.png)

Repo: [https://github.com/timescam/idle](https://github.com/timescam/idle)

**Comment by zenorocha** [comment]
Hey @timescam! 

I'm glad to see that you created a theme for IDLE! Are you interested in transferring your repository to the official organization (https://github.com/dracula)? You'll continue maintaining this project, the only difference is that we can make it more visible and include it on the site (https://draculatheme.com).

I just sent you an invite to join the organization. If you accept, you'll be able to transfer the repo and we can continue with adding to the site.

Thanks for building it!

**Comment by timescam** [comment]
transferred

**Comment by zenorocha** [comment]
https://draculatheme.com/idle :D
