### ISSUE TITLE
New theme: Dracula theme for thelounge

### ISSUE THREAD

**Issue by ronilaukkarinen** [dracula/dracula-theme#449]
## New Theme?

Hello! I have created a Dracula theme for [thelounge IRC client](https://github.com/thelounge/thelounge), it's available [here on GitHub](https://github.com/ronilaukkarinen/thelounge-theme-dracula).

<img src="https://i.imgur.com/rBadsRb.png" alt="Screenshot of the Dracula theme for The Lounge" width="550">

**Comment by zenorocha** [comment]
Hey @ronilaukkarinen! 

I'm glad to see that you created a theme for thelounge! Are you interested in transferring your repository to the official organization (https://github.com/dracula)? You'll continue maintaining this project, the only difference is that we can make it more visible and include it on the site (https://draculatheme.com).

I just sent you an invite to join the organization. If you accept, you'll be able to transfer the repo and we can continue with adding to the site.

I noticed you didn't use the https://github.com/dracula/template. Would you mind creating a repo from there? That way we can have everything standardized.

Thanks for building it!

**Comment by ronilaukkarinen** [comment]
Yes! Transferred it just now, can be found [here](https://github.com/dracula/thelounge). I did not notice the template, will add stuff from there asap. Thanks for this privilege!

**Comment by zenorocha** [comment]
https://draculatheme.com/thelounge :D
