### ISSUE TITLE
New ReNoise Theme

### ISSUE THREAD

**Issue by molotovbliss** [dracula/dracula-theme#450]
## New ReNoise Theme

![ReNoise](https://raw.githubusercontent.com/molotovbliss/dracula-renoise-theme/master/mb-dracula-renoise.png)

- https://github.com/molotovbliss/dracula-renoise-theme

### What's ReNoise?
ReNoise is a multiOS tracker based DAW (Digital Audio Workstation)
- https://www.renoise.com/
- https://wikipedia.org/wiki/Renoise
- https://forum.renoise.com/t/color-themes-for-renoise/18003/605

**Comment by zenorocha** [comment]
Hey @molotovbliss! 

I'm glad to see that you create a theme for ReNoise! Are you interested in transferring this repository to the official organization (https://github.com/dracula)? You'll continue maintaining this project, the only difference is that we can make it more visible and include it on the site (https://draculatheme.com).

I just sent you an invite to join the organization. If you accept, you'll be able to transfer the repo and we can continue with adding to the site.

Thanks for building it!

**Comment by molotovbliss** [comment]
Hey @zenorocha No problem maintaining the repo and transferring it to the organization.

* https://github.com/molotovbliss/renoise

Let me know, Thanks! 🧛

**Comment by zenorocha** [comment]
And we're live, thanks @molotovbliss! 🎉 🎉 🎉 

https://draculatheme.com/renoise
