### ISSUE TITLE
New theme - xfce4-terminal

### ISSUE THREAD

**Issue by ArthurBacci64** [dracula/dracula-theme#451]
# dracula for xfce4-terminal

So, I created this theme based on `gnome-terminal` dracula theme, with some modifications, like the background color, to match with the window manager's color.
<https://github.com/ArthurBacci64/dracula-xfce4-terminal>

**Comment by zenorocha** [comment]
We ended up moving this other theme since it was older: https://github.com/dracula/xfce4-terminal/

Let's join forces over there @ArthurBacci64? Thanks!

**Comment by ArthurBacci64** [comment]
Ok.
