### ISSUE TITLE
Keypirinha theme

### ISSUE THREAD

**Issue by ChildishGiant** [dracula/dracula-theme#453]
I made a theme for keypirinha but I'm not quite sure how to package it.
Here it is: 

```ini
[gui]
theme = Dracula

[theme/Dracula]
opacity_back = 100
satellite_show = never
satellite_pos = topcenter
satellite_size = jumbo
control_margin = 6
textbox_padding = 4
listitem_padding = 3
layout = list_dialnum,list_actions,list_selmark,list_icon,list_hits
color_background = #282A36
color_foreground = #F8F8F2
color_title = #BD93F9
color_textbox_back = #44475A
color_faded = #a2a2a2
color_status = #44475A
color_accent = #a6e5ff
color_warn = #FF5555
color_listitem_back = #282A36
color_listitem_title = #f2f2f2
color_listitem_desc = #BCC2CD
color_listitem_tips = #6272A4
color_listitem_selected_back = #2f2f2f
color_listitem_selected_title = #BD93F9
color_listitem_selected_desc = #F8F8F2
color_listitem_selected_tips = #8BE9FD
font_large_size = 28
font_large_style = bold
font_snormal_size = 14
font_snormal_style = cleartype
font_normal_size = 14
font_normal_style = cleartype
font_small_size = 9
font_small_style = cleartype
font_face = Tahoma, Arial, Segoe UI
compact_results = no
listitem_title_font = snormal
```

**Comment by zenorocha** [comment]
Hey @ChildishGiant, that's great!

I suggest you create a new repository based on the [template](https://github.com/dracula/template) and then create a file to store this code snippet. We did something similar with the [Slack theme](https://github.com/dracula/slack) (see dracula.md).

Having its own dedicated repo is important to keep track of any future changes and also to feature on the site :)

**Comment by mawiseman** [comment]
@zenorocha  i didn't see this ticket wen i created mine.

Are we doing the same thing here?
Not sure how different this is but we could include it as an alternative .ini file in my repo

https://github.com/mawiseman/keypirinha-theme-dracula

**Comment by ChildishGiant** [comment]
![image](https://user-images.githubusercontent.com/13716824/96334182-a3751500-1066-11eb-8a95-86d8036f879d.png)
This is what mine looks like

**Comment by zenorocha** [comment]
Closing this in favor of #457, since it contains the entire repository ;)

Thank you so much @ChildishGiant and @mawiseman for pushing this!
