### ISSUE TITLE
theme for fman

### ISSUE THREAD

**Issue by sf-pear** [dracula/dracula-theme#454]
Hi there,

I have adjusted my settings on fman based on dracula as I love it on sublime and hyper. So I thought I'd share: https://github.com/sf-pear/dracula-for-fman

It's pretty basic, to use it all you have to do is copy the code to update the styles.

This is the first time ever I'm sharing something on github, so if I did something incorrectly and need to fix anything please let me know!

Cheers :)

**Comment by spikecodes** [comment]
Looks good! Maybe delete the [sample](https://github.com/sf-pear/dracula-for-fman/tree/master/sample) folder?

**Comment by sf-pear** [comment]
> Looks good! Maybe delete the [sample](https://github.com/sf-pear/dracula-for-fman/tree/master/sample) folder?

Deleted it :) Thanks!

**Comment by zenorocha** [comment]
Hey @sf-pear! 

I'm glad to see that you create this theme! Are you interested in transferring your repository to the official organization (https://github.com/dracula)? You'll continue maintaining this project, the only difference is that we can make it more visible and include it on the site (https://draculatheme.com).

I just sent you an invite to join the organization. If you accept, you'll be able to transfer the repo and we can continue with adding to the site.

Thanks for building it!

**Comment by sf-pear** [comment]
> Hey @sf-pear!
> 
> I'm glad to see that you create this theme! Are you interested in transferring your repository to the official organization (https://github.com/dracula)? You'll continue maintaining this project, the only difference is that we can make it more visible and include it on the site (https://draculatheme.com).
> 
> I just sent you an invite to join the organization. If you accept, you'll be able to transfer the repo and we can continue with adding to the site.
> 
> Thanks for building it!

Of course, I have transferred it. Happy to contribute :)

**Comment by zenorocha** [comment]
Thank you so much @sf-pear, it's live now! 

https://draculatheme.com/fman

Happy Halloween 👻
