### ISSUE TITLE
New theme for midnight commander (mc)

### ISSUE THREAD

**Issue by davison** [dracula/dracula-theme#455]
## New Theme

Simple theme for midnight commander (mc) - a terminal based file manager
https://github.com/davison/mc

At present this has a dependency on a suitable terminal theme also being installed (as it simply references colours defined in the terminal theme palette) - don't know if that breaks any rules for inclusion.

Tested in gnome-terminal on Linux and iTerm2 on macos with the appropriate terminal themes installed.

**Comment by davison** [comment]
pushed a version that works independently of the terminal's colour palette but which has theme colours that are not as true to the Dracula theme. Either or both can be installed giving the user a choice at runtime.

**Comment by zenorocha** [comment]
Hey @davison! 

I'm glad to see that you create this theme! Are you interested in transferring your repository to the official organization (https://github.com/dracula)? You'll continue maintaining this project, the only difference is that we can make it more visible and include it on the site (https://draculatheme.com).

I just sent you an invite to join the organization. If you accept, you'll be able to transfer the repo and we can continue with adding to the site.

Thanks for building it!

**Comment by davison** [comment]
transferred. https://github.com/dracula/mc

**Comment by zenorocha** [comment]
It's live! https://draculatheme.com/midnight-commander 🎉 🎉 🎉
