### ISSUE TITLE
Dracula theme for StandardNotes

### ISSUE THREAD

**Issue by SlyBouhafs** [dracula/dracula-theme#456]
## Dracula theme for StandardNotes

Hey, i created another theme for StandarNotes, i know there are two Dracula themes for Standarnotes out there but they didn't feel too Draculish for me, so i made this one.

Here's a screenshot: 
![preview](https://user-images.githubusercontent.com/1410462/94815036-fce80d80-03f1-11eb-8708-9e580781f7ea.png)

And here's the repo: https://github.com/SlyBouhafs/sn-theme-dracula

**Comment by zenorocha** [comment]
This looks great @SlyBouhafs! Are you interested in merging efforts @cameronldn @jansendotsh?

Related:
* https://github.com/dracula/dracula-theme/issues/330
* https://github.com/cameronldn/sn-theme-dracula
* https://github.com/jansendotsh/sn-dracula-theme

**Comment by SlyBouhafs** [comment]
I started the repository transfer over to the Dracula organization.

**Comment by zenorocha** [comment]
It's live https://draculatheme.com/standard-notes 🎉 🎉 🎉
