### ISSUE TITLE
New Theme: Keypirinha 

### ISSUE THREAD

**Issue by mawiseman** [dracula/dracula-theme#457]
Please checkout my theme contribution for the windows launcher Keypirinha 
https://github.com/mawiseman/keypirinha-theme-dracula

**Comment by zenorocha** [comment]
Hey @mawiseman! 

I'm glad to see that you create this theme! Are you interested in transferring your repository to the official organization (https://github.com/dracula)? You'll continue maintaining this project, the only difference is that we can make it more visible and include it on the site (https://draculatheme.com).

I just sent you an invite to join the organization. If you accept, you'll be able to transfer the repo and we can continue with adding to the site.

Thanks for building it!

**Comment by zenorocha** [comment]
It's live! https://draculatheme.com/keypirinha

Thanks @mawiseman for adding the submodule on dracula-theme and for adding the entry on the website too!
