### ISSUE TITLE
CopyQ Theme

### ISSUE THREAD

**Issue by kshaner** [dracula/dracula-theme#458]
I've created a Dracula based theme for the [CopyQ ](https://hluk.github.io/CopyQ/) clipboard manager. Here's the link: https://github.com/kshaner/dracula-copyq

**Comment by zenorocha** [comment]
Hey @kshaner! 

I'm glad to see that you create this theme! Are you interested in transferring your repository to the official organization (https://github.com/dracula)? You'll continue maintaining this project, the only difference is that we can make it more visible and include it on the site (https://draculatheme.com).

I just sent you an invite to join the organization. If you accept, you'll be able to transfer the repo and we can continue with adding to the site.

Thanks for building it!

**Comment by kshaner** [comment]
No problem! I've transferred the repo. Feel free to add the submodule in the main repo whenever you have time. :)

**Comment by zenorocha** [comment]
It's live on the site now! https://draculatheme.com/copyq

Thanks @kshaner and happy Halloween! 🎃
