### ISSUE TITLE
Dracula theme for Cryptowatch

### ISSUE THREAD

**Issue by diogorsergio** [dracula/dracula-theme#460]
Hi! I've created a Dracula theme for Cryptowatch (crypto trading terminal).

Repo: https://github.com/diogorsergio/dracula-cryptowatch

**Comment by zenorocha** [comment]
Hey @diogorsergio! 

I'm glad to see that you create this theme! Are you interested in transferring your repository to the official organization (https://github.com/dracula)? You'll continue maintaining this project, the only difference is that we can make it more visible and include it on the site (https://draculatheme.com).

I just sent you an invite to join the organization. If you accept, you'll be able to transfer the repo and we can continue with adding to the site.

Thanks for building it!

**Comment by diogorsergio** [comment]
Hi @zenorocha!

Thanks for the amazing theme I manage to use everywhere. 

I've made the transfer and renamed from 'dracula-cryptowatch' to 'cryptowatch' to follow convention. But feel free to change if thats not how it should be. 

Thanks!

**Comment by zenorocha** [comment]
Thanks @diogorsergio, it's live on the site now! https://draculatheme.com/cryptowatch

Happy Halloween! 🎃
