### ISSUE TITLE
Dracula Theme for Micro

### ISSUE THREAD

**Issue by spikecodes** [dracula/dracula-theme#461]
Hi! I love the Dracula theme and I use the popular terminal text editor, [Micro](https://github.com/zyedidia/micro).
I have ported the Dracula theme to Micro here: https://github.com/spikecodes/dracula-micro.

![image](https://user-images.githubusercontent.com/19519553/97040392-b4200200-1522-11eb-81fe-874c6db935bc.png)

Thank you in advance!

**Comment by zenorocha** [comment]
Hey @spikecodes! 

I'm glad to see that you create this theme! Are you interested in transferring your repository to the official organization (https://github.com/dracula)? You'll continue maintaining this project, the only difference is that we can make it more visible and include it on the site (https://draculatheme.com).

I just sent you an invite to join the organization. If you accept, you'll be able to transfer the repo and we can continue with adding to the site.

Thanks for building it!

**Comment by spikecodes** [comment]
Hey Zeno!

Thank you, I accepted the invite!

I will happily transfer the micro port of Dracula to the main org!

**Comment by spikecodes** [comment]
@zenorocha How might I go about submitting micro to [draculatheme.com](https://github.com/dracula/draculatheme.com)?

**Comment by zenorocha** [comment]
I just added ;)

https://draculatheme.com/micro

**Comment by spikecodes** [comment]
Wonderful, thank you :D
