### ISSUE TITLE
Kicad

### ISSUE THREAD

**Issue by bagnaram** [dracula/dracula-theme#464]
## New Theme?

Support for a dark [Kicad](https://kicad-pcb.org) 5.x JSON theme for eschema and pcbnew. See https://github.com/bagnaram/dracula-kicad

**Comment by zenorocha** [comment]
Hey @bagnaram! 

I'm glad to see that you create this theme! Are you interested in transferring your repository to the official organization (https://github.com/dracula)? You'll continue maintaining this project, the only difference is that we can make it more visible and include it on the site (https://draculatheme.com).

I just sent you an invite to join the organization. If you accept, you'll be able to transfer the repo and we can continue with adding to the site.

Thanks for building it!

**Comment by bagnaram** [comment]
Hey @zenorocha  I am interested in maintaining the theme and happy to merge it to the dracula org

**Comment by zenorocha** [comment]
@bagnaram I see that you accepted the invitation already, but did not transfer yet. Can you transfer the repository to the `dracula` organization now? Thanks!

**Comment by bagnaram** [comment]
Oh I did transfer it already @zenorocha. It is located here: https://github.com/dracula/kicad

**Comment by zenorocha** [comment]
It's live https://draculatheme.com/kicad. Thanks @bagnaram! 🎉 🎉 🎉
