### ISSUE TITLE
New theme for Albert

### ISSUE THREAD

**Issue by cvandal** [dracula/dracula-theme#467]
Hello :wave: 

I have created a Dracula theme for [Albert](https://github.com/albertlauncher/albert). The repo can be found here: [https://github.com/cvandal/albert-dracula-theme](https://github.com/cvandal/albert-dracula-theme).

**Comment by zenorocha** [comment]
Hey @cvandal! 

I'm glad to see that you create this theme! Are you interested in transferring your repository to the official organization (https://github.com/dracula)? You'll continue maintaining this project, the only difference is that we can make it more visible and include it on the site (https://draculatheme.com).

I just sent you an invite to join the organization. If you accept, you'll be able to transfer the repo and we can continue with adding to the site.

Thanks for building it!

**Comment by zenorocha** [comment]
It's live https://draculatheme.com/albert 🎉 🎉 🎉
