### ISSUE TITLE
Icon theme support for github desktop and stacer

### ISSUE THREAD

**Issue by slottwo** [dracula/dracula-theme#472]

**Comment by bigpick** [comment]
Hey @slottwo! Not exactly sure what you're looking for here, so some more information would be appreciated if it means could help you get what you were originally interested in.

If you're using the [GTK Dracula theme](https://github.com/dracula/gtk) and are talking about support for new icons in that theme, probably would be best to move as a a new issue under that specific repo to get support from the folks maintaining those.  If not, would need more information to say much more; thanks!

**Comment by slottwo** [comment]
OK, I will go to the specific repository, i had no idea how it worked at the time I opened the issue, sorry
