### ISSUE TITLE
New Theme: Thunderbird

### ISSUE THREAD

**Issue by maxfrei750** [dracula/dracula-theme#473]
Thunderbird theme based on the [Firefox theme](https://github.com/dracula/firefox). Already available for testing at:

https://addons.thunderbird.net/en-US/thunderbird/addon/dracula-theme-for-thunderbird/
https://github.com/maxfrei750/thunderbird

Would close https://github.com/dracula/dracula-theme/issues/416.

## TODO

- [x] Screenshot
- [x] Testing on Windows

**Comment by maxfrei750** [comment]
![Screenshot](https://raw.githubusercontent.com/maxfrei750/thunderbird/main/screenshot.png)
![Screenshot Calendar](https://raw.githubusercontent.com/maxfrei750/thunderbird/main/screenshot_calendar.png)

**Comment by zenorocha** [comment]
Thanks for building that @maxfrei750!  🎉 🎉 🎉  

I just sent you an invitation to join the Dracula org. Once you accept it, you can transfer the repository and I'll take care of the website part ;)

**Comment by maxfrei750** [comment]
@zenorocha You're welcome. Thanks for creating this great color scheme. Are there any instructions on how to transfer the repo? I'm a little scared of breaking something. :sweat_smile: 

Do I just create a new repo in the organization and push to it?

**Comment by zenorocha** [comment]
Sure!

You don't need to create a new repo in the organization. You can go to the Settings (https://github.com/maxfrei750/thunderbird/settings) and follow the instructions on the Transfer section.

Thanks again :)

**Comment by maxfrei750** [comment]
I see. Very convenient. Done.

**Comment by avatar-lavventura** [comment]
https://github.com/dracula/thunderbird/settings site cannot find

**Comment by maxfrei750** [comment]
@avatar-lavventura Sorry, but I don't seem to understand. The link you posted (https://github.com/dracula/thunderbird/settings) leads to the settings of the repo, which are not public. I think you want https://github.com/dracula/thunderbird.

Concerning the version, I'm actually not sure. But it may very well be that only current versions of thunderbird are supported.

**Comment by avatar-lavventura** [comment]
Seems like it does not work for Thunderbird newest version (78.6.0 ) and I don't know how to downgrade Thunderbird.

This site (https://draculatheme.com/thunderbird) seems dead. If you could guide me to set it up for the newest version for Thunderbird it will be helpful

**Comment by maxfrei750** [comment]
`Thunderbird 60.0 - *` means everything _above_ version 60.0. It was tested very recently and still works on the current version.

> This site (https://draculatheme.com/thunderbird) seems dead

Actually, it is not yet alive, because the repo is brand new. @zenorocha will update the homepage soon.

> If you could guide me to set it up for the newest version for Thunderbird it will be helpful

Just follow the instructions in https://github.com/dracula/thunderbird/blob/main/INSTALL.md. If you have any questions, please let me know.

**Comment by avatar-lavventura** [comment]
@maxfrei750 Thanks I am able to add the theme and its great!

Just a small questions, color for folders seems so bright (ex: `Impartant` in the image) is it normal since it was not color in Dracula?

<img width="392" alt="image" src="https://user-images.githubusercontent.com/18537398/104485619-cbc7cd80-55db-11eb-896f-aa4d57b60914.png">

**Comment by zenorocha** [comment]
@maxfrei750 I had to rename the branch from `main` to `master` for the site's build process to work properly, ok?

**Comment by maxfrei750** [comment]
@avatar-lavventura I'm glad that you like it. I don't have this issue with the bright folder color. All my folders are just white like your other folders (e.g. `Starred`). I guess that it might be a custom setting in your Thunderbird. Maybe something with the folder properties.

@zenorocha Sure.

**Comment by zenorocha** [comment]
We're live now! https://draculatheme.com/thunderbird 🎉 🎉 🎉 

Feel free to share it with your friends and other Thunderbird fans!

**Comment by avatar-lavventura** [comment]
@maxfrei750 I love the Dracula Theme, its golden. My terminal is and everything I can make is Dracula Theme :-)

One more small questions: Should I also make following changes, if I don't make it sometimes text is seens as black and its hard to read it:

<img width="664" alt="image" src="https://user-images.githubusercontent.com/18537398/104496356-edc84c80-55e9-11eb-86e4-a759ee7ba45b.png">

**Comment by maxfrei750** [comment]
@avatar-lavventura Yeah, me too. :-D

> One more small questions: Should I also make following changes under the fonts and colors

After all, it is up to you. But it is certainly a good idea. I also made similar changes:

<img width="505" alt="image" src="https://user-images.githubusercontent.com/36265931/104502097-92de2780-55e0-11eb-9bdc-9e37b04614a6.png">

Maybe, I should add a small note in the instructions. Thanks for bringing that up.

**Comment by maxfrei750** [comment]
@zenorocha I added the instructions on how to change the text, background and link colors to the repo. I saw that you usually perform submodule updates yourself. If you want to keep it that way, then please update the version of the submodule, when you get to it. If not, then please let me know, and I'll update the version myself. Thanks.

**Comment by avatar-lavventura** [comment]
@maxfrei750 sorry for keep asking further questions, hoping it might help.

On `Threads` background seems gray.

<img width="671" alt="image" src="https://user-images.githubusercontent.com/18537398/104510575-69cb9000-55fc-11eb-90e4-743ad3e42d98.png">

----------

For `Threads` its easier to see them as converstaion (seeing all in one page), for that I am using https://github.com/thunderbird-conversations. But when thats on background is white, I am not sure could be solved on Dracula's end.

<img width="675" alt="image" src="https://user-images.githubusercontent.com/18537398/104510388-296c1200-55fc-11eb-9a3c-04f1a4988ee2.png">

**Comment by maxfrei750** [comment]
> sorry for keep asking further questions, hoping it might help.

No problem, but I think that it would make more sense to discuss these issues here: https://github.com/dracula/thunderbird/issues

Concerning the conversations plugin: Unfortunately, I also think that this cannot be solved on Dracula's end.
