### ISSUE TITLE
New Theme: MailSpring

### ISSUE THREAD

**Issue by devhammed** [dracula/dracula-theme#474]
Hello there, I created Dracula theme for MailSpring and the repo is available at https://github.com/devhammed/mailspring-ui-dracula.

Would close #415

**Comment by zenorocha** [comment]
Hey @devhammed, I'm afraid we already have a Mailspring theme. Have you seen this?

* https://draculatheme.com/mailspring 
* https://github.com/dracula/mailspring

Sorry for keeping that issue open. This was built by @avelino a couple of months ago.

Thanks for the effort and let's combine forces.

**Comment by devhammed** [comment]
> Hey @devhammed, I'm afraid we already have a Mailspring theme. Have you seen this?
> 
> * https://draculatheme.com/mailspring 
> * https://github.com/dracula/mailspring
> 
> Sorry for keeping that issue open. This was built by @avelino a couple of months ago.
> 
> Thanks for the effort and let's combine forces.
> 
> 

Though I didn't see that while looking for it 🙂🙂🙂
