### ISSUE TITLE
New Theme: Linear

### ISSUE THREAD

**Issue by jamieshiers** [dracula/dracula-theme#475]
Good Morning, 

I've create a new theme for [Linear](https://linear.app) Desktop app. 

Repo can be found here: 

[https://github.com/jamieshiers/Dracula-for-Linear](https://github.com/jamieshiers/Dracula-for-Linear)

**Comment by zenorocha** [comment]
Hey @jamieshiers! 

I'm glad to see that you create this theme! I've used Linear myself and loved the app.

Are you interested in transferring your repository to the official organization (https://github.com/dracula)? You'll continue maintaining this project, the only difference is that we can make it more visible and include it on the site (https://draculatheme.com).

I just sent you an invite to join the organization. If you accept, you'll be able to transfer the repo and we can continue with adding to the site.

Thanks for building it!

**Comment by jamieshiers** [comment]
Good Morning @zenorocha!, 

I've accepted your requested and transferred the repository.

**Comment by zenorocha** [comment]
It's live https://draculatheme.com/linear 🎉 🎉 🎉
