### ISSUE TITLE
New Theme?

### ISSUE THREAD

**Issue by gabrielcaussi** [dracula/dracula-theme#477]
Support for a dark Arduino Pro IDE theme. See https://github.com/gabrielcaussi/arduino-pro-ide

**Comment by zenorocha** [comment]
I just sent you an invitation to join the Dracula org. Can you transfer the repository now? Thanks @gabrielcaussi!

**Comment by gabrielcaussi** [comment]
Repository transferred to the dracula repository. Thanks @zenorocha!

**Comment by zenorocha** [comment]
It's live, thanks Gabriel! https://draculatheme.com/arduino-pro-ide 🎉 🎉 🎉
