### ISSUE TITLE
SubEthaEdit

### ISSUE THREAD

**Issue by zenorocha** [dracula/dracula-theme#478]
[SubEthaEdit](https://subethaedit.net/) ([GitHub](https://github.com/subethaedit/SubEthaEdit))

**Comment by bigpick** [comment]
I looked at this, and played around with it for a bit.

The SubEthaEdit [syntax highlighting scope(s)](https://github.com/subethaedit/SubEthaEdit/tree/develop/Documentation/SyntaxScopes) seem(s) pretty limited.

... so you aren't really able to distinguish much between syntax elements, and end up with results that are a bit washed in one color. 

## Examples (all vs' against vs code theme)
### Ruby

<img width="816" alt="Screen Shot 2021-07-15 at 6 14 06 PM" src="https://user-images.githubusercontent.com/9803299/125864615-66bb6b3f-de44-42e2-8ab8-cf5416a868db.png">


vs

<img width="447" alt="Screen Shot 2021-07-15 at 6 11 18 PM" src="https://user-images.githubusercontent.com/9803299/125864376-06295023-2ce8-4ab6-910e-85e7dcab66c9.png">

### Python
<img width="816" alt="Screen Shot 2021-07-15 at 6 13 06 PM" src="https://user-images.githubusercontent.com/9803299/125864592-54ef45e5-2238-49cb-8e7a-0286144c7bc9.png">

vs

<img width="402" alt="Screen Shot 2021-07-15 at 6 13 46 PM" src="https://user-images.githubusercontent.com/9803299/125864599-d5c388f8-35f3-4486-a0fa-f57796a3c538.png">

### Go
<img width="945" alt="Screen Shot 2021-07-15 at 6 19 13 PM" src="https://user-images.githubusercontent.com/9803299/125865070-aa7ac1ca-d65f-4aba-9357-1fc56cdf65eb.png">

vs

<img width="511" alt="Screen Shot 2021-07-15 at 6 19 35 PM" src="https://user-images.githubusercontent.com/9803299/125865073-2594d73b-14e4-42a7-be3b-11ea9c93f373.png">
