### ISSUE TITLE
Dracula for Logseq!

### ISSUE THREAD

**Issue by SlyBouhafs** [dracula/dracula-theme#479]
## Logseq Dracula
Hey, i created another theme for Logseq!
https://github.com/SlyBouhafs/logseq-dracula

Here's a screenshot:
![Screen Shot 2020-12-15 at 18 03 55](https://user-images.githubusercontent.com/1410462/102247432-3ebc2680-3f00-11eb-9fab-df5d74fde647.png)

**Comment by zenorocha** [comment]
@SlyBouhafs that's amazing, thanks for building another great theme! Can you transfer to the Dracula org now so I can create the website page? Thanks!

**Comment by SlyBouhafs** [comment]
@zenorocha The repo transfer is done!

**Comment by zenorocha** [comment]
It's live now! https://draculatheme.com/logseq 🎉 🎉 🎉 

Feel free to share it with your friends and other Logseq users!
