### ISSUE TITLE
webstorm 2020.3 dracula pro theme bug.

### ISSUE THREAD

**Issue by nico281** [dracula/dracula-theme#482]
Hi, How are you? 
Dracula pro on WebStorm 2020.3 is bugged. the font color on all menus are black. I just followed the readme and install the plugin.

Cheers!!
![Capture](https://user-images.githubusercontent.com/15875218/103092684-d099f280-45d6-11eb-8691-80e7491114fc.PNG)

**Comment by benknoble** [comment]
This belongs on [dracula/jetbrains](https://github.com/dracula/jetbrains) run by @WhiteVermouth. I can't transfer it, though.

**Comment by nico281** [comment]
ohh sorry . my bad.

**Comment by zenorocha** [comment]
@nico281 that looks like a conflict with MaterialUI plugin. Once you uninstall it, it will work as expected.
