### ISSUE TITLE
Request Dark Theme (Jar file) for BonitaBPM Studio (Base on Eclipse)

### ISSUE THREAD

**Issue by alishirini** [dracula/dracula-theme#484]
Hi dear,

Have a good New Year ;)

I am a fan of this product and always use this theme in VSCode version.

I request that this product be produced for BonitaBPM Studio (Base on Eclipse) as well.
This studio restricted to install new package from outside but same as this theme (https://guari.github.io/eclipse-ui-theme/) we can download jar file manually and put it into plugins folder, and Worked!

I hope you have the opportunity to do this because my eyes are going blind ..

‌Best Regards,
Ali

**Comment by zenorocha** [comment]
Hey @alishirini, does BonitaBPM Studio support Eclipse themes? If yes, then you could try this out: https://github.com/dracula/eclipse

**Comment by alishirini** [comment]
Hi @zenorocha Thanks for your answer!
I try to use it .

‌Best Regards,
Ali
