### ISSUE TITLE
New Theme: qt5

### ISSUE THREAD

**Issue by TechieAndroid** [dracula/dracula-theme#486]
https://github.com/TechieAndroid/qt5

**Comment by zenorocha** [comment]
This is awesome @TechieAndroid, thanks for another theme!

We already have this https://github.com/dracula/qtcreator repository, is that the same thing or is it something else? I'm not familiar with qt.io, so please help me out @ergenekonyigi.

**Comment by TechieAndroid** [comment]
I believe Qt Creator is an IDE.

What I made is completely different. My theme is for applications that use Qt as the default theme engine.

**Comment by zenorocha** [comment]
Got it! You can go ahead and transfer now

**Comment by TechieAndroid** [comment]
Done! Thanks.

**Comment by zenorocha** [comment]
We're live! https://draculatheme.com/qt5 🧛 🧛 🧛

**Comment by TechieAndroid** [comment]
Thank you so much!
