### ISSUE TITLE
New Theme: bashtop

### ISSUE THREAD

**Issue by TechieAndroid** [dracula/dracula-theme#487]
https://github.com/TechieAndroid/bashtop

**Comment by TechieAndroid** [comment]
Do you need anything else from me or can you merge my two themes?

**Comment by zenorocha** [comment]
Hey @TechieAndroid, thanks for building this theme, I love it! 🤩 

I just sent you an invitation to join the Dracula org, once you accept it, can you transfer the repository? 

Also, do you mind renaming `bashtop.png` to `screenshot.png`? We need this exact filename in order for the site to pick it up.

**Comment by TechieAndroid** [comment]
I renamed the file as you asked, and transferred it to dracula.

**Comment by zenorocha** [comment]
It's live! https://draculatheme.com/bashtop 🎉 🎉 🎉 

Feel free to share it with your friends and other Bashtop users!
