### ISSUE TITLE
Dracula GRUB Theme.

### ISSUE THREAD

**Issue by pspiagicw** [dracula/dracula-theme#488]
## GRUB Theme
It would be so cool to have a Dracula GRUB Theme.I was thinking some thing like pop-os GRUB theme but instead of pop-logo we could have Dracula Logo.

**Comment by Trollwut** [comment]
why closed?

**Comment by zenorocha** [comment]
We are discussing via this issue now: https://github.com/dracula/dracula-theme/issues/490
