### ISSUE TITLE
Dracula Plymouth Theme

### ISSUE THREAD

**Issue by pspiagicw** [dracula/dracula-theme#489]
## Dracula Plymouth Theme.
It would be also cool to have a Dracula Plymouth Theme.Please consider.

**Comment by pspiagicw** [comment]
I designed a Plymouth Theme.The link is here https://github.com/pspiagicw/dracula-plymouth.It looks okay but could be improved over time.

**Comment by pspiagicw** [comment]
I cannot test the boot animation but can confirm shutdown animation.
There is a bug in plymouth https://bbs.archlinux.org/viewtopic.php?id=186902 
This prevents me from seeing the boot animation but the shutdown animation is visible.
You can test it with other versions.But I will later test it in VM with older versions.

**Comment by pspiagicw** [comment]
I tested the theme on Ubuntu 20.04 and it works perfectly.

**Comment by luxonauta** [comment]
🧟 It's alive: https://draculatheme.com/plymouth
