### ISSUE TITLE
Dracula GRUB Theme

### ISSUE THREAD

**Issue by pspiagicw** [dracula/dracula-theme#490]
[GRUB] Dracula
Dracula theme for GRUB.I know there is another one but it did not fit my setup.So I created a original one.
The link https://github.com/pspiagicw/dracula-grub

**Comment by zenorocha** [comment]
Hey @pspiagicw, thanks for building it! Would you mind adding a screenshot? We will need that to feature it on the site ;)

About the other theme, I believe you might be referring to: https://github.com/zshzero/dracula-grub2

@zshzero are you interested in merging efforts?

**Comment by pspiagicw** [comment]
I added in the screenshot.Sorry for the delay

**Comment by zenorocha** [comment]
Great! You can now transfer the repository to the Dracula org ;)

**Comment by zshzero** [comment]
@zenorocha Yes

**Comment by zenorocha** [comment]
@pspiagicw friendly ping ;)

**Comment by pspiagicw** [comment]
Ping recieved :)

**Comment by pspiagicw** [comment]
Sorry for the late reply , I missed the point that I have to transfer the repository .I thought you being the maintainer would transfer.I never noticed that I was supposed to transfer.Sorry again! I can imagine what you must of thought.Sorry again.I will transfer it today itself, I am a little new to GitHub can you provide some instruction on how to do it.
If in any way you got offended please , forgive me.

**Comment by pspiagicw** [comment]
I transfered the repository.Sorry for the misunderstanding again.I think you can close the repository.

**Comment by zenorocha** [comment]
No problem at all @pspiagicw, that's totally fine, it's all good 😄 

I just wanted to let you know that your theme is now live! 🎉 🎉 🎉 

https://draculatheme.com/grub 

Thanks for creating it!
