### ISSUE TITLE
Qtile Theme

### ISSUE THREAD

**Issue by ALipAkrohk** [dracula/dracula-theme#492]
This is my configuration in QtileWM. I got most of the colors inspired by Dracula. I hope it gets better with your help.
https://github.com/Pakrohk-DotFiles/PkTile

**Comment by luxonauta** [comment]
This is already fantastic! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/Pakrohk-DotFiles/PkTile)
- [New repository.](https://github.com/dracula/qtile)

Thanks for building this! 🎉

**Comment by ALipAkrohk** [comment]
You didn't answer this issue for a long time, I thought it was forgotten, yes, I will provide updates for the config soon.
Hoping for freedom for everyone around the world.
