### ISSUE TITLE
A little question about colors 

### ISSUE THREAD

**Issue by Dhyfer1** [dracula/dracula-theme#493]
Hi @zenorocha 

I want to create the Dracula theme for an app and I have a question. 

I know I have to use this [color palette](https://github.com/dracula/dracula-theme#color-palette) but... can I use also some colors from your site draculatheme.com?

That's all. I hope your answer.

**Comment by zenorocha** [comment]
Yeah, that's totally fine @Dhyfer1 ;)

**Comment by Dhyfer1** [comment]
@zenorocha Okay, thank you very much! 👍
