### ISSUE TITLE
Theme Dracula for Ditto.

### ISSUE THREAD

**Issue by Dhyfer1** [dracula/dracula-theme#494]
## New Theme for Ditto

Hi @zenorocha 

I am not a developer or programmer, but I created a theme based on the Dracula color palette for the Ditto clipboard manager, is a very popular and very useful clipboard manager. I also created a new [repository](https://github.com/Dhyfer1/Dracula-for-Ditto) based on the template you left as a guide, but I have not put the instructions in the repository since the instructions must be found at dracula.com/Ditto if my theme is approved.

But the instructions are ready, only that I just don't know where to put them.

That's all. I await your response. :slightly_smiling_face:
Thanks in advanced.

**Comment by zenorocha** [comment]
That's awesome @Dhyfer1! I just sent you an invite to join the organization.

Once you accept it, you'll be able to transfer the repo and I'll take care of adding it to the site.

Thanks for building this! 🎉

**Comment by Dhyfer1** [comment]
Oh. @zenorocha Thank you very much! 😀
I already accepted your invitation and transferred the repository, I hope I did it right.

I transferred the repository to the dracula organization, I hope it's ok because I didn't know whether to write it as "dracula" or "Dracula". As you can see in the [image](https://imgur.com/a/VY4rLLT) I put dracula in its respective field, and after that appears what you can see in the second image, there I chose Ditto and finally appears what you see in the third image.

I hope I transferred it correctly. Let me know if there is anything that has been left pending.
Thanks.

**Comment by zenorocha** [comment]
All good @Dhyfer1! https://draculatheme.com/ditto ;)

**Comment by Dhyfer1** [comment]
> All good @Dhyfer1! https://draculatheme.com/ditto ;)

Hi again @zenorocha 

I am writing to you for 2 reasons:

1.  First of all I want to thank you because my theme is listed on draculatheme.com as well as in the dracula-theme repository on Github. Again, thank you very much. 😊😀
2.  Before my theme was approved and uploaded, I could edit the INSTALL.md file but now I can't edit it and when the cursor hovers over the edit icon I get this message: "You must be on a branch to make or propose changes to this file". The reason why the INSTALL.md file needs to be edited is that the part where Ctrl+/ appears is wrong, since Ditto is activated by default using the hotkey ``(Ctrl+`)`` or the Ctrl key together with the punctuation mark ``(`)``.
So, please, edit the INSTALL.md file and replace this: 
```
`Ctrl + /`
``` 
with this: 
```
<kbd>Ctrl</kbd>+<kbd>`</kbd>
```
After editing that part in the md file, it will look like this: <kbd>Ctrl</kbd>+<kbd>`</kbd>

3. When you finish editing the md file, it is also necessary to correct the hotkey in draculatheme.com/ditto and also correct the content inside the squares that you see in the next image. Above you can see the part of "Activate theme" in the INSTALL.md file and below its equivalent in <url>https://draculatheme.com/ditto</url>
![msedge_bEs7UtLOmR](https://user-images.githubusercontent.com/50301201/105647959-eec56d80-5e76-11eb-99d7-cd17b7d6cba3.png)

That's all, and thank you for your attention. :)

**Comment by Dhyfer1** [comment]
**UPDATE**

I have edited and updated the INSTALL.md file with the change I described in my previous message, but you still need to make the respective changes in <url>https://draculatheme.com/ditto </url> how I said previous in point 3, please. 🙏

**Comment by zenorocha** [comment]
I just regenerated the site: https://draculatheme.com/ditto

For some weird reason, I can still see that `b`. I have absolutely no idea why this is happening :(

**Comment by Dhyfer1** [comment]
> I just regenerated the site: https://draculatheme.com/ditto
> 
> For some weird reason, I can still see that `b`. I have absolutely no idea why this is happening :(

Hi @zenorocha 
I looked at the site again and you're right, it looks like that b doesn't want to leave. 😅 and the hotkey part is correct. 

Ok, then you have to modify the site again, sorry, but it will be very easy for you with the changes I am going to tell you, I believe that with these changes you will be able to see it correctly on the site:

- In point 1 of the site it only changes from this: `b i.e. hold down Ctrl and press the back-quote (tilde ~) key` to this: `i.e. hold down Ctrl and press the back-quote (tilde ~) key`
- In the same point 1, change this: `menu icon b/` to this: `three dots`

Easy, right? So that in the end it can look like this: 
**Open Ditto by clicking its icon in the system tray or by pressing its Hot Key which defaults to Ctrl+` i.e. hold down Ctrl and press the back-quote (tilde ~) key, and go to its settings (click on the three dots of the lower right corner and click on Options.)**

Now, about the Ditto INSTALL.md file, have you seen the differences between [this one](https://github.com/dracula/ditto/blob/master/INSTALL.md) and [this one](https://github.com/dracula/ditto/blob/e76aefb151d289fcf01262597c092e6d9195b288/INSTALL.md)? The md file in the first link I edited it without problem but I can't edit the md file in the second link to be the same as the first link because I don't have permissions to edit it, so if it's no problem I would like you to edit it to look like the one I edited, just look at the instructions in point 2 that I left you two messages up. ⬆

That´s all. I look forward to your answer :)
