### ISSUE TITLE
Dracula theme for Xournal++

### ISSUE THREAD

**Issue by tim-clifford** [dracula/dracula-theme#495]
It's an Xournal++ toolbar with all the dracula colors so notes can look good :) [here is the link](https://github.com/tim-clifford/dracula-xournalpp)

**Comment by zenorocha** [comment]
That's amazing! The screenshot looks great too.

I just sent you an invite to join the organization.
Once you accept it, you'll be able to transfer the repo and I'll take care of adding it to the site.

Thanks for building this! 🎉

**Comment by tim-clifford** [comment]
Awesome! I have accepted the invite, transferred the repo, and renamed it to dracula/xournalpp. 

Let me know if there's anything else I can do 🚀

**Comment by zenorocha** [comment]
https://draculatheme.com/xournalpp 🎉 🎉 🎉
