### ISSUE TITLE
Dracula Theme for LibreOffice

### ISSUE THREAD

**Issue by tim-clifford** [dracula/dracula-theme#499]
[A color palette for LibreOffice to make documents look good](https://github.com/tim-clifford/dracula-libreoffice). Let me know if you want me to do screenshot.png differently, I thought it would be nice to show a composite of the different LibreOffice programs rather than a screenshot of just one of them.

I seem to have made it a mission to make everything I use dracula themed, so I'll be opening a few more issues when I get around to organising everything into their own repos :)

**Comment by zenorocha** [comment]
Woooow, that's amazing. Keep them coming! Our mission is the same now :P

About the screenshot.png, what about adding some Dracula related text instead? You can get some inspiration from this [Wikipedia article](https://en.wikipedia.org/wiki/Dracula).

**Comment by tim-clifford** [comment]
Good idea, I'll get on that when I find some more spare time :P

**Comment by tim-clifford** [comment]
@zenorocha thoughts on the new screenshot?

**Comment by zenorocha** [comment]
That looks amazing 🤩 🤩 🤩  Let's do it! Can you transfer?

**Comment by zenorocha** [comment]
This is really exciting, I never thought we would have a LibreOffice theme!

https://draculatheme.com/libreoffice 🎉 🎉 🎉

**Comment by tim-clifford** [comment]
What can I say, thanks to you my eyes now bleed looking at any other colors :P

**Comment by zenorocha** [comment]
lol

![giphy](https://user-images.githubusercontent.com/398893/107451438-1e71a800-6afc-11eb-8a7c-540e37d9af47.gif)

**Comment by ykhurshid** [comment]
Sorry but this is not working for me at all. I copied the `dracula.soc` file to the correct directory but I do not see it listed in the application colors menu.

**Comment by sk8rnetwork** [comment]
> Sorry but this is not working for me at all. I copied the `dracula.soc` file to the correct directory but I do not see it listed in the application colors menu.

did you find any solution? it ain't working for me either.

**Comment by tim-clifford** [comment]
see [this issue](https://github.com/dracula/libreoffice/issues/3)
