### ISSUE TITLE
Dracula Theme for Nova

### ISSUE THREAD

**Issue by bdielman** [dracula/dracula-theme#502]
With the help from the folks at Panic, there's a [theme for the new Nova editor](https://github.com/bdielman/nova) ready to be added to the Dracula org.

**Comment by zenorocha** [comment]
Hey @bdielman, quick question - how is this different from https://dev.panic.com/panic/dracula-theme?

In any case, I just sent you an invitation to join the organization. Once you accept it, you'll be able to transfer the repo ;)

**Comment by bdielman** [comment]
@zenorocha - That repo is no longer maintained. I contacted Kyle Rimkus from Panic to migrate the repo to Github so we could get it included in the Dracula org. :)

**Comment by bdielman** [comment]
@zenorocha - the repo has been transferred and I've re-published the theme to Nova's extension library as Dracula Official. Kyle is going to do some work on Panic's end to help people using the old theme migrate to the new one.

**Comment by bdielman** [comment]
@zenorocha - Let me know if there's anything else I need to do to wrap up the transfer.

**Comment by zenorocha** [comment]
It's live now, thanks for your patience @bdielman!

Feel free to share it online https://draculatheme.com/nova :)

**Comment by bdielman** [comment]
Thanks, @zenorocha!

**Comment by BryanSchuetz** [comment]
Is there any chance that we'll see the light variant of the theme in this Nova version?
