### ISSUE TITLE
Dracula Vivado Theme

### ISSUE THREAD

**Issue by ALK222** [dracula/dracula-theme#504]
## [Dracula Vivado theme](https://github.com/ALK222/Vivado)
Dracula theme for the hardware development tool [Vivado](https://www.xilinx.com/products/design-tools/vivado.html). Although the tool only offers support for changing the color of the code editor, the logs and schemes.
If there is anything to change in the screenshot, feel free to say it!

https://github.com/ALK222/Vivado

**Comment by zenorocha** [comment]
That looks great, I like the screenshot!

You should have received an invitation to join the Dracula org now. Once you accept it, you can transfer the repository and I'll add a page for the website ;)

**Comment by ALK222** [comment]
Already transferred!

**Comment by zenorocha** [comment]
It's live now! https://draculatheme.com/vivado

Thanks @ALK222!
