### ISSUE TITLE
Dracula theme for TTY

### ISSUE THREAD

**Issue by tim-clifford** [dracula/dracula-theme#505]
Redefines the 16 ANSI colors in a TTY to dracula. I have absolutely no idea what to put as the website hahaha. [Link](https://github.com/tim-clifford/dracula-tty)

**Comment by zenorocha** [comment]
Looks awesome! I love it  🎉 🎉 🎉 

Would you mind transferring it?

**Comment by tim-clifford** [comment]
One day I'll manage to submit a theme without needing one of your "Standardize
repository" commits... anyway thanks for adding it :tada:

**Comment by zenorocha** [comment]
Hehe that was a super tiny one ;)

**Comment by zenorocha** [comment]
Aaaand we're live: https://draculatheme.com/tty :)
