### ISSUE TITLE
Dracula theme for EverythingToolbar

### ISSUE THREAD

**Issue by Dhyfer1** [dracula/dracula-theme#510]
## New Theme for EverythingToolbar

Hi @zenorocha 👋

I have created a Dracula theme for the [EverythingToolbar](https://github.com/stnkl/EverythingToolbar) launcher and the repository of the new theme you can see it [here](https://github.com/Dhyfer1/Dracula-for-EverythingToolbar). 

By the way, I had to reopen my issue #494 and I need you to see the last messages I left you after you closed it, it is very important for me.

That's all. I await your response. 🙂
Thanks in advanced.

**Comment by zenorocha** [comment]
@Dhyfer1 that looks great! Would you mind transferring the repo? Cheers!

P.S.: I'll take a look at that other issue.

**Comment by Dhyfer1** [comment]
> @Dhyfer1 that looks great! Would you mind transferring the repo? Cheers!

@zenorocha Done,! my repository has been transferred. Let me know if it has been successfully transferred. :)
> P.S.: I'll take a look at that other issue.

Thanks, it is important that you make some changes that I mentioned there.

By the way, when I transfer a new repository and I get to the list you see in the example image, does the repository create the entry in the list or do you create the entry? Because when I created my repository last week and wanted to transfer it and got to the list you saw in the image, EverythingToolbar did not appear in the list, until now.

That's all, good day. 👍

![List](https://i.imgur.com/VpSMJ0v.png)

**Comment by zenorocha** [comment]
It's live https://draculatheme.com/vivado 🎉 🎉 🎉 

Feel free to share it online :)

**Comment by Dhyfer1** [comment]
> It's live https://draculatheme.com/vivado 🎉 🎉 🎉

@zenorocha LOL 😄 I think you were wrong. My theme was for EverythingToolbar, I am not the owner of the Vivado theme but I already saw my theme on https://draculatheme.com/everythingtoolbar and I am happy, thank you very much. 😀

**Comment by zenorocha** [comment]
Oops, wrong URL. https://draculatheme.com/everythingtoolbar

About transferring repositories - the teams are not created automatically. I manually create each one before transferring new repos.
