### ISSUE TITLE
Dracula theme for Inkscape

### ISSUE THREAD

**Issue by Dpbm** [dracula/dracula-theme#513]
Dracula theme for inkscape, based on the dracula theme made for GTK. [link for repository](https://github.com/Dpbm/dracula-inkscape)

**Comment by zenorocha** [comment]
Hey @Dpbm, that's awesome! Thanks for building this.

I just sent you an invitation to join the Dracula org. Once you accept it, you'll be able to transfer the repository. I'll handle the addition to the site after you do that. Sounds good?

**Comment by Dpbm** [comment]
Oh, this is really awesome, thank you very much and sorry for the long time to reply.

**Comment by zenorocha** [comment]
Here it is: https://draculatheme.com/inkscape 🎉 🎉 🎉
