### ISSUE TITLE
Dracula Theme for Dunst

### ISSUE THREAD

**Issue by tim-clifford** [dracula/dracula-theme#517]
[Dracula for Dunst](https://github.com/tim-clifford/dracula-dunst). The screenshot is fairly low quality, but as dunst is a notification daemon the available area to screenshot is fairly small :(

**Comment by zenorocha** [comment]
Sweet! Let's get this transferred?

**Comment by tim-clifford** [comment]
It's done :tada:

**Comment by zenorocha** [comment]
100% fine 🎉 🎉 🎉

**Comment by tim-clifford** [comment]
Finallyyyyyyy :tada: :tada: :tada:

**Comment by zenorocha** [comment]
You're the best bro, thanks for adding all these new themes ;)

**Comment by tim-clifford** [comment]
Haha you're the mastermind, all I have to do is copy the hex codes :P thanks for making such a great colorscheme!

**Comment by zenorocha** [comment]
You're too kind :)

Here it is https://draculatheme.com/dunst 🎉 🎉 🎉
