### ISSUE TITLE
Dracula Theme for Spotify TUI 

### ISSUE THREAD

**Issue by juanscr** [dracula/dracula-theme#519]
[Dracula theme for Spotify TUI](https://github.com/juanscr/dracula-spotify-tui). Feel free to suggest any changes.

**Comment by zenorocha** [comment]
That's awesome @juanscr! I had no idea you could have Spotify in your terminal like that :O

I just sent you an invite to join the organization.

Once you accept it, you'll be able to transfer the repo and I'll take care of adding it to the site.

Thanks for building this! 🎉

**Comment by juanscr** [comment]
Done! Yeah, I discovered it recently and have used it since, as it is very lightweight :)

**Comment by zenorocha** [comment]
And we're live! https://draculatheme.com/spotify-tui

Thanks @juanscr!
