### ISSUE TITLE
Dracula theme for ncspot

### ISSUE THREAD

**Issue by dbasinge** [dracula/dracula-theme#520]
https://github.com/dbasinge/ncspot

**Comment by zenorocha** [comment]
Hey @dbasinge! 

I'm glad to see that you create this theme! Are you interested in transferring your repository to the official organization (https://github.com/dracula)? You'll continue maintaining this project, the only difference is that we can make it more visible and include it on the site (https://draculatheme.com).

I just sent you an invite to join the organization. If you accept, you'll be able to transfer the repo and we can continue with adding to the site.

Thanks for building it!

**Comment by zenorocha** [comment]
https://draculatheme.com/ncspot 🎉 🎉 🎉
