### ISSUE TITLE
Add color theme for sc-im (terminal based spreadsheet program)

### ISSUE THREAD

**Issue by poetaman** [dracula/dracula-theme#522]
## New Theme?

Please add color-theme for sc-im (terminal-based spreadsheet program): https://github.com/andmarti1424/sc-im

**Comment by Darkstarinternet** [comment]
Yes please, I would like this too!

**Comment by reportaman** [comment]
@zenorocha @Darkstarinternet  @lperero92 Actually I already contributed a theme on sc-im's GitHub: https://github.com/andmarti1424/sc-im/blob/main/themes/dracula.sc

**Comment by luxonauta** [comment]
How cool, @poetaman! 🚀

✅ Please create a repository following this template and post instructions so you can be listed as a contributor!
