### ISSUE TITLE
Dracula theme for Unigram

### ISSUE THREAD

**Issue by weeebdev** [dracula/dracula-theme#523]
Dracula theme for [Unigram](https://github.com/UnigramDev/Unigram) (Telegram client)
https://github.com/weeebdev/unigram

Colors are ported from: https://github.com/dracula/telegram

P.S. There are may be issues with some colors, because I couldn't find documentation about each property, so the properties which I don't know left with `#FF5555`

**Comment by zenorocha** [comment]
Great! I just sent you an invite to join the organization.

Once you accept it, you'll be able to transfer the repo and I'll take care of adding it to the site.

Thanks for building this! 🎉

**Comment by weeebdev** [comment]
@zenorocha done!

**Comment by weeebdev** [comment]
I am sorry, but how do I turn off email notifications about repo transfers? I am afraid of changing the settings of your organisation, so I decided to ask you directly

**Comment by zenorocha** [comment]
It's live! 🎉 🎉 🎉 

https://draculatheme.com/unigram

Thanks @weeebdev, you should stop receiving notifications now. :)
