### ISSUE TITLE
Visual Spigot Theme

### ISSUE THREAD

**Issue by kacperleague9** [dracula/dracula-theme#525]
Hello, I created a dracula theme for visual spigot program.

https://github.com/kacperleague9/template

**Comment by avelino** [comment]
Type **how to** do the installation into the **INSTALL** file: https://github.com/kacperleague9/visualspigot-dracula/blob/master/INSTALL.md

I couldn't identify the theme file (code) in the repository, was it uploaded to the repository?

**Comment by kacperleague9** [comment]
Done

**Comment by zenorocha** [comment]
Awesome job @kacperleague9 ! I just sent you an invite to join the organization.

Once you accept it, you'll be able to transfer the repo and I'll take care of adding it to the site.

Thanks for building this! 🎉

And thanks @avelino for reviewing :DDD

**Comment by kacperleague9** [comment]
Hi, thanks for inviting me.
I don't know how to transfer this repo.

**Comment by zenorocha** [comment]
@kacperleague9 you can follow these instructions to transfer: https://docs.github.com/en/github/administering-a-repository/transferring-a-repository#transferring-a-repository-owned-by-your-user-account

**Comment by kacperleague9** [comment]
Done :)

**Comment by zenorocha** [comment]
It's live! https://draculatheme.com/visual-spigot

Thanks @kacperleague9 :DDD
