### ISSUE TITLE
Dracula Theme for Abricotine (Markdown editor)

### ISSUE THREAD

**Issue by calderds** [dracula/dracula-theme#527]
New theme: https://github.com/calderds/dracula_abricotine

**Comment by zenorocha** [comment]
Nice! I love Markdown, thanks for building this 💜 

I just sent you an invite to join the organization.

Once you accept it, you'll be able to transfer the repo and I'll take care of adding it to the site.

Thanks for building this! 🎉

**Comment by calderds** [comment]
I accepted the offer and created a new repo called abricotine, importing from my repo. Hope this works!

**Comment by zenorocha** [comment]
Thanks @calderds! We're live now!

https://draculatheme.com/abricotine 🎉 🎉 🎉
