### ISSUE TITLE
Dracula Theme for Sumatra PDF

### ISSUE THREAD

**Issue by TheForgottened** [dracula/dracula-theme#529]
https://github.com/TheForgottened/dracula-sumatra-pdf

![preview](https://raw.githubusercontent.com/TheForgottened/sumatra-pdf/master/screenshot.png)

The theme ain't much since there's only a few options you can edit. Hope you like it 🖤

**Comment by zenorocha** [comment]
That's really cool @TheForgottened!

I just sent you an invite to join the organization.

Once you accept it, you'll be able to transfer the repo and I'll take care of adding it to the site.

Thanks for building this! 🎉

**Comment by TheForgottened** [comment]
Hi! I just transfered the repo, I'll wait for the link to modify the `README.md` accordingly.

Thanks for inviting me to the organization :)

**Comment by zenorocha** [comment]
We're live now https://draculatheme.com/sumatra-pdf

Thanks @TheForgottened 🎉 🎉 🎉
