### ISSUE TITLE
Missing dropdown arrow in Chrome Devtools

### ISSUE THREAD

**Issue by ivandotv** [dracula/dracula-theme#53]
Dropdown arrow which reveals more panels is missing.
![dropdown_arrow_2014-03-03_2010](https://f.cloud.github.com/assets/390700/2313327/bcb6b330-a307-11e3-992f-6741f56f88a0.png)

**Comment by griiettner** [comment]
I believe you should add somewhere this explanation, because I was crazy here looking for the Chrome theme... I used it in the past and now I don't see it anymore...
