### ISSUE TITLE
Black highlighting on text outside of window.

### ISSUE THREAD

**Issue by JohnClient** [dracula/dracula-theme#533]
I am using the dracula colorscheme on vim on ubuntu. When I load an existing file any text that doesn't initially fit into the window will have a strange black highlight on any space without a character. I only have one colorscheme enabled and it definitely is an issue with this colorscheme. It is annoying as opposed to unusuable but would really appreciate a fix.
I've attached a screenshot of what this looks like.
![draculacsissue ](https://user-images.githubusercontent.com/80011800/109886364-d9aedc00-7c77-11eb-957b-343ad34cf71a.png)

**Comment by avelino** [comment]
This issue should be opened in the vim repository
https://github.com/dracula/vim
