### ISSUE TITLE
Dracula for bemenu

### ISSUE THREAD

**Issue by ns-ian** [dracula/dracula-theme#536]
Dracula color configuration for bemenu, an application launcher similar to dmenu.

https://github.com/ns-ian/bemenu-dracula

**Comment by zenorocha** [comment]
Looks good @ns-ian!

I just sent you an invite to join the organization.

Once you accept it, you'll be able to transfer the repo and I'll take care of adding it to the site.

Thanks for building this! 🎉

**Comment by ns-ian** [comment]
Thanks @zenorocha, I've accepted the invite & transferred the repo.

**Comment by zenorocha** [comment]
Thanks @ns-ian, the page has been created and it's live now!

https://draculatheme.com/bemenu
