### ISSUE TITLE
Dracula Theme for LTSpice

### ISSUE THREAD

**Issue by tim-clifford** [dracula/dracula-theme#537]
[This is getting out of hand.](https://github.com/tim-clifford/dracula-ltspice)

**Comment by zenorocha** [comment]
🤣 🤣 🤣  that's amazing 🎉 🎉 🎉

**Comment by tim-clifford** [comment]
transferred :rocket:

**Comment by zenorocha** [comment]
https://draculatheme.com/ltspice 🚀 🚀 🚀
