### ISSUE TITLE
Dracula theme for Pandoc

### ISSUE THREAD

**Issue by tim-clifford** [dracula/dracula-theme#539]
[I think I might be developing an addiction](https://github.com/tim-clifford/dracula-pandoc) :eyes:

**Comment by tim-clifford** [comment]
I've tried to stick to the spec as closely as possible but the pandoc highlighting specification is a bit limiting :(

**Comment by zenorocha** [comment]
Woooooooooow! Last year I used Pandoc for the first time to build my book and I really wished there was a Dracula theme for it. Now it's a reality.  If you keep it that way we'll hit 200 themes real soon. 🤯

**Comment by tim-clifford** [comment]
wowww 200 themes that would be awesome :open_mouth: I've transferred this one :)

**Comment by zenorocha** [comment]
171 themes! 29 to go 😆 

https://draculatheme.com/pandoc 💥 💥 💥
