### ISSUE TITLE
[dracula/duckduckgo] Side wiki font is unreadable

### ISSUE THREAD

**Issue by avatar-lavventura** [dracula/dracula-theme#540]
There is a bug on `dracula/duckduckgo` theme. As you can see on the picture, right-side wiki's font color is black and it is unreadable.

Opened issue since last year: https://github.com/dracula/duckduckgo/issues/1#issue-545308816

Example view:

<img width="1217" alt="image" src="https://user-images.githubusercontent.com/18537398/110483717-0d1bbb80-80fb-11eb-8f97-9f93e2d0f04a.png">

**Comment by bigpick** [comment]
Looking [into this in the theme's repo issue](https://github.com/dracula/duckduckgo/issues/1).

**Comment by bigpick** [comment]
Resolved.
