### ISSUE TITLE
Dracula Theme for FreeCAD

### ISSUE THREAD

**Issue by tim-clifford** [dracula/dracula-theme#541]
[Link](https://github.com/tim-clifford/dracula-freecad). This one was an absolute pain to make, there are like a million XML variables to change plus a stylesheet! I think I've still missed a few spots because there are just too many :cry: but still I love it :heart_eyes:

**Comment by zenorocha** [comment]
Woooooow, that's amazing @tim-clifford! Let's transfer it :DDD

**Comment by tim-clifford** [comment]
Transferred :tada: I also added the team for it :)

**Comment by zenorocha** [comment]
Ohhh thanks for doing that! https://draculatheme.com/freecad ;)
