### ISSUE TITLE
Changing colour of class in Dracula Official on vsCode

### ISSUE THREAD

**Issue by theb4ku** [dracula/dracula-theme#543]
Hey, can you guys help me to navigate which line I should change in .json file to change white colour to blue? As in the screenshot, the **Program** class is blue but the **Thread** class is white and I would like to change that to also blue.
![image](https://user-images.githubusercontent.com/75274385/111886124-388c8900-89cc-11eb-9493-4f859facc39d.png)

**Comment by benknoble** [comment]
Probably belongs on dracula/visual-studio-code

**Comment by Trollwut** [comment]
Author opened an issue in the mentioned repository here: https://github.com/dracula/visual-studio-code/issues/171

Going to close this issue, as it is being worked on elsewhere. :)
