### ISSUE TITLE
Dracula Pro not supported in the latest version of PyCharm Community

### ISSUE THREAD

**Issue by mrpbennett** [dracula/dracula-theme#547]
When trying to install via zip I get the following error:

```
Plugin 'Dracula Pro' (version '1.2.0') is not compatible with the current version of the IDE, because it requires build 202.* or older but the current build is PC-203.7717.65
```

My Pycharm Community build is :

```
PyCharm 2020.3.4 (Community Edition)
Build #PC-203.7717.65, built on March 16, 2021
Runtime version: 11.0.10+8-b1145.96 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.2.3
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Non-Bundled Plugins: com.markskelton.one-dark-theme, me.lensvol.blackconnect
```

**Comment by benknoble** [comment]
Probably should go to the pycharm repo? @zenorocha

**Comment by lukaszklis** [comment]
@mrpbennett please make sure you're using the latest version of the theme. I can confirm 1.3.0 is working just fine with my PyCharm 2020.3.4

**Comment by mrpbennett** [comment]
Ok great thanks. How can I get the upgraded version without paying the $79.99 again ?

**Comment by lukaszklis** [comment]
Once you login to the Gumroad account you should be able to fetch the latest version without having to pay for theme again.

**Comment by mrpbennett** [comment]
Great thanks @lukaszklis after many attempts and trying to remember my email...I have the latest version and all installed ok thanks man

**Comment by lukaszklis** [comment]
You're welcome! Happy coding!

**Comment by zenorocha** [comment]
@benknoble @lukaszklis you guys are the best. Thank you so much ;D
