### ISSUE TITLE
Theme Request for Kdiff3 

### ISSUE THREAD

**Issue by cdalexndr** [dracula/dracula-theme#548]
## New Theme?

`~/.kdiff3rc` file for color theme, example:

```
FgColor=248,248,242
BgColor=40,42,54
ColorA=139,233,253
ColorB=80,250,123
ColorC=189,147,249
ColorForConflict=255,85,85
CurrentRangeBgColor=68,71,90
CurrentRangeDiffBgColor=98,114,164
DiffBgColor=98,114,164
ManualAlignmentRangeColor=255,184,108
MidAgeFileColor=255,184,108
MissingFileColor=40,42,54
NewestFileColor=80,250,123
OldestFileColor=255,85,85
```

**Comment by zenorocha** [comment]
Hey @cdalexndr! Thanks for putting together this Kdiff3.

Would you mind creating a repository from https://github.com/dracula/template? You will need to add an image (screenshot.png) and setup instructions (INSTALL.md). Once that's done we can add it to the official org and website.

Thanks!

**Comment by cdalexndr** [comment]
@zenorocha done: https://github.com/cdalexndr/template
The `screenshot.png` is shown differently in github, but cloning on local pc shows it fine.

**Comment by zenorocha** [comment]
Great @cdalexndr! I just sent you an invitation to join the organization.

Once you accept, you need to transfer the repository, so I can add it to the site.

**Comment by cdalexndr** [comment]
> Once you accept, you need to transfer the repository, so I can add it to the site.

How do I do this?

**Comment by cdalexndr** [comment]
Tried to transfer ownership to `dracula` organization and got error: `dracula/template already exists`

**Comment by zenorocha** [comment]
Hey @cdalexndr, can you please navigate to https://github.com/cdalexndr/kdiff3 and then Settings. Once you're there you can disable the "Template" option and then try to transfer again. It's this option over here:


<img width="1240" alt="Screen Shot 2021-04-06 at 10 19 27 PM" src="https://user-images.githubusercontent.com/398893/113814295-45c4aa00-9726-11eb-9c08-323fb36068c3.png">

**Comment by cdalexndr** [comment]
Disabled `Template repository`, tried to transfer ownership to `dracula` organization: `dracula already has a repository in the dracula/template network `

**Comment by zenorocha** [comment]
No problem, let's try another route. I cloned the repository and pushed it to the dracula org: https://github.com/dracula/kdiff3

Feel free to delete this repo now: https://github.com/cdalexndr/kdiff3

I also made a few changes to standardize the repo: https://github.com/dracula/kdiff3/commit/e59198dbea6b2955ce3a9b0cfbbe52b3856ce5c5

**Comment by zenorocha** [comment]
It's live now! https://draculatheme.com/kdiff3

**Comment by zenorocha** [comment]
Thanks @cdalexndr for doing this! 🎉 🎉 🎉
