### ISSUE TITLE
Add dracula theme for ghostwriter

### ISSUE THREAD

**Issue by totoroot** [dracula/dracula-theme#550]
I noticed that there was no theme for the Markdown editor [ghostwriter](https://wereturtle.github.io/ghostwriter/), so I went ahead and created one myself at [dracula-ghostwriter](https://github.com/totoroot/dracula-ghostwriter).

**Comment by zenorocha** [comment]
That's great @totoroot! 

I'm glad to see that you created this theme! Are you interested in transferring your repository to the official organization (https://github.com/dracula)? You'll continue maintaining this project, the only difference is that we can make it more visible and include it on the site (https://draculatheme.com).

I just sent you an invite to join the organization. If you accept, you'll be able to transfer the repo and we can continue with adding to the site.

Thanks for building it!

**Comment by totoroot** [comment]
Perfect, thank you!

Yes, my intention was to have it incorporated into the Dracula theme ecosystem and to maintain it as a member of the organization.
I have already transferred the ownership to the ghostwriter team inside the Dracula organization and renamed the repository, so all should be set to include it on the homepage.

Please let me know if I can help you any further and whether I should close this issue.

All the Best!

**Comment by zenorocha** [comment]
We're live now: https://draculatheme.com/ghostwriter

Feel free to share this with the ghostwriter community @totoroot ;D

Congrats! 🎉
