### ISSUE TITLE
Shipping Dracula with our IDEs

### ISSUE THREAD

**Issue by abrudz** [dracula/dracula-theme#554]
We are going to include your lovely theme into our IDEs from this coming summer. For that:
* Do you want us to include attribution? If so, let me know what and how.
* Do you want to list this on your website? The links to our IDEs are: [Dyalog APL IDE](https://dyalog.com) and [Dyalog APL Remote IDE (RIDE)](https://github.com/dyalog/ride)
* I've [forked your template](https://github.com/abrudz/dracula) but I'm not sure if the content there is to your liking, considering that it is an unusual situation.

**Comment by zenorocha** [comment]
That's awesome @abrudz! Glad to hear that you decided to ship Dracula natively on Dyalog.

It would be nice if you can include attribution. A link to the draculatheme.com site would be great if that's possible.

About the template, that looks great! I sent you an invitation to join the Dracula org. Once you accept it, you can transfer that repository and I'll be able to add it to the site.

**Comment by abrudz** [comment]
OK, good. I'll hold off on the actual transfer until we release the version that includes the theme. This way, you don't need to keep track of the time; simply add it when I transfer it.

**Comment by zenorocha** [comment]
That would be perfect. Thanks a lot @abrudz!

**Comment by abrudz** [comment]
OK, now at [dracula/dyalog](https://github.com/dracula/dyalog) so you can add it to the site.

**Comment by luxonauta** [comment]
It's 🧟‍♂️ a-live: https://draculatheme.com/dyalog
