### ISSUE TITLE
buy dracula pro not get a email?

### ISSUE THREAD

**Issue by zdmgmail** [dracula/dracula-theme#556]
https://draculatheme.com/pro

I first use paypal pay , get `Your purchase with PayPal failed....` email

then I use credit card pay success, but not get any email? 

After pay success, I give a password(no username), but not auto login or something

Now the money is deducted from the credit card, but  don’t get anything

Is this a normal situation? what should I do?

**Comment by benknoble** [comment]
Probably email @zenorocha and/or Gumroad?

**Comment by zdmgmail** [comment]
> Probably email @zenorocha and/or Gumroad?

What is their email address?

**Comment by avelino** [comment]
> What is their email address?

zeno@draculatheme.com

**Comment by zdmgmail** [comment]
> > What is their email address?
> 
> [zeno@draculatheme.com](mailto:zeno@draculatheme.com)

thanks , I send to him

**Comment by zdmgmail** [comment]
waiting ...

**Comment by zdmgmail** [comment]
@zenorocha I send again,  please reply  quicker.........

**Comment by zdmgmail** [comment]
sorry , seems I write wrong email,  it corrected
