### ISSUE TITLE
Dracula Theme for SolidWorks

### ISSUE THREAD

**Issue by tim-clifford** [dracula/dracula-theme#559]
[Link](https://github.com/tim-clifford/dracula-solidworks). This one... wow. It was very very hard to make work. SolidWorks really doesn't want to be themed...  and I can't make it look quite as good as I want to :(

If you're interested, I wrote a blog post about how I did it [here](https://tim.clifford.lol/blog/dracula-for-solidworks) :)

**Comment by zenorocha** [comment]
Let's get this one transferred too Tim :D

**Comment by tim-clifford** [comment]
It is done :tada: Also, just realized that this is my 10th theme wowwwwww :sunglasses: :sunglasses: :sunglasses:

**Comment by zenorocha** [comment]
Wooooow! 10 themes, that's unbelievable @tim-clifford! 

Congrats man and sorry for taking so long to reply.

https://draculatheme.com/solidworks

**Comment by tim-clifford** [comment]
No problem at all @zenorocha! We all get busy sometimes :)
