### ISSUE TITLE
Dracula Theme for Metaeditor

### ISSUE THREAD

**Issue by AbraaoM** [dracula/dracula-theme#560]
https://github.com/abraaom/dracula-metaeditor

**Comment by zenorocha** [comment]
Hey @AbraaoM! This theme looks great, thanks for creating it!

I just cloned the repository and added it to the Dracula org. I also sent you an invitation to join the org, so you can manage the repo. Feel free to delete the repo on your own user now (https://github.com/abraaom/dracula-metaeditor).

https://draculatheme.com/metaeditor 🎉
