### ISSUE TITLE
Dracula for SwiftUI

### ISSUE THREAD

**Issue by rphlfc** [dracula/dracula-theme#561]
## Dracula for SwiftUI

[Dracula for SwiftUI](https://github.com/rphlfc/Dracula)

## New Theme?

We would love to support all code editors out there, but we need your help to accomplish that. Feel free to create a new theme based on our [color palette](https://github.com/dracula/dracula-theme#color-palette).

## Existing Theme?

Find the appropriate repository on the [Dracula organization](https://github.com/dracula). This is just the umbrella place where we store all themes.

And remember - consider fixing the issue yourself. That's the best way to contribute ;)

**Comment by zenorocha** [comment]
That's super amazing @rphlfc! 

I just sent you an invite to join the organization. If you accept, you'll be able to transfer the repo and we can continue with adding to the site.

Thanks for building it!

**Comment by zenorocha** [comment]
It's finally live, sorry for taking so long @rphlfc, this SwiftUI theme is 🔥 🔥 🔥 

https://draculatheme.com/swiftui
