### ISSUE TITLE
Theme for NANO 

### ISSUE THREAD

**Issue by AlexZigante** [dracula/dracula-theme#562]
## New Theme?

Hii, anyone played with nano?
https://www.nano-editor.org/dist/latest/nano.html#Syntax-Highlighting

**Comment by SpikedPaladin** [comment]
Nano themes can be changed by changing terminal color profile

**XTerm**
![XTerm Gnome Terminal](https://user-images.githubusercontent.com/47825679/115386727-70146e00-a1e2-11eb-8a7e-20d7ed1e02ee.png)

**Dracula**
![Dracula Gnome Terminal](https://user-images.githubusercontent.com/47825679/115386771-83273e00-a1e2-11eb-9051-082a00069be9.png)

**Comment by AlexR00T** [comment]
Thanks. Its not exactly a theme for nano. For now solves my problem. But doesnt apply for remote servers when people tty. So if anyone will have time to play around.. however thank you @SpikedPaladin

**Comment by clari7744** [comment]
Nano does support theming, to an extent. It's on a per-file basis, but it's possible. [This project](https://github.com/galenguyer/nano-syntax-highlighting) has a lot of `nanorc` files, could they be adapted/dracula-themeified?
