### ISSUE TITLE
Theme for eM Client

### ISSUE THREAD

**Issue by zenorocha** [dracula/dracula-theme#563]
[Instructions here](https://www.emclient.com/blog/design-your-own-em-client-421)

> A feature request made by @ivanalmasi via email

**Comment by bigpick** [comment]
I'm going to install eM client and work on this today

**Comment by bigpick** [comment]
So far (there is _a lot_ of things to configure!):

![image](https://user-images.githubusercontent.com/9803299/127700633-030cd5c5-c107-417e-8ce3-a89a13d228c5.png)

**Comment by zenorocha** [comment]
This is awesome ;D

Closing in favor of #605
