### ISSUE TITLE
Dracula for zsh-syntax-highlighting

### ISSUE THREAD

**Issue by bigpick** [dracula/dracula-theme#567]
## New Theme -- [zsh-syntax-highlighting](https://github.com/bigpick/zsh-syntax-highlighting)
> Implemented from [the dracula template](https://github.com/dracula/template).

![](https://github.com/bigpick/zsh-syntax-highlighting/raw/master/screenshot.png)

### Implementation

This theme attempts to cover all possible zsh-syntax-highlighting options for the [**main** highlighter](https://github.com/zsh-users/https://draculatheme.com//blob/master/docs/highlighters/main.md). The coloring was implemented/modelled after the [official Dracula color specification](https://spec.draculatheme.com/) as much as logically possible.

As such, the theme is grouped by Dracula spec section; Each section in the spec is 1:1 with a `## <header>` in the theme file. For settings that didn't seem to fall under any of the Dracula spec, they are under the `## No category relevant in spec` section.

Within a section, the options occur in the same order they do on the [main highlighter doc page](https://github.com/zsh-users/https://draculatheme.com//blob/master/docs/highlighters/main.md).

# Notes/Todo

The spec doesn't really line up 1:1 with this sort of work, so I tried to model as close as possible; I would not mind additional eyes inspecting [my choices for the specific settings](https://github.com/bigpick/zsh-syntax-highlighting/blob/master/zsh-syntax-highlighting.sh)/associated spec groupings where possible (or maybe arguments on "ungrouped" ones being grouped into a different category).

**Comment by zenorocha** [comment]
This is great! As a user of zsh-syntax-highlighting myself, I really appreciate the work you've done here ;D

Can you transfer the repo now?

Cheers!

**Comment by bigpick** [comment]
🚀  

[Done](https://github.com/dracula/zsh-syntax-highlighting)! Thanks Zeno.

**Comment by zenorocha** [comment]
https://draculatheme.com/zsh-syntax-highlighting 🎉 🎉 🎉
