### ISSUE TITLE
Dracula theme for Mako

### ISSUE THREAD

**Issue by karl37** [dracula/dracula-theme#568]
https://github.com/karl37/mako

![screenshot](https://user-images.githubusercontent.com/46323937/115861360-60dc2d00-a43b-11eb-9213-6b30a4cff0c4.png)

**Comment by zenorocha** [comment]
This looks cool, congrats @karl37 for building it!

I just sent you an invite to join the organization.

Once you accept it, you'll be able to transfer the repo and I'll take care of adding it to the site.

Thanks for building this! 🎉

**Comment by zenorocha** [comment]
It's finally live, thanks @karl37! 🎉 🎉 🎉 

https://draculatheme.com/mako
