### ISSUE TITLE
Dracula Theme for ImageGlass

### ISSUE THREAD

**Issue by FelkonEx** [dracula/dracula-theme#571]
## Dracula for ImageGlass
[https://github.com/FelkonEx/Dracula-ImageGlass](https://github.com/FelkonEx/Dracula-ImageGlass)
[https://imageglass.org](https://imageglass.org)

## Screenshot
![preview](https://user-images.githubusercontent.com/12007786/116776678-20208b80-aaad-11eb-85ba-b2f04671e3b4.jpg)
(the image shown is the stock image that comes with the program)

**Comment by zenorocha** [comment]
Looks great @FelkonEx! I just sent you an invite to join the organization.

Once you accept it, you'll be able to transfer the repo and I'll take care of adding it to the site.

Thanks for building this! 🎉

**Comment by zenorocha** [comment]
It's live on the site now: https://draculatheme.com/imageglass

Thanks @FelkonEx! The theme looks great!
