### ISSUE TITLE
fzf theme

### ISSUE THREAD

**Issue by caarlos0** [dracula/dracula-theme#573]
Just created a fzf theme, would be happy to transfer it to the org!

https://github.com/caarlos0/dracula-fzf

**Comment by zenorocha** [comment]
Hey @caarlos0, that's awesome man.

All of our themes follow the same template: https://github.com/dracula/template

Can you please update the repo before we start the transfer?

**Comment by caarlos0** [comment]
Sure @zenorocha, done: https://github.com/caarlos0/dracula-fzf

Also tried to send the transfer request, but it seems I need some sort of permission on the dracula org...

**Comment by zenorocha** [comment]
Awesome! You should be able to transfer now @caarlos0

**Comment by caarlos0** [comment]
done!

https://github.com/dracula/fzf

Thanks @zenorocha 🖤

**Comment by zenorocha** [comment]
I had to rename `main` to `master` in order to follow the organization standard and for the website to be able to fetch it correctly, okay?

It's live now, thanks @caarlos0 for building this theme!

 https://draculatheme.com/fzf 🎉

**Comment by caarlos0** [comment]
no problem at all, thanks @zenorocha ! 🚀
