### ISSUE TITLE
New Theme - Qbittorrent

### ISSUE THREAD

**Issue by MahdyMirzade** [dracula/dracula-theme#576]
**App:** [QBittorrent](https://www.qbittorrent.org/)
**Repo:** https://github.com/MahdyMirzade/qbittorrent
**From:** https://github.com/MahdyMirzade/Dotfiles/tree/main/config/qbittorrent
![Screenshot](https://github.com/MahdyMirzade/qbittorrent/raw/master/screenshot.png)

**Comment by zenorocha** [comment]
Great! I just sent you an invite to join the organization.

Once you accept it, you'll be able to transfer the repo and I'll take care of adding it to the site.

Thanks for building this! 🎉

**Comment by MahdyMirzade** [comment]
thank you for your answer, great just transfered it to organization:
https://github.com/dracula/qbittorrent

**Comment by zenorocha** [comment]
Here you go! Thanks @MahdyMirzade :D

https://draculatheme.com/qbittorrent

**Comment by MahdyMirzade** [comment]
Thank you :D
