### ISSUE TITLE
Write access to Dracula Nova theme

### ISSUE THREAD

**Issue by bdielman** [dracula/dracula-theme#577]
@zenorocha - When permissions for the Dracula theme were changed last month, my read-only permissions also applied to the [Nova theme](https://github.com/dracula/nova) that I contribute to. I had some PR rules in place so when I push to the repo, it's rejected.

**Comment by zenorocha** [comment]
Sorry about that @bdielman, it should be fixed now ;)

**Comment by bdielman** [comment]
@zenorocha - Thanks!
