### ISSUE TITLE
Dracula Theme for musikcube

### ISSUE THREAD

**Issue by theonlydarkuser** [dracula/dracula-theme#579]
## Dracula Theme for [musikcube](https://musikcube.com/)
[Here is the repository](https://github.com/theonlydarkuser/musikcube)

**Comment by zenorocha** [comment]
That's awesome @theonlydarkuser! I just sent you an invite to join the organization.

Once you accept it, you'll be able to transfer the repo and I'll take care of adding it to the site.

Thanks for building this! 🎉

**Comment by theonlydarkuser** [comment]
umm... i know this is pretty stupid but can you tell me how to join a the organisation? (i couldn't find the option anywhere)

btw sorry for the late response, i wasn't opening github these days

**Comment by theonlydarkuser** [comment]
oh found it on my email but it's expired now 😅 can you pls send it again? sorry for the trouble.

**Comment by zenorocha** [comment]
@theonlydarkuser I resent you the invitation, can you try now?

**Comment by zenorocha** [comment]
Closing in favor of https://github.com/dracula/dracula-theme/issues/648
