### ISSUE TITLE
Dracula theme for Ripcord

### ISSUE THREAD

**Issue by SylveonBottle** [dracula/dracula-theme#580]
Ripcord: https://cancel.fm/ripcord/
Theme: https://github.com/SylveonBottle/dracula-ripcord

Instructions:
Copy code in samples/custom.json to clipboard
View > Preferences > Style > Customize > Paste from JSON

I don't know of a way to automate this using command line, however ripcord has a very simple color/theme editor built-in. This was just something I threw together in about 2 minutes.

**Comment by zenorocha** [comment]
I just sent you an invite to join the organization @SylveonBottle. 

Once you accept it, you'll be able to transfer the repo and I'll take care of adding it to the site.

Thanks for building this! 🎉

**Comment by SylveonBottle** [comment]
Joined and transferred.

**Comment by zenorocha** [comment]
@SylveonBottle can you update the `INSTALL.md` file? That's what the site uses to build the page.

On top of that, can you rename `screenshot-ripcord.png` to `screenshot.png`? The site needs that specific filename too.

**Comment by SylveonBottle** [comment]
Is that good?

**Comment by zenorocha** [comment]
Looking good now:
https://github.com/dracula/ripcord/commit/1cba228998f9f1887be13cff864e5c9f645ef478

Thanks @SylveonBottle!
https://draculatheme.com/ripcord
