### ISSUE TITLE
Dracula for Beyond Compare 4

### ISSUE THREAD

**Issue by cr45hmurphy** [dracula/dracula-theme#581]
I have created a Dracula theme for the Beyond Compare 4 application.

Github repo: https://github.com/cr45hmurphy/bc4_dracula

**Comment by zenorocha** [comment]
Great! I just sent you an invite to join the organization @cr45hmurphy.

Once you accept it, you'll be able to transfer the repo and I'll take care of adding it to the site.

Thanks for building this! 🎉

**Comment by cr45hmurphy** [comment]
> Great! I just sent you an invite to join the organization @cr45hmurphy.
> 
> Once you accept it, you'll be able to transfer the repo and I'll take care of adding it to the site.
> 
> Thanks for building this! 🎉

Done!

**Comment by zenorocha** [comment]
Looks like the repository still needs to be transferred.

**Comment by cr45hmurphy** [comment]
Try now.

**Comment by zenorocha** [comment]
https://draculatheme.com/beyond-compare-4 💥 💥 💥
