### ISSUE TITLE
Dracula for Flarum

### ISSUE THREAD

**Issue by iamdarkle** [dracula/dracula-theme#582]
Hi, I'm developing a theme for Flarum, I hope to finish it in the next few days and I'll fill in the issue properly with all the data.

But first I don't know if you are familiar with Composer, but Flarum uses a package system called Composer to install its extensions, I was wondering if you could add the package to [packagist.org](https://packagist.org/) when it's ready and add me as maintainer, first I think you should claim the name as you have the name Dracula on Github it won't take you long (a few months ago I had to do it and they replied in 2 days).

If we do this the users when they install the theme will use

`composer require Dracula/flarum`

Instead of:

`composer require IamDarkle/flarum`

It is quite necessary otherwise I would have to maintain both repositories at the same time.

Let me know what you think about this. Thanks :)

**Comment by IamDarkle** [comment]
In case you want to create the new repo here is the current one I'm working on.
App: [Flarum](https://flarum.org)
Repo: https://github.com/IamDarkle/flarum

**Comment by IamDarkle** [comment]
The theme is ready! Here a screenshot:
![screenshot](https://user-images.githubusercontent.com/15818451/121249324-bf9f1e00-c8a4-11eb-94e5-f5d218f2f937.png)

**Comment by zenorocha** [comment]
Hey @iamdarkle, we can definitely publish it to composer. 

I just sent you an invite to join the organization.

Once you accept it, you'll be able to transfer the repo and I'll take care of adding it to the site.

Thanks for building this! 🎉

**Comment by iamdarkle** [comment]
Thank you, it's done! 😄

**Comment by zenorocha** [comment]
It's live in the website now: https://draculatheme.com/flarum

Cheers @iamdarkle!
