### ISSUE TITLE
New Theme - Nyxt Browser

### ISSUE THREAD

**Issue by MahdyMirzade** [dracula/dracula-theme#583]
### A theme for [Nyxt Browser](https://nyxt.atlas.engineer/) (The first one I believe)

**Repo:** https://github.com/dracula/nyxt

**Screenshot:**
![img](https://github.com/dracula/nyxt/raw/master/screenshot.png)

P.S: I actually transferred this to organization for faster publish, I don't know If I what I did was appropriate or not, I apologize If I shouldn't but notice me if we need to sync requests here beforehand.

**Comment by zenorocha** [comment]
Re-opening as a reminder for myself to add this to the website.

**Comment by zenorocha** [comment]
https://draculatheme.com/nyxt ;)
