### ISSUE TITLE
New Theme - Dracula for TeXstudio

### ISSUE THREAD

**Issue by afazevedo** [dracula/dracula-theme#584]
A syntax style for the LaTeX editor [TeXstudio](https://www.texstudio.org/)! The first one for LaTeX, I think? 🤔 

**Repository**: https://github.com/afazevedo/texstudio-dracula-theme

![screenshot](https://user-images.githubusercontent.com/58051437/121761115-5f0e1c00-cb04-11eb-8a2b-8cb16ef46607.png)

**Comment by zenorocha** [comment]
This is super awesome @afazevedo! 🇧🇷 

I just sent you an invite to join the organization.

Once you accept it, you'll be able to transfer the repo and I'll take care of adding it to the site.

Thanks for building this! 🎉

**Comment by afazevedo** [comment]
Thank you! I just transferred it to the organization. 🎉 

Let me know if I need to do anything else. Looking forward to seeing it on the website 🤩

**Comment by zenorocha** [comment]
https://draculatheme.com/texstudio

Congrats @afazevedo! ⭐⭐⭐⭐⭐
