### ISSUE TITLE
Spyder

### ISSUE THREAD

**Issue by dinwun450** [dracula/dracula-theme#585]
![Screenshot 2021-06-17 7 44 50 PM](https://user-images.githubusercontent.com/42019518/122498897-c31d5e00-cfa4-11eb-8e11-09749bc8036f.png)

## Installation Guide
1. Go to Tools -> Preferences
2. Then Appearance -> Create new scheme
3. Specify the scheme of the text editor by pasting the following colors into the correct speculation below:

Text:
Normal text: #f8f8f2
Comment: #6272a4
String: #f1fa8c (yellow)
Number: #bd93f9 (purple)
Keyword: #ff79c6 (pink)
Builtin: #8be9fd (cyan)
Definition: #50fa7b (green)
instance #bd93f9 (again purple)

Highlight:
Current Cell and line: #44475a
Occurance: #ffb86c (orange)
Matched parens: #50fa7b (green)
Unmatched parens: #ff5555 (red)
Link: #bd93f9 (purple)

Background:
Background and Side areas: #282a36

**Comment by bigpick** [comment]
Heya! If you're looking to get your theme added as a additional Dracula org sub-theme, you'll want to [create a new repo based off the Dracula theme template](https://github.com/dracula/template) and then use that as your link here to have something to request for transfer into the org.

The standardized theme repo helps keeps things consistent across the (many) ports of Dracula themes. It also helps to have (at least one) screenshot of the theme, so people have an idea of what it looks like without having to configure it all just to look; same goes for the install section too.

Think you could fork the template repo and update accordingly with your theme's appropriate info and then update this issue, so this issue has a better chance of making it in to the official org? Thanks!

**Comment by bigpick** [comment]
... and if this for the Spyder IDE, Dracula actually already has an official repo for that here: 
* https://github.com/dracula/spyder-dracula

If this is the same spyder, I'd suggest opening an issue in that repository, to provide feedback/recommendations/changes on the theming there, if any.

Otherwise, this issue can be closed. Thanks!

**Comment by zenorocha** [comment]
It's live now!

https://draculatheme.com/spyder-ide
https://github.com/dracula/spyder-ide
