### ISSUE TITLE
New theme - LXTerminal

### ISSUE THREAD

**Issue by samcottle** [dracula/dracula-theme#590]
Hey Dracula team, I created a theme for the LXTerminal (the terminal that comes bundled with Raspberry Pi OS + some other OSes), using the color palette provided on https://draculatheme.com/contribute

Repo https://github.com/samcottle/lx-terminal

Let me know what you need me to do :)

**Comment by zenorocha** [comment]
This is super sweet @samcottle!

I just sent you an invite to join the organization.

Once you accept it, you'll be able to transfer the repo and I'll take care of adding it to the site.

Thanks for building this! 🎉

**Comment by samcottle** [comment]
[Done](https://github.com/dracula/lx-terminal) - thanks @zenorocha!

Shall I close this issue now?

**Comment by zenorocha** [comment]
It's live now! https://draculatheme.com/lxterminal
