### ISSUE TITLE
New Theme - Leftwm

### ISSUE THREAD

**Issue by mjbn** [dracula/dracula-theme#591]
hey guys, i create a theme for leftwm based on the [Dracula Team Color Palette](https://draculatheme.com/contribute#color-palette)
Repo: https://github.com/mjbn/leftwm-dracula-theme

**Comment by luxonauta** [comment]
Hey, very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/mjbn/leftwm-dracula-theme)
- [New repository.](https://github.com/dracula/leftwm)

Thanks for building this! 🎉

**Comment by luxonauta** [comment]
It's 🧟‍♂️ a-live: https://draculatheme.com/leftwm

**Comment by mjbn** [comment]
Hello,
Can you send me another invitation link?
the previous one got expired.

**Comment by luxonauta** [comment]
Sure! 💪🏻
