### ISSUE TITLE
New theme: Dwarf Fortress

### ISSUE THREAD

**Issue by benknoble** [dracula/dracula-theme#592]
## New Theme?

Not a code editor, but a fun game :)

https://github.com/benknoble/dracula-dwarffortress

I've assumed the transfer would end up with the name `dracula/dwarffortress` and made all the links appropriate to that.

**Comment by zenorocha** [comment]
I love it @benknoble! 👾 

I just sent you an invite to join the organization.

Once you accept it, you'll be able to transfer the repo and I'll take care of adding it to the site.

Thanks for building this! 🎉

**Comment by benknoble** [comment]
@zenorocha done. I didn't see the team until just now, so the repo needs added to the dracula/dwarf-fortress team; it also needs to be renamed, methinks

**Comment by zenorocha** [comment]
https://draculatheme.com/dwarf-fortress

Another great theme @benknoble ;D
