### ISSUE TITLE
New Theme - Caprine Messenger

### ISSUE THREAD

**Issue by fabian-pandas** [dracula/dracula-theme#593]
A dracula color theme for the Caprine messenger.

https://github.com/fabian-pandas/Dracula-for-Caprine

**Comment by zenorocha** [comment]
Great @fabian-pandas! I just sent you an invite to join the organization.

Once you accept it, you'll be able to transfer the repo and I'll take care of adding it to the site.

Thanks for building this! 🎉

P.S.: Can you please update the `INSTALL.md` file with the instructions to install?

**Comment by zenorocha** [comment]
@fabian-pandas friendly ping ;)

You should have received another invitation to join the Dracula org now. Can you transfer the repo?

**Comment by fabian-pandas** [comment]
> Great @fabian-pandas! I just sent you an invite to join the organization.
> 
> Once you accept it, you'll be able to transfer the repo and I'll take care of adding it to the site.
> 
> Thanks for building this! tada
> 
> P.S.: Can you please update the `INSTALL.md` file with the instructions to install?

done :)

**Comment by zenorocha** [comment]
Here it is: https://draculatheme.com/caprine-messenger

Thanks @fabian-pandas!
