### ISSUE TITLE
Cmus theme

### ISSUE THREAD

**Issue by worbgge** [dracula/dracula-theme#595]
Hello, i edited it a bit but i don't think that it's a finished thing, the theme and a screenshot will be added below.

![2021-07-15_21-28](https://user-images.githubusercontent.com/23532123/125853221-fbcd628d-701a-4258-8051-174d046dd1f7.png)
[https://clbin.com/cG6Z1](url)

**Comment by bigpick** [comment]
Heya! If you're looking to get your theme added as a additional Dracula org sub-theme, you'll want to [create a new repo based off the Dracula theme template](https://github.com/dracula/template) and then use that as your link here to have something to request for transfer into the org.

The standardized theme repo helps keeps things consistent across the (many) ports of Dracula themes. It also helps to have (at least one) screenshot of the theme, so people have an idea of what it looks like without having to configure it all just to look; same goes for the install section too.

Think you could fork the template repo and update accordingly with your theme's appropriate info and then update this issue, so this issue has a better chance of making it in to the official org? Thanks!
