### ISSUE TITLE
New Theme - Funkwhale

### ISSUE THREAD

**Issue by zstix** [dracula/dracula-theme#596]
## A new theme for [Funkwhale](https://funkwhale.audio)
Repository: https://github.com/zstix/funkwhale

![screenshot](https://user-images.githubusercontent.com/1946433/125878418-b649873c-f2fc-4550-a391-0fe9499e11dc.png)

**Comment by bigpick** [comment]
This looks really clean. Only (nitpick) thing I could find was do you think you could update the 

```
This theme is maintained by the following person(s) and a bunch of [awesome contributors](https://github.com/dracula/template/graphs/contributors).
```

bit in the main README to point at the eventual dracula repo URL instead of the template one? (https://github.com/dracula/funkwhale/graphs/contributors).

**Comment by zstix** [comment]
@bigpick sorry for the slow response (my Github notifications are a nightmare).

I've made the requested update!

**Comment by zenorocha** [comment]
Thanks for building this theme @zstix!

I just sent you an invite to join the organization.

Once you accept it, you'll be able to transfer the repo and I'll take care of adding it to the site.

Thanks for building this! 🎉

**Comment by zstix** [comment]
@zenorocha Just submitted the transfer, let me know if you need anything else!

**Comment by zenorocha** [comment]
There you go! https://draculatheme.com/funkwhale

Thanks @zstix :D
