### ISSUE TITLE
New Theme - ueli

### ISSUE THREAD

**Issue by CapnSammeh** [dracula/dracula-theme#598]
A Dracula Theme for ueli - A keystroke launcher for Windows and macOS
https://github.com/CapnSammeh/dracula-ueli

**Comment by bigpick** [comment]
This looks nice! Though, after downloading ueli and importing the themes, it doesn't seem to have any effect on changing the window for me? e.g

## Default
![image](https://user-images.githubusercontent.com/9803299/127667446-7e353ecd-6ee8-4213-afd1-89bf7544da46.png)

## Red
![image](https://user-images.githubusercontent.com/9803299/127667612-f0b61285-f79f-4d1d-8f0c-f5bba19a4713.png)

**Comment by CapnSammeh** [comment]
I think that's great feedback @bigpick, thanks for the suggestion! I've made your proposed changes, feel free to check it out! :)

**Comment by zenorocha** [comment]
This looks amazing, good job @CapnSammeh!

I just sent you an invite to join the organization.

Once you accept it, you'll be able to transfer the repo and I'll take care of adding it to the site.

Thanks for building this! 🎉

**Comment by CapnSammeh** [comment]
All done @zenorocha; thanks for having me, and for starting this wonderful movement!

**Comment by zenorocha** [comment]
Thank you @CapnSammeh, it's really awesome to see the Ueli theme there :D

https://draculatheme.com/ueli 🎉 🎉 🎉
