### ISSUE TITLE
Dracula theme for WindTerm

### ISSUE THREAD

**Issue by lpadula** [dracula/dracula-theme#599]
I have created a Dracula inspired theme for WindTerm: https://github.com/kingToolbox/WindTerm/issues/62

The theme files: https://github.com/kingToolbox/WindTerm/files/6431558/dracula.zip

**Comment by bigpick** [comment]
Heya! If you're looking to get your theme added as a additional Dracula org sub-theme, you'll want to [create a new repo based off the Dracula theme template](https://github.com/dracula/template) and then use that as your link here to have something to request for transfer into the org.

The standardized theme repo helps keeps things consistent across the (many) ports of Dracula themes. It also helps to have (at least one) screenshot of the theme, so people have an idea of what it looks like without having to configure it all just to look; same goes for the install section too.

Think you could fork the template repo and update accordingly with your theme's appropriate info and then update this issue, so this issue has a better chance of making it in to the official org? Thanks!

**Comment by zenorocha** [comment]
@lpadula can you create that [template repository](https://github.com/dracula/template) so we can add this to the official site?

**Comment by lpadula** [comment]
Hi, sorry for the late response. I need to fork this: https://github.com/dracula/template and put my files inside?

**Comment by zenorocha** [comment]
That's correct @lpadula, you can use this button to facilitate the process: 
![CleanShot 2021-11-24 at 13 16 38@2x](https://user-images.githubusercontent.com/398893/143313920-26af3507-6ffd-499b-8eb7-7d6202bd23da.png)

**Comment by lpadula** [comment]
Perfect: https://github.com/lpadula/windterm-dracula

**Comment by zenorocha** [comment]
Looks awesome now @lpadula!

I just sent you an invite to join the organization.

Once you accept it, you'll be able to transfer the repo and I'll take care of adding it to the site.

Thanks for building this! 🎉

**Comment by lpadula** [comment]
Done!

**Comment by zenorocha** [comment]
https://draculatheme.com/windterm 🎉
