### ISSUE TITLE
New Theme - Spicetify

### ISSUE THREAD

**Issue by Darkempire78** [dracula/dracula-theme#600]
## New Theme for Spicetify

A dracula color theme for the Spicetify-cli

https://github.com/Darkempire78/Dracula-Spicetify

**Comment by bigpick** [comment]
Partially personal preference, but partially "theme-vibe" inspired - not sure that the chosen colors for all elements align as much as they could with the general/expected Dracula spec. Granted, this isn't a language so it doesn't match the spec exactly (obviously) but still, using the color red for things other than something specifically error related doesn't seem right

It also seems overly background+purple, but maybe that's just the screenshot

**Comment by Darkempire78** [comment]
Regarding the background and the purple color, it is really very readable, it is indeed certainly due to the screenshot

**Comment by bigpick** [comment]
I didn't get time to get spicetify downloaded and tested locally this past weekend, so I will have to find some time to do that this week and look for myself.

But, what I meant in terms of it being too purple dominant is that I was thinking it should look something more like the player demonstrated in the Funkwhale theme:  https://github.com/dracula/dracula-theme/issues/596

**Comment by luxonauta** [comment]
This is very cool! 🤩

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/Darkempire78/Dracula-Spicetify)
- [New repository.](https://github.com/dracula/spicetify)

Thanks for building this! 🎉 And let's continue this discussion about colours in this new repository! 💬

**Comment by luxonauta** [comment]
It's 🧟‍♂️ a-live: https://draculatheme.com/spicetify
