### ISSUE TITLE
Gtk-Warning messages

### ISSUE THREAD

**Issue by j0ker70** [dracula/dracula-theme#602]
`(evince:223665): Gtk-WARNING **: 05:00:55.557: Theme directory actions/24 of theme Dracula has no size field`
`(evince:223665): Gtk-WARNING **: 05:00:55.557: Theme directory actions/32 of theme Dracula has no size field`
`(evince:223665): Gtk-WARNING **: 05:00:55.557: Theme directory actions/16@2x of theme Dracula has no size field`
`(evince:223665): Gtk-WARNING **: 05:00:55.557: Theme directory actions/22@2x of theme Dracula has no size field`
`(evince:223665): Gtk-WARNING **: 05:00:55.557: Theme directory actions/24@2x of theme Dracula has no size field`
`(evince:223665): Gtk-WARNING **: 05:00:55.557: Theme directory actions/32@2x of theme Dracula has no size field`
`(evince:223665): Gtk-WARNING **: 05:00:55.557: Theme directory actions/symbolic of theme Dracula has no size field`

I get these warning messages whenever I start evince. I am using dracula icon theme and color theme. I am running Ubuntu 20.04. Is there any way I can remove these warning mesages?

**Comment by bigpick** [comment]
Heya! If you close/move this over to https://github.com/dracula/gtk/issues you might be able to get some more relevant/quicker support on it, as that way it will at least be in the specific repo for the GTK theme (which I assume you're using here, correct)?

**Comment by j0ker70** [comment]
Yes. I will do that.
