### ISSUE TITLE
New Theme - Side Notes

### ISSUE THREAD

**Issue by gustavosaez** [dracula/dracula-theme#604]
https://github.com/gustavosaez/draculatheme-sidenotes/blob/master/README.md

**Comment by bigpick** [comment]
Hey, this looks nice! 

On your repository though, could you move all the install sectioned stuff, i.e 

```
## Install

1. Download the **Dracula-SideNotes.sntheme** file
2. Open Side Notes
3. Access Preferences of the app with keyboard shortcut "command + comma" (⌘,)
4. Click **Appearance**
5. <img width="698" alt="CleanShot 29 07 2021 - 10h57m34s@2x" src="https://user-images.githubusercontent.com/7749461/127505049-5246f544-5457-4850-ad4c-0741692c5615.png">
6. Then **Manage** and **Add**
7. ![CleanShot 29 07 2021 - 11h00m38s@2x](https://user-images.githubusercontent.com/7749461/127505578-33394874-2516-45c9-8ad3-43ef05dbf98f.png)
8. Select the **Dracula-SideNotes.sntheme** and after this, double click to apply
9. Close the window
10. Enjoy your Dracula Site Notes
```

...  into the separate `INSTALL.md` file to match the standardized layout of all the other Dracula org repos? This way, if/when Zeno takes a look, it'll be all set to transfer? And then change it to just be the standard

```
## Install
All instructions can be found at [draculatheme.com/sidenotes](https://draculatheme.com/sidenotes).
```

And then just update the repo's description to match, and the syntax in the main README as well (relative link to the screenshot/imgs)?

For reference, the standardized theme repo layout is here: https://github.com/dracula/template

 Thanks!

**Comment by gustavosaez** [comment]
Thank you @bigpick ! That's my first use publishing something and I didn't get it how to proceed. I will try to fix this but I confess it's hard as a first use haha. Anyway, thank you!!!

**Comment by bigpick** [comment]
No problem - if you want some help, lmk and I can make a PR against yours with the changes. 

Cheers

**Comment by gustavosaez** [comment]
I need to learn! But If I take so long to do the changes, I scream for help here, for sure.

**Comment by zenorocha** [comment]
Great job @gustavosaez! I just sent you an invite to join the organization.

Once you accept it, you'll be able to transfer the repo and I'll take care of adding it to the site.

Thanks for building this! 🎉

**Comment by gustavosaez** [comment]
@zenorocha I just did it. Thanks!

**Comment by zenorocha** [comment]
Thanks for adding this theme @gustavosaez! 🎉 
 
https://draculatheme.com/sidenotes
