### ISSUE TITLE
New Theme - eM Client

### ISSUE THREAD

**Issue by bigpick** [dracula/dracula-theme#605]
## New Theme Addition - [eM Client](https://www.emclient.com/)

Source: 
* https://github.com/bigpick/em-client

This closes https://github.com/dracula/dracula-theme/issues/563 when incorporated. 

When this gets the OK to be transferred over, I'll transfer it over and then email the folks at eM Client to also get the theme added officially to their store (https://www.emclient.com/themes)

**Comment by zenorocha** [comment]
That's super cool @bigpick, I particularly love that Calendar view <3

Let's get it transferred!

**Comment by bigpick** [comment]
[Done](https://github.com/dracula/em-client) ✅

**Comment by zenorocha** [comment]
https://draculatheme.com/em-client

Thanks @bigpick!! It looks pretty good ;D
