### ISSUE TITLE
The latest 2021.02 version of PyCharm fails to load the theme

### ISSUE THREAD

**Issue by scott91e1** [dracula/dracula-theme#606]
![iMPORT-ERROR](https://user-images.githubusercontent.com/6354142/127755468-63e2f13a-c848-4ffd-91e1-44ebc90f1d05.png)

Is produced with the latest version of PyCharm:

![PYCHARM-VERSION](https://user-images.githubusercontent.com/6354142/127755478-cfe01e80-a67a-4bba-b588-23c80afef4a4.png)

Is there an easy fix or new download for this?

Thanks and regards,

Scott.

**Comment by bigpick** [comment]
Hey @scott91e1 ! This was actually discussed on the Dracula Discord server a few days ago - Zeno ended up pushing out a new version (1.3.2) that fixes the compatibility issue; you should be able to re-download the latest from gumroad.com again and it should resolve your issue!
