### ISSUE TITLE
even darker theme?

### ISSUE THREAD

**Issue by pjalsGit** [dracula/dracula-theme#607]
I think the background is a little bit too light for me, it would be nice to have a "distribution" of it which has the background a little darker. Kind of like dracula-at-night but not only for VS Code.

**Comment by bigpick** [comment]
Hey! This looks like it'd be better suited as a topic for a discussion over at https://github.com/dracula/dracula-theme/discussions instead of an issue here; That way we can keep the issues list to mostly just new theme transfer requests/actual issues?

Thanks!

**Comment by pjalsGit** [comment]
ok!
