### ISSUE TITLE
any thoughts into create an kde oficial theme?

### ISSUE THREAD

**Issue by mzramna** [dracula/dracula-theme#609]
## New Theme?

since has some unnoficial themes to kde like [ant-dracula kde](https://store.kde.org/p/1370871) has any thoughts to create an official version?

just to padronize the system,with this much of the system already gets all the colors and feel of dracula

**Comment by zenorocha** [comment]
We actually see that one as the official version:
* https://draculatheme.com/gtk
* https://github.com/dracula/gtk
