### ISSUE TITLE
New Theme - BTCPay

### ISSUE THREAD

**Issue by FosterHangdaan** [dracula/dracula-theme#613]
Created a dracula theme for BTCPay server. The BTCPay store checkout theme will be added in the future.

https://github.com/FosterHangdaan/btcpay-server

**Comment by zenorocha** [comment]
Awesome @FosterHangdaan! I just sent you an invite to join the organization.

Once you accept it, you'll be able to transfer the repo and I'll take care of adding it to the site.

Thanks for building this! 🎉

**Comment by FosterHangdaan** [comment]
Thanks @zenorocha. I have joined the org and transferred the repo.

**Comment by zenorocha** [comment]
It's live now! https://draculatheme.com/btcpay-server

Thanks @FosterHangdaan ;D
