### ISSUE TITLE
New Theme - MiXplorer

### ISSUE THREAD

**Issue by sionta** [dracula/dracula-theme#615]
Created a dracula theme for MiXplorer android.

https://github.com/kybo15/dracula-mixplorer

@zenorocha

**Comment by zenorocha** [comment]
That's really cool @kybo15!

I just sent you an invite to join the organization.

Once you accept it, you'll be able to transfer the repo and I'll take care of adding it to the site.

Thanks for building this! 🎉

**Comment by zenorocha** [comment]
Try navigating to https://github.com/dracula, you should see a top banner with a message about the invitation.

**Comment by kybo15** [comment]
> Try navigating to https://github.com/dracula, you should see a top banner with a message about the invitation.

Done sir.

**Comment by zenorocha** [comment]
It's live now: https://draculatheme.com/mixplorer

Thanks @kybo15 ;D

**Comment by kybo15** [comment]
@zenorocha sorry, why i don't have access anymore to my repo https://github.com/dracula/mixplorer.

**Comment by zenorocha** [comment]
@kybo15 sorry about that, looks like the GitHub Team wasn't properly setup. You should have admin access now ;)

**Comment by kybo15** [comment]
> @kybo15 sorry about that, looks like the GitHub Team wasn't properly setup. You should have admin access now ;)

and till now i can't access https://github.com/dracula/mixplorer how can i can update my repo.

**Comment by luxonauta** [comment]
Oops, it seems that your permission was read-only. I've already fixed that for you. 😉

**Comment by sionta** [comment]
hei @zenorocha @luxonauta i lost my access rights again in my [mixplorer](https://github.com/dracula/mixplorer) repo, i need help because i previously changed the wrong settings in the repo.

**Comment by luxonauta** [comment]
I added you again and have updated the team permissions to administer the theme within the organization 😊
