### ISSUE TITLE
Pro version for Eclipse

### ISSUE THREAD

**Issue by psaraf** [dracula/dracula-theme#617]
## New Theme
Yes(Van Helsing)
We would love to support all code editors out there, but we need your help to accomplish that. Feel free to create a new theme based on our [color palette](https://github.com/dracula/dracula-theme#color-palette).

## Existing Theme?
Yes 

Can we have pro version eclipse.

**Comment by psaraf** [comment]
is anyone looking into pro support?

**Comment by zenorocha** [comment]
Yes, I am. There's a backlog of themes to be ported to Dracula PRO. Eclipse is on the list, but there are others with higher priority.

**Comment by psaraf** [comment]
any chance this get priority? its been several months

**Comment by e2t** [comment]
Anyone?

**Comment by luxonauta** [comment]
Unfortunately, there is no theme for Eclipse yet.

It is in our plans to ✅ add it, but at the moment, we have a list of themes to be ported to Dracula PRO with higher priority.
