### ISSUE TITLE
New Theme - Pantheon Terminal

### ISSUE THREAD

**Issue by mgoggin** [dracula/dracula-theme#619]
I created a theme for Pantheon Terminal, the default terminal application in elementary OS.

https://github.com/mgoggin/pantheon-terminal-dracula

![Dracula for Pantheon Terminal](https://raw.githubusercontent.com/mgoggin/pantheon-terminal-dracula/master/screenshot.png)

**Comment by zenorocha** [comment]
Great @mgoggin! I just sent you an invite to join the organization.

Once you accept it, you'll be able to transfer the repo and I'll take care of adding it to the site.

Thanks for building this! 🎉

**Comment by mgoggin** [comment]
Thanks @zenorocha! Transfer should be underway.

**Comment by zenorocha** [comment]
It's live now! https://draculatheme.com/pantheon-terminal

Thanks @mgoggin ;)
