### ISSUE TITLE
New theme request: Code::Blocks and KDE Themes

### ISSUE THREAD

**Issue by Huoi** [dracula/dracula-theme#620]
GTK theme works well with GNOME, but an official KDE global theme would be awesome.
I'm also surprised Dracula doesn't have official support for Code::Blocks theme.

**Comment by zenorocha** [comment]
Hey @huoi, do you want to give it a try and create those themes?

Here are the instructions on how to create a theme: https://draculatheme.com/contribute

**Comment by luxonauta** [comment]
This is already built and added to the Dracula Theme organization, so I will close this Issue. 🦇
