### ISSUE TITLE
New theme - Passky

### ISSUE THREAD

**Issue by zigazajc007** [dracula/dracula-theme#621]
https://github.com/Rabbit-Company/passky

**Comment by zenorocha** [comment]
Cool stuff @zigazajc007! I just sent you an invite to join the organization.

Once you accept it, you'll be able to transfer the repo and I'll take care of adding it to the site.

Thanks for building this! 🎉

**Comment by zigazajc007** [comment]
and thank you for creating such an amazing theme.

**Comment by zenorocha** [comment]
https://draculatheme.com/passky 💥 

Congrats on Passky, it looks great!
