### ISSUE TITLE
New theme - tym

### ISSUE THREAD

**Issue by gnsfujiwara** [dracula/dracula-theme#622]
https://github.com/gnsfujiwara/Tym-Dracula-theme

**Comment by zenorocha** [comment]
That's really cool!

@gnsfujiwara I just sent you an invite to join the organization.

Once you accept it, you'll be able to transfer the repo and I'll take care of adding it to the site.

Thanks for building this! 🎉

**Comment by zenorocha** [comment]
https://draculatheme.com/tym 🧛‍♂️
