### ISSUE TITLE
New Theme - Dev C++

### ISSUE THREAD

**Issue by Nxrth-x** [dracula/dracula-theme#626]
## Dracula for [Dev C++](https://www.bloodshed.net/)

I've been using [Dev ++](https://www.bloodshed.net/) for a while now and I've really enjoyed using this theme on it. 🧛‍♀️

### dracula-dev-cpp

[https://github.com/Nxrth-x/dracula-dev-cpp](https://github.com/Nxrth-x/dracula-dev-cpp)

### Screenshot

![Theme screenshot](https://raw.githubusercontent.com/Nxrth-x/dracula-dev-cpp/master/screenshot.png)

**Comment by zenorocha** [comment]
That's super cool @Nxrth-x!

I just sent you an invite to join the organization.

Once you accept it, you'll be able to transfer the repo and I'll take care of adding it to the site.

Thanks for building this! 🎉

**Comment by zenorocha** [comment]
https://draculatheme.com/dev-cpp 🎉 🎉 🎉
