### ISSUE TITLE
New Theme - gamepad viewer

### ISSUE THREAD

**Issue by mly32** [dracula/dracula-theme#627]
## New Theme

[https://github.com/dracula/gamepad-viewer](https://github.com/dracula/gamepad-viewer)

Created dracula-based themes for ds4 and xbox one controllers for the popular tool [Gamepad Viewer](https://gamepadviewer.com/).

You can use any controller (connected to your computer) to test these themes out,

**Comment by zenorocha** [comment]
This is super awesome @mly32! Thanks for building this.

It's live in the site now: https://draculatheme.com/gamepad-viewer
