### ISSUE TITLE
New GTK theme - DraculaSur

### ISSUE THREAD

**Issue by Aryan20** [dracula/dracula-theme#633]
## New Theme for GTK

I modified the Whitesur-gtk-theme with Dracula colors to make - https://github.com/Aryan20/DraculaSur-gtk-theme

It also has gtk 4 support, I know I probably didn't do lots of customizations but I still think it is worth trying anyway :)

**Comment by dbasinge** [comment]
The main issue right now with the Dracula gtk theme is lack of support for gtk 4.0. I know the author is working on it, but I do not use it do to that.
