### ISSUE TITLE
Dracula for Revolt!

### ISSUE THREAD

**Issue by Wild54** [dracula/dracula-theme#634]
## Dracula for Revolt.

I added Dracula theme to the Revolt Chat app. The author of Revolt has merged my pull-request which adds the Dracula theme to the official Revolt Theme Shop.

Now I want to add Dracula for Revolt!

https://github.com/Wild54/revolt

**Comment by zenorocha** [comment]
It's live now! Thanks @Wild54 ;D

https://draculatheme.com/revolt
