### ISSUE TITLE
New Theme - Nova Launcher (Android)

### ISSUE THREAD

**Issue by scientiac** [dracula/dracula-theme#641]
I've created a Dracula theme for Nova Launcher (Android).
The repository for the project is [here](https://github.com/scientiac/dracula_nova_launcher).

Hope you like it!
![Screenshot_1](https://user-images.githubusercontent.com/58177655/138840633-cc017296-6a35-45aa-b748-cdace49b4b8c.png)
![Screenshot_2](https://user-images.githubusercontent.com/58177655/138840659-b15b26b7-5671-4032-9881-dc577315716c.png)

**Comment by scientiac** [comment]
I wrote a step by step guide to modify the colors of the user just wants to change the color scheme. 

I added a default layout .backup file as well as a beautified layout .backup file if the user wants that .

**Comment by zenorocha** [comment]
Great job @scientiac! I just sent you an invite to join the organization.

Once you accept it, you'll be able to transfer the repo and I'll take care of adding it to the site.

Thanks for building this! 🎉

**Comment by scientiac** [comment]
Thanks!@zenorocha I will be adding it in a few days.

**Comment by scientiac** [comment]
It is transferred!

**Comment by zenorocha** [comment]
https://draculatheme.com/nova-launcher

It's live now! :D

Great job @scientiac!
