### ISSUE TITLE
New Theme - Textastic

### ISSUE THREAD

**Issue by kjharcombe** [dracula/dracula-theme#642]
I made some subtle changes to your Textmate scheme to allow it to work with Textastic, a text editor for the Apple ecosystem.

![Textastic](https://github.com/kjharcombe/textastic/blob/master/screenshot.png)

https://github.com/kjharcombe/textastic/tree/master

**Comment by zenorocha** [comment]
That's super cool @kjharcombe!

Feel free to transfer to the org now ;)

**Comment by zenorocha** [comment]
https://draculatheme.com/textastic

Awesome stuff @kjharcombe ;D
