### ISSUE TITLE
Foot Terminal dracula dark theme

### ISSUE THREAD

**Issue by syrofoam** [dracula/dracula-theme#643]
## Theme did not exist that is why I made it.

https://github.com/syrofoam/dracula-foot/tree/master

**Comment by zenorocha** [comment]
Great @syrofoam! I just sent you an invite to join the organization.

Once you accept it, you'll be able to transfer the repo and I'll take care of adding it to the site.

Thanks for building this! 🎉

**Comment by syrofoam** [comment]
Hi, I went ahead and created it under the 'application' name and finished setting it up.

Let me know if anything is missing or something.

No problem, I hope everything is smooth looking for those who want to try it out!

**Comment by zenorocha** [comment]
@syrofoam looks like you accepted the invitation to join the org, but still haven't transferred the repository.

Here are some instructions: https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-user-account

**Comment by syrofoam** [comment]
Could I just delete the 'mirror' repo on my personal github and only use the repo on dracula?. They both seem to be 'forks' of the template and are 'ahead' of the template. And if I want to just move it I have to delete the repo witch exist for it has the name already. github.com/dracula/foot

You think that's okey solution? I'm not that skilled with git so thanks for the link.

**Comment by zenorocha** [comment]
@syrofoam I made some changes to the installation instructions, can you take a look? https://github.com/dracula/foot/commit/f3bb85d3b8bf0bc4038511cd4061a00feb4e2aca

Feel free to delete the https://github.com/syrofoam/dracula-foot/tree/master repo now.

**Comment by zenorocha** [comment]
It's finally live! https://draculatheme.com/foot-terminal

Thanks @syrofoam ;)
