### ISSUE TITLE
repo naming

### ISSUE THREAD

**Issue by mralusw** [dracula/dracula-theme#644]
I suppose this is impossible to fix now, but the repo naming scheme is severely misguided. For example if I clone `dracula/kakoune`, I will get a plugin sub-folder (inside the `plugins` folder, whatever plugin manager I use) named... `kakoune`. Just like the editor's own source code `git` folder, you know.

Luckily, no other projects had the bright idea to name their repos *exactly* like the editor, because if I wanted to install `dracula/kakoune` and `atom/kakoune`, for instance, the plugin manager would find a conflict.

**Comment by benknoble** [comment]
You can always specify the name of the directory to clone into.

**Comment by mralusw** [comment]
> You can always specify the name of the directory to clone into.

Manually. Most plugin managers don't have renaming capabilities.

**Comment by benknoble** [comment]
> Manually. Most plugin managers don't have renaming capabilities.

I don't specifically know atom or kakoune, but most of the vim ecosystem allows this. And if you are cloning the plugin, I assumed that was with (manually or automatically) `git clone`, which has a destination parameter.

**Comment by mralusw** [comment]
I agree that plugin managers should certainly be able to rename the clone.

My example was meant to illustrate something a bit different &mdash; the case where `dracula` has a `kakoune` repo, and `desert` also has a `kakoune` repo etc &mdash; i.e. several theme providers follow the same naming scheme.

Anyway, thank you for your input.
