### ISSUE TITLE
New Theme - Sequel Ace

### ISSUE THREAD

**Issue by crydotsnake** [dracula/dracula-theme#647]
## New Theme for Sequel Ace

Hello!

I added a new theme for Sequel Ace:

https://github.com/crydotsnake/sequel-ace

**Comment by crydotsnake** [comment]
Since Sequel Pro is not in development anymore, i thought it would be great to have the same for Sequel Ace! :)

**Comment by crydotsnake** [comment]
Theme file is now added in the repository, totally forgot to include it.

**Comment by zenorocha** [comment]
That's awesome @crydotsnake!

I just sent you an invite to join the organization.

Once you accept it, you'll be able to transfer the repo and I'll take care of adding it to the site.

Thanks for building this! 🎉

**Comment by crydotsnake** [comment]
Thanks you a lot ! 😍🙏🏼

**Comment by crydotsnake** [comment]
Its transfered ! 🎉
https://github.com/dracula/sequel-ace

**Comment by zenorocha** [comment]
https://draculatheme.com/sequel-ace 💥💥💥

thanks for building this @crydotsnake ;)

**Comment by crydotsnake** [comment]
Whoop Whoop! 🥳

**Comment by crydotsnake** [comment]
But i found a typo in the install section. But i fixed it already :)
