### ISSUE TITLE
Dracula for musikcube

### ISSUE THREAD

**Issue by quetzal-ux** [dracula/dracula-theme#648]
[here's the repo](https://github.com/quetzal-ux/Dracula-musikcube)

**Comment by zenorocha** [comment]
Hey @quetzal-ux, looks like the repository is not following the https://github.com/dracula/template.

Can you adjust to that? Those files are required to autogenerate the website.

**Comment by quetzal-ux** [comment]
okay ill get on it

**Comment by quetzal-ux** [comment]
@zenorocha  finished, if it needs anything let me know

**Comment by zenorocha** [comment]
Looks good now, thanks for doing this @quetzal-ux!

I just sent you an invite to join the organization.

Once you accept it, you'll be able to transfer the repo and I'll take care of adding it to the site.

Thanks for building this! 🎉

**Comment by zenorocha** [comment]
https://draculatheme.com/musikcube 🔥
