### ISSUE TITLE
New Theme - Revolution IRC

### ISSUE THREAD

**Issue by gnsfujiwara** [dracula/dracula-theme#649]
Hello.

I added a new theme for Revolution IRC.

Here is the theme: 

https://github.com/gnsfujiwara/revolution-irc

**Comment by zenorocha** [comment]
Hey @gnsfujiwara, this looks cool! Feel free to transfer the repo now ;)

**Comment by zenorocha** [comment]
https://draculatheme.com/revolution-irc 🔥🔥🔥
