### ISSUE TITLE
Theme with the use of fish shell !

### ISSUE THREAD

**Issue by ekarious** [dracula/dracula-theme#65]
Hello !

I've been trying to add dracula theme on my Terminal and iTerm2 app but those couldn't show up properly with the use of fish shell which add it's own theme.

So i will probably make my own based on dracula theme to match it !

By the way, how do you get the arrow at the beginning of each line ?

**Comment by lowski** [comment]
@Kitefr have you created your own dracula theme for fish?

**Comment by Kitefr** [comment]
I started it but didn't liked it very much so i dropped it in the end.
