### ISSUE TITLE
Dracula for Powerlevel10k

### ISSUE THREAD

**Issue by jseashell** [dracula/dracula-theme#650]
Brings Dracula to the popular Oh My Zsh theme Powerlevel10k!

![Preview](https://raw.githubusercontent.com/jseashell/dracula-powerlevel10k/main/screenshot.png)

Repo: [Dracula for Powerlevel10k](https://github.com/jseashell/dracula-powerlevel10k)

Install steps:

1. Install [Dracula for iTerm](https://draculatheme.com/iterm)
2. Install [oh-my-zsh](https://github.com/ohmyzsh/ohmyzsh)
3. Install [powerlevel10k](https://github.com/romkatv/powerlevel10k)
4. Replace `~/.zshrc` with `./files/.zshrc`
5. Replace `~/.p10k.zsh` with `./files/.p10k.zsh`
6. Run `source ~/.zshrc`

**Comment by zenorocha** [comment]
Great stuff @jseashell!

Here are some changes that I'd like to suggest:
1. When using purple as a background, it's better to consider black as the text color. This should improve the contrast ratio. 
2. The install steps should be added to the INSTALL.md file. This is required for the website to be automatically generated. See the https://github.com/dracula/template for a reference.

I just sent you an invite to join the organization.

Once you accept it, you'll be able to transfer the repo and I'll take care of adding it to the site.

Thanks for building this! 🎉

**Comment by jseashell** [comment]
Thanks for that feedback @zenorocha! I've merged those suggestions and will get to transferring the repo here shortly

**Comment by jseashell** [comment]
Transfer complete https://github.com/dracula/powerlevel10k

**Comment by zenorocha** [comment]
Looks amazing now, great screenshot!

By the way, I made some changes to the instructions since powerlevel10k can be installed not only with Oh My ZSH.

**Comment by zenorocha** [comment]
https://draculatheme.com/powerlevel10k 🔥🔥🔥
