### ISSUE TITLE
New Theme - YouTube using Enhancer for Youtube

### ISSUE THREAD

**Issue by uttsav1025** [dracula/dracula-theme#652]
Hello!

I added a new theme for YouTube using an extension called Enhancer for YouTube.

Here's the link to the theme:

https://github.com/uttsav1025/enhancer-for-youtube

**Comment by luxonauta** [comment]
I appreciate your interest in creating and wanting to contribute to the project. 🥰

But from what I saw, we already have a theme for Youtube. Would you be interested in joining the organization and collaborating with this theme that we already have? 🤔

**Comment by uttsav1025** [comment]
Thank you, I've been following the project and would absolutely be interested in joining the organization and collaborating.
