### ISSUE TITLE
Dracula theme for `ggplot2` and `R` palette

### ISSUE THREAD

**Issue by jrdnbradford** [dracula/dracula-theme#653]
I'm wondering if the following is a good fit to be added: https://github.com/jrdnbradford/ggplot2

It includes a `ggplot2` theme and a `R` color palette that, when combined, make a Dracula-ish plot. Let me know.

**Comment by zenorocha** [comment]
Looks great @jrdnbradford!

I just sent you an invite to join the organization.

Once you accept it, you'll be able to transfer the repo and I'll take care of adding it to the site.

Thanks for building this! 🎉

**Comment by jrdnbradford** [comment]
Great! I transferred it over: https://github.com/dracula/ggplot2. Let me know if I can do anything else.

**Comment by zenorocha** [comment]
https://draculatheme.com/ggplot2 ✨
