### ISSUE TITLE
Dracula for Unreal Engine 5

### ISSUE THREAD

**Issue by jaiden-d** [dracula/dracula-theme#656]
Unreal Engine 5 has support for custom editor themes, so I decided to make a Dracula one 😄 

You can find it here! [jaiden-d/dracula-ue5](https://github.com/jaiden-d/dracula-ue5)

**Comment by zenorocha** [comment]
That's awesome @jaiden-d!! :D

I just sent you an invite to join the organization.

Once you accept it, you'll be able to transfer the repo and I'll take care of adding it to the site.

Thanks for building this! 🎉

**Comment by jaiden-d** [comment]
Just accepted and submitted the transfer, thanks!

**Comment by zenorocha** [comment]
https://draculatheme.com/unreal-engine 🥳
