### ISSUE TITLE
New MySQL Workbench Theme

### ISSUE THREAD

**Issue by michaelcaxias** [dracula/dracula-theme#657]
## New theme for MySQL Workbench

I've made a theme based on Dracula Theme for MySQL Workbench with [the default color scheme](https://draculatheme.com/contribute)

[Theme's link here](https://github.com/michaelcaxias/mysql-workbench-dracula-theme)

**Comment by zenorocha** [comment]
Hey @michaelcaxias, this looks cool, congrats!

Before we move this to the Dracula org and website, there are some changes that need to be made.

Can you follow the same file structure from the template? https://github.com/dracula/template
For example, the `INSTALL.md` is required to generate the page on the website and the `screenshot.png` is required to display it.

After you're done with that, I'll send an invite.

Thanks!

**Comment by zenorocha** [comment]
> Related: https://github.com/dracula/dracula-theme/issues/509

**Comment by michaelcaxias** [comment]
Now the **github repository** is adapted to the **Dracula Template**. [Check it out](https://github.com/michaelcaxias/mysql-workbench-dracula-theme)

**Comment by zenorocha** [comment]
Awesome! I just sent you an invite, we're ready to transfer ;)

**Comment by michaelcaxias** [comment]
Very nice! I accepted the organization's invitation =)

**Comment by zenorocha** [comment]
You can transfer the repo now: https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-user-account

**Comment by michaelcaxias** [comment]
The transfer was successful! https://github.com/dracula/mysql-workbench

**Comment by zenorocha** [comment]
https://draculatheme.com/mysql-workbench :)
