### ISSUE TITLE
New Delphi/RAD Studio Theme

### ISSUE THREAD

**Issue by RRUZ** [dracula/dracula-theme#658]
I've made a theme based on Dracula Theme for Delphi.

[Theme's link here](https://github.com/RRUZ/delphi-dracula)

**Comment by zenorocha** [comment]
Great stuff @RRUZ! I just sent you an invite to join the organization.

Once you accept it, you'll be able to transfer the repo and I'll take care of adding it to the site.

Thanks for building this! 🎉

**Comment by RRUZ** [comment]
Thank you @zenorocha I just have transferred the repo to the organization.

**Comment by zenorocha** [comment]
It's live now!

https://draculatheme.com/delphi 🎉
