### ISSUE TITLE
New theme for FlorisBoard

### ISSUE THREAD

**Issue by Venem** [dracula/dracula-theme#659]
## FlorisBoard
Since there were not any really good themes available, I turned to trusty old Count Dracula and decided to design a new theme.

Link here: https://github.com/Venem/dracula-florisboard

Thanks in advance

**Comment by zenorocha** [comment]
Looks great @Venem! I just sent you an invite to join the organization.

Once you accept it, you'll be able to transfer the repo and I'll take care of adding it to the site.

Thanks for building this! 🎉

**Comment by Venem** [comment]
I have transferred the repo! Thank you

**Comment by zenorocha** [comment]
https://draculatheme.com/florisboard 💥
