### ISSUE TITLE
GitKraken Theme Request

### ISSUE THREAD

**Issue by arunpkqt** [dracula/dracula-theme#660]
With the latest relaese of GitKraken they introduced themening. It would be nice to get the Dracula shining there as well :) 

https://support.gitkraken.com/start-here/themes/

**Comment by Anselmoo** [comment]
Maybe this one, would be a good starting point? [https://github.com/Anselmoo/gitkraken/](https://github.com/Anselmoo/gitkraken/)

**Comment by Anselmoo** [comment]
> I'm getting a 404 error page, is this repo private?

@zenorocha sorry, was still private. Please, try again

**Comment by zenorocha** [comment]
That looks awesome, I love it!

I just sent you an invite to join the organization.

Once you accept it, you'll be able to transfer the repo and I'll take care of adding it to the site.

Thanks for building this! 🎉

**Comment by Anselmoo** [comment]
I have transferred the repo! Thank you

**Comment by arunpkqt** [comment]
@Anselmoo Didn't know that it already exist. That looks nice. Thank you :) 

@zenorocha This link https://draculatheme.com/gitkraken doesn't seem to work. I get the error: 505

**Comment by zenorocha** [comment]
It's live now ;)
