### ISSUE TITLE
Add Scrivener theme

### ISSUE THREAD

**Issue by ayushpokh** [dracula/dracula-theme#661]
## New Theme?

We would love to support all code editors out there, but we need your help to accomplish that. Feel free to create a new theme based on our [color palette](https://github.com/dracula/dracula-theme#color-palette).

## Existing Theme?

Find the appropriate repository on the [Dracula organization](https://github.com/dracula). This is just the umbrella place where we store all themes.

And remember - consider fixing the issue yourself. That's the best way to contribute ;)

**Comment by zenorocha** [comment]
Great @ayushpokh! I just sent you an invite to join the organization.

Once you accept it, you'll be able to transfer the repo and I'll take care of adding it to the site.

Thanks for building this! 🎉

**Comment by ayushpokh** [comment]
Thank you! I saw that. I'll transfer the repo.

**Comment by zenorocha** [comment]
@ayushpokh looks like you forgot to add the installation instructions on the [INSTALL.md[(https://github.com/dracula/scrivener/blob/master/INSTALL.md) file.

Can you update? We need that before adding to the website.

**Comment by luxonauta** [comment]
I checked here that the changes have already been made, and I will proceed with including them. 🧑🏻‍🚀

**Comment by luxonauta** [comment]
It's 🧟‍♂️ a-live: https://draculatheme.com/scrivener
