### ISSUE TITLE
Add bobthefish theme

### ISSUE THREAD

**Issue by zenorocha** [dracula/dracula-theme#662]
https://github.com/oh-my-fish/theme-bobthefish

**Comment by Trollwut** [comment]
Don't know what has been done yet, but a few months ago I forked this repo and used Dracula colors:

https://github.com/Trollwut/theme-bobthefish

Bear in mind that it is a few commits behind, so one might look over that.

**Comment by zenorocha** [comment]
Looks like they already have a dracula theme built-in. Can you confirm?

https://github.com/dracula/bobthefish/blob/master/INSTALL.md

**Comment by zenorocha** [comment]
https://draculatheme.com/bobthefish

**Comment by Trollwut** [comment]
did just a quick test on Manjaro Linux and also WSL with Pengwin.

removed my own configs and just did two things:

1. `omf install bobthefish`
2. create a `.config/fish/config.fish` with content: `set -g theme_color_scheme dracula`

Then I just `cd` into a random git repository and for me it worked as intended :)
