### ISSUE TITLE
Minecraft UI Resource Pack [Help needed + Discussion]

### ISSUE THREAD

**Issue by Venem** [dracula/dracula-theme#664]
I have recently been working on a Dracula theme for Minecraft. This is quite a slow and repetitive task and I'm not sure about the efficiency and/or quality of what I have produced so far. 

The theme is based on the VanillaTweaks Dark Mode pack (https://vanillatweaks.net/picker/resource-packs/)

Currently I have been using the HSL Colour mode on the Bucket in GIMP to individually fill every part of the UI textures but, again, I am concerned about how true it actually is to the Dracula colours. 

I have very little experience working with actual images and colouring in GIMP so any help would be appreciated. The primary thing I am looking into at the moment is the logistics of the colour guidlines and correctly implementing them into Minecraft.

Thanks

**Comment by kjharcombe** [comment]
@Venem I might be able to help you with this. I'm quite comfortable working with GIMP and colouring. Feel free to give me a bell by email 😃

**Comment by Venem** [comment]
Thanks! I'll send you an email

For anyone else interested, I forgot to mention that the project is located at https://github.com/dracula/minecraft

**Comment by luxonauta** [comment]
I believe the project has already been transferred and is ready to be listed on the website so I will close this Issue. 🧱
