### ISSUE TITLE
Dracula theme for Gajim

### ISSUE THREAD

**Issue by rickylinden** [dracula/dracula-theme#665]
## Dracula theme for Gajim

Available here https://github.com/rickylinden/gajim

Please let me know if I missed anything.

**Comment by zenorocha** [comment]
Awesome stuff @rickylinden!

I just sent you an invite to join the organization.

Once you accept it, you'll be able to transfer the repo and I'll take care of adding it to the site.

Thanks for building this! 🎉

**Comment by rickylinden** [comment]
Thank you, I have transferred the repo now.

**Comment by zenorocha** [comment]
It's live now, thanks @rickylinden!
https://draculatheme.com/gajim 🎉
