### ISSUE TITLE
Add Warp page

### ISSUE THREAD

**Issue by zenorocha** [dracula/dracula-theme#669]
[Warp](https://www.warp.dev/) comes with a built-in Dracula theme, so we could create a page to display it.

![image](https://user-images.githubusercontent.com/398893/148622491-9ab29944-4f6b-41ad-890c-aa28ae957a37.png)

**Comment by zenorocha** [comment]
https://draculatheme.com/warp 🎉 

Thanks @luxonauta for making your first pull request!

**Comment by luxonauta** [comment]
Super happy to contribute to this project! 😁
