### ISSUE TITLE
New Theme: Dracula for Wikipedia

### ISSUE THREAD

**Issue by wasi-master** [dracula/dracula-theme#675]
So I've created a Dracula theme for the Wikipedia website.

![Screenshot](https://github.com/wasi-master/wikipedia/raw/master/screenshots/screenshot.png)

**Github repository**: https://github.com/wasi-master/wikipedia
**Installation instructions**: https://github.com/wasi-master/wikipedia/blob/master/INSTALL.md
[![Install directly with Stylus](https://img.shields.io/badge/Install%20directly%20with-Stylus-00adad.svg)](https://raw.githubusercontent.com/wasi-master/wikipedia/master/wikipedia.user.css)
### Notes

I've made sure it works on as many pages as possible so users don't have to disable the theme to view a page. I've tested it on a lot of pages and made sure it works for the elements in those pages.

The theme is based on CSS selectors so if Wikipedia changes some classes then it may break but I use Wikipedia every day so I'll be sure to keep it updated.

**Comment by wasi-master** [comment]
Now that I think about it, this doesn't really make much sense since this can be achieved with dark theme extensions, but with this, the colors are more true to the Dracula theme. and other colors such as red and green are from the Dracula theme. I guess it's up to @zenorocha whether he wants it or not

**Comment by wasi-master** [comment]
I think I'll just close this and make a Dracula theme for something more meaningful instead

**Comment by zenorocha** [comment]
https://draculatheme.com/starship 🚀 🚀 🚀
