### ISSUE TITLE
New theme for Code::Blocks

### ISSUE THREAD

**Issue by wasi-master** [dracula/dracula-theme#676]
### A dracula theme for [Code::Blocks](https://codeblocks.org)

**Repository:** https://github.com/wasi-master/codeblocks
**Installation:** https://github.com/wasi-master/codeblocks/blob/master/INSTALL.md

Closes https://github.com/dracula/dracula-theme/issues/620

**Comment by zenorocha** [comment]
Great work @wasi-master! 

I just sent you an invite to join the organization.

I also cloned your repo to the dracula organization, so you can go ahead and delete yours:
* https://github.com/dracula/codeblocks
* https://github.com/wasi-master/codeblocks

Thanks for building this! 🎉

**Comment by wasi-master** [comment]
Thanks, @zenorocha!

I've accepted the invitation and am now able to manage the https://github.com/dracula/codeblocks repo.
I've also archived my repo and added a notice saying the project has been moved to https://github.com/dracula/codeblocks

Once draculatheme.com/codeblocks is up and running I'll edit https://github.com/dracula/codeblocks/blob/master/INSTALL.md with the image links being on draculatheme.com/codeblocks.

Cheers!

**Comment by zenorocha** [comment]
https://draculatheme.com/codeblocks
