### ISSUE TITLE
New theme for: Starship - Cross Shell Prompt

### ISSUE THREAD

**Issue by b3vis** [dracula/dracula-theme#677]
Hi There,

I've whipped up a repo to share my starship prompt dracula theme which can be found here: https://github.com/b3vis/dracula-starship

I try to dracula theme everything I can and this shell prompt didn't have a dracula theme. So what better way to give back to the theme I love the most than creating the theme for it myself!

Any questions please let me know.

Kind regards,
b3vis

**Comment by luxonauta** [comment]
Hi @b3vis, great job! 😁

I just sent you an invitation to join the organization.

I also cloned [your repository](https://github.com/b3vis/dracula-starship) for [Dracula's organization](https://github.com/dracula), so you can go ahead and delete or archive yours!

- [New repository in Dracula](https://github.com/dracula/starship)

Thanks so much for building this! 🎉

**Comment by b3vis** [comment]
Hi @luxonauta,

Thanks! I'll do that now, I've accepted the invitation too.

Kind regards,
b3vis

**Comment by b3vis** [comment]
Just to note @luxonauta, this link 500's - https://draculatheme.com/starship I take it I just need to wait for any CI/CD to finish  and it will be available on the main website?

**Comment by zenorocha** [comment]
https://draculatheme.com/starship
