### ISSUE TITLE
Add SerenityOS theme

### ISSUE THREAD

**Issue by zenorocha** [dracula/dracula-theme#679]
https://github.com/SerenityOS/serenity/commit/e3aa7723fa0ca7fe77aae4aef470904319868492

@hansejo @bgianfo could you send a screenshot and steps on how to enable this theme on SerenityOS? This would allow us to add a page on https://draculatheme.com ;)

**Comment by bgianfo** [comment]
There is a screen shot with the settings page in the PR https://github.com/SerenityOS/serenity/pull/12174

**Comment by zenorocha** [comment]
Thanks @bgianfo!

Does this look accurate to you?

https://github.com/dracula/serenityos/blob/master/INSTALL.md 
https://github.com/dracula/serenityos/blob/master/screenshot.png

I just sent you an invite to the organization @hansejo ;)

**Comment by zenorocha** [comment]
Added to the website: https://github.com/dracula/draculatheme.com/commit/271df8939f2ee6b9950a82e9820daec466f323a2

Deploy pending.

**Comment by bgianfo** [comment]
Looks correct to me!

**Comment by hansejo** [comment]
Thank you :). I've accepted the invite. Feel free to push to the website.

**Comment by zenorocha** [comment]
Sweet! We're live now ;)

https://draculatheme.com/serenityos 🎉
