### ISSUE TITLE
Theme for stackoveflow

### ISSUE THREAD

**Issue by wasi-master** [dracula/dracula-theme#680]
## New Theme?

So I was wondering if a theme for StackOverflow was possible or not and then I thought about why don't I make one myself.
So I tried and made this theme, [link](https://gist.github.com/wasi-master/9c98fbe0e354d29f71cd39f7f38039c5/raw/1b74fcf255dc6e9d621167515ee7aca3245a1ce1/dracula-stackoverflow.user.css)

This is a userstyle so it shall be installed with the [stylus browser extension](https://add0n.com/stylus.html).

This works on the same principle as the Dracula for GitHub theme, as in using custom CSS to modify the variables the site uses for color. and a few selectors for QOL. 

Now I did not make a template repo yet since I'll just wait to hear what @zenorocha thinks about adding this to dracula and then go on from there

P.S: I am already a member of the Dracula organization and maintainer of [dracula/codeblocks](https://github.com/dracula/codeblocks)

**Comment by wasi-master** [comment]
Forgot to add a screenshot. here it is

![image](https://user-images.githubusercontent.com/63045920/151791846-da8a4aae-015d-4e4b-b3ea-d94772bd08dd.png)
![image](https://user-images.githubusercontent.com/63045920/151792240-3b589962-98d2-4b16-8408-911bf8d178ed.png)

**Comment by wasi-master** [comment]
And about keeping the theme updated in case of a CSS change, I am pretty active on StackOverflow and I try to help as many people as possible. So if something needs to be fixed I'll be notified within a day or so :)

**Comment by wasi-master** [comment]
I've also added color themes now, (red, green, cyan, purple, orange, pink, red, yellow, comment, white)

![image](https://i.imgur.com/EWpMHqO.png)

**Comment by wasi-master** [comment]
Since stackoverflow also uses a code editor (codemirror) this theme also fixes that,

## Before
![image](https://user-images.githubusercontent.com/63045920/151974027-97b9be90-3b36-48d8-818c-018dbfa22deb.png)

## After
![image](https://user-images.githubusercontent.com/63045920/151974045-47a2fd8a-eaac-4efc-afd2-a8f4cc6a925c.png)

**Comment by wasi-master** [comment]
So @zenorocha what do you think about this? could this be added? If yes then I'll make a template repo for this

**Comment by wasi-master** [comment]
So far I've been using the theme extensively and I've found no issues and it is very pleasing for me

**Comment by zenorocha** [comment]
This looks great @wasi-master, I love it!

You can go ahead and create that template repo so we can showcase to the rest of the Dracula community ;)

**Comment by wasi-master** [comment]
@zenorocha I've created the template repo in [dracula/stackoverflow](https://github.com/dracula/stackoverflow).

**Comment by zenorocha** [comment]
https://draculatheme.com/stackoverflow 💥 

I love the level of detail that you went on the DOCUMENTATION.md. Amazing job!

**Comment by wasi-master** [comment]
Thanks :)
