### ISSUE TITLE
Theme for ITFY forum

### ISSUE THREAD

**Issue by DaSh-More** [dracula/dracula-theme#682]
Theme for code
![](https://raw.githubusercontent.com/DaSh-More/ITFY/master/screenshot.png)
https://github.com/DaSh-More/ITFY

**Comment by luxonauta** [comment]
Hey, very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/DaSh-More/ITFY)
- [New repository.](https://github.com/dracula/itfy)

Thanks for building this! 🎉

**Comment by DaSh-More** [comment]
Glad to join you!

**Comment by zenorocha** [comment]
https://draculatheme.com/itfy 🎉 🎉 🎉
