### ISSUE TITLE
Postbox Theme

### ISSUE THREAD

**Issue by arukshpatel** [dracula/dracula-theme#685]
## Postbox Email Client Theme

Hello,
I created a postbox theme using Dracula Color Palette. The screenshot does not clearly portray all the colors but after utilization, users surely can see all the colors being used.

This is the [link to my git repo](https://github.com/arukshpatel/Dracula_Postbox.git).

**Comment by luxonauta** [comment]
Hey, very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/arukshpatel/Dracula_Postbox)
- [New repository.](https://github.com/dracula/postbox)

Thanks for building this! 🎉

**Comment by zenorocha** [comment]
It's live on the website now! https://draculatheme.com/postbox

@arukshpatel you can go ahead and remove your repository now.

Congrats on this new theme 🎉 🎉 🎉
