### ISSUE TITLE
New theme: WezTerm

### ISSUE THREAD

**Issue by timescam** [dracula/dracula-theme#686]
# Dracula for [WezTerm](https://wezfurlong.org/wezterm)

![screenshot](https://user-images.githubusercontent.com/45168541/152924000-4fb6a189-533d-47d7-93e1-6efda85ee1f5.png)

Repo: https://github.com/timescam/wezterm

**Comment by luxonauta** [comment]
Hey, very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/timescam/wezterm)
- [New repository.](https://github.com/dracula/wezterm)

Thanks for building this! 🎉

**Comment by timescam** [comment]
already in the org before,
archived the original repo

**Comment by zenorocha** [comment]
It's live now! https://draculatheme.com/wezterm 🎉
