### ISSUE TITLE
Dracula Theme for Cider Music

### ISSUE THREAD

**Issue by Monochromish** [dracula/dracula-theme#687]
## Dracula Theme for [Cider Music](https://cider.sh/)

I've made a theme for Cider Music Client based on [Dracula Theme](https://draculatheme.com/contribute)

![image](https://user-images.githubusercontent.com/79590499/153705954-161b0387-6fc2-45be-a337-da5b8fbee265.png)

=> [Link to Repository](https://github.com/Monochromish/Dracula-Cider-Music-Theme) <=

Thank You!

**Comment by Monochromish** [comment]
Hi @luxonauta, just wanted to inform you that I have updated the [README](https://github.com/Monochromish/Dracula-Cider-Music-Theme/blob/main/README.md) in the official repository. Thank you!

**Comment by luxonauta** [comment]
Hey, very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/Monochromish/Dracula-Cider-Music-Theme)
- [New repository.](https://github.com/dracula/cider)

Thanks for building this! 🎉

**Comment by luxonauta** [comment]
There are some things we need to do! 😅

First, we need the repository to follow [this standard Dracula Theme template](https://github.com/dracula/template); this way, we will be able to move to the next step, the publication on the site.

Let me know if something isn't possible or if you have any questions! 🙂

**Comment by Monochromish** [comment]
Okay no problem; I'll try to match the template repository and I'll keep you updated!

**Comment by Monochromish** [comment]
Hi @luxonauta!
I've updated the repository and have added a screenshot of the theme to it, but there's not much I can change in the README since the Markdown to HTML parser that Cider currently has is not perfect. If I use a markdown table to display the collaborator(s), it looks broken in Cider. I've made a separate markdown file for the collaborators' table and added a redirect hyperlink to the README as well.
Is it still possible to publish this theme on the website? 

Thank you and sorry for the inconvenience!

**Comment by zenorocha** [comment]
It's live now: https://github.com/dracula/cider 🎉 

I had to make some adjustments in order for the website to be autogenerated:
https://github.com/dracula/cider/commit/308e67cb6151a02a1b917038c54f957445bab912

Awesome job @Monochromish!
