### ISSUE TITLE
Dracula theme for phpMyAdmin

### ISSUE THREAD

**Issue by sandenbergmelo** [dracula/dracula-theme#688]
Dracula theme for phpMyAdmin would be nice.

**Comment by cnsair** [comment]
For WAMP as a whole

**Comment by zenorocha** [comment]
That would be great!

Here are some good resources:
* https://github.com/phpmyadmin/themes
* https://www.phpmyadmin.net/themes

Do you want to give it a shot @sandenbergmelo?

**Comment by zeronegithub** [comment]
Dracula Theme for TikTok
