### ISSUE TITLE
GitKraken

### ISSUE THREAD

**Issue by JTeeuwissen** [dracula/dracula-theme#690]
# GitKraken

[https://github.com/JTeeuwissen/GitKraken](https://github.com/JTeeuwissen/GitKraken)

![screenshot](https://user-images.githubusercontent.com/15076530/154493282-62e4b4f2-95b7-4a5d-805e-1f700069d4f6.png)

**Comment by zenorocha** [comment]
For future reference: https://draculatheme.com/gitkraken
