### ISSUE TITLE
[New Dracula Theme] Git CLI

### ISSUE THREAD

**Issue by revagomes** [dracula/dracula-theme#691]
Hello! 

I am working on a new Dracula theme for git-cli. 

Here is the GH page: 
https://revagomes.github.io/git-cli/

I would like to know your thoughts and start the process of submitting this one to Dracula themes list.

**Comment by zenorocha** [comment]
Hey @revagomes,

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/revagomes/git-cli)
- [New repository.](https://github.com/dracula/git)

You can check the live page here:
https://draculatheme.com/git

Thanks for building this! 🎉
