### ISSUE TITLE
Dracula Theme for JDownloader2

### ISSUE THREAD

**Issue by ixanza** [dracula/dracula-theme#692]
## New Theme?

JDownloader2 has a "FLATAF_DRACULA" User Interface Theme but that doesn't really do anything except set some of the classes to dark.
I modified the color schemes to make sort of a dracula theme using the color schemes provided

https://github.com/ixanza/jdownloader2

**Comment by zenorocha** [comment]
Hey @ixanza,

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/ixanza/jdownloader2)
- [New repository.](https://github.com/dracula/jdownloader2)

You can check the live page here:
https://draculatheme.com/jdownloader2

Thanks for building this! 🎉
