### ISSUE TITLE
Dracula theme for Zellij

### ISSUE THREAD

**Issue by welcoMattic** [dracula/dracula-theme#695]
I've created a new theme for [Zellij](https://zellij.dev). It's a terminal multiplexer (see it as a modern tmux).

[https://github.com/welcoMattic/zellij](https://github.com/welcoMattic/zellij)

Let me know if I missed something :)

**Comment by zenorocha** [comment]
Hey @welcoMattic,

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/welcoMattic/zellij)
- [New repository.](https://github.com/dracula/zellij)

You can check the live page here:
https://draculatheme.com/zellij

Thanks for building this! 🎉
