### ISSUE TITLE
Dracula for Roblox Studio (WIP)

### ISSUE THREAD

**Issue by wasi-master** [dracula/dracula-theme#697]
I am opening this issue for a reminder for me to create a dracula theme for roblox studio.

I've researched a bit and found [this twitter post](https://twitter.com/SyntaxE3rr/status/1366524456407982080?t=fWAkG07CaZi-xifH5C-s6g&s=19) and I am hoping to implement that with a template repo with instructions

### About Roblox Studio
Roblox is a very popular kids' game that is basically like a place where people can make games and play games created by others. Roblox itself is not a playable game. So people need to create games inside roblox using roblox's custom IDE called Roblox Studio. Roblox games are made in the Lua scripting language and Roblox Studio has full support for that including syntax highlighting. 

I do not play roblox but my brother does, and I saw that he was making a game, and saw some code. I looked closely and figured it was using the one dark theme so I went into the settings to see what themes are available. It looks like by default, monokai and one dark are available. So I want to add a dracula theme to the mix

**Comment by wasi-master** [comment]
So I've made the theme

![image](https://user-images.githubusercontent.com/63045920/157095533-ce61c375-110e-46ec-b831-f687c7997124.png)


But the sad thing is that roblox doesn't have a built-in method of sharing themes. So people would have to use plugins. I'll see what I can do!

**Comment by luxonauta** [comment]
Very lovely the intention to create the theme and contribute, but this is not the place for a reminder; it ends up disrupting our organization a bit, so I'll be closing the Issue! 😅

**Comment by wasi-master** [comment]
Yeah I can see that
