### ISSUE TITLE
New theme for Vortex Mod Manager

### ISSUE THREAD

**Issue by jaiden-d** [dracula/dracula-theme#698]
Hey all, back again with a new theme!

Just created this one for the Vortex Mod Manager super quick - [jaiden-d/vortex-dracula](https://github.com/jaiden-d/vortex-dracula).

Would have made it directly in the org but wanted to go through the official channels first just in case, let me know what you think!

![Preview](https://user-images.githubusercontent.com/2781577/159739494-13464a43-0705-4f8d-96e3-eeab6fd62bfd.png)

**Comment by luxonauta** [comment]
Hey, very cool! ✨

I just sent you an invitation to join the new team for this one.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/jaiden-d/vortex-dracula)
- [New repository.](https://github.com/dracula/vortex-mod-manager)

Thanks for building this! 🎉

**Comment by zenorocha** [comment]
The theme is finally live: https://draculatheme.com/vortex-mod-manager 🎉 

Thanks @jaiden-d!
