### ISSUE TITLE
New theme: GNU dircolors (ls etc color configurator)

### ISSUE THREAD

**Issue by scop** [dracula/dracula-theme#699]
I added a theme for [`dircolors`](https://www.gnu.org/software/coreutils/manual/html_node/dircolors-invocation.html#dircolors-invocation), the thing in GNU coreutils that generates `LS_COLORS` env var that GNU `ls` and some other related tools use to colorize their output.

https://github.com/scop/dracula-dircolors

I should probably delete the `sample/` dir that the template brought in as I suppose it has no use in this theme.

**Comment by luxonauta** [comment]
Hey, very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/scop/dracula-dircolors)
- [New repository.](https://github.com/dracula/dircolors)

Thanks for building this! 🎉

**Comment by scop** [comment]
Nice, removed mine, removed unneeded samples, and synced with new changes that I contributed to coreutils upstream.

I don't see this theme yet at https://draculatheme.com, and https://draculatheme.com/dircolors gives a 500. Anything I can do to help fix that?

**Comment by luxonauta** [comment]
Nice! Now I will be adding it, and soon it will be online on the site! ✨

**Comment by zenorocha** [comment]
It's live now https://draculatheme.com/dircolors ;)
