### ISSUE TITLE
New Theme: Oh My Posh 💅

### ISSUE THREAD

**Issue by Gary-H9** [dracula/dracula-theme#701]
## New Theme: Oh My Posh 💅 

Hello I've created a new theme for [Oh My Posh](https://ohmyposh.dev/). This has been merged into the Oh My Posh themes as you can see [here](https://ohmyposh.dev/docs/themes#dracula). 

I'm creating this issue to see if [this repository](https://github.com/Gary-H9/dracula-oh-my-posh) which I've created is suitable to be included in the dracula project. 🧛‍♂️

Initially I began writing a lot of detail in INSTALL.md but since Oh My Posh can be used on multiple OS's and installed in multiple manners that it was best to back off to the Oh My Posh [docs](https://ohmyposh.dev/docs). 

Any feedback appreciated. 👋

**Comment by zenorocha** [comment]
Hey @Gary-H9,

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository](https://github.com/Gary-H9/dracula-oh-my-posh)
- [New repository](https://github.com/dracula/oh-my-posh)

You can check the live page here:
https://draculatheme.com/oh-my-posh

Thanks for building this! 🎉

**Comment by Gary-H9** [comment]
HI @zenorocha, thank you for accepting this submission, I've accepted the invitation to the organisation. 😊
