### ISSUE TITLE
New Theme for Clone Hero

### ISSUE THREAD

**Issue by ItzSwirlz** [dracula/dracula-theme#703]
Ready for transfer!

https://github.com/ItzSwirlz/dracula-Clone-Hero

**Comment by luxonauta** [comment]
Hey, very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/ItzSwirlz/dracula-Clone-Hero)
- [New repository.](https://github.com/dracula/clone-hero)

Thanks for building this! 🎉

**Comment by ItzSwirlz** [comment]
Thanks for checking in! (And for the open arms, go open source!)

All looks good! Just had to fix the git repo URL in INSTALL.MD.

I'll leave this issue open, and it can be closed when the submodule is added to the repo. Cheers \o/

**Comment by ItzSwirlz** [comment]
Fixed in commit https://github.com/dracula/dracula-theme/commit/bc32d92e1e5c11b8ac57485f2401ff7cfc147d78

**Comment by zenorocha** [comment]
It's finally live: https://draculatheme.com/clone-hero

Thanks @ItzSwirlz!
