### ISSUE TITLE
New theme for HyperX NGNUITY

### ISSUE THREAD

**Issue by eduardovilke** [dracula/dracula-theme#704]
## New Theme

Theme created and available here: https://github.com/eduardovilke/dracula-ngenuity

**Comment by luxonauta** [comment]
Hey, very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/eduardovilke/dracula-ngenuity)
- [New repository.](https://github.com/dracula/ngenuity)

Thanks for building this! 🎉

**Comment by zenorocha** [comment]
It's live now: https://draculatheme.com/ngenuity

Thanks @eduardovilke!
