### ISSUE TITLE
Homebrew installers

### ISSUE THREAD

**Issue by danielbayley** [dracula/dracula-theme#705]
See: https://github.com/danielbayley/homebrew-install

@zenorocha Happy to transfer this repo to the organization…

**Comment by luxonauta** [comment]
Hey, very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/danielbayley/homebrew-install)
- [New repository.](https://github.com/dracula/homebrew-install)

Thanks for building this! 🎉

**Comment by luxonauta** [comment]
I will leave this issue open and close it when the submodule is added 😅
