### ISSUE TITLE
New Theme for CodePen.io

### ISSUE THREAD

**Issue by DaSh-More** [dracula/dracula-theme#706]
[CodePen.io](https://codepen.io) is a fairly popular site for site layout, since I didn't find a dracula theme for it (which I was surprised at), I created it

![screenshot](https://user-images.githubusercontent.com/52647986/163253882-213fab6b-1df8-4e08-bcd5-29278a6b064a.png)

https://github.com/DaSh-More/CodePen

**Comment by zenorocha** [comment]
It's finally live: https://draculatheme.com/codepen

Thanks @DaSh-More!
