### ISSUE TITLE
New Theme for macOS native Color Picker

### ISSUE THREAD

**Issue by danielbayley** [dracula/dracula-theme#707]
@zenorocha See: https://github.com/danielbayley/dracula-color-picker

![img](https://github.com/danielbayley/dracula-color-picker/raw/main/screenshot.png)

**Comment by luxonauta** [comment]
Hey, very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/danielbayley/dracula-color-picker)
- [New repository.](https://github.com/dracula/macos-color-picker)

Thanks for building this! 🎉

**Comment by zenorocha** [comment]
It's finally live: https://draculatheme.com/macos-color-picker

Thanks @danielbayley!
