### ISSUE TITLE
dracula/psychopy

### ISSUE THREAD

**Issue by alexchaichan** [dracula/dracula-theme#708]
## New Theme

Hey Guys, 

I've created a theme for [PsychoPy](https://github.com/psychopy/psychopy). 

I would be happy if you publish it

https://github.com/alexchaichan/psychopy

Best regards

Alex

**Comment by luxonauta** [comment]
Hey, very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/alexchaichan/psychopy)
- [New repository.](https://github.com/dracula/psychopy)

Thanks for building this! 🎉

**Comment by zenorocha** [comment]
It's finally live: https://draculatheme.com/psychopy

Thanks @alexchaichan!

**Comment by alexchaichan** [comment]
Nice, thanks you guys aswell for posting.
Love the icon !
