### ISSUE TITLE
New theme for i3lock-color

### ISSUE THREAD

**Issue by fccapria** [dracula/dracula-theme#713]
## New Theme?

We would love to support all code editors out there, but we need your help to accomplish that. Feel free to create a new theme based on our [color palette](https://github.com/dracula/dracula-theme#color-palette).

Hi, I recently created an i3lock-color theme based on Dracula theme. Check if it can be helpful! :)

https://github.com/fccapria/i3lock-color-dracula-theme

**Comment by luxonauta** [comment]
Hey, very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/fccapria/i3lock-color-dracula-theme)
- [New repository.](https://github.com/dracula/i3lock)

Thanks for building this! 🎉

**Comment by fccapria** [comment]
Hey! Thanks a lot, I'm glad you like it!
Anyway I saw the invitation and just accepted it, I'm very happy to be part of Dracula :)

**Comment by luxonauta** [comment]
Until the theme is listed on the website, we will leave this issue open because through it, I will let you know.

**Comment by luxonauta** [comment]
It's 🧟‍♂️ a-live: https://draculatheme.com/i3lock-color
