### ISSUE TITLE
A Dracula Pro request

### ISSUE THREAD

**Issue by alexeygrant** [dracula/dracula-theme#716]
I've struggled to find any support channel for Dracula Pro, so I'm writing here. If it's an inappropriate channel, please point me in the right direction.
My question if there's a way to change/tweak line numbers colors in Dark Pro themes in  JetBrains IDE It's very low contrast, and much lower compared to VSCode.

### VSCode
![image](https://user-images.githubusercontent.com/10379605/166621506-04af1710-e8e9-4a7f-a817-d4592cc15afd.png)

### JetBrain IDE
![image](https://user-images.githubusercontent.com/10379605/166621706-1d579e4f-0c9d-4d46-a125-e5bb10f43c85.png)

I'm happy to tweak it myself if you tell me how. Thank you.

**Comment by luxonauta** [comment]
Hi @alexeygrant 👋🏻, the best place to get help is on our [Discord](https://draculatheme.com/discord-invite)!

There has a channel dedicated to **Dracula Pro**, we are always attentive there, and other users are always willing to help! 😊

This low-contrast issue is interesting; I'll be investigating! 🔥
