### ISSUE TITLE
Tridactyl Theme

### ISSUE THREAD

**Issue by lonepie** [dracula/dracula-theme#717]
## New Theme

[Dracula Tridactyl](https://github.com/lonepie/dracula-tridactyl)

**Comment by raffaem** [comment]
Thanks! That looks awesome!

How long till he gets in the official repo?

**Comment by luxonauta** [comment]
Hey, very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/lonepie/dracula-tridactyl)
- [New repository.](https://github.com/dracula/tridactyl)

Thanks for building this! 🎉

**Comment by lonepie** [comment]
https://github.com/dracula/tridactyl/pull/2
