### ISSUE TITLE
New Theme - Vital Synthesizer Skin

### ISSUE THREAD

**Issue by MElemental** [dracula/dracula-theme#719]
Hello,
I have made a skin for the [Vital](https://vital.audio) Synthesizer and I would like to submit it as a new theme.
I'll gladly make any adjustments.

## Repo

https://github.com/MElemental/vital-synth

## About Vital

Vital is an Open-Source software wavetable synthesizer.
It has many features such as Microtonal and MPE support.

Vital is a visual synthesizer. See what's happening behind the scenes with animated controls, filter responses, waveforms, smooth LFOs, oscilloscopes, spectrograms and more.

All animations run at 60 frames per second and are GPU optimized which leaves your CPU to do its real job: the audio processing. 

## Editing Themes in Vital
To edit themes in vital `Ctrl+Alt+Click` on the menu button in vital, and select `Open Skin Designer`

**Comment by luxonauta** [comment]
Hey, very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/MElemental/vital-synth)
- [New repository.](https://github.com/dracula/vital)

Thanks for building this! 🎉

**Comment by MElemental** [comment]
Hi @luxonauta I thought I did accept the invitation, but I must have missed the 7 day window. Would I be able to receive another one?

**Comment by luxonauta** [comment]
No problem, I just sent you another invitation to join the organization! Check your email! 😅

**Comment by MElemental** [comment]
Wonderful, I have accepted it!
