### ISSUE TITLE
Dracula for lsd

### ISSUE THREAD

**Issue by urrickhunt** [dracula/dracula-theme#720]
new theme yay 

https://github.com/urrickhunt/Dracula-for-lsd

**Comment by luxonauta** [comment]
Hey, very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/urrickhunt/Dracula-for-lsd)
- [New repository.](https://github.com/dracula/lsd)

Thanks for building this! 🎉
