### ISSUE TITLE
Dracula for WP

### ISSUE THREAD

**Issue by bhadaway** [dracula/dracula-theme#721]
New Submission: https://github.com/bhadaway/wp

**Comment by bhadaway** [comment]
WordPress is highly customizable and highly themeable. That existing plugin themes the WP back-end admin UI only; my plugin themes the front-end code examples; they have a completely separate purpose. In fact, with both our plugins, there's still 2-3 other places left unthemed that could use a solution.

If you're thinking "Well then, there should be just one plugin that has toggleable options to theme all possible areas..." that's a very tall order, plus there would also need to be a theme, which is different from a plugin (I may have just confused you there, but just take my word for it).

There's:

- The admin UI (what the existing plugin themes)
- The admin editor UI (not yet themed)
- The front-end theme (not yet themed)
- The front-end code example display (what my plugin themes)
- There might be something else I'm forgetting

**Comment by luxonauta** [comment]
Oh yes, I understand. 😅

Okay, do you have a suggestion on how we can name this addition of yours, as the name _WordPress_ has already been taken; _WP_, I don't think it's very intuitive. 😥

**Comment by bhadaway** [comment]
_WP_ is probably the best option. People that use WordPress recognize it automatically. It's an extremely common acronym, as common as CSS, PHP, HTML, JS, etc.

**Comment by luxonauta** [comment]
Thanks! 😊 Alright, so I'll proceed with the inclusion later today! 🚀

**Comment by luxonauta** [comment]
I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/bhadaway/wp)
- [New repository.](https://github.com/dracula/wp)

Thanks for building this! 🎉
