### ISSUE TITLE
New Theme for Drafts

### ISSUE THREAD

**Issue by danielbayley** [dracula/dracula-theme#728]
[Drafts](https://getdrafts.com)
Drafts Directory [published theme](https://directory.getdrafts.com/t/2Ak)

@zenorocha @luxonauta See: https://github.com/dracula/drafts

<p align="center">
  <img src="https://github.com/dracula/drafts/raw/main/screenshots/ios/edit.png" width="45%"/>
  <img src="https://github.com/dracula/drafts/raw/main/screenshots/ios/list.png" width="45%"/>
  <img src="https://github.com/dracula/drafts/raw/main/screenshots/ios/actions.png" width="45%"/>
  <img src="https://github.com/dracula/drafts/raw/main/screenshots/ios/settings.png" width="45%"/>
</p>

![Screenshot](https://github.com/dracula/drafts/raw/main/screenshots/macos.png)

**Comment by zenorocha** [comment]
That's awesome, I didn't know about Drafts, it looks great! 

https://draculatheme.com/drafts 🎉
