### ISSUE TITLE
Typo on website

### ISSUE THREAD

**Issue by SleepyMario** [dracula/dracula-theme#729]
Hiya, on https://draculatheme.com/zsh-syntax-highlighting the 'source /some/path/to/your/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh'  has an .sh extension, not .zsh. I'm not sure if this is the right place to report it, but anyway, there is this tiny error on the website.

**Comment by PoorPocketsMcNewHold** [comment]
https://github.com/dracula/zsh-syntax-highlighting

**Comment by luxonauta** [comment]
Hi @SleepyMario, I'll close this one since you opened the issue there already. Thanks for letting us know! 💜
