### ISSUE TITLE
Homer Theme

### ISSUE THREAD

**Issue by Tuetenk0pp** [dracula/dracula-theme#732]
I created a theme for Homer (the dashboard) in this repo: https://github.com/Tuetenk0pp/homer

**Comment by zenorocha** [comment]
We're live! 🎉 

https://draculatheme.com/homer
https://github.com/dracula/homer

Thanks for building this theme @Tuetenk0pp!
Feel free to remove the initial repository now.

**Comment by Tuetenk0pp** [comment]
Very nice! Thank you @zenorocha
