### ISSUE TITLE
New Theme for Blink Shell

### ISSUE THREAD

**Issue by yuys13** [dracula/dracula-theme#734]
[Blink Shell](https://blink.sh) is a terminal emulator for iOS.
Blink Shell has [dracula theme](https://github.com/blinksh/themes/blob/master/themes/Dracula.js), but the colors are different from those defined in the [Dracula Syntax Highlighting Specification](https://spec.draculatheme.com/).
So I created a theme that follows the specification.

https://github.com/yuys13/blink

**Comment by luxonauta** [comment]
Hi @yuys13 👋🏻, how cool!

Therefore, we can [open an issue](https://github.com/blinksh/themes/issues/new) in the repository where the original theme exists, so we inform the maintainers of the same. If necessary, we can create a PR with this correction! 🔥

Let me know what you think, and you can subscribe to the issue too! 😊

**Comment by yuys13** [comment]
Hi @luxonauta ,thank you for checking this issue!

I tried to create a PR in blinksh/themes but could not figure out how to create a [screenshot](https://github.com/blinksh/themes/blob/master/screenshots/dracula.png), so I will create an issue.

**Comment by yuys13** [comment]
Hi @luxonauta!
I created https://github.com/blinksh/themes/issues/32 but this PJ looks non active.
I would like to add https://github.com/yuys13/blink to this organization so that other users can use the dracula theme with blink.
Please let me know what you think.

**Comment by luxonauta** [comment]
Oh 😥, I understand.

Okay, we can proceed then. ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/yuys13/blink)
- [New repository.](https://github.com/dracula/blink-shell)

**Comment by yuys13** [comment]
Thanks for creating the blink-shell repository!
I have joined the organization and updated some URLs for the dracula organization.

**Comment by yuys13** [comment]
Thanks for adding this to draculatheme.com!
I will close the Issue.
