### ISSUE TITLE
Theme for PolyMC

### ISSUE THREAD

**Issue by Lutitious** [dracula/dracula-theme#738]
Hi there I have just written a theme for PolyMC (A qt minecraft launcher) based on your template if you would take a look its available [here](https://github.com/Lutitious/dracula-polymc/tree/master).

**Comment by Lutitious** [comment]
Any chance i can get an update on this?

**Comment by luxonauta** [comment]
Hey, very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/Lutitious/dracula-polymc)
- [New repository.](https://github.com/dracula/polymc)

Thanks for building this! 🎉

**Comment by luxonauta** [comment]
It Will soon be included; and will likely be featured in our newsletter and blog! We've waited a while to include a few at once. 🧑🏻‍🚀

**Comment by luxonauta** [comment]
Hi, the theme is already on the [site](https://draculatheme.com/polymc)! Thanks for building this! 🎃
