### ISSUE TITLE
Youtube theme

### ISSUE THREAD

**Issue by LrnzDC3696** [dracula/dracula-theme#739]
Something like this https://draculatheme.com/github but for youtube!!!
I saw 2 other repository open for this but it would be nice if the extension used is uniform instead

**Comment by luxonauta** [comment]
Hi @LrnzDC3696 👋🏻, that would be cool! Are you interested in trying to code the same?
If yes, here is the [template](https://github.com/dracula/template) to create the repository in the Dracula Theme pattern.

I'll tag this issue as a `new-theme-request`.

Thanks! 😊

**Comment by leozz37** [comment]
Hey!

I'll be creating a theme for Youtube!

**Comment by leozz37** [comment]
Just created it! #743
