### ISSUE TITLE
Contribute a theme for Pleroma FE!

### ISSUE THREAD

**Issue by asdreemurr844** [dracula/dracula-theme#740]
Hello! I created a theme for Pleroma!

https://github.com/asdreemurr844/dracula-pleroma-theme

**Comment by luxonauta** [comment]
Hey, very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/asdreemurr844/dracula-pleroma-theme)
- [New repository.](https://github.com/dracula/pleroma)

Thanks for building this! 🎉
