### ISSUE TITLE
Steam does not have the "skins" folder on MacOS?

### ISSUE THREAD

**Issue by bit-burger** [dracula/dracula-theme#742]
MacOS does not have the skins folder in this path anymore: ~/Library/Application Support/Steam/Steam.AppBundle/Steam/Contents/MacOS/skins.

Basically the whole path is valid except the last folder.

I tried adding it and then do the rest of the instructions. This however did not work

**Comment by benknoble** [comment]
This should migrate to dracula/steam (or whatever the appropriate repo name is).

**Comment by luxonauta** [comment]
Hi @bit-burger, this is a question to open in the [Steam theme repository](https://github.com/dracula/steam) so that the project maintainers can help you with your doubt. 😊 You can do this by [clicking here](https://github.com/dracula/steam/issues/new).
So I will close this issue! 😅
