### ISSUE TITLE
Youtube Theme

### ISSUE THREAD

**Issue by leozz37** [dracula/dracula-theme#743]
Add Youtube theme using Stylus!

Link for my repo [here](https://github.com/leozz37/dracula-youtube). You can check the theme [here](https://userstyles.world/style/5979/oficial-dracula-theme)!

### Home: 

<img width="1440" alt="screenshot-youtube" src="https://user-images.githubusercontent.com/38125236/182954877-b0c123c6-24f7-43a2-8474-1315acfe4ac5.png">
 
### Video: 

<img width="1440" alt="Captura de Tela 2022-08-04 às 17 30 23" src="https://user-images.githubusercontent.com/38125236/182954895-7bd80143-91ea-492b-8783-9b5e434f2c0d.png">

**Comment by LrnzDC3696** [comment]
that was fast!

**Comment by luxonauta** [comment]
Hey, very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/leozz37/dracula-youtube)
- [New repository.](https://github.com/dracula/youtube)

Thanks for building this! 🎉

**Comment by leozz37** [comment]
Awesome! Just opened a PR with the install instructions!

**Comment by luxonauta** [comment]
Thank you, the theme is already listed on the [site](https://draculatheme.com/youtube)! 🚀
