### ISSUE TITLE
Should I use your theme in my editor?

### ISSUE THREAD

**Issue by StoneCypher** [dracula/dracula-theme#744]
I like `Dracula`.  However, my use case is to build themes directly into an editor that I built, rather than to send them to someone else.

I'd like to build `Dracula` into my editor, the way I have `Penumbra` and `Solarized` and some others.  I'm not sure, in this case, if it's appropriate: you charge for your stuff.  I am uncertain if I am supporting you or pirating you.

Please clarify.  May I add Dracula to my web-based editor?  Thank you.

**Comment by benknoble** [comment]
Only the Dracula Pro themes are paid content. The regular Dracula theme is free.

**Comment by luxonauta** [comment]
Hi @StoneCypher 👋🏻

You can integrate the Dracula theme into your editor. 😅
Zeno Rocha created Dracula Theme under the MIT License; that is, you are allowed to:

- Commercial use
- Modification
- Distribution
- Private use

Just what I would ask you to [collaborate with the project](https://draculatheme.com/contribute) by adding the steps to activate it in your editor; this is also a way to **give visibility to your project**.

Now, [Dracula Pro](https://draculatheme.com/pro) is a closed-source project, and you don't have those legal permissions in this one.

I hope this clarifies your doubt. 🧛🏻

**Comment by StoneCypher** [comment]
It does. Thank you. I will try to follow your process.

I got themes working yesterday, so, probably over the next week or two.
