### ISSUE TITLE
Hacker News Theme

### ISSUE THREAD

**Issue by leozz37** [dracula/dracula-theme#745]
I created a theme for Hacker News using Stylus!

Link for my repo [here](https://github.com/leozz37/dracula-hacker-news), and you can check the theme [here](https://userstyles.world/style/6043/dracula-for-hacker-news)

![screenshot-hacker-news](https://user-images.githubusercontent.com/38125236/183821325-f3197ca1-9e32-4d70-9364-3a05e70ca0d8.png)

**Comment by luxonauta** [comment]
Hey, very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/leozz37/dracula-hacker-news)
- [New repository.](https://github.com/dracula/hacker-news)

Thanks for building this! 🎉

**Comment by leozz37** [comment]
Awesome! Just opened a PR with the install instructions!

**Comment by luxonauta** [comment]
Thank you, the theme is already listed on the [site](https://draculatheme.com/hacker-news)! 🚀
