### ISSUE TITLE
 CudaText

### ISSUE THREAD

**Issue by MetalistPavlenko** [dracula/dracula-theme#746]
I would like someone to make a theme for [CudaText](https://github.com/Alexey-T/CudaText), because i'm not good at it

**Comment by diluteoxygen** [comment]
Is this the same base for CudaText? github.com/jackdp/Dracula-CudaText

**Comment by MetalistPavlenko** [comment]
> Это та же база для CudaText? [Ссылка на сайт ](https://github.com/jackdp/Dracula-CudaText)

Yes, this is it, but the theme is different from Dracula, there are differences in syntax highlighting, maybe also in the color design of the program itself. Perhaps this is due to an outdated version of the theme itself

**Comment by MetalistPavlenko** [comment]
Here's what else I found: [SourceForge](https://sourceforge.net/projects/cudatext/files/addons/themes/theme.Darcula.zip/download) or [GitHub](https://github.com/dimon40001/cudatext-theme-darcula). But the theme is different in color, for example, it is dimmer
