### ISSUE TITLE
New Theme: Nextcloud

### ISSUE THREAD

**Issue by SIMULATAN** [dracula/dracula-theme#748]
I made a theme for [Nextcloud](https://nextcloud.com) and would be happy to get it accepted and moved. Additionally, I'm ready to maintain it until further notice.

Screenshot:
![Screenshot](https://user-images.githubusercontent.com/63104422/185686289-8a478153-c956-42f3-a2fd-5e017758cc70.png)

I'd happily implement suggestions, so please do not hesitate to give me feedback =)

Repo: [SIMULATAN/dracula-nextcloud](https://github.com/SIMULATAN/dracula-nextcloud)

**Comment by luxonauta** [comment]
Hey, very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/SIMULATAN/dracula-nextcloud)
- [New repository.](https://github.com/dracula/nextcloud)

Thanks for building this! 🎉

**Comment by SIMULATAN** [comment]
Thank you so much!

I've joined the organization and archived my repo.
Thus, this issue can be closed from my side, please let me know if I missed something or in general if there's anything I can do.

Thanks again for the quick inclusion ♥️

**Comment by luxonauta** [comment]
Super Cool! 🦇

I'll leave it open until it's live on the site, then I'll let you know here and close the Issue. 🧛🏻

**Comment by luxonauta** [comment]
Thank you, the theme is already listed on the [site](https://draculatheme.com/nextcloud)! 🚀
