### ISSUE TITLE
Border around cosmic dock Pop!_OS 22.04 LTS

### ISSUE THREAD

**Issue by sinful-mads** [dracula/dracula-theme#749]
Hello there!

![image](https://user-images.githubusercontent.com/105631567/187621536-ad637e6e-c659-404a-8ab2-13ad52cfc35c.png)
![image](https://user-images.githubusercontent.com/105631567/187623613-14c820d9-aa3f-4625-8ae3-b1ab1e9688db.png)

I have run into an issue where there is a visible border around the Cosmic Dock in Pop!_OS 22.04 LTS GTK 4 :) I have tried searching for the border settings to the dock in the css files of the gtk-4.0 theme folder, but to no avail.. Which css setting should I look at to achieve the change and remove the border? :)

**Comment by Its-Juice** [comment]
I have the exact same issue only with the gnome extension in fedora. Visually the same issue idk what's causing it

**Comment by luxonauta** [comment]
Hello, thank you very much for your interest in providing this feedback. ✨

However, this is not the correct place to do so; the proper place for this is in the project repository, where you can chat with the theme maintainers.

I believe it's the [GTK repository](https://github.com/dracula/gtk) in this case; you can open it by [clicking here](https://github.com/dracula/gtk/issues/new/choose).

**Comment by sinful-mads** [comment]
> Hello, thank you very much for your interest in providing this feedback. sparkles
> 
> However, this is not the correct place to do so; the proper place for this is in the project repository, where you can chat with the theme maintainers.
> 
> I believe it's the [GTK repository](https://github.com/dracula/gtk) in this case; you can open it by [clicking here](https://github.com/dracula/gtk/issues/new/choose).

issue has been posted here https://github.com/dracula/gtk/issues/216
