### ISSUE TITLE
New Theme : PLSQL Developer

### ISSUE THREAD

**Issue by emir-karpuz** [dracula/dracula-theme#750]
Hello Guys,

I would like to contribute my work, hope you like it, enjoy :)

https://github.com/emir-karpuz/plsql-developer-dracula-color-theme

**Comment by luxonauta** [comment]
Hi Emir 👋🏻, this is a duplicate of [another Issue](https://github.com/dracula/dracula-theme/issues/754) that we are already transferring. So I'll be closing this one. 😉
