### ISSUE TITLE
YouTube Desktop Music Player Theme

### ISSUE THREAD

**Issue by MayhemBill** [dracula/dracula-theme#751]
New theme for YTMD

https://github.com/MayhemBill/YTMD-Dracula

based on the themes from OceanicSquirrel, using Dracula palette

**Comment by luxonauta** [comment]
Hey, very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/MayhemBill/YTMD-Dracula)
- [New repository.](https://github.com/dracula/youtube-music-desktop)

Thanks for building this! 🎉

**Comment by luxonauta** [comment]
That's great to know! I'll be re-opening the Issue here because that's where I'll let you know when it's online on the website. 😅

**Comment by luxonauta** [comment]
Hi, the theme is already on the [site](https://draculatheme.com/youtube-music-desktop)! Thanks for building this! 🎃
