### ISSUE TITLE
Theme for FL Studio Mobile iPad app

### ISSUE THREAD

**Issue by powerobject** [dracula/dracula-theme#752]
## New Theme?

No, this is not a new theme submission. Since I could not find your email address, I'm submitting this request to create a Dracula theme for **FL Studio Mobile** iOS and iPadOS apps -

https://apps.apple.com/us/app/fl-studio-mobile/id432850619

As you can see from the above, FL Studio Mobile is a great mobile app but the UI is a **disaster** compared to its Desktop counterpart which is an EYE-CANDY!! Since you created Dracula themes for Ableton Live, ReNoise apps and also some iOS apps, I thought FL Studio Mobile could use some help from you good folks.

## Existing Theme?

No.

**Please create a Dracula theme for FL Studio Mobile.**

**Comment by mrhappyma** [comment]
Is it possible to create themes for iOS apps? How would this be done?

**Comment by luxonauta** [comment]
I will close this Issue for organizational purposes, as it is an old request without community proposals. 😅
