### ISSUE TITLE
New Theme: Dracula for AutoAO3App

### ISSUE THREAD

**Issue by enigmalea** [dracula/dracula-theme#753]
I've coded a Stylus Dracula Theme for AutoAO3App. The app is a project which helps fans run exchanges on archiveofourown.org, but it currently doesn't have a dark mode available.

You can find the repo here: https://github.com/enigmalea/Dracula-For-AutoAO3App

**Comment by luxonauta** [comment]
Hey, very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/enigmalea/Dracula-For-AutoAO3App)
- [New repository.](https://github.com/dracula/auto-ao3-app)

Thanks for building this! 🎉

**Comment by enigmalea** [comment]
Hi there! I've archived my copy of the repo, updated my screenshots and closed the issue over on the [Dracula Org Repo](https://github.com/dracula/auto-ao3-app), and also merged the image optimization PR. Let me know if there's anything else I need to do.

**Comment by luxonauta** [comment]
Thanks! I'll include it later, and it will be on the site soon; Until then, I'll leave this Issue open! 🚀

**Comment by luxonauta** [comment]
Hi, the theme is already on the [site](https://draculatheme.com/auto-ao3-app)! Thanks for building this! 🎃
