### ISSUE TITLE
New theme: new tab Firefox/Chrome

### ISSUE THREAD

**Issue by Superredstone** [dracula/dracula-theme#755]
The old new tab theme for chromium based browsers was just an image in the center of the screen (The image don't even load anymore), so i created this extension, i will problably upload it as soon as possible on the chrome store.
https://github.com/Superredstone/Dracula-new-tab

**Comment by Superredstone** [comment]
Update: i also ported this extension to Firefox!
https://github.com/Superredstone/Dracula-new-tab-firefox

I had to change the link for the chrome extension so as not to confuse people, here's the new one: 
https://github.com/Superredstone/Dracula-new-tab-chrome

**Comment by luxonauta** [comment]
Hi 👋🏻 Patrick, how cool!

✨ The ideal would be to concentrate both in the same repository and write both instructions in the same `install.md` file, separating the method for both browsers.

Let me know if there are any impediments so that we can proceed!

Thanks so much for building this! 💖

**Comment by Superredstone** [comment]
Ok, i merged the two repos inside [https://github.com/Superredstone/dracula-new-tab](https://github.com/Superredstone/dracula-new-tab)
I also added `install.md `file as requested :D

**Comment by luxonauta** [comment]
It's 🧟 Alive: https://draculatheme.com/new-tabs

**Comment by Superredstone** [comment]
I'm so proud to contribute to Dracula Theme! 🧛
