### ISSUE TITLE
Dracula for Cava

### ISSUE THREAD

**Issue by etrigan63** [dracula/dracula-theme#757]
## New Theme?

I have created a Dracula theme for the Cava app (terminal audio visualizer) and am submitting it for your consideration.

https://github.com/etrigan63/cava.git

**Comment by luxonauta** [comment]
Hey, very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/etrigan63/cava)
- [New repository.](https://github.com/dracula/cava)

Thanks for building this! 🎉
