### ISSUE TITLE
Dracula for OpenGL Shaders

### ISSUE THREAD

**Issue by ericjeker** [dracula/dracula-theme#762]
## Dracula for OpenGL Shaders

https://github.com/ericjeker/dracula-shader

**Comment by ItzSwirlz** [comment]
You should encourage those running the Minecraft texture pack to also run this shader with OptiFine!

**Comment by luxonauta** [comment]
Hey, very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/ericjeker/dracula-shader)
- [New repository.](https://github.com/dracula/opengl-shaders)

Thanks for building this! 🎉
