### ISSUE TITLE
Dracula for novelWriter

### ISSUE THREAD

**Issue by bvout** [dracula/dracula-theme#765]
## Dracula for novelWriter

https://github.com/bvout/novelwriter

I made syntax highlighting and GUI themes for [novelWriter](https://novelwriter.io/).

**Comment by luxonauta** [comment]
Hey, very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/bvout/novelwriter)
- [New repository.](https://github.com/dracula/novel-writer)

Thanks for building this! 🎉

**Comment by luxonauta** [comment]
It's 🧟‍♂️ a-live: https://draculatheme.com/novel-writer
