### ISSUE TITLE
Dracula for Lapce

### ISSUE THREAD

**Issue by d4rkr41n** [dracula/dracula-theme#766]
Text editor project with github based theme repos similar to Atom.
[https://github.com/d4rkr41n/lapce-dracula](https://github.com/d4rkr41n/lapce-dracula)

**Comment by luxonauta** [comment]
Hey, very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/d4rkr41n/lapce-dracula)
- [New repository.](https://github.com/dracula/lapce)

Thanks for building this! 🎉
