### ISSUE TITLE
New Theme: Suckless Tabbed

### ISSUE THREAD

**Issue by SIMULATAN** [dracula/dracula-theme#767]
[Tabbed](https://tools.suckless.org/tabbed/) is a simple program by [suckless](https://suckless.org) that adds Tabbing into Xorg.

Repo: [SIMULATAN/DraculaTabbed](https://github.com/SIMULATAN/DraculaTabbed)

Screenshot:
![screenshot of tabbed with dracula](https://user-images.githubusercontent.com/63104422/199724809-7c13af8f-e89f-45d0-8faf-45f040250f96.png)
Let me know if you have a suggestion, I'm not too good at creating & applying color palettes...

I'd love to transfer the repo and continue to maintain it.

**Comment by SIMULATAN** [comment]
I'm sorry, did I forget to do something?
I archived my version and the new one is set up, but it's not on the site yet, which usually the reason for closing these issues.

**Comment by luxonauta** [comment]
Wow, how annoying that this happened; it was probably a mistake; I will do the PR for it to be added to the next wave of themes that will go up!

Sorry for the mistake! 😥
