### ISSUE TITLE
New Theme Request: Navidrome

### ISSUE THREAD

**Issue by XxAcielxX** [dracula/dracula-theme#773]
Hello,

I would like to request theme for the [Navidrome](https://github.com/navidrome/navidrome). They have their documentation on how to create new themes for it at https://www.navidrome.org/docs/developers/creating-themes/

**Regards~**

**Comment by luxonauta** [comment]
I will close this Issue for organizational purposes, as it is an old request without community proposals. 😅

**Comment by Grim73** [comment]
Seeing if this was ever picked up by another group? search lead me here.
