### ISSUE TITLE
Many elements are broken on GNOME 43

### ISSUE THREAD

**Issue by notblank00** [dracula/dracula-theme#775]
e.g.: ![image](https://user-images.githubusercontent.com/25267577/201785760-3d52cd4a-924b-48a8-ba3b-d8fb559325bb.png)

**Comment by luxonauta** [comment]
Hi 👋🏻 Igor, the ideal is to create this Issue in [its repository](https://github.com/dracula/gtk/issues/new?assignees=&labels=bug&template=bug_report.md&title=%5BBUG%5D+Write+a+suitable+title); here in this repository, we keep only questions about theme submissions, updates or suggestions for the organization.
