### ISSUE TITLE
Dracula for FL Studio 21

### ISSUE THREAD

**Issue by TanZboi** [dracula/dracula-theme#783]
link: https://github.com/TanZboi/Dracula-for-FL-Studio-21

I hope the repository is all set up as it should be! if there are any issues let me know.

FL Studio official theming is a little bit funky in places, so colour values my not be EXACTLY as listed on the website, but I got them as close as I possibly could, while making the theme suit the software and still look like dracula.

Many thanks :)

**Comment by luxonauta** [comment]
Hey, very cool! ✨

I just sent you an invitation to join the organization.

I decided to make some adjustments to fit the organization's standards. 😅

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/TanZboi/Dracula-for-FL-Studio-21)
- [New repository.](https://github.com/dracula/fl-studio-21)

Thanks for building this! 🎉

**Comment by TanZboi** [comment]
Thank you. much appreciated!

**Comment by luxonauta** [comment]
🧟‍♂️ It's alive: https://draculatheme.com/fl-studio-21
