### ISSUE TITLE
Created Repo For Dracula Theme in omg.lol

### ISSUE THREAD

**Issue by vkeerthivikram** [dracula/dracula-theme#784]
@luxonauta @zenorocha I have created a repo showing how to activate Dracula Theme in [omg.lol](https://home.omg.lol/) . Could you add it to the website!! Link to the repo: https://github.com/vkeerthivikram/omg.lol

**Comment by luxonauta** [comment]
Hey, very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/vkeerthivikram/omg.lol)
- [New repository.](https://github.com/dracula/omglol)

Thanks for building this! 🎉

**Comment by luxonauta** [comment]
🧟‍♂️ It's alive: https://draculatheme.com/omglol
