### ISSUE TITLE
New Theme for Transfer - Campfire

### ISSUE THREAD

**Issue by kjharcombe** [dracula/dracula-theme#785]
I've created a new Dracula theme for Campfire, a writing and worldbuilding app.
[Repository](https://github.com/dracula/campfire)
This has already been transferred to the Dracula org

**Comment by luxonauta** [comment]
Hey, very cool! ✨

Thanks for building this! 🎉

**Comment by luxonauta** [comment]
🧟‍♂️ It's alive: https://draculatheme.com/campfire
