### ISSUE TITLE
No way to achieve "Selection" color in 256-color palette

### ISSUE THREAD

**Issue by ryspace** [dracula/dracula-theme#786]
When it comes to theming applications that only support 256 color terminal colors, there's no way to achieve `#44475a`

![screenshot-20221212224818](https://user-images.githubusercontent.com/102413892/207221889-6cc9e05c-52a0-4e24-a726-43e1ebe2e53b.png)

This is based off the Dracula theme for Alacritty. There are a couple applications I'd love to create themes for that only allow you to assign things as `color0`, `color1`, etc., but I can't get that one color

**Comment by luxonauta** [comment]
The closest color would be ideal; if you browse our themes, some only follow our palette due to limitations like this; feel free to adapt it if needed! 🎯
