### ISSUE TITLE
 Created Repo For Dracula Theme in Fedilab

### ISSUE THREAD

**Issue by vkeerthivikram** [dracula/dracula-theme#788]
@luxonauta @zenorocha I have created a repo showing how to activate Dracula Theme in [Fedilab](https://fedilab.app/) . Could you add it to the website!! Link to the repo: https://github.com/vkeerthivikram/fedilab

**Comment by luxonauta** [comment]
Hey, very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/vkeerthivikram/fedilab)
- [New repository.](https://github.com/dracula/fedilab)

Thanks for building this! 🎉

**Comment by luxonauta** [comment]
It's 🧟 Alive: https://draculatheme.com/fedilab
