### ISSUE TITLE
 Created Repo For Dracula Theme in Libreddit

### ISSUE THREAD

**Issue by vkeerthivikram** [dracula/dracula-theme#791]
@luxonauta @zenorocha I have created a repo showing how to activate Dracula Theme in [Libreddit](https://libreddit.net/) . Could you add it to the website!! Link to the repo: https://github.com/vkeerthivikram/libreddit

**Comment by luxonauta** [comment]
Hey, very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/vkeerthivikram/libreddit)
- [New repository.](https://github.com/dracula/libreddit)

Thanks for building this! 🎉
