### ISSUE TITLE
New theme for Transfer - makehuman

### ISSUE THREAD

**Issue by Apilonius64** [dracula/dracula-theme#793]
I've created a small Dracula theme for [makehuman](http://www.makehumancommunity.org), an open source tool for making 3D characters. Link to repo: https://github.com/Apilonius64/makehuman-dark

**Comment by luxonauta** [comment]
Hey, very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/Apilonius64/makehuman-dark)
- [New repository.](https://github.com/dracula/makehuman)

Thanks for building this! 🎉

**Comment by luxonauta** [comment]
It's 🧟 Alive: https://draculatheme.com/makehuman
