### ISSUE TITLE
The new theme for qBittorrent 4.5.0 is completely broken and unpolished (on Windows 10/11)

### ISSUE THREAD

**Issue by lynx2333** [dracula/dracula-theme#794]
I don't know if this was intentional, but the new theme looks awful - everything's too big and square. Here's the comparison between the old theme and the new redesigned one, which looks nothing like the one from the [homepage](https://draculatheme.com/static/img/screenshots/qbittorrent.png).

![new 1](https://user-images.githubusercontent.com/121351817/209443778-49513113-c06b-45b7-9790-7d46f61ca8aa.png)
![new 2](https://user-images.githubusercontent.com/121351817/209443780-2897097f-3f6a-4a26-9716-041a47bc8f9a.png)
![old 1](https://user-images.githubusercontent.com/121351817/209443782-26f86661-fea2-48df-a429-3ebd778598d7.png)
![old 2](https://user-images.githubusercontent.com/121351817/209443784-71745640-53ad-4d19-8a25-d9542ce7a526.png)

**Comment by luxonauta** [comment]
Hi 👋🏻, thank you so much for your interest in providing this feedback. ✨

But there is a better place to share the same, which is [the project repository](https://github.com/dracula/qbittorrent), where you can talk to the theme maintainers.

✅ [Clicking here](https://github.com/dracula/qbittorrent/issues/new), you can open an Issue on it.
