### ISSUE TITLE
Problem with Gnome Shell dropdowns

### ISSUE THREAD

**Issue by omoghadasi** [dracula/dracula-theme#801]
![image](https://user-images.githubusercontent.com/48834949/211011113-c48965e2-5066-4b4d-b87b-9cb7af4a7ace.png)

**Comment by luxonauta** [comment]
Hi 👋🏻, thank you so much for your interest in providing this feedback. ✨

But there is a better place to share the same, which is the [project repository](https://github.com/dracula/gtk), where you can talk to the theme maintainers.

✅ [Clicking here](https://github.com/dracula/gtk/issues/new/choose), you can open an Issue on it.
