### ISSUE TITLE
New Theme: Todoist

### ISSUE THREAD

**Issue by SIMULATAN** [dracula/dracula-theme#802]
[Todoist](https://todoist.com) is a popular ToDo-Application and I decided to spend my day developing a dracula theme for it.
Unfortunately, there's no native support for user contributed themes, which is why the theme has to be installed through stylus.

**Screenshot**
![Demo Screenshot](https://user-images.githubusercontent.com/63104422/211025772-781e5f11-38cc-4077-9991-c9b54df4ccfb.png)

As always, I'm ready to maintain the theme until further notice and I'd love to hear some feedback.

Repo: [SIMULATAN/DraculaTodoist](https://github.com/SIMULATAN/DraculaTodoist)

**Notes**
- the CSS for the app is unfortunately really chaotic (no clear naming convention, the variables (even the accent color for some reason) often are just ignored and the colors are hardcoded), therefore it's possible that I missed something, in which case please open an inssue.
- there are some apparently obfuscated CSS classes, we'll have to see how long it takes until those break, in such an event again please open an issue, at some point we might have to change the css selectors to automatically support newer versions

**Comment by luxonauta** [comment]
It's 🧟 Alive: https://draculatheme.com/todoist
