### ISSUE TITLE
New theme Request: Aegisub

### ISSUE THREAD

**Issue by BhaturaGuy** [dracula/dracula-theme#803]
Aegisub supports editing colors but I can't seem to find a proper Dracula version.
https://github.com/arch1t3cht/Aegisub
![image](https://user-images.githubusercontent.com/93109835/211146517-06155e3f-bcb4-4521-9c5b-7c8d7fb0d15d.png)

**Comment by luxonauta** [comment]
I will close this Issue for organizational purposes, as it needs community proposals. 😅
