### ISSUE TITLE
New Theme: Chatty

### ISSUE THREAD

**Issue by Hetsig** [dracula/dracula-theme#804]
## [Chatty](https://chatty.github.io/)
Chatty is a chat software specifically made for Twitch, in the spirit of a classic IRC Client. It runs on Windows and any other OS that supports Java 8 or later.

![screenshot-chatty](https://user-images.githubusercontent.com/45275390/211469443-ac357ed4-8d55-403f-9c33-c26ad861fa68.png)

Repository: [Hetsig/dracula-chatty-template](https://github.com/Hetsig/dracula-chatty-template)

**Comment by Hetsig** [comment]
> Hi 👋🏻, this repository no longer exists in your profile; are you still interested in contributing to the project with this theme you made?

Hello! Yes, I can maintain it. I don't know why it got removed. Isn't this working? https://github.com/Hetsig/dracula-chatty-template/blob/master/.chatty/settings

**Comment by luxonauta** [comment]
This link is broken 🦖; I saw in your profile that you have only one open repository.
