### ISSUE TITLE
Misskey/Calckey Theme Submission.

### ISSUE THREAD

**Issue by MayhemBill** [dracula/dracula-theme#805]
I am submitting a repository for support for Misskey/Calckey, linked below.

https://github.com/MayhemBill/Misskey

**Comment by luxonauta** [comment]
Hey, very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/MayhemBill/Misskey)
- [New repository.](https://github.com/dracula/misskey)

Thanks for building this! 🎉

**Comment by MayhemBill** [comment]
Archived it, and I'm already apart of the org, so I'm good to close this then.
