### ISSUE TITLE
New theme: cli-visualizer

### ISSUE THREAD

**Issue by jobcmax** [dracula/dracula-theme#806]
## [cli-visualizer](https://github.com/jobcmax/cli-visualizer)
cli-visualizer is a CLI based audio visualizer. [repo link](https://github.com/jobcmax/cli-visualizer)
screenshot:
![Screenshot](https://github.com/jobcmax/cli-visualizer/blob/master/screenshot.png?raw=true)

**Comment by luxonauta** [comment]
Hey, very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/jobcmax/cli-visualizer)
- [New repository.](https://github.com/dracula/cli-visualizer)

Thanks for building this! 🎉

**Comment by luxonauta** [comment]
It's 🧟 Alive: https://draculatheme.com/cli-visualizer
