### ISSUE TITLE
New theme: Replugged

### ISSUE THREAD

**Issue by mrhappyma** [dracula/dracula-theme#808]
[Replugged](https://replugged.dev) dracula theme!
[mrhappyma/discord-dracula](https://github.com/mrhappyma/discord-dracula)
Imports css file from the [BetterDiscord theme](https://github.com/dracula/betterdiscord).

Not sure how transferring the repo to you guys works. The updating information for the theme points to my repo currently.

**Comment by luxonauta** [comment]
Hey, very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/mrhappyma/dracula-replugged)
- [New repository.](https://github.com/dracula/replugged)

Thanks for building this! 🎉

**Comment by mrhappyma** [comment]
Cool, thanks!

**Comment by mrhappyma** [comment]
@luxonauta when will this start appearing on the website? Do I have to do something additionally for that to happen?

**Comment by luxonauta** [comment]
You don't have to do anything 🫡; as soon as we release the following newsletter announcing the new themes that have been included, you will be able to check yours and others on the site 🦇
