### ISSUE TITLE
New Theme: Uptime Kuma

### ISSUE THREAD

**Issue by Subtixx** [dracula/dracula-theme#810]
Created a Dracula Version for uptime kuma :)

[![Uptime Kuma Screen](https://github.com/IT-Hock/dracula-uptime-kuma/raw/master/screenshot.png)](https://github.com/IT-Hock/dracula-uptime-kuma)

[https://github.com/IT-Hock/dracula-uptime-kuma](https://github.com/IT-Hock/dracula-uptime-kuma)

**Comment by luxonauta** [comment]
Hey, very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/IT-Hock/dracula-uptime-kuma)
- [New repository.](https://github.com/dracula/uptime-kuma)

Thanks for building this! 🎉

**Comment by luxonauta** [comment]
It's 🧟 Alive: https://draculatheme.com/uptime-kuma
