### ISSUE TITLE
New Theme: Yakuake

### ISSUE THREAD

**Issue by Subtixx** [dracula/dracula-theme#811]
Created a theme for the drop-down terminal [Yakuake](https://apps.kde.org/de/yakuake/) 

[![Yakuake Theme](https://github.com/IT-Hock/yakuake-dracula/raw/master/screenshot.png)](https://github.com/IT-Hock/yakuake-dracula)

https://github.com/IT-Hock/yakuake-dracula

**Comment by luxonauta** [comment]
Hey, very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/IT-Hock/dracula-yakuake)
- [New repository.](https://github.com/dracula/yakuake)

Thanks for building this! 🎉

**Comment by luxonauta** [comment]
It's 🧟 Alive: https://draculatheme.com/yakuake
