### ISSUE TITLE
New Theme: Newsboat

### ISSUE THREAD

**Issue by staal0** [dracula/dracula-theme#814]
### Newsboat RSS/Atom feed reader
https://github.com/staal0/newsboat

**Comment by luxonauta** [comment]
Hey, very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/staal0/newsboat)
- [New repository.](https://github.com/dracula/newsboat)

Thanks for building this! 🎉

**Comment by luxonauta** [comment]
It's 🧟 Alive: https://draculatheme.com/newsboat
