### ISSUE TITLE
new steam update broke the theme

### ISSUE THREAD

**Issue by ogmicco** [dracula/dracula-theme#815]
![image](https://user-images.githubusercontent.com/107354268/216279351-690b78e2-03f7-412c-99b9-44fab3b4fb01.png)

**Comment by luxonauta** [comment]
Hi 👋🏻, thank you for your interest in providing this feedback. ✨

But there is a better place to share the same, which is the project repository, where you can talk to the theme maintainers.

✅ [Clicking here](https://github.com/dracula/steam/issues/new), you can open an Issue on it.
