### ISSUE TITLE
New Theme: Firefox CSS Theme

### ISSUE THREAD

**Issue by jannikbuscha** [dracula/dracula-theme#816]
Hey, I have created a complete Firefox CSS theme with custom JSON Viewer and DevTools theme.

![thumbnail](https://user-images.githubusercontent.com/74017697/216740324-8811d0b8-de9b-417e-ae05-a233bc0f81c9.png)

I think it would be quite cool if this could be already included under the existing [Firefox](https://draculatheme.com/firefox) repository, next to the simple theme what already exists.

My Repository:
https://github.com/jannikbuscha/firefox-dracula

**Comment by luxonauta** [comment]
@RaphGL I'll add Jannik as a collaborator; let's bring the projects together! ✨

**Comment by RaphGL** [comment]
That's fine by me. I'd hope we could unify the look of both though as the colors chosen for some things are different between the two.

**Comment by luxonauta** [comment]
Let me know if you need help with anything! ☕
