### ISSUE TITLE
Created Repo For Dracula Theme in JabRef

### ISSUE THREAD

**Issue by Inf166** [dracula/dracula-theme#818]
I have made a theme for JabRef, a library manager I used during my thesis. I am open for feedback and would like to contribute to my favorite theme. You can find the repository for the theme [here.](https://github.com/Inf166/theme-jabref-dracula)

<img width="1680" alt="preview" src="https://user-images.githubusercontent.com/38419872/217955355-b4deb535-5ff2-4741-8332-71d5b140922f.png">

**Comment by luxonauta** [comment]
Hey, very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/Inf166/theme-jabref-dracula)
- [New repository.](https://github.com/dracula/jabref)

Thanks for building this! 🎉

**Comment by luxonauta** [comment]
It's 🧟 Alive: https://draculatheme.com/jabref

**Comment by Inf166** [comment]
Hey, sorry to bother - there might be an error in my pull-request since the images are broken
[See it here](https://draculatheme.com/jabref)

**Comment by luxonauta** [comment]
🎯 I already corrected it, but Zeno does the deployment on the site; you can rest assured that soon you will be right on the site.
