### ISSUE TITLE
qbittorrent 4.5.1 docker

### ISSUE THREAD

**Issue by blacknwhite98** [dracula/dracula-theme#819]
issue after update qbittorrent 4.5.1
![image](https://user-images.githubusercontent.com/90709781/219656294-4d7c0c3a-5360-4230-abd1-2aafd6f0c95b.png)

**Comment by luxonauta** [comment]
Hi 👋🏻, thank you for your interest in providing this feedback. ✨

But there is a better place to share the same, which is the project repository, where you can talk to the theme maintainers.

✅ [Clicking here](https://github.com/dracula/qbittorrent/issues/new), you can open an Issue on it.
