### ISSUE TITLE
New Theme: Hyprland

### ISSUE THREAD

**Issue by milkknife** [dracula/dracula-theme#822]
Hyprland is a dynamic tiling Wayland compositor based on wlroots that doesn't sacrifice on its looks.

https://github.com/milkknife/hyprland

**Comment by luxonauta** [comment]
Hey, very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/milkknife/hyprland)
- [New repository.](https://github.com/dracula/hyprland)

Thanks for building this! 🎉

**Comment by luxonauta** [comment]
🧟 It's alive: https://draculatheme.com/hyprland
