### ISSUE TITLE
New Theme: st

### ISSUE THREAD

**Issue by gildasio** [dracula/dracula-theme#823]
## st/simple terminal

https://github.com/gildasio/st

**Comment by luxonauta** [comment]
Hey, very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/gildasio/st)
- [New repository.](https://github.com/dracula/st)

Thanks for building this! 🎉

**Comment by gildasio** [comment]
Nice, thanks @luxonauta ! :)

I just accepted the invitation. Let me know if I need to do anything else.

**Comment by luxonauta** [comment]
🧟 It's alive: https://draculatheme.com/st
