### ISSUE TITLE
New Theme: Waybar

### ISSUE THREAD

**Issue by milkknife** [dracula/dracula-theme#826]
Waybar is a highly customizable Wayland bar for Sway and Wlroots based compositors.

https://github.com/milkknife/waybar

**Comment by luxonauta** [comment]
Hey, very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/milkknife/waybar)
- [New repository.](https://github.com/dracula/waybar)

Thanks for building this! 🎉

**Comment by luxonauta** [comment]
🧟 It's alive: https://draculatheme.com/waybar
