### ISSUE TITLE
[New Theme] Kristall

### ISSUE THREAD

**Issue by x-industries-uk** [dracula/dracula-theme#828]
Hi, I've just made a basic theme for [Kristall](https://kristall.random-projects.net/), a client for the Gemini protocol. The UI itself is Qt-based, so your Qt theme is used for that. This theme changes the colours of the pages themselves.

The repository can be found [here](https://github.com/x-industries-uk/dracula-kristall).

Thanks!

**Comment by luxonauta** [comment]
Hey, very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/x-industries-uk/dracula-kristall)
- [New repository.](https://github.com/dracula/kristall)

Thanks for building this! 🎉

**Comment by luxonauta** [comment]
🧟 It's alive: https://draculatheme.com/kristall
