### ISSUE TITLE
Dracula Theme FreeTube

### ISSUE THREAD

**Issue by ghost** [dracula/dracula-theme#829]
https://github.com/AnyaCodeX/Dracula-Theme-FreeTube

**Comment by luxonauta** [comment]
Hey, very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/AnyaCodeX/Dracula-Theme-FreeTube)
- [New repository.](https://github.com/dracula/freetube)

Thanks for building this! 🎉

**Comment by luxonauta** [comment]
🧟 It's alive: https://draculatheme.com/freetube
