### ISSUE TITLE
New Theme: Mkdocs

### ISSUE THREAD

**Issue by FernandoCelmer** [dracula/dracula-theme#832]
## Theme for [Mkdocs](https://www.mkdocs.org/) 
Mkdocs is a fast, simple and downright gorgeous static site generator that's geared towards building project documentation. For more information visit the official [Mkdocs](https://www.mkdocs.org/) documentation.

- **Github: https://github.com/FernandoCelmer/mkdocs**
- Theme: https://fernandocelmer.github.io/mkdocs/

**Comment by luxonauta** [comment]
Hey, very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/FernandoCelmer/mkdocs)
- [New repository.](https://github.com/dracula/mkdocs)

Thanks for building this! 🎉

**Comment by luxonauta** [comment]
🧟 It's alive: https://draculatheme.com/mkdocs
