### ISSUE TITLE
Theme for jupyter notebook

### ISSUE THREAD

**Issue by lex-andr** [dracula/dracula-theme#833]
## Dracula theme for jupyter notebook

Hi, I've been working on a Dracula theme for Jupyter Notebook, here's the link to my github repository if you want to check it!
[https://github.com/lex-andr/jupyter-notebook](https://github.com/lex-andr/jupyter-notebook)

Cheers!

**Comment by luxonauta** [comment]
Hey, very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/lex-andr/jupyter-notebook)
- [New repository.](https://github.com/dracula/jupyter-notebook)

Thanks for building this! 🎉

**Comment by luxonauta** [comment]
🧟 It's alive: https://draculatheme.com/jupyter-notebook
