### ISSUE TITLE
New Theme: Neovim

### ISSUE THREAD

**Issue by maxmx03** [dracula/dracula-theme#834]
## New Theme

I created a port of the Dracula color scheme for Neovim. Check it out.
I haven't deleted the samples folder yet, so you guys can see if everything is okay with the highlights groups.

https://github.com/maxmx03/dracula.nvim

![Dracula](https://user-images.githubusercontent.com/50273941/227610774-22d0cfad-4416-49db-a61f-955ef23c5cd3.png)

**Comment by benknoble** [comment]
Can you expand on how it's different from dracula/vim (and please don't say the only difference is Lua)?

**Comment by maxmx03** [comment]
> Can you expand on how it's different from dracula/vim (and please don't say the only difference is Lua)?

Of course, it's not just because of Lua. One significant difference is that the newer version of Neovim incorporates semantic highlighting, which can enhance the overall highlighting experience.

![Screenshot](https://user-images.githubusercontent.com/50273941/227637803-76b86861-4210-4469-95d5-a4cd6f27f5c4.png)

You can read more here: https://gist.github.com/swarn/fb37d9eefe1bc616c2a7e476c0bc0316

**Comment by benknoble** [comment]
Got it. Is the semantic highlighting colorscheme code something that can be added to dracula/vim ? We already have some treesitter support, for example.

**Comment by maxmx03** [comment]
Yes, you can add semantic highlighting to Dracula/Vim by adding the necessary code to your lua/dracula/init.lua file, or just write everything in vimscript

```lua
  local c = {
     fg = "#f8f8f2",
     bg = "#282a36",
     float_bg = "#23252f",
     currentline = "#44475a",
     comment = "#6272a4",
     cyan = "#8be9fd",
     green = "#50fa7b",
     orange = "#ffb86c",
     pink = "#ff79c6",
     purple = "#bd93f9",
     red = "#ff5555",
     yellow = "#f1fa8c",
     cursor_fg = "#282a36",
     cursor_bg = "#f8f8f2",
     sign_add = "#50fa7b",
     sign_change = "#ffb866",
     sign_delete = "#ff5555",
     error = "#ff555b",
     warning = "#ffb866",
     info = "#8be9fd",
     hint = "#8be9fd",
     other = "#bd93f9",
     blended_orange = "#483F3E",
     blended_red = "#48303B",
     blended_cyan = "#374754",
  }

  local hl = vim.api.nvim_set_hl

  -- TreeSitter
  hl(0, "@comment", { fg = c.comment, bg = 'NONE' })
  hl(0, "@comment.documentation", { fg = c.comment, bg = 'NONE' })
  hl(0, "@error", { link = 'Error' })
  hl(0, "@operator", { fg = c.pink, bg = 'NONE' })
  hl(0, "@punctuation.delimiter", { fg = c.fg, bg = 'NONE' })
  hl(0, "@punctuation.delimiter.cpp", { fg = c.pink, bg = 'NONE' })
  hl(0, "@punctuation.bracket", { fg = c.pink, bg = 'NONE' })
  hl(0, "@punctuation.special", { fg = c.pink, bg = 'NONE' })
  hl(0, "@string", { fg = c.yellow, bg = 'NONE' })
  hl(0, "@string.regex", { fg = c.red, bg = 'NONE' })
  hl(0, "@string.escape", { fg = c.pink, bg = 'NONE' })
  hl(0, "@string.special", { fg = c.pink, bg = 'NONE' })
  hl(0, "@character", { fg = c.yellow, bg = 'NONE' })
  hl(0, "@character.special", { fg = c.pink, bg = 'NONE' })
  hl(0, "@function", { fg = c.green, bg = 'NONE' })
  hl(0, "@function.builtin", { fg = c.green, bg = 'NONE' })
  hl(0, "@function.call", { fg = c.green, bg = 'NONE' })
  hl(0, "@method", { fg = c.green, bg = 'NONE' })
  hl(0, "@method.call", { fg = c.green, bg = 'NONE' })
  hl(0, "@constructor", { fg = c.pink, bg = 'NONE' })
  hl(0, "@constructor.c_sharp", { link = '@type' })
  hl(0, "@constructor.php", { link = '@type' })
  hl(0, "@parameter", { fg = c.orange, bg = 'NONE', italic=true, })
  hl(0, "@boolean", { fg = c.purple, bg = 'NONE' })
  hl(0, "@number", { fg = c.purple, bg = 'NONE' })
  hl(0, "@float", { fg = c.purple, bg = 'NONE' })
  hl(0, "@label.json", { fg = c.cyan, bg = 'NONE' })
  hl(0, "@exception", { link = 'Exception' })
  hl(0, "@type", { link = 'Type' })
  hl(0, "@type.dart", { link = '@type' })
  hl(0, "@type.builtin", { fg = c.cyan, bg = 'NONE', italic=true, })
  hl(0, "@type.builtin.cpp", { fg = c.pink, bg = 'NONE', italic=true, })
  hl(0, "@type.definition", { link = 'Type' })
  hl(0, "@type.qualifier", { fg = c.pink, bg = 'NONE' })
  hl(0, "@storageclass", { fg = c.pink, bg = 'NONE' })
  hl(0, "@attribute", { fg = c.pink, bg = 'NONE' })
  hl(0, "@field", { fg = c.fg, bg = 'NONE' })
  hl(0, "@property", { link = '@field' })
  hl(0, "@property.css", { fg = c.cyan, bg = 'NONE' })
  hl(0, "@variable", { fg = c.fg, bg = 'NONE' })
  hl(0, "@variable.builtin", { fg = c.purple, bg = 'NONE' })
  hl(0, "@constant", { fg = c.purple, bg = 'NONE' })
  hl(0, "@constant.builtin", { fg = c.purple, bg = 'NONE' })
  hl(0, "@constant.macro", { fg = c.purple, bg = 'NONE' })
  hl(0, "@namespace", { fg = c.fg, bg = 'NONE' })
  hl(0, "@symbol", { fg = c.purple, bg = 'NONE' })
  hl(0, "@text", { fg = c.yellow, bg = 'NONE' })
  hl(0, "@text.strong", { fg = c.orange, bg = 'NONE', bold=true, })
  hl(0, "@text.emphasis", { fg = c.green, bg = 'NONE', italic=true, })
  hl(0, "@text.strike", { fg = c.yellow, bg = 'NONE', strikethrough=true, })
  hl(0, "@text.title", { fg = c.cyan, bg = 'NONE', bold=true, })
  hl(0, "@text.literal", { fg = c.green, bg = 'NONE', italic=true, })
  hl(0, "@text.quote", { fg = c.pink, bg = 'NONE' })
  hl(0, "@text.uri", { fg = c.cyan, bg = 'NONE' })
  hl(0, "@text.math", { fg = c.pink, bg = 'NONE' })
  hl(0, "@text.reference", { fg = c.pink, bg = 'NONE' })
  hl(0, "@text.todo", { link = 'Todo' })
  hl(0, "@text.warning", { link = 'WarningMsg' })
  hl(0, "@text.danger", { link = 'ErrorMsg' })
  hl(0, "@text.diff.add", { link = 'DiffAdd' })
  hl(0, "@text.diff.delete", { link = 'DiffDelete' })
  hl(0, "@tag", { fg = c.pink, bg = 'NONE' })
  hl(0, "@tag.attribute", { fg = c.green, bg = 'NONE' })
  hl(0, "@tag.delimiter", { fg = c.fg, bg = 'NONE' })

  -- semantic highlight
  hl(0, "@lsp.type.namespace", { link = '@namespace' })
  hl(0, "@lsp.type.type", { link = '@type' })
  hl(0, "@lsp.type.class", { link = '@type' })
  hl(0, "@lsp.type.enum", { link = '@type' })
  hl(0, "@lsp.type.interface", { link = '@type' })
  hl(0, "@lsp.type.struct", { link = '@structure' })
  hl(0, "@lsp.type.parameter", { link = '@parameter' })
  hl(0, "@lsp.type.variable", { link = '@variable' })
  hl(0, "@lsp.type.property", { link = '@property' })
  hl(0, "@lsp.type.enumMember", { link = '@constant' })
  hl(0, "@lsp.type.function", { link = '@function' })
  hl(0, "@lsp.type.method", { link = '@method' })
  hl(0, "@lsp.type.macro", { link = '@macro' })
  hl(0, "@lsp.type.decorator", { link = '@function' })
  hl(0, "@lsp.typemod.variable.defaultLibrary", { link = '@constant' })
  hl(0, "@lsp.typemod.parameter.readyonly", { link = 'Italic' })
  hl(0, "@lsp.typemod.variable.readonly", { link = '@variable.builtin' })
```

and then importing it to your colors/dracula.vim. Please note that this will only work for Neovim users.

```vim
if has('nvim-0.8.0')
lua << eof
require('dracula')
eof
endif
```

**Comment by benknoble** [comment]
I can see where you're coming from, but we already have some NeoVim support. Ripping it out now and suggesting people use a different plugin would cause a lot of unnecessary churn, to me; worse, maintaining it in the face of a different plugin would lead to lots of questions about the discrepancies. Heck, having 2 different plugins is likely to lead to that.

Perhaps @dsifford has thoughts as both dracula/vim maintainer and (IIRC) NeoVim user?

**Comment by MuhametSmaili** [comment]
> > Neat! I would encourage you to consider contributing back to dracula/vim instead of trying to maintain two parallel themes… it would be great to see the best of both worlds in one place, I think.
> 
> Hi, I get that you wanted to have everything in a single repository, but I believe it would be better to have separate themes for each text editor. That way, you don't have to worry about Neovim and its plugins. I think it would be easier for Dracula/Vim if they focused solely on improving the Vim syntax instead of trying to support Neovim

I completely agree with this take. The current `dracula/vim` theme, lacks a lot of support especially when you lazy load plugins (cmp for example), also the last issues in the dracula/vim are mostly about neovim. 

Why not have different repository?  They are different editors.
This way I also think it will help a lot the neovim community because this is written in lua hence it would be a lot easier to contribute and read the code.

**Comment by benknoble** [comment]
> The current `dracula/vim` theme, lacks a lot of support especially when you lazy load plugins (cmp for example)

I've been meaning to try to address this, but it's not trivial to detect when a plugin is loaded in the middle of the editor running. I think the solution is for dracula/vim to unconditionally link plugin related groups? cf. https://github.com/dracula/vim/pull/301 (And why lazy load anyway? If most code is behind `autoload`, it shouldn't be a big deal, but maybe I misunderstand the purpose of lazy load?)

> also the last issues in the dracula/vim are mostly about neovim.

To me this indicates interest in improving dracula/vim to include NeoVim compatibility, not necessarily interest in splitting off entirely.

> Why not have different repository? They are different editors. This way I also think it will help a lot the neovim community because this is written in lua hence it would be a lot easier to contribute and read the code.

How different the editors are is debatable, given the compatibility focus for many major features.

[The actual highlighting code](https://github.com/maxmx03/dracula.nvim/blob/master/lua/dracula/themes/init.lua) is almost the same in Lua as in Vimscript, and the layout of all the Lua files is harder to follow if you aren't used to the Lua+Vim structure… Stringly-typed APIs like the one in this link are also not the easiest to use, IMO.

What is being done in Lua that couldn't be done clearly in the original?

From poking around, the major differences I see are
- the "soft" variant (what is this?)
- the initialization code is more complicated because of Lua
- the require/Lua organization practically re-invents all of the existing `:colorscheme name` mechanism (which just executes the corresponding file), switching it for a `setup` method

I don't want to be hostile to change. I just believe fragmenting things is the wrong way to go, and getting a dedicated group together to improve the state of dracula/vim would be better than two independent groups trying to keep up with each other in ad-hoc ways. I'm sure @dsifford and I are willing to take on more maintainers with a NeoVim focus (my focus is typically very Vim, since that's what I use, but I try to review NeoVim-related things where I can).

**Comment by dsifford** [comment]
> the "soft" variant (what is this?)

I had to add that to the VSCode theme because of the overwhelming amount of issues related to how macos renders colors. Soft just reduces the saturation of the colors to make them appear more normal on mac displays. (that said, I use a mac for work and still don't personally use "soft" in vscode)

**Comment by benknoble** [comment]
> > the "soft" variant (what is this?)
> 
> 
> 
> I had to add that to the VSCode theme because of the overwhelming amount of issues related to how macos renders colors. Soft just reduces the saturation of the colors to make them appear more normal on mac displays. (that said, I use a mac for work and still don't personally use "soft" in vscode)

Ah, thanks. Haven't had this trouble in Vim, presumably, so I wasn't aware of it.
