### ISSUE TITLE
Website related: No Bug but a mistake and missing contact informations!

### ISSUE THREAD

**Issue by itsmetoolala** [dracula/dracula-theme#841]
Hello there!

Unfortunately, you don't have any contact information on your website, so I can only contact you here.
You _should_ please change this.

There is an error on your "Homepage" in the "Activating theme" section.

It says there:
"1. Go to %AppData%\Notepad++\themes".

But this is wrong. Correctly it should read:
"1. Go to %AppData%\ **Roaming** \Notepad++\themes".

_Thank you for this theme! It's great and I like it a lot!_

Sincerely

Translated with www.DeepL.com/Translator (free version)

**Comment by luxonauta** [comment]
It was [already adjusted](https://github.com/dracula/notepad-plus-plus/blob/master/INSTALL.md)! Thanks for the feedback! 💖
