### ISSUE TITLE
New theme for `lsd`

### ISSUE THREAD

**Issue by urrickhunt** [dracula/dracula-theme#845]
## New Theme

Dracula for [lsd](https://github.com/Peltoche/lsd)

**Comment by luxonauta** [comment]
I saw that [we already have a repository](https://github.com/dracula/lsd) for this project, and you are its maintainer, so I sent an invitation again to join the community. So could you update it? 🤔

**Comment by urrickhunt** [comment]
updated

**Comment by luxonauta** [comment]
🧟 It's alive: https://draculatheme.com/lsd
