### ISSUE TITLE
New theme for `exa`

### ISSUE THREAD

**Issue by urrickhunt** [dracula/dracula-theme#846]
## New Theme

Dracula Universal for [exa](https://github.com/ogham/exa)

**Comment by luxonauta** [comment]
Hi 👋🏻 

That's cool, but we need a repo that follows the pattern; would you like to try to do the same? Here is [the template](https://github.com/dracula/template) and a [guide for contributing](https://draculatheme.com/contribute).

**Comment by luxonauta** [comment]
Hey, very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/urrickhunt/Dracula-universal-for-exa)
- [New repository.](https://github.com/dracula/exa)

Thanks for building this! 🎉

**Comment by luxonauta** [comment]
🧟 It's alive: https://draculatheme.com/exa
