### ISSUE TITLE
New theme for `man-pages`

### ISSUE THREAD

**Issue by urrickhunt** [dracula/dracula-theme#847]
## New Theme

Dracula Universal for [man-pages](https://man7.org/linux/man-pages/man1/man.1.html)

**Comment by luxonauta** [comment]
Hey, very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/urrickhunt/Dracula-universal-for-manpages)
- [New repository.](https://github.com/dracula/man-pages)

Thanks for building this! 🎉

**Comment by luxonauta** [comment]
🧟 It's alive: https://draculatheme.com/man-pages
