### ISSUE TITLE
New theme for iSH

### ISSUE THREAD

**Issue by urrickhunt** [dracula/dracula-theme#850]
## New Theme

Dracula for [iSH](https://github.com/ish-app/ish)

**Comment by luxonauta** [comment]
Hey, very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/urrickhunt/Dracula-for-iSH)
- [New repository.](https://github.com/dracula/ish)

Thanks for building this! 🎉

**Comment by luxonauta** [comment]
🧟 It's alive: https://draculatheme.com/ish
