### ISSUE TITLE
New theme: SpeedCrunch

### ISSUE THREAD

**Issue by betazedd** [dracula/dracula-theme#851]
Greetings! I made a new Dracula theme for SpeedCrunch, a calculator program, a while back. I'm finally getting around to uploading it. This is my first contribution to GitHub of any kind so let me know what I may have messed up. Here's the link to my repository: https://github.com/betazedd/dracula-speedcrunch

**Comment by luxonauta** [comment]
Hey, very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/betazedd/dracula-speedcrunch)
- [New repository.](https://github.com/dracula/speedcrunch)

Thanks for building this! 🎉

**Comment by luxonauta** [comment]
🧟 It's alive: https://draculatheme.com/speedcrunch
