### ISSUE TITLE
New Theme: Blockbench

### ISSUE THREAD

**Issue by Subtixx** [dracula/dracula-theme#852]
# Blockbench - A low-poly 3D model editor

## Repository

https://github.com/IT-Hock/dracula-blockbench

## Preview

![Preview](https://github.com/IT-Hock/dracula-blockbench/raw/master/screenshot.png)

**Comment by luxonauta** [comment]
Hey, very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/IT-Hock/dracula-blockbench)
- [New repository.](https://github.com/dracula/blockbench)

Thanks for building this! 🎉

**Comment by Subtixx** [comment]
Archived the original repository =)

**Comment by luxonauta** [comment]
🧟 It's alive: https://draculatheme.com/blockbench
