### ISSUE TITLE
Kurozora x Dracula

### ISSUE THREAD

**Issue by kiritokatklian** [dracula/dracula-theme#854]
Hey there! As an avid fan an user of the Dracula theme for Xcode, I've added support for it in my anime/manga tracking app called Kurozora.

Here's the repo with the screenshot: https://github.com/Kurozora/Kurozora-x-Dracula

**Comment by kiritokatklian** [comment]
Haha, thank you too!

Asuna is doing just fine kicking some virtual butt 😉

**Comment by luxonauta** [comment]
🧟 It's alive: https://draculatheme.com/kurozora

**Comment by kiritokatklian** [comment]
Amazing! Thank you 😄
