### ISSUE TITLE
Can Someone Please Help Java blockbench model issues

### ISSUE THREAD

**Issue by uhhhhi57** [dracula/dracula-theme#856]
Can someone please help me, I work with java models, and when I make a texture things disappear, and when I color one block it appears on another. Like there connected. I have tried switching to a generic model creating a texture and then switching back. But my model is still broken, there's always errors, but if I change them it wont even be close to looking like anything good. I am making a lizard for my grandpa, he died from cancer. I promised my family I would make one for him. I have no clue why its not working.
#852

**Comment by Subtixx** [comment]
Is this a problem with the theme or a general Blockbench issue? Can you please explain a little bit more?

I tested the theme extensively and haven't had this issue. 

Please keep in mind that:

1. You're on the wrong repository. You should open an issue in the theme [repository](https://github.com/dracula/blockbench/issues)
2. If this a general issues with blockbench please open an issue with them instead located **[here](https://github.com/JannisX11/blockbench)**

**Comment by uhhhhi57** [comment]
Ah I am sorry for not responding, I have tried many things. Even converting it back and forth. I would really like to get it figured out. I am trying to make a mob with a generic model, then convert it over to a modded entity for my mod.  But it always has texture issues, and wont load the model with the texture right. There are random colors and invisible parts. I could send you a video or screenshots of the issues.

**Comment by uhhhhi57** [comment]
> Ah I am sorry for not responding, I have tried many things. Even converting it back and forth. I would really like to get it figured out. I am trying to make a mob with a generic model, then convert it over to a modded entity for my mod. But it always has texture issues, and wont load the model with the texture right. There are random colors and invisible parts. I could send you a video or screenshots of the issues.

Ah I am sorry for not responding, I have tried many things. Even converting it back and forth. I would really like to get it figured out. I am trying to make a mob with a generic model, then convert it over to a modded entity for my mod. But it always has texture issues, and wont load the model with the texture right. There are random colors and invisible parts. I could send you a video or screenshots of the issues.

**Comment by luxonauta** [comment]
Hi 👋🏻, there are better places to look for this help than this repository.
