### ISSUE TITLE
New Theme: OneCommander - Modern files manager for Windows 11 and Windows 10

### ISSUE THREAD

**Issue by Subtixx** [dracula/dracula-theme#857]
## About OneCommander

OneCommander is a modern file manager for Windows 10 and Windows 11. Features include tabs, dual-pane browsers, columns navigation, built-in preview, a theming system, color tags, and much more. It is free for home use and has no ads.

## Preview

![Preview](https://github.com/IT-Hock/dracula-onecommander/raw/master/screenshot.png)

## Repository

https://github.com/IT-Hock/dracula-onecommander

**Comment by luxonauta** [comment]
Hey, very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/IT-Hock/dracula-onecommander)
- [New repository.](https://github.com/dracula/onecommander)

Thanks for building this! 🎉
