### ISSUE TITLE
config and font of cover Image in ITerm2 Theme

### ISSUE THREAD

**Issue by VictoryHero** [dracula/dracula-theme#858]
I follow the guide to install dracula both in iTerm2 and oh-my-zsh, however, It looks different from the cover image of offical website.  I really want to know more info about the config and fonts. That cover really cool!

**Comment by VictoryHero** [comment]
The following is mine:
<img width="1016" alt="uTools_1683023621632" src="https://user-images.githubusercontent.com/36233728/235644680-07bed096-195a-4fad-9b81-c3e164349630.png">

The following is Offical:
<img src="https://draculatheme.com/static/img/screenshots/iterm.png>

**Comment by luxonauta** [comment]
Hi 👋🏻, thank you for your interest in providing this feedback. ✨

But there is a better place to share the same, which is the project repository, where you can talk to the theme maintainers.

✅ [Clicking here](https://github.com/dracula/iterm/issues/new), you can open an Issue on it.

**Comment by StackTc** [comment]
i am the same
