### ISSUE TITLE
Dracula for Microsoft Edge

### ISSUE THREAD

**Issue by ziroau** [dracula/dracula-theme#862]
https://github.com/ziroau/dracula-microsoft-edge

Just trying to package it to MS Edge store now :)

![screenshot](https://github.com/dracula/dracula-theme/assets/60493188/07cf6c26-f2a6-451a-b78e-25d5e75045d7)

**Comment by luxonauta** [comment]
Hey, very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/ziroau/dracula-microsoft-edge)
- [New repository.](https://github.com/dracula/microsoft-edge)

Thanks for building this! 🎉

**Comment by ziroau** [comment]
Thanks! Have joined the org.
Will let you know if there's any issues
