### ISSUE TITLE
[Bug] The example image for the Xcode theme is broken on the website

### ISSUE THREAD

**Issue by DerekTurtleRoe** [dracula/dracula-theme#863]
The example image on the website for Xcode is broken.

On the https://draculatheme.com/pro page, the Xcode image is broken. Specifically `"/static/img/pro/xcode/1.png"`

I tried in Microsoft Edge, Google Chrome, Brave, Firefox, and Mullvad Browser on Windows 10 as well as Linux Mint.

I can provide version numbers and OS build numbers, etc. but I think you get the idea, should be a simple fix. 😄

**Comment by luxonauta** [comment]
Is this still a problem for you? We tried to reproduce it here but couldn't! 🤔
