### ISSUE TITLE
New theme for the protonmail web client

### ISSUE THREAD

**Issue by Blisterexe** [dracula/dracula-theme#864]
## New Theme?
I made a theme for the protonmail web client, here is the link: https://github.com/Blisterexe/Dracula-Protonmail-theme
it is meant to be used with the [stylus extension](https://addons.mozilla.org/en-US/firefox/addon/styl-us/) just like the official youtube theme.

**Comment by luxonauta** [comment]
Hey, very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/Blisterexe/Dracula-Protonmail-theme)
- [New repository.](https://github.com/dracula/protonmail)

Thanks for building this! 🎉

**Comment by Blisterexe** [comment]
thank you for accepting my theme! I am very honored!
