### ISSUE TITLE
Dracula for Rio terminal

### ISSUE THREAD

**Issue by raphamorim** [dracula/dracula-theme#866]
# New theme

Dracula theme for [Rio terminal](https://github.com/raphamorim/rio)

Repo: https://github.com/raphamorim/rio-dracula

cc @luxonauta @zenorocha 🙏 ⭐ 🧛

**Comment by luxonauta** [comment]
Hey, very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/raphamorim/rio-dracula)
- [New repository.](https://github.com/dracula/rio-terminal)

Thanks for building this! 🎉

**Comment by raphamorim** [comment]
Thank you very much @luxonauta, just deleted the old repo 👌 🙏
