### ISSUE TITLE
Dracula Theme for Serum

### ISSUE THREAD

**Issue by sleeplessKomodo** [dracula/dracula-theme#868]
I created a theme with the Dracula colour scheme for Xfer's Serum VST. Let me know if anything should be changed!

https://github.com/sleeplessKomodo/serumDracula

![interface](https://github.com/dracula/dracula-theme/assets/82418204/3f362728-e67e-4084-9f06-87181c700c47)

**Comment by luxonauta** [comment]
Hey, very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/sleeplessKomodo/serumDracula)
- [New repository.](https://github.com/dracula/serum)

Thanks for building this! 🎉
