### ISSUE TITLE
Dracula for rime

### ISSUE THREAD

**Issue by shlroland** [dracula/dracula-theme#869]
[rime](https://rime.im/) is an input method.

I create Dracula theme for it
https://github.com/shlroland/rime

**Comment by luxonauta** [comment]
Hey, very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/shlroland/rime)
- [New repository.](https://github.com/dracula/rime)

Thanks for building this! 🎉
