### ISSUE TITLE
Dracula for WinAmp

### ISSUE THREAD

**Issue by veevyo** [dracula/dracula-theme#871]
Hey, I've made a Dracula theme for WinAmp! Here's my repository: https://github.com/veevyo/dracula-winamp. It's my first time contributing to Dracula properly, so let me know if I need to fix anything up with my repository.

**Comment by luxonauta** [comment]
Hey, very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/veevyo/dracula-winamp)
- [New repository.](https://github.com/dracula/winamp)

Thanks for building this! 🎉
