### ISSUE TITLE
YouTube Music (desktop apps and website)

### ISSUE THREAD

**Issue by Ugau943** [dracula/dracula-theme#872]
Hello,

First of all thanks to @MayhemBill for his "[YouTube Music Desktop](https://ytmdesktop.app/)" theme (from #751, here [his repo](https://github.com/MayhemBill/YTMD-Dracula), here the [Dracula repo](https://github.com/dracula/youtube-music-desktop) and here the [Dracula webpage](https://draculatheme.com/youtube-music-desktop)), it works very well. 

I should add that it works for me with another desktop app for YouTube Music : "[YouTube Music Desktop App](https://th-ch.github.io/youtube-music/)" ([repo](https://github.com/th-ch/youtube-music) ; `Options > Visual Tweaks > Theme > Import custom CSS file` ; and yes, this app name differ only with the "_App_" at the end) as much as with the YouTube Music [official website](https://music.youtube.com/) via Stylus.

It might be worth mentioning these compatibilities on the draculatheme.com website, or even creating two specific repo and adding these applications to draculatheme.com (which unfortunately is beyond my skills).

**Comment by MayhemBill** [comment]
I will add a list of compatible sites/apps on the YTMD repo I have, since it just works™
