### ISSUE TITLE
Dracula for fcitx5

### ISSUE THREAD

**Issue by SushiWaUmai** [dracula/dracula-theme#875]
I found an fcitx5 dracula theme repository here: https://github.com/drbbr/fcitx5-dracula-theme
It would be nice if we could add this as well.
I also created an issue on this one to ask the owner of the repository [here](https://github.com/drbbr/fcitx5-dracula-theme/issues/3)

**Comment by luxonauta** [comment]
If you get authorization from the author or he wants to add the same to be listed on the site, please open an Issue here, and I can proceed with the transfer to the organization.
