### ISSUE TITLE
Dracula for Mantine

### ISSUE THREAD

**Issue by zeretkk** [dracula/dracula-theme#876]
Hey!

I made a Dracula color scheme for [Mantine](https://mantine.dev/) components library.
Here is my repository: https://github.com/zeretkk/mantine-dracula

**Comment by luxonauta** [comment]
Hey, that's very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/zeretkk/mantine-dracula)
- [New repository.](https://github.com/dracula/mantine)

Thanks for building this! 🎉
