### ISSUE TITLE
Dracula for CodeEdit

### ISSUE THREAD

**Issue by luanpiegas** [dracula/dracula-theme#877]
Hey, I just created a Dracula theme for [CodeEdit](https://github.com/CodeEditApp/CodeEdit), a code editor for macOS.

https://github.com/luanpiegas/CodeEdit-Dracula-Theme/

**Comment by luxonauta** [comment]
Hey, how cool! ✨
😅 But we need to get a few things straightened out before we add it to the organization!

We use a [template for our themes](https://github.com/dracula/template); this provides the standardized instructions, a Readme and an image of a screenshot of the themed app with its Dracula version.

✅ This is the only way we can, for example, list it on the website.

Let me know if you have any doubts! 🦇
