### ISSUE TITLE
Dracula Official theme not found in VSCode

### ISSUE THREAD

**Issue by brnsalg** [dracula/dracula-theme#878]
I installed vscode and when I went to look for the official dracula theme it just isn't there

**Comment by JSDTES** [comment]
I'm having the same issue. The official theme is nowhere to be found in VSCode,

**Comment by shawnhardernhippo** [comment]
missing for me as well

**Comment by luxonauta** [comment]
Thanks for reporting; I'm looking into it now and have contacted the Microsoft team. Also, friendly ping @dsifford 😅

**Comment by brnsalg** [comment]
this worked for me, **with VSCODE closed**

1. download the theme from official repo: https://github.com/dracula/visual-studio-code
2. rename the folder extracted to: dracula-theme.theme-dracula-2.24.2
3. open the vscode extension folder and paste the folder (dracula-theme.theme-dracula-2.24.2) (in linux is): '~/.vscode/extensions'
4. open the folder (dracula-theme.theme-dracula-2.24.2) and run in terminal: npm install; npm run build
5. open VSCODE and press CTRL+K CTRL+T (to open theme select), Dracula theme is appear

_if theme dont appear, do:_
**with VSCODE closed**

-  in VSCODE, CTRL+SHIFT+P and search: install extension from location (and select the folder dracula-theme.theme-dracula-2.24.2)

**maybe you need close and open VSCODE or run npm install; npm run build again**

sorry for bad english

**Comment by alexferreiraofc** [comment]
> this worked for me, **with VSCODE closed**
> 
> 1. download the theme from official repo: https://github.com/dracula/visual-studio-code
> 2. rename the folder extracted to: dracula-theme.theme-dracula-2.24.2
> 3. open the vscode extension folder and paste the folder (dracula-theme.theme-dracula-2.24.2) (in linux is): '~/.vscode/extensions'
> 4. open the folder (dracula-theme.theme-dracula-2.24.2) and run in terminal: npm install; npm run build
> 5. open VSCODE and press CTRL+K CTRL+T (to open theme select), Dracula theme is appear
> 
> _if theme dont appear, do:_ **with VSCODE closed**
> 
> * in VSCODE, CTRL+SHIFT+P and search: install extension from location (and select the folder dracula-theme.theme-dracula-2.24.2)
> 
> **maybe you need close and open VSCODE or run npm install; npm run build again**
> 
> sorry for bad english

It works! Thanks for sharing.

**Comment by dsifford** [comment]
Hm, very strange. It doesn't appear to be on the store. And there appears to be a [clear copy](https://marketplace.visualstudio.com/items?itemName=titouan.theme-dracula) of the theme under a different namespace.

Can you get in touch with the MS folks @luxonauta? I'm AFK for the rest of the day.

cc: @tyriar @mjbvz @jrieken

**Comment by dsifford** [comment]
I also reached out to the MS folks.. Seems like the extension was unpublished and locked suddenly, but it's not clear why.

I'll update as I hear back.

**Comment by Tyriar** [comment]
FYI @isidorn

**Comment by luxonauta** [comment]
Yes, I already sent an email, but still awaiting a response. 😅

**Comment by zenorocha** [comment]
I just sent an email to a few people I know from Microsoft to see if they can escalate the issue.

**Comment by isidorn** [comment]
Hi, VS Code PM here.
Thanks for reaching out. We have engaged with the VS Marketplace team and we are investigating what happened. I will provide details here as we find out more.

**Comment by isidorn** [comment]
We have located the issue and we have restored the dracula theme extension. It is again available on the Marketplace https://marketplace.visualstudio.com/items?itemName=dracula-theme.theme-dracula

This was an honest mistake of our team. We are actively working on removing copy-cat duplicate extensions that do not bring any real value, and by accident we removed the wrong extension. We are very sorry about this, and to apologise for this mistake we offer to Feature the Dracula extension on our Marketplace website when we do our next update in a couple of weeks. @seaniyer and me will work to make sure mistakes like this do not happen again in the future.

The issues was fixed by @madhurivadaligithub

Thank you for your understanding.

**Comment by brnsalg** [comment]
thanks!! closing this issue

**Comment by seaniyer** [comment]
> we offer to Feature the Dracula extension on our Marketplace website when we do our next update

Just dropping a closing note to let y'all know as promised we've featured [Dracula Theme](https://marketplace.visualstudio.com/publishers/dracula-theme) this month.  Cheers!
