### ISSUE TITLE
Adding a dracula theme for gh-dash

### ISSUE THREAD

**Issue by Janik-Haag** [dracula/dracula-theme#879]
## New Theme?

I created a theme for [gh-dash](https://github.com/dlvhdr/gh-dash) which can be found on [my profile](https://github.com/Janik-Haag/gh-dash)

**Comment by luxonauta** [comment]
Hi 🙋🏻‍♂️, it looks like the link provided there is broken 😅

**Comment by Janik-Haag** [comment]
Ah yeah I messed up sorry here is the correct one, messages is also edited https://github.com/Janik-Haag/gh-dash

**Comment by Janik-Haag** [comment]
Do I have to do anything else to get this added?

**Comment by luxonauta** [comment]
No, I do the rest of the process myself! Soon I'll be taking care of it! 😅

**Comment by Janik-Haag** [comment]
Take your time, I just wondered since I didn't get a response ^^

**Comment by luxonauta** [comment]
I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/Janik-Haag/gh-dash)
- [New repository.](https://github.com/dracula/gh-dash)

Thanks for building this! 🎉
