### ISSUE TITLE
Dracula Theme For IDEA

### ISSUE THREAD

**Issue by fenglangjunzi** [dracula/dracula-theme#881]
<img width="813" alt="image" src="https://github.com/dracula/dracula-theme/assets/5000975/9a7e6d14-1199-4a30-8ad6-70d89aa355c2">

The annotations will not be highlighted !

**Comment by fenglangjunzi** [comment]
Files in most formats such as java xml can be highlighted, but the html file cannot be highlighted！

**Comment by luxonauta** [comment]
Hi 👋🏻, thank you for your interest in providing this feedback. ✨

But there is a better place to share the same: the [project repository](https://github.com/dracula/jetbrains/issues/new), where you can talk to the theme maintainers 🟢 (@WhiteVermouth).

✅ [Clicking here](https://github.com/dracula/jetbrains/issues/new), you can open an Issue on it.
