### ISSUE TITLE
KiCad theme seems to be inactive

### ISSUE THREAD

**Issue by 2231puppy** [dracula/dracula-theme#882]
Hello! The [KiCad Dracula theme](https://github.com/dracula/kicad) seems to be inactive and has been for a while. I ended up publishing the theme to the KiCad PCM (Plugin and Content Manager) under a different name, Vampire, but I think it'd be much better if one of these things happened:

1. The original creator of the theme, @bagnaram updates the official theme to have PCM support, and I delete my fork.
2. Someone, whether it's me or anyone else who's interested, takes ownership of the repo. I would delete my fork and an official PCM theme could be created.

Of course, I'm open to any ideas and suggestions.

Thanks for your time!

**Comment by 2231puppy** [comment]
Sorry, I hit enter by accident! I'll edit this issue in a moment.

**Comment by bagnaram** [comment]
I will take a stab at merging in the changes thanks for calling the attention - I have not updated my software

**Comment by luxonauta** [comment]
So let me know if there are any changes to the installation instructions, and we will redeploy to update them on the website. 💜
