### ISSUE TITLE
Add Sniffnet to supported applications

### ISSUE THREAD

**Issue by GyulyVGC** [dracula/dracula-theme#884]
I'd like to add [Sniffnet](https://github.com/GyulyVGC/sniffnet) among the apps supporting Dracula.

Repo created from template: https://github.com/GyulyVGC/sniffnet-dracula-theme/

Sniffnet natively supports Dracula, so there is actually no need to install the theme but I thought it was nice to have it featured anyway.

**Comment by luxonauta** [comment]
Hey, that's very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/GyulyVGC/sniffnet-dracula-theme)
- [New repository.](https://github.com/dracula/sniffnet)

Thanks for building this! 🎉

**Comment by GyulyVGC** [comment]
Thanks to you!

I've accepted the invitation to the organization.

Is there still something I can do to correctly display it on https://draculatheme.com/sniffnet os is it an automated process?

**Comment by luxonauta** [comment]
The `installs` and `list` of apps are cached in build-time, so soon, we will redeploy them! ✨
