### ISSUE TITLE
New Theme: Anne Pro 2

### ISSUE THREAD

**Issue by gildasio** [dracula/dracula-theme#885]
Anne Pro 2 is a mechanical keyboard:

https://github.com/gildasio/anne-pro-2

**Comment by luxonauta** [comment]
Hey, that's very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/gildasio/anne-pro-2)
- [New repository.](https://github.com/dracula/anne-pro-2)

Thanks for building this! 🎉
