### ISSUE TITLE
Dracula theme for Notesnook

### ISSUE THREAD

**Issue by c4ssiopei4** [dracula/dracula-theme#886]
https://github.com/c4ssiopei4/dracula-notesnook

**Comment by luxonauta** [comment]
Hey, that's very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/c4ssiopei4/dracula-notesnook)
- [New repository.](https://github.com/dracula/notesnook)

Thanks for building this! 🎉
