### ISSUE TITLE
Dracula for LCD Smartie

### ISSUE THREAD

**Issue by limbo666** [dracula/dracula-theme#887]
## New Theme - LCD Smartie
I would like to announce that a Dracula skin for LCD Smartie is available on: 
https://github.com/limbo666/Dracula_for_LCD_Smartie

FYI:
LCD Smartie is an open source software for Windows. It drives character LCD Screens and displays diagnostics and other informational messages to external hardware and virtual LCD screens.

**Comment by luxonauta** [comment]
Hey, that's very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/limbo666/Dracula_for_LCD_Smartie)
- [New repository.](https://github.com/dracula/lcd-smartie)

Thanks for building this! 🎉
