### ISSUE TITLE
chrome styling Issues  

### ISSUE THREAD

**Issue by hyjhbzzal** [dracula/dracula-theme#888]
I love this theme, but it just broke in my chrome. A purple line shows up across my URL bar.

**Comment by poiromaniax** [comment]
Me too
<img width="1626" alt="image" src="https://github.com/dracula/dracula-theme/assets/15910083/56e2ba7c-926e-4380-a41c-5cdcc74c9c26">

Chrome Version 116.0.5845.96

**Comment by luxonauta** [comment]
Hey, @nickimola, can you take a look at this? 🤔

**Comment by nickimola** [comment]
Hi
An update was released a couple of days ago which fixes the issue.
It is on version 3.2 oh the theme
