### ISSUE TITLE
Dracula for Tumblr

### ISSUE THREAD

**Issue by D-u-c-k-s-e-l** [dracula/dracula-theme#889]
I made dracula for Tumblr (custom css theme)

https://github.com/D-u-c-k-s-e-l/draculaForTumblr

**Comment by luxonauta** [comment]
Hey, that's very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/D-u-c-k-s-e-l/draculaForTumblr)
- [New repository.](https://github.com/dracula/tumblr)

Thanks for building this! 🎉
