### ISSUE TITLE
Add LabPlot to supported applications

### ISSUE THREAD

**Issue by Chrismettal** [dracula/dracula-theme#890]
I would like to add the currently being created LabPlot Dracula theme to the organization:

https://github.com/chrismettal/labplot-dracula

The theme consists of 3 parts, application, worksheet and color-map. The worksheet part is already done and currently being merged into LabPlots source. Application and color-map are pending creation.

Installation instructions for manual installation from the repo need to be added yet, but can be removed once a version of LabPlot is released that has the theme in the source.

**Comment by luxonauta** [comment]
Hey, that's very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/Chrismettal/labplot-dracula)
- [New repository.](https://github.com/dracula/labplot)

Thanks for building this! 🎉
