### ISSUE TITLE
Port .Yaml to .toml

### ISSUE THREAD

**Issue by CarlosRivera4726** [dracula/dracula-theme#894]
## New Theme?

We would love to support all code editors out there, but we need your help to accomplish that. Feel free to create a new theme based on our [color palette](https://github.com/dracula/dracula-theme#color-palette).

## Existing Theme?

Find the appropriate repository on the [Dracula organization](https://github.com/dracula). This is just the umbrella place where we store all themes.

And remember - consider fixing the issue yourself. That's the best way to contribute ;)

i write all code from .yaml to .toml
`
[colors]
  primary = { background="#282a36", foreground="#f8f8f2", bright_foreground="#ffffff" }
  cursor = { text = "CellBackground", cursor = "CellForeground" }
  vi_mode_cursor = { text = "CellBackground", cursor = "CellForeground" }
  search = { matches={ foreground = "#44475a", background = "#50fa7b"}, focused_match= { foreground = "#44475a", background = "#ffb86c"} }
  footer_bar={ background= '#282a36', foreground= '#f8f8f2' }
  hints={ start= { foreground= '#282a36', background= '#f1fa8c' }, end={ foreground= '#f1fa8c', background= '#282a36'} }
  line_indicator={ foreground= "None", background= "None" }
  selection={ text = "CellForeground", background= '#44475a' }

  normal={ black= '#21222c', red= '#ff5555', green= '#50fa7b', yellow= '#f1fa8c', blue= '#bd93f9', magenta= '#ff79c6', cyan= '#8be9fd', white= '#f8f8f2'}
  bright={ black= '#6272a4', red= '#ff6e6e', green= '#69ff94', yellow= '#ffffa5', blue= '#d6acff', magenta= '#ff92df', cyan= '#a4ffff', white= '#ffffff'}

`

**Comment by luxonauta** [comment]
Hi 👋🏻 Carlos, can you elaborate more on your collaboration? The way it is, I don't understand it.

**Comment by CarlosRivera4726** [comment]
HI, the files .yaml is deprecated in newer versions of alacritty, they migrate to .toml files, is a new method for config files, more in my repository where i use your theme migrated and a basic config

**Comment by luxonauta** [comment]
✅ Nice! I understand a little better now.

Can you [do a PR on the Alacritty repo](https://github.com/dracula/alacritty/compare) so we can discuss this further? In addition, I'll 🟢 ping the maintainers @leandropincini and @clarfon.

**Comment by benknoble** [comment]
Assuming we migrate this over to the Alacritty repo, just note that (I think) the versions using TOML have not be officially released yet (there may be pre-releases).

**Comment by CarlosRivera4726** [comment]
Is officialy, is the new alacritty documentation

**Comment by benknoble** [comment]
Quite sure none of these [releases](https://github.com/alacritty/alacritty/releases) indicate that the configuration change has been released yet, but I'm willing to be shown where I'm wrong.

**Comment by benknoble** [comment]
The 0.13 release officially switched to TOML

**Comment by luxonauta** [comment]
https://github.com/dracula/alacritty/commit/9ae0fdedd423803f0401f6e7a23cd2bb88c175b2
