### ISSUE TITLE
Dracula in asciinema player

### ISSUE THREAD

**Issue by ku1ik** [dracula/dracula-theme#895]
Hi,

I'm the creator of [asciinema](https://asciinema.org) project. It's FOSS, non-commercial project. asciinema includes Dracula theme on the community hosting site (https://asciinema.org), as well as in the self-hosted JS player (https://github.com/asciinema/asciinema-player#theme). The theme is here https://github.com/asciinema/asciinema-player/blob/develop/src/less/themes/_dracula.less and it's included in player's CSS bundle, there's nothing extra to download/install.

https://asciinema.org/a/TEDV5LByUacc78o2cKKrJ4ZF1

I was wondering if it would be possible to include asciinema on the list at https://draculatheme.com/

Usage instructions could be something like this:

---

Dracula theme is bundled in asciinema player CSS since version 3.6.1. To use it pass `theme: 'dracula'` option when initializing the player on your page:

```javascript
AsciinemaPlayer.create('/demo.cast', document.getElementById('demo'), {
  theme: 'dracula'
});
```

More on theme support in asciinema player: https://github.com/asciinema/asciinema-player#theme

---

Thanks!

**Comment by ku1ik** [comment]
Do you want me to open a PR, or not interested in this?

**Comment by luxonauta** [comment]
Sorry for the delay; we've been working on many updates!

It would be fantastic if you could make a repo like this template: https://github.com/dracula/template

🫱🏻‍🫲🏻 Here on this page is a complete guide to contributing: https://draculatheme.com/contribute
