### ISSUE TITLE
https://github.com/0xFOSSMan/dracula-thumb-key

### ISSUE THREAD

**Issue by 0xFOSSMan** [dracula/dracula-theme#896]
## New Theme?

We would love to support all code editors out there, but we need your help to accomplish that. Feel free to create a new theme based on our [color palette](https://github.com/dracula/dracula-theme#color-palette).

## Existing Theme?

Find the appropriate repository on the [Dracula organization](https://github.com/dracula). This is just the umbrella place where we store all themes.

And remember - consider fixing the issue yourself. That's the best way to contribute ;)

**Comment by luxonauta** [comment]
Hey, that's very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/0xFOSSMan/dracula-thumb-key)
- [New repository.](https://github.com/dracula/thumb-key)

Thanks for building this! 🎉
