### ISSUE TITLE
Issues in PopOS GTK

### ISSUE THREAD

**Issue by alirezaalavi87** [dracula/dracula-theme#898]
https://github.com/dracula/gtk

Hi, and thanks for the great dracula project.

I have downloaded the GTK theme, put it into `/usr/share/themes/Dracula` , installed gnome tweaks and and gnome-shell-extension-manager. I have installed the user-themes extention, and from extention manager set theme to Dracula. also from gnome tweaks, have set applications theme and shell theme to dracula. 

I have faced two issues:
1. first is that the dock gets an outline:
![image](https://github.com/dracula/dracula-theme/assets/63902085/36bef0d3-30ff-475c-80f5-c54c1d16bdec)

second is that by setting application theme to Dracula, It's like the dark theme isn't applied (for example selected field should be some grayish, not white) :
![image](https://github.com/dracula/dracula-theme/assets/63902085/c60580ec-f5d6-4c36-9da1-c38e6a964749)

**Comment by luxonauta** [comment]
Hi 👋🏻 Alireza,

Thank you so much for your interest in providing this feedback. ✨

But there is a better place to share the same, which is the project repository, where you can talk to the theme maintainers.

There, @EliverLara could help you, as he is the current maintainer.
