### ISSUE TITLE
Google Calendar - New Theme

### ISSUE THREAD

**Issue by accountingnerd** [dracula/dracula-theme#901]
I created a theme for Google Calendar. I've enjoyed using it, and thought maybe the community would like it as well.

I'm an accountant more than a designer, so if there are critiques or fixes that I could address, I'm happy to do so.

Here's the repository: https://github.com/accountingnerd/google-calendar/

Thanks, team!

**Comment by luxonauta** [comment]
Hey, that's very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/accountingnerd/google-calendar)
- [New repository.](https://github.com/dracula/google-calendar)

Thanks for building this! 🎉
