### ISSUE TITLE
SmartGit - New Theme

### ISSUE THREAD

**Issue by Subtixx** [dracula/dracula-theme#902]
## What is SmartGit?

SmartGit is a Git GUI client with support for GitHub, BitBucket, GitLab pull requests and comments. SmartGit targets professional users.

## How does it look?
![](https://github.com/IT-Hock/dracula-smartgit/raw/master/screenshot.png)

## Repository

https://github.com/IT-Hock/dracula-smartgit

## Additional Note

There are some "bugs" in the theme, like the button text sometimes is unreadable because the foreground color is dark gray. I'm looking into a way to fix it.

**Comment by luxonauta** [comment]
Hey, that's very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/IT-Hock/dracula-smartgit)
- [New repository.](https://github.com/dracula/smartgit)

Thanks for building this! 🎉
