### ISSUE TITLE
Dracula theme for Homepage

### ISSUE THREAD

**Issue by mmozzano** [dracula/dracula-theme#903]
## Dracula theme for [Homepage](https://gethomepage.dev)

I've been previously using [Homer](https://github.com/bastienwirtz/homer) for my homelab dashboard alongside the excellent [Dracula Homer theme](https://draculatheme.com/homer) however I've recently moved over to [Homepage](https://gethomepage.dev).

There was no Dracula theme for Homepage so I decided to start putting one together.  The link to the repo is:

https://github.com/mmozzano/dracula-homepage

![Screenshot](https://github.com/mmozzano/dracula-homepage/blob/fb07ee83fad0b6efafd136d5939e65b37ed3cb14/screenshot.png)

I need to refine the theme to utilise more of the Dracula colour palette but I thought I'd share just in case anyone is interested.

**Comment by luxonauta** [comment]
Hey, that's very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/mmozzano/dracula-homepage)
- [New repository.](https://github.com/dracula/homepage)

Thanks for building this! 🎉
