### ISSUE TITLE
Dracula theme for FontForge

### ISSUE THREAD

**Issue by walpox** [dracula/dracula-theme#905]
This is a feature request to add this dark theme for FontForge to Dracula.
<https://github.com/walpox/fontforge>

**Comment by luxonauta** [comment]
Hey, that's very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/walpox/fontforge)
- [New repository.](https://github.com/dracula/fontforge)

Thanks for building this! 🎉
