### ISSUE TITLE
It's not working properly for version 8.0 (Windows)

### ISSUE THREAD

**Issue by Shiroo77** [dracula/dracula-theme#906]
![image](https://github.com/dracula/dracula-theme/assets/141759574/d0dfe4df-88c5-4c1c-ad77-164d24ad7c1c)

I've properly followed the steps mentioned here : https://draculatheme.com/mysql-workbench

Dark theme is not being applied to entire workbench, Just the code editor ! 

Any suggestions ? How can I resolve this ?

Thank You !

**Comment by samuior98** [comment]
Idem for me. Not change the other part of the workbench.

**Comment by Shiroo77** [comment]
> Idem for me. Not change the other part of the workbench.

Have you found the fix yet ?? The light mode is really annoying 
On mac it's working properly but on windows it's not :(

**Comment by samuior98** [comment]
no fix found
