### ISSUE TITLE
GKrellM - New Theme

### ISSUE THREAD

**Issue by timsan7sk** [dracula/dracula-theme#909]
Hello team!
I created a theme for GKrellM. I've enjoyed using it, and thought maybe the community would like it as well.
Here's the repository: https://github.com/timsan7sk/Dracula

--
Best regards,
timsan

**Comment by luxonauta** [comment]
Hey, that's very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/timsan7sk/Dracula)
- [New repository.](https://github.com/dracula/gkrellm)

Thanks for building this! 🎉
