### ISSUE TITLE
A yellow inconsistency

### ISSUE THREAD

**Issue by IGLOU-EU** [dracula/dracula-theme#911]
Hi dear fellow vampires, in this dark night I found a yellow inconsistency :scream: 
Between the yellow into the website and the yellow into the "Color Palette"

Color Palette: #F1FA8C
Dark Side: #F2F256

![shot-2023-10-31_17-57-50](https://github.com/dracula/dracula-theme/assets/15379333/e95488ae-032e-49bf-a8be-e72209dd4f4e)

**Comment by IGLOU-EU** [comment]
The trouble is begger then expected

Web site color:
```
  --cyan: #5cf5f5;
  --green: #66f859;
  --orange: #f8b659;
  --pink: #f859a8;
  --purple: #7359f8;
  --red: #f87359;
  --yellow: #f8f859;
```

Official color
![shot-2023-11-03_17-15-03](https://github.com/dracula/dracula-theme/assets/15379333/c5e28050-6a97-44a6-b46a-7cbb8689c71f)

**Comment by luxonauta** [comment]
Hahaha, it's cool that you noticed; you were among the first people! What happened is that the website was rebuilt with the colours of Dracula PRO and not the Classic, with some adjustments due to contrast on the web. 🫡💜

**Comment by IGLOU-EU** [comment]
Hi @luxonauta, thanks for the reply. 
But Dracula PRO a proprietary ? Or can we propose some Dracula PRO into the Dracula template ? :disappointed:

**Comment by IGLOU-EU** [comment]
Ho... this is sad. Consider releasing it as free software, free not like a free beer :disappointed:
