### ISSUE TITLE
Dracula theme for Chatterino

### ISSUE THREAD

**Issue by iSpace202** [dracula/dracula-theme#914]
Made this theme for Chatterino! 😁

https://github.com/iSpace202/Dracula-for-Chatterino/

**Comment by luxonauta** [comment]
Hey, that's very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/iSpace202/Dracula-for-Chatterino)
- [New repository.](https://github.com/dracula/chatterino)

Thanks for building this! 🎉
