### ISSUE TITLE
Dracula for Helix editor

### ISSUE THREAD

**Issue by zoedsoupe** [dracula/dracula-theme#917]
[Helix](https://github.com/helix-editor/helix) is a post-modern modal editor, has native tree-sitter and LSP integrations and use base16 themes. There’s already a attempt to implement dracula for `helix` however the existing theme doesn’t seem to match the official specs and doesn’t integrate very well with treesitter.

Below an example of an Elixir code in `helix` and `neovim` both with dracula theme applied:

Helix:
<img width="1083" alt="Screenshot 2023-11-27 at 22 53 15" src="https://github.com/dracula/dracula-theme/assets/44469426/6af52c33-2391-427b-9da7-480f6b255bfa">

Neovim:
<img width="1083" alt="Screenshot 2023-11-27 at 23 01 33" src="https://github.com/dracula/dracula-theme/assets/44469426/b7dc3513-7dab-43f3-a0fb-689de4ab5d77">

I ‘ll try to create an official port of this theme, but I’m very noob on theme creation, so any help and/or amterial would be awesome. I’ll reference the vim theme, although I ain’t used to vimscript.

**Comment by zoedsoupe** [comment]
Also it seems so different from the visual studio code one! Does anyone is porting the vim theme to use treesitter?

<img width="1136" alt="Screenshot 2023-11-27 at 23 08 43" src="https://github.com/dracula/dracula-theme/assets/44469426/fee4603e-fd5e-479f-9d35-bf5c0df230b7">

**Comment by luxonauta** [comment]
Hi Zoey, would you like to try an iteration to improve this? 😅

As much as I would like to help with this (and all others), I can't do so now. This is why the community is essential for this project to continue evolving. 🌱

✅ Please tell me if I can help you unblock something!

**Comment by zoedsoupe** [comment]
Yeah, I'll give it a try! I never wrote a theme but helix theme API is so simple and it uses tree-sitter natively, so I think I could have success on this port.

Does you have any recommendations or tips for writing/porting a theme?

**Comment by Akagi201** [comment]
It's already included in helix.
https://github.com/helix-editor/helix/blob/master/runtime/themes/dracula.toml

**Comment by luxonauta** [comment]
Still, we would need the instructions in the template format to display and list on the website. I'm a little overwhelmed at the moment, so let me know if you can and want to do it. 😅

**Comment by zoedsoupe** [comment]
> It's already included in helix. https://github.com/helix-editor/helix/blob/master/runtime/themes/dracula.toml

that's not so simple. i don't know dracula colors semantics

**Comment by benknoble** [comment]
See spec.draculatheme.com, and note that differences in appearance between editors is normal due to different implementations of syntax highlighting.
