### ISSUE TITLE
Dracula Port for Papirus Folder-Icons

### ISSUE THREAD

**Issue by Vibhav201** [dracula/dracula-theme#918]
Here is my repo for Papirus-Folder Icons created according to the instructions on https://draculatheme.com/contribute. 

Link :  https://github.com/Vibhav201/Dracula-Papirus

Just to be clear I've created this theme for the folder icons for the [Papirus Icon Theme](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme) and it has to be used in conjunction with [this](https://github.com/PapirusDevelopmentTeam/papirus-folders) script. 

[Here](https://github.com/catppuccin/papirus-folders) is the similar port for the catppuccin theme.

Other details are in my repo. Hope this gets accepted.

**Comment by luxonauta** [comment]
Hey, that's very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/Vibhav201/Dracula-Papirus)
- [New repository.](https://github.com/dracula/papirus-folders)

Thanks for building this! 🎉
