### ISSUE TITLE
Dracula Theme for Swaylock.

### ISSUE THREAD

**Issue by cosmicwanderer7** [dracula/dracula-theme#920]
Repository for Swaylock Theme - Improved Version

Link: [Swaylock Dracula Theme](https://github.com/cosmicwanderer7/swaylock)

Hello 👋

I'm excited to share my Swaylock theme, an improved version inspired by the [Dracula Swaylock Theme](https://github.com/dracula/swaylock) maintained by [milkknife](https://github.com/milkknife).

Features:

Enhanced aesthetics for a pleasing lock screen experience.
Designed to complement the Dracula theme for a cohesive look.
Follows best practices outlined in the [Dracula Theme Contribution Guidelines](https://draculatheme.com/contribute).
Usage:

Clone or download the repository.
Integrate with the existing Dracula Theme for a complete visual overhaul.
Feel free to explore the [repository](https://github.com/cosmicwanderer7/swaylock) for more details and customization options.

Your feedback and contributions are highly welcome.

**Comment by luxonauta** [comment]
This is exceptionally cool! Let's do the following: I will add you as a collaborator in our repo. What do you think?

**Comment by cosmicwanderer7** [comment]
Absolutely, that sounds fantastic!

**Comment by cosmicwanderer7** [comment]
Should I open a pull request to make the changes?

**Comment by luxonauta** [comment]
I just sent you the invitation. I'm sorry for the delay. I believe that @milkknife is no longer on Github, so if you could become the theme maintainer, that would be great! ✨

**Comment by cosmicwanderer7** [comment]
Yes I would like to become the theme maintainer.
