### ISSUE TITLE
Dracula theme for tut

### ISSUE THREAD

**Issue by RastalDev** [dracula/dracula-theme#923]
Here is my Dracula theme for tut.

[tut](https://github.com/RasmusLindroth/tut) is a terminal user interface for Mastodon.

[Mastodon](https://joinmastodon.org/) is a decentralised social network.

[Link to my Dracula theme for tut repository](https://github.com/RastalDev/dracula_tut).

**Comment by luxonauta** [comment]
Hey, that's very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/RastalDev/dracula_tut)
- [New repository.](https://github.com/dracula/tut)

Thanks for building this! 🎉
