### ISSUE TITLE
Dracula for Homepage w/ Dracula themed icons for open-source apps.

### ISSUE THREAD

**Issue by Jas-SinghFSU** [dracula/dracula-theme#924]
# Theme
I'm creating a [theme](https://github.com/Jas-SinghFSU/homepage-dracula) for the dashboard [Homepage](https://github.com/gethomepage/homepage) which is one of the most popular dashboards for the self-hosting community. My goal is to continuously support this project to be compatible with all new Homepage features.

Preview:
<p align="center">
  <img src="https://github.com/Jas-SinghFSU/homepage-dracula/blob/main/homepage-dracula.png?raw=true" />
</p>

# Icons
But more importantly, I have created and am in the process of creating Dracula themed icons for most (or all, which is the ultimate goal) open-source [dashboard icons listed here](https://github.com/walkxcode/dashboard-icons/blob/main/ICONS.md), 

The modified icons can be previewed [here](https://github.com/Jas-SinghFSU/homepage-dracula/blob/main/icons-preview.md).

The plan is full (or close to) completion.

**Comment by luxonauta** [comment]
This is fantastic; let's create a template and publish it on the website; you can follow the steps from here: [https://draculatheme.com/contribute](https://draculatheme.com/contribute)

**Comment by Jas-SinghFSU** [comment]
> let's create a template  

I have created a template in the repository https://github.com/Jas-SinghFSU/homepage-dracula . Please let me know if I need to change something, I think that follows the template?

**Comment by Jas-SinghFSU** [comment]
I wonder if I should host the icons in a separate repository? That way people that want to use them outside of just homepage can do so. Something like Dracula-Icons.

**Comment by luxonauta** [comment]
The same repo is better! 😅

**Comment by luxonauta** [comment]
Hi 👋🏻 @Jas-SinghFSU and @mmozzano,

🌱 Quick updates:

1. I've archived the [old repository](https://github.com/dracula/homepage) and set up the new one: [homepage-app](https://github.com/dracula/homepage-app);
2. It wasn't listed on our website, which I'll rectify! 🧙🏻
3. As maintainers of this new repo, I'm excited to see your collaboration;
4. Please email _support@draculatheme.com_ for a follow-up and a **gift** of thanks! 😉

I'm sorry for the delay. I'll make sure to communicate better in the future. Please feel free to reach out if you need any assistance.

**Comment by Jas-SinghFSU** [comment]
Hi @luxonauta 👋 ! Thank you for the updates and no worries about the delay, I understand that you're busy.
