### ISSUE TITLE
New Theme for lichess.org

### ISSUE THREAD

**Issue by jonathan-scholbach** [dracula/dracula-theme#926]
I created a dracula theme for https://lichess.org. The theme comes as a css file which can be installed with stylus. 

I would love to share it here with the community.

The repository is at https://github.com/jonathan-scholbach/dracula-lichess

**Comment by jonathan-scholbach** [comment]
Are there any blockers I could help remove? @luxonauta

**Comment by luxonauta** [comment]
Hey 👋🏻, Jonathan, that's very cool! ✨

Sorry for the delay! 😅

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/jonathan-scholbach/dracula-lichess)
- [New repository.](https://github.com/dracula/lichess)

💜 Please email [support@draculatheme.com](mailto:support@draculatheme.com) for a follow-up and a gift of thanks! 😉

Thanks for building this! 🎉
