### ISSUE TITLE
Dracula for Stirling-PDF

### ISSUE THREAD

**Issue by Jas-SinghFSU** [dracula/dracula-theme#927]
Repository and instructions: https://github.com/Jas-SinghFSU/stirlingpdf-dracula
App the theme is for: https://github.com/Frooodle/Stirling-PDF

Stirling-PDF is an open-source PDF manipulation tool.

**Comment by luxonauta** [comment]
Hey, that's very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/Jas-SinghFSU/stirlingpdf-dracula)
- [New repository.](https://github.com/dracula/stirling-pdf)

Thanks for building this! 🎉

**Comment by luxonauta** [comment]
Also, 💜 please email [support@draculatheme.com](mailto:support@draculatheme.com) for a follow-up and a gift of thanks!
