### ISSUE TITLE
Dracula Theme Heroic Games Launcher

### ISSUE THREAD

**Issue by ANYAYASS** [dracula/dracula-theme#928]
Heroic Games Launcher

Predefined Theme

**Comment by ANYAYASS** [comment]
here is the link 
https://github.com/ANYAYASS/Dracula-Theme-Heroic-Games-Launcher

**Comment by luxonauta** [comment]
Hey, that's very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/ANYAYASS/Dracula-Theme-Heroic-Games-Launcher)
- [New repository.](https://github.com/dracula/heroic-games-launcher)

Thanks for building this! 🎉

**Comment by luxonauta** [comment]
Also, 💜 please email [support@draculatheme.com](mailto:support@draculatheme.com) for a follow-up and a gift of thanks!
