### ISSUE TITLE
Duolingo Dark Theme

### ISSUE THREAD

**Issue by sonofactgnrd** [dracula/dracula-theme#931]
New Theme
Duolingo Dark Theme

[The repository](https://github.com/sonofactgnrd/Duolingo-Dark-Mode)
![Screenshot](https://github.com/dracula/dracula-theme/assets/136293967/06b7ed4f-00ec-43a4-947d-cff032873fef)
An example of what it looks like.

I would love any constructive criticism

**Comment by luxonauta** [comment]
Hey, that's very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/sonofactgnrd/Duolingo-Dracula)
- [New repository.](https://github.com/dracula/duolingo)

Thanks for building this! 🎉

**Comment by luxonauta** [comment]
Also, 💜 please email [support@draculatheme.com](mailto:support@draculatheme.com) for a follow-up and a gift of thanks!
