### ISSUE TITLE
Dracula theme for Prompt terminal application

### ISSUE THREAD

**Issue by k7hpn** [dracula/dracula-theme#932]
I have created a new Dracula theme for the [Prompt](https://panic.com/prompt/) terminal application for Mac and iOS.

- Currently it lives in [k7hpn/prompt](https://github.com/k7hpn/prompt)

Please let me know if there's anything else you need from me!

**Comment by luxonauta** [comment]
Hey, that's very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/k7hpn/prompt)
- [New repository.](https://github.com/dracula/prompt)

Thanks for building this! 🎉

**Comment by luxonauta** [comment]
Also, 💜 please email [support@draculatheme.com](mailto:support@draculatheme.com) for a follow-up and a gift of thanks!
