### ISSUE TITLE
Edge browser has enabled vertical tabs, all the vertical tabs are white in color.

### ISSUE THREAD

**Issue by Pnut-GGG** [dracula/dracula-theme#933]
## Existing Theme
dracula for edge

My Edge browser has enabled vertical tabs, but all the vertical tabs are white in color.

Windows 11 Microsoft Edge 121.0.2277.83 (64 bit)

**Comment by luxonauta** [comment]
Hi 👋🏻, thanks for your interest in providing this feedback. ✨

But there is a better place to share this information: [the project repository](https://github.com/dracula/microsoft-edge/issues/new), where you can talk to the theme maintainer, cc @hudsonm62 😅

✅ [Clicking here](https://github.com/dracula/microsoft-edge/issues/new), you can open an Issue on it.
