### ISSUE TITLE
Zed theme

### ISSUE THREAD

**Issue by Otterpocket** [dracula/dracula-theme#935]
## New Theme?

Started building dracula for zed.

https://github.com/Otterpocket/zed-dracula-theme

### Notes
- terminal colours still need work
- certain specific syntax styles missing, such as Inherited classes being italic. (Possibly limitations of the syntax highlighting?)

**Comment by luxonauta** [comment]
Hey, that's very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/Otterpocket/zed-dracula-theme)
- [New repository.](https://github.com/dracula/zed)

Thanks for building this! 🎉

**Comment by luxonauta** [comment]
Also, 💜 Please email [support@draculatheme.com](mailto:support@draculatheme.com) for a follow-up and a gift of thanks!
