### ISSUE TITLE
Dracula theme for CadZinho

### ISSUE THREAD

**Issue by zecruel** [dracula/dracula-theme#939]
[CadZinho](https://github.com/zecruel/CadZinho) is a Computer Aided Design (CAD) software, aimed at a desktop application for 2D technical drawings.

Now with Dracula theme:

![dracula](https://github.com/dracula/dracula-theme/assets/17029180/065febc9-a236-4482-9e5f-a168efb17e3e)

**Comment by luxonauta** [comment]
Hey 👋🏻 @zecruel,

Please create a repo based on [this template](https://github.com/dracula/template) to include the theme you made. 😊

> [Here are some instructions on how to do it.](https://draculatheme.com/contribute)

**Comment by zecruel** [comment]
> Hey 👋🏻 @zecruel,
> 
> Please create a repo based on [this template](https://github.com/dracula/template) to include the theme you made. 😊
> 
> > [Here are some instructions on how to do it.](https://draculatheme.com/contribute)

Everythings alright now: [CadZinho-dracula_theme](https://github.com/zecruel/CadZinho-dracula_theme)

**Comment by luxonauta** [comment]
Hey, that's very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/zecruel/CadZinho-dracula_theme)
- [New repository.](https://github.com/dracula/cadzinho)

Thanks for building this! 🎉
