### ISSUE TITLE
New Theme for Windows PowerShell ISE 🔌

### ISSUE THREAD

**Issue by StarKev** [dracula/dracula-theme#940]
## Description

 

Hello if I’m wrong by there is no theme for PowerShell ISE yet. My theme that I realized uses your colors and I want to know if my proposal would accept (the theme applies to the console and the script) and I would like to have more information to put my theme. I am of Swiss origin so in the screenshots there are chances that there are some terms in French.

 

Anyway I hope my theme will be accepted and here is the [link](https://github.com/StarKev/powershell_ISE)

**Comment by luxonauta** [comment]
Hey, that's very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/StarKev/powershell_ISE)
- [New repository.](https://github.com/dracula/powershell-ise)

Thanks for building this! 🎉
