### ISSUE TITLE
XFCE4 panel icons' background is always solid rather than  transparent

### ISSUE THREAD

**Issue by Lamb666** [dracula/dracula-theme#941]
When I add launchers to the panel, the icons' background is solid color, rather than transparent.
Even when I set the panel's background to transparent, it's still solid.
This problem is not present in other themes.
![image](https://github.com/dracula/dracula-theme/assets/32459505/096b96db-3f7c-4d26-98ea-3908436c451b)

**Comment by luxonauta** [comment]
Hi 👋🏻, thanks for your interest in providing this feedback. ✨

But there is a better place to share it: the project repository, where you can talk to the theme maintainers, cc @kuangyujing

✅ [Clicking here](https://github.com/dracula/xfce4-terminal), you can open an Issue on it.
