### ISSUE TITLE
Subsonic Dracula Theme

### ISSUE THREAD

**Issue by octaviz** [dracula/dracula-theme#944]
## 🌱 New Theme?

New theme for Subsonic, server music

https://github.com/octaviz/subsonic-dracula-theme

<img width="1497" alt="screen" src="https://github.com/dracula/dracula-theme/assets/856579/05c5bce9-61a4-4c6c-8fd2-1ba0b6d154c2">

**Comment by luxonauta** [comment]
Hey, that's very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/octaviz/subsonic-dracula-theme)
- [New repository.](https://github.com/dracula/subsonic)

Thanks for building this! 🎉
