### ISSUE TITLE
HyperOS by Xiaomi drakula theme

### ISSUE THREAD

**Issue by orabeidm** [dracula/dracula-theme#945]
In the world, there is a huge number of Android phones, with a significant portion being Xiaomi or Poco phones. However, using custom launchers on these devices prohibits the use of gesture navigation, unlocking the bootloader, flashing custom recovery, or finding a suitable port of AOSP or Pixel Experience firmware or GSI to transform the firmware. Not every user can or wants to deal with these tasks.

Perhaps there are people here knowledgeable enough about the system to create a native Dracula theme for HyperOS by Xiaomi that can be enabled with a single click on the screen?

**Comment by sionta** [comment]
Take a look at this reference it might help you https://zhuti.designer.intl.xiaomi.com/theme-competition-2023/guide
