### ISSUE TITLE
[New Theme] Backstage.io Dracula theme

### ISSUE THREAD

**Issue by fjudith** [dracula/dracula-theme#946]
Hello community !

I created a theme for Backstage, the popular internal development portal donated by Spotify to the Cloud Native Computing Founation (CNCF) under the umbrella of the Linux Foundation.

I will be happy to maintain it as i also participate to plugin development and stabilization.

The overall theming orientation is very close to the Visual Studio Code theme.

**project**:  <https://github.com/fjudith/backstage-dracula>

![Picture](https://github.com/fjudith/backstage-dracula/blob/main/screenshot.png?raw=true)
![image](https://github.com/dracula/dracula-theme/assets/17888379/9278e985-1471-46e0-a553-da6078bbc254)

**Comment by luxonauta** [comment]
Hey, that's very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/fjudith/backstage-dracula)
- [New repository.](https://github.com/dracula/backstage)

Thanks for building this! 🎉
