### ISSUE TITLE
Windows PowerShell ISE

### ISSUE THREAD

**Issue by kawells** [dracula/dracula-theme#947]
I noticed the PowerShell ISE theme no longer exists in the official repository, so I remade it as closely as possible to the existing PowerShell and VS Code themes.

[Dracula for Windows PowerShell ISE](https://github.com/kawells/dracula-powershell-ise)

**Comment by StarKev** [comment]
Hello it's been more than a month since I proposed a theme for powershell ise and for him in 3 days it's assigned. I do not want to be rude but what is this bullshit. thank you for your attention and understanding

**Comment by luxonauta** [comment]
Hey 👋🏻 folks,

Thanks for submitting the app theme. We understand the importance of keeping you informed about the progress of your submissions and apologize for the delay. 🙇🏻

> However, please avoid using offensive words or aggressively expressing displeasure. We are a small team and often need to prioritize one task at a time.

✅ With this in mind, I have transferred the submitted theme first and invited both to collaborate directly in the repository.
