### ISSUE TITLE
[New Theme] nnn

### ISSUE THREAD

**Issue by staal0** [dracula/dracula-theme#948]
Added Dracula to nnn filemanager: https://github.com/staal0/nnn

**Comment by luxonauta** [comment]
Hey, that's very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/staal0/nnn)
- [New repository.](https://github.com/dracula/nnn)

Thanks for building this! 🎉
