### ISSUE TITLE
Dracula theme for GtkSourceView

### ISSUE THREAD

**Issue by solbero** [dracula/dracula-theme#955]
Here is a Dracula [theme](https://github.com/solbero/gtksourceview) for [GtkSourceView](https://wiki.gnome.org/Projects/GtkSourceView). It is the library that provides syntax highlighting for [GNOME Builder](https://apps.gnome.org/Builder/) and [GNOME Text Editor](https://apps.gnome.org/TextEditor/).

A theme for GtkSourceView has been submitted earlier in https://github.com/dracula/dracula-theme/issues/566, but it is marked as inactive. I have created this new implementation using [Schemes](https://gitlab.gnome.org/chergert/schemes).

To make the theme easier to discover, it might be an idea to create additional, separate theme repositories for GNOME Builder and GNOME Text Editor. The install instructions for the two applications, however, will be identical to GtkSourceView.

**Comment by solbero** [comment]
Any update on this? I can see my other contribution has been assigned, while this one has not.

**Comment by luxonauta** [comment]
Hey, that's very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/solbero/gtksourceview)
- [New repository.](https://github.com/dracula/gtksourceview)

Thanks for building this! 🎉
