### ISSUE TITLE
Dracula Powerlevel10k theme Oh My Posh

### ISSUE THREAD

**Issue by Festiis** [dracula/dracula-theme#956]
## 🌱 New Theme

I have made a Dracula Powerlevel10k theme for Oh My Posh.

[Dracula Powerlevel10k for Oh My Posh](https://github.com/Festiis/p10k-oh-my-posh)

**Comment by luxonauta** [comment]
Hey, that's very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/Festiis/p10k-oh-my-posh)
- [New repository.](https://github.com/dracula/p10k-oh-my-posh)

Thanks for building this! 🎉
