### ISSUE TITLE
Dracula theme for OpenSCAD

### ISSUE THREAD

**Issue by solbero** [dracula/dracula-theme#958]
## 🌱 New Theme

Dracula theme for [OpenSCAD](https://openscad.org/).

Repository: [https://github.com/solbero/openscad](https://github.com/solbero/openscad)

**Comment by luxonauta** [comment]
Hey, that's very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/solbero/openscad)
- [New repository.](https://github.com/dracula/openscad)

Thanks for building this! 🎉
