### ISSUE TITLE
Dracula theme for AdiIRC

### ISSUE THREAD

**Issue by zeretkk** [dracula/dracula-theme#960]
## 🌱 New Theme

Implement dracula colors in the AdiIRC client

repo: [zeretkk/dracula-adiirc](https://github.com/zeretkk/dracula-adiirc)

**Comment by luxonauta** [comment]
Hey, that's very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/zeretkk/dracula-adiirc)
- [New repository.](https://github.com/dracula/adiirc)

Thanks for building this! 🎉
