### ISSUE TITLE
New Alucard theme is not accessible

### ISSUE THREAD

**Issue by KarChung-Konstant** [dracula/dracula-theme#964]
I'm exicited about the new color theme but it seems still not mature yet. What I mean is that the code highlighting seems all black to me since they are not that 'obvious' compare to dark theme. Especially in PHP file.

**Comment by luxonauta** [comment]
Could you provide more examples so we can improve the experience for you and others facing the same difficulties? 😊

When we created the theme, we wanted it to be accessible, so we tested and refined all the colours to meet AAA standards (for fonts above 16) and AA standards (for fonts smaller than 16).

✅ However, there is always room for improvement, so feedback is essential!

**Comment by KarChung-Konstant** [comment]
![alucard](https://github.com/dracula/dracula-theme/assets/173343776/6a79d1cb-9252-45f7-b6b5-d3b872d689ca)
![dracula](https://github.com/dracula/dracula-theme/assets/173343776/158d6250-bb1b-4d19-b788-a56114c73dda)

Please have a look at the above images.
Let's start with line 1. let's say I want to look for the function name, the color highlighting here is actually not helpful because the green is really not that obvious, I can't even identify what color is it if I don't look carefully. So I have to do it in traditional way by reading from left instead of catching the function name directly by its color highlighting.

Now let's go to line 3, is it actually that much difference between the black and the green? I mean if you step away from the monitor, they all look like black. Same goes to the yellow.

What I'm trying to say is that the current color highlighting for Alucard looks like all black to me such as words on a white paper. The color contrast is not that obvious compare to Dracula which is fantastic.

**Comment by luxonauta** [comment]
I understand your concern regarding the contrast and difficulty distinguishing colours in the current Alucard variation. 😥

It is challenging to achieve the right balance between adequate contrast and compliance with the WCAG standard, especially for light themes.

While designing Alucard, we recognized that this could lead to less noticeable contrast for some elements than dark variants. However, we will continue to iterate on the palette of all variants to improve this. 🧩
