### ISSUE TITLE
icons too dark

### ISSUE THREAD

**Issue by maravento** [dracula/dracula-theme#966]
The icons are too dark, if applied on Ubuntu 24.04. You could create a lighter version of the icons, to highlight them among so much darkness
thank you

![Captura de pantalla -2024-07-15 09-45-36](https://github.com/user-attachments/assets/5289863b-6194-4175-b0c2-0ab5971c3101)

**Comment by benknoble** [comment]
I wouldn't call the reaction of one account which is otherwise completely unaffiliated with the project "offended." 

If you want traction on the issue, though, you need to take it to the right repo and provide some more clarity about what "too dark" means. (It is a dark theme, after all.)

**Comment by benknoble** [comment]
A fair problem, but one that should probably be discussed in the right place. Which application are you using with the problem?

**Comment by benknoble** [comment]
I don't know, that's why I asked. Are you using https://github.com/dracula/gtk or something else?

**Comment by benknoble** [comment]
@EliverLara Do you want to transfer this issue to https://github.com/dracula/gtk?
