### ISSUE TITLE
red bracket is very strange

### ISSUE THREAD

**Issue by llzmgjzhy** [dracula/dracula-theme#968]
platform: vscode extension dracula-theme.theme-dracula
version: v2.25.0
description: the python bracket is red,that is very stange
![image](https://github.com/user-attachments/assets/b89fc950-cd8b-4b23-81fe-3751e0961df7)

**Comment by pablomuroovo** [comment]
Can we edit in some place the new version to look like the older version?

**Comment by eric-kreis** [comment]
It's still not the best solution. But if you want to improve this situation at least slightly, paste the following code into your settings.json.

```json
{
    "workbench.colorCustomizations": {
        "[Dracula Theme]": {
            "editorBracketHighlight.foreground1": "#FFD700",  // Gold
            "editorBracketHighlight.foreground2": "#DA70D6",  // Orchid
            "editorBracketHighlight.foreground3": "#87CEFA",  // Light Sky Blue
            "editorBracketHighlight.foreground4": "#32CD32",  // Lime Green
            "editorBracketHighlight.foreground5": "#FFA500",  // Orange
            "editorBracketHighlight.foreground6": "#BA55D3"   // Medium Orchid
        }
    }
}
```

**Comment by eric-kreis** [comment]
Another way is to install the past version, `2.23.3`.

![image](https://github.com/user-attachments/assets/5110b251-9701-4f74-a00c-5a0afee2f6c2)

**Comment by Slessi** [comment]
Seems like it was a temporary issue, latest version is back to normal on vscode
