### ISSUE TITLE
Dracula theme for Calibre

### ISSUE THREAD

**Issue by foxtrot222** [dracula/dracula-theme#969]
Dark theme based on color palette of Dracula for [Calibre E-book reader](https://calibre-ebook.com/)
Link to repository - https://github.com/foxtrot222/draculathemeforcalibre

**Comment by luxonauta** [comment]
Hey, that's very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/foxtrot222/draculathemeforcalibre)
- [New repository.](https://github.com/dracula/calibre)

Thanks for building this! 🎉
