### ISSUE TITLE
Dracula for Cosmic Terminal

### ISSUE THREAD

**Issue by eosdev-x** [dracula/dracula-theme#972]
## [Cosmic-term](https://github.com/pop-os/cosmic-term), part of System76's new Rust-based Cosmic Desktop Environment, is a modern terminal emulator focused on performance, customizability, and a seamless user experience.

Link to theme [Dracula for Cosmic Terminal](https://github.com/eosdev-x/Dracula_for_Cosmic/tree/main)

**Comment by eosdev-x** [comment]
Hope this can be added soon!

**Comment by luxonauta** [comment]
Hey, that's very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/eosdev-x/Dracula_for_Cosmic)
- [New repository.](https://github.com/dracula/cosmic-terminal)

Thanks for building this! 🎉

**Comment by eosdev-x** [comment]
Thank you, I'm happy to contribute!
