### ISSUE TITLE
Blender theme is very outdated!!

### ISSUE THREAD

**Issue by foxtrot222** [dracula/dracula-theme#974]
Blender had an major update 5 years which completely changed UI of it. 
https://github.com/dracula/blender
Current theme is 6 years old which makes theme not working for many part of software.
Anyways I would like to contribute to theme or rather change it fully but how?

**Comment by luxonauta** [comment]
@childishgiant, would you be open to reviewing a PR for this? If you can no longer maintain the project, @ foxtrot222 could take over as maintainer.

**Comment by ChildishGiant** [comment]
I can't commit to maintaining this and would happily hand-over

**Comment by ChildishGiant** [comment]
I think I've given @foxtrot222 admin permissions for the repo
