### ISSUE TITLE
Theme for tlrc

### ISSUE THREAD

**Issue by noraj** [dracula/dracula-theme#983]
I made a dracula theme for tlrc: https://github.com/noraj/tlrc-dracula

**Comment by noraj** [comment]
Does the `in trasnfer` label means the theme was accepted and I should transfer it to https://github.com/dracula?

> Finally, [submit an issue](https://github.com/dracula/dracula-theme/issues/new) with a link to your repository. Once the theme is accepted, we will move the repository under the Dracula organization and give you rights to maintain it 😀

**Comment by luxonauta** [comment]
Hey, that's very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/noraj/tlrc-dracula)
- [New repository.](https://github.com/dracula/tlrc)

Thanks for building this! 🎉
