### ISSUE TITLE
New theme for Django Admin

### ISSUE THREAD

**Issue by sjbitcode** [dracula/dracula-theme#986]
Hi there! 👋 

Here's a new theme for the [Django](https://www.djangoproject.com/) web framework's built-in admin:
https://github.com/sjbitcode/django-admin-dracula

The Django admin already comes with a default light and dark theme, so I made "dracula" versions for both! 🦇

Thank you!

**Comment by luxonauta** [comment]
Hey, that's very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/sjbitcode/django-admin-dracula)
- [New repository.](https://github.com/dracula/django-admin)

Thanks for building this! 🎉
