### ISSUE TITLE
New theme for Yazi

### ISSUE THREAD

**Issue by raghavkrish** [dracula/dracula-theme#987]
Hey there!

I have created a dark theme for [Yazi](https://yazi-rs.github.io) (terminal file manager)

https://github.com/raghavkrish/dracula-for-yazi

Cheers!

**Comment by luxonauta** [comment]
Hey, that's very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/raghavkrish/dracula-for-yazi)
- [New repository.](https://github.com/dracula/yazi)

Thanks for building this! 🎉
