### ISSUE TITLE
New theme for x64dbg

### ISSUE THREAD

**Issue by CX330Blake** [dracula/dracula-theme#989]
Hi there, I've made a Dracula Theme for [x64dbg](https://x64dbg.com/).

- [Theme Repo](https://github.com/CX330Blake/x64dbg-theme-dracula)

Cheers!

**Comment by luxonauta** [comment]
Hey, that's very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/CX330Blake/x64dbg-theme-dracula)
- [New repository.](https://github.com/dracula/x64dbg)

Thanks for building this! 🎉
