### ISSUE TITLE
New theme for Cutter

### ISSUE THREAD

**Issue by CX330Blake** [dracula/dracula-theme#990]
Hi there, I've made a Dracula Theme for [Cutter](https://cutter.re/).

- [Theme Repo](https://github.com/CX330Blake/Cutter-Theme-Dracula)

Cheers!

**Comment by luxonauta** [comment]
Hey, that's very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/CX330Blake/Cutter-Theme-Dracula)
- [New repository.](https://github.com/dracula/cutter)

Thanks for building this! 🎉
