### ISSUE TITLE
New theme for Binary Ninja

### ISSUE THREAD

**Issue by CX330Blake** [dracula/dracula-theme#992]
Hey, it's me again. This time I made a theme for Binary Ninja.

- [Theme Repo](https://github.com/CX330Blake/BinaryNinja-Theme-Dracula)

CU next time.

**Comment by luxonauta** [comment]
Hey, that's very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/CX330Blake/BinaryNinja-Theme-Dracula)
- [New repository.](https://github.com/dracula/binary-ninja)

Thanks for building this! 🎉
