### ISSUE TITLE
New Theme for lazyigt 

### ISSUE THREAD

**Issue by nerdbude** [dracula/dracula-theme#993]
I'm slowly starting to like building dracula for other tools :D 

Here is the Dracula theme for lazygit:
- [Dracula for lazygit](https://github.com/nerdbude/lazygit)

**Comment by luxonauta** [comment]
Hey, that's very cool! ✨

I just sent you an invitation to join the organization.

I also cloned your repository for Dracula's organization, so you can go ahead and delete or archive yours:

- [Your repository.](https://github.com/nerdbude/lazygit)
- [New repository.](https://github.com/dracula/lazyigt)

Thanks for building this! 🎉

**Comment by nerdbude** [comment]
thanks for all. 
my repo is archived.

**Comment by hacknug** [comment]
@luxonauta I noticed the repo's description still shows `lazyigt` instead of `lazygit` (didn't wan't to open an issue there just for this 🙏)
